prompt --application/pages/page_00137
begin
wwv_flow_api.create_page(
 p_id=>137
,p_user_interface_id=>wwv_flow_api.id(95249231080808714)
,p_name=>'Areas'
,p_step_title=>'Areas'
,p_autocomplete_on_off=>'OFF'
,p_javascript_file_urls=>'#IMAGE_PREFIX#javascript/infortributos/js/utilidades.js'
,p_javascript_code_onload=>'ocultarAyudaD();'
,p_step_template=>wwv_flow_api.id(29519719109068494)
,p_page_template_options=>'#DEFAULT#'
,p_last_updated_by=>'ELAFAURIE'
,p_last_upd_yyyymmddhh24miss=>'20191023085425'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(5271795543384808)
,p_plug_name=>unistr('\00C1reas')
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(29552524947068508)
,p_plug_display_sequence=>30
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select ID_AREA,',
'       CDGO_CLNTE,',
'       NMBRE_AREA,',
'       ID_AREA_PDRE,',
'       ''<button style="color:blue" type="button" class="a-Button a-Button--noLabel a-Button--iconTextButton">Procesos<span class="fa fa-external-link-square"></span></button>'' html',
'  from DF_C_AREAS'))
,p_plug_source_type=>'NATIVE_IG'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(5271944204384810)
,p_name=>'ID_AREA'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ID_AREA'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>30
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_is_primary_key=>true
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(5272041084384811)
,p_name=>'CDGO_CLNTE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'CDGO_CLNTE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_HIDDEN'
,p_display_sequence=>40
,p_attribute_01=>'Y'
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_is_primary_key=>false
,p_default_type=>'ITEM'
,p_default_expression=>'F_CDGO_CLNTE'
,p_duplicate_value=>true
,p_include_in_export=>false
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(5272179606384812)
,p_name=>'NMBRE_AREA'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'NMBRE_AREA'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>false
,p_item_type=>'NATIVE_TEXT_FIELD'
,p_heading=>'Nombre '
,p_heading_alignment=>'CENTER'
,p_display_sequence=>50
,p_value_alignment=>'CENTER'
,p_attribute_05=>'BOTH'
,p_is_required=>true
,p_max_length=>50
,p_enable_filter=>true
,p_filter_operators=>'C:S:CASE_INSENSITIVE:REGEXP'
,p_filter_is_required=>false
,p_filter_text_case=>'MIXED'
,p_filter_exact_match=>true
,p_filter_lov_type=>'DISTINCT'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(5272262053384813)
,p_name=>'ID_AREA_PDRE'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'ID_AREA_PDRE'
,p_data_type=>'NUMBER'
,p_is_query_only=>false
,p_item_type=>'NATIVE_SELECT_LIST'
,p_heading=>unistr('\00C1rea Padre')
,p_heading_alignment=>'CENTER'
,p_display_sequence=>60
,p_value_alignment=>'CENTER'
,p_is_required=>false
,p_lov_type=>'SQL_QUERY'
,p_lov_source=>'select nmbre_area, id_area from df_c_areas'
,p_lov_display_extra=>true
,p_lov_display_null=>true
,p_lov_cascade_parent_items=>'ID_AREA'
,p_ajax_items_to_submit=>'ID_AREA'
,p_ajax_optimize_refresh=>true
,p_filter_is_required=>false
,p_use_as_row_header=>false
,p_enable_hide=>true
,p_is_primary_key=>false
,p_duplicate_value=>true
,p_include_in_export=>true
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(5272316397384814)
,p_name=>'APEX$ROW_ACTION'
,p_item_type=>'NATIVE_ROW_ACTION'
,p_display_sequence=>20
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(5272426432384815)
,p_name=>'APEX$ROW_SELECTOR'
,p_item_type=>'NATIVE_ROW_SELECTOR'
,p_display_sequence=>10
,p_attribute_01=>'Y'
,p_attribute_02=>'Y'
,p_attribute_03=>'N'
);
wwv_flow_api.create_region_column(
 p_id=>wwv_flow_api.id(5273263490384823)
,p_name=>'Procesos'
,p_source_type=>'DB_COLUMN'
,p_source_expression=>'HTML'
,p_data_type=>'VARCHAR2'
,p_is_query_only=>true
,p_item_type=>'NATIVE_HTML_EXPRESSION'
,p_heading_alignment=>'CENTER'
,p_display_sequence=>70
,p_value_alignment=>'CENTER'
,p_attribute_01=>'&HTML.'
,p_link_target=>'f?p=&APP_ID.:138:&SESSION.::&DEBUG.:RP,138:P138_ID_AREA:&ID_AREA.'
,p_use_as_row_header=>false
,p_enable_sort_group=>true
,p_enable_control_break=>true
,p_enable_hide=>true
,p_is_primary_key=>false
,p_include_in_export=>true
);
wwv_flow_api.create_interactive_grid(
 p_id=>wwv_flow_api.id(5271832352384809)
,p_internal_uid=>5271832352384809
,p_is_editable=>true
,p_edit_operations=>'i:u:d'
,p_lost_update_check_type=>'VALUES'
,p_add_row_if_empty=>true
,p_submit_checked_rows=>false
,p_lazy_loading=>false
,p_requires_filter=>false
,p_show_nulls_as=>'-'
,p_select_first_row=>true
,p_fixed_row_height=>true
,p_pagination_type=>'SCROLL'
,p_show_total_row_count=>true
,p_show_toolbar=>true
,p_enable_save_public_report=>false
,p_enable_subscriptions=>true
,p_enable_flashback=>true
,p_define_chart_view=>true
,p_enable_download=>true
,p_enable_mail_download=>true
,p_fixed_header=>'PAGE'
,p_show_icon_view=>false
,p_show_detail_view=>false
);
wwv_flow_api.create_ig_report(
 p_id=>wwv_flow_api.id(5412617723118956)
,p_interactive_grid_id=>wwv_flow_api.id(5271832352384809)
,p_type=>'PRIMARY'
,p_default_view=>'GRID'
,p_show_row_number=>false
,p_settings_area_expanded=>true
);
wwv_flow_api.create_ig_report_view(
 p_id=>wwv_flow_api.id(5412737843118956)
,p_report_id=>wwv_flow_api.id(5412617723118956)
,p_view_type=>'GRID'
,p_stretch_columns=>true
,p_srv_exclude_null_values=>false
,p_srv_only_display_columns=>true
,p_edit_mode=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(5413260379118957)
,p_view_id=>wwv_flow_api.id(5412737843118956)
,p_display_seq=>1
,p_column_id=>wwv_flow_api.id(5271944204384810)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(5413761736118959)
,p_view_id=>wwv_flow_api.id(5412737843118956)
,p_display_seq=>2
,p_column_id=>wwv_flow_api.id(5272041084384811)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(5414221969118960)
,p_view_id=>wwv_flow_api.id(5412737843118956)
,p_display_seq=>4
,p_column_id=>wwv_flow_api.id(5272179606384812)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>407
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(5414796243118962)
,p_view_id=>wwv_flow_api.id(5412737843118956)
,p_display_seq=>5
,p_column_id=>wwv_flow_api.id(5272262053384813)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>324
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(5415956588122614)
,p_view_id=>wwv_flow_api.id(5412737843118956)
,p_display_seq=>0
,p_column_id=>wwv_flow_api.id(5272316397384814)
,p_is_visible=>true
,p_is_frozen=>false
);
wwv_flow_api.create_ig_report_column(
 p_id=>wwv_flow_api.id(5505821628438313)
,p_view_id=>wwv_flow_api.id(5412737843118956)
,p_display_seq=>6
,p_column_id=>wwv_flow_api.id(5273263490384823)
,p_is_visible=>true
,p_is_frozen=>false
,p_width=>191
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(5272778612384818)
,p_plug_name=>'Ayuda'
,p_region_template_options=>'#DEFAULT#:t-Region--removeHeader:t-Region--scrollBody'
,p_plug_template=>wwv_flow_api.id(29552524947068508)
,p_plug_display_sequence=>40
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'REGION_POSITION_03'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
'<br>',
'<h5>',
'    <b>',
'        <i>',
'            <center>Ayuda <i class="fa fa-question-circle" aria-hidden="true"></i></center>',
' ',
'    </b>',
'</h5>',
unistr('<b>1.</b> Funcionalidad que permite ingresar, consultar, modificar y eliminar las \00E1reas.<br><br>'),
unistr('<b>2.</b>  Funcionalidad que permite ingresar, consultar, modificar, eliminar, activar y desactivar los procesos correspondientes a cada \00E1rea, hacer clic en el bot\00F3n proceso se mostrar\00E1 una ventana con los procesos del \00E1rea seleccionada, para guardar')
||unistr(' los procesos debe diligenciar los datos solicitados y hacer clic en el bot\00F3n guardar.'),
'<br><br>	',
unistr('Si desea conocer m\00E1s informaci\00F3n referente a la funcionalidad dir\00EDjase al Manual de Usuario.'),
'',
'</i>',
''))
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_validation(
 p_id=>wwv_flow_api.id(5271698825384807)
,p_tabular_form_region_id=>wwv_flow_api.id(5271795543384808)
,p_validation_name=>unistr('Validar \00E1rea diferente a ella misma')
,p_validation_sequence=>10
,p_validation=>'nvl(:ID_AREA_PDRE, 0) != :ID_AREA'
,p_validation_type=>'PLSQL_EXPRESSION'
,p_error_message=>'#COLUMN_HEADER# no puede ser igual a ella misma.'
,p_associated_column=>'ID_AREA_PDRE'
,p_error_display_location=>'INLINE_WITH_FIELD_AND_NOTIFICATION'
);
wwv_flow_api.create_page_process(
 p_id=>wwv_flow_api.id(5272508526384816)
,p_process_sequence=>20
,p_process_point=>'AFTER_SUBMIT'
,p_region_id=>wwv_flow_api.id(5271795543384808)
,p_process_type=>'NATIVE_IG_DML'
,p_process_name=>'New - Save Interactive Grid Data'
,p_attribute_01=>'REGION_SOURCE'
,p_attribute_05=>'Y'
,p_attribute_06=>'Y'
,p_attribute_08=>'Y'
,p_error_display_location=>'INLINE_IN_NOTIFICATION'
);
end;
/
