
  CREATE OR REPLACE EDITIONABLE PROCEDURE "TEMP_ACTLZA_PRDIOS_VAL" (P_RFRNCIA_CTSTRAL VARCHAR2) is

  --RECORRER LOS PREDIOS DE VALORIZACI?N
  CURSOR C1 IS
    SELECT I.ID_SJTO, I.ID_SJTO_IMPSTO
      FROM SI_I_SUJETOS_IMPUESTO I
     WHERE I.ID_IMPSTO = 2300115
       AND EXISTS (SELECT 1
              FROM SI_I_SUJETOS_IMPUESTO T
             WHERE T.ID_SJTO = I.ID_SJTO
               AND T.ID_SJTO_IMPSTO <> I.ID_SJTO_IMPSTO)
       AND EXISTS (SELECT 1
              FROM SI_C_SUJETOS S
             WHERE S.ID_SJTO = I.ID_SJTO
               AND (S.IDNTFCCION = P_RFRNCIA_CTSTRAL OR
                   P_RFRNCIA_CTSTRAL IS NULL));

  --SUJETO PREDIAL
  CURSOR C2(R_ID_SJTO NUMBER) IS
    SELECT I.ID_SJTO_IMPSTO, I.ID_SJTO_ESTDO
      FROM SI_I_SUJETOS_IMPUESTO I
     WHERE I.ID_IMPSTO = 230011
       AND I.ID_SJTO = R_ID_SJTO;

  -- BUSCO LOS DATOS PREDIAL
  CURSOR C3(R_ID_SJTO_IMPSTO NUMBER) IS
    SELECT P.AVLUO_CTSTRAL,
           P.MTRCLA_INMBLRIA,
           P.AREA_TRRNO,
           P.AREA_CNSTRDA,
           P.CDGO_ESTRTO,
           P.CDGO_DSTNO_IGAC,
           P.AREA_GRVBLE,
           P.ID_PRDIO_DSTNO,
           P.CDGO_PRDIO_TPO,
           P.AVLUO_TRRNO,
           P.AVLUO_CNSTRCCION,
           P.PRO_INDVSO,
           P.LTTUD,
           P.LNGTUD
      FROM SI_I_PREDIOS P
     WHERE P.ID_SJTO_IMPSTO = R_ID_SJTO_IMPSTO;

  V_ID_SJTO_IMPSTO_PRDAL NUMBER;
  V_AVLUO                NUMBER;
  V_AREA_TRRNO           NUMBER;
  V_AREA_CNSTRDA         NUMBER;
  V_ESTDO_SJTO_PRDIAL    NUMBER;
  V_MTRCLA               VARCHAR2(50);
  V_DSTNO                VARCHAR2(5);
  V_ESTRTO               NUMBER;
  V_AREA_GRVBLE          NUMBER;
  V_ID_PRDIO_DSTNO       NUMBER;
  V_CDGO_PRDIO_TPO       NUMBER;
  V_AVLUO_TRRNO          NUMBER;
  V_AVLUO_CNSTRCCION     NUMBER;
  V_PRO_INDVSO           VARCHAR2(5);
  V_LTTUD                VARCHAR2(100);
  V_LNGTUD               VARCHAR2(100);
begin

  FOR R1 IN C1 LOOP
    V_ID_SJTO_IMPSTO_PRDAL := NULL;
    V_ESTDO_SJTO_PRDIAL    := NULL;
    FOR R2 IN C2(R1.ID_SJTO) LOOP
      V_ID_SJTO_IMPSTO_PRDAL := R2.ID_SJTO_IMPSTO;
      V_ESTDO_SJTO_PRDIAL    := R2.ID_SJTO_ESTDO;
    END LOOP;

    FOR R3 IN C3(V_ID_SJTO_IMPSTO_PRDAL) LOOP
      V_AVLUO            := R3.AVLUO_CTSTRAL;
      V_MTRCLA           := R3.MTRCLA_INMBLRIA;
      V_AREA_TRRNO       := R3.AREA_TRRNO;
      V_AREA_CNSTRDA     := R3.AREA_CNSTRDA;
      V_ESTRTO           := R3.CDGO_ESTRTO;
      V_DSTNO            := R3.CDGO_DSTNO_IGAC;
      V_AREA_GRVBLE      := R3.AREA_GRVBLE;
      V_ID_PRDIO_DSTNO   := R3.ID_PRDIO_DSTNO;
      V_CDGO_PRDIO_TPO   := R3.CDGO_PRDIO_TPO;
      V_AVLUO_TRRNO      := R3.AVLUO_TRRNO;
      V_AVLUO_CNSTRCCION := R3.AVLUO_CNSTRCCION;
      V_PRO_INDVSO       := R3.PRO_INDVSO;
      V_LTTUD            := R3.LTTUD;
      V_LNGTUD           := R3.LNGTUD;
    END LOOP;

    --ACTUALIZO AVALUO Y MATRICULA VALORIZACION
    UPDATE SI_I_PREDIOS P
       SET P.AVLUO_CTSTRAL    = V_AVLUO,
           P.MTRCLA_INMBLRIA  = V_MTRCLA,
           P.AVLUO_CMRCIAL    = V_AVLUO,
           P.AREA_TRRNO       = V_AREA_TRRNO,
           P.AREA_CNSTRDA     = V_AREA_CNSTRDA,
           P.CDGO_ESTRTO      = V_ESTRTO,
           P.CDGO_DSTNO_IGAC  = V_DSTNO,
           P.AREA_GRVBLE      = V_AREA_GRVBLE,
           P.ID_PRDIO_DSTNO   = V_ID_PRDIO_DSTNO,
           P.CDGO_PRDIO_TPO   = V_CDGO_PRDIO_TPO,
           P.AVLUO_TRRNO      = V_AVLUO_TRRNO,
           P.AVLUO_CNSTRCCION = V_AVLUO_CNSTRCCION,
           P.PRO_INDVSO       = V_PRO_INDVSO,
           P.LTTUD            = V_LTTUD,
           P.LNGTUD           = V_LNGTUD
     WHERE P.ID_SJTO_IMPSTO = R1.ID_SJTO_IMPSTO;

    UPDATE SI_I_SUJETOS_IMPUESTO I
       SET I.ID_SJTO_ESTDO = V_ESTDO_SJTO_PRDIAL
     WHERE I.ID_SJTO_IMPSTO = R1.ID_SJTO_IMPSTO;

    DELETE FROM SI_I_SUJETOS_RESPONSABLE R
     WHERE R.ID_SJTO_IMPSTO = R1.ID_SJTO_IMPSTO;

    INSERT INTO SI_I_SUJETOS_RESPONSABLE
      (ID_SJTO_IMPSTO,
       CDGO_IDNTFCCION_TPO,
       IDNTFCCION,
       PRMER_NMBRE,
       SGNDO_NMBRE,
       PRMER_APLLDO,
       SGNDO_APLLDO,
       PRNCPAL_S_N,
       CDGO_TPO_RSPNSBLE,
       PRCNTJE_PRTCPCION,
       ORGEN_DCMNTO,
       ID_PAIS_NTFCCION,
       ID_DPRTMNTO_NTFCCION,
       ID_MNCPIO_NTFCCION,
       DRCCION_NTFCCION,
       EMAIL,
       TLFNO,
       CLLAR,
       ACTVO,
       ID_TRCRO,
       INDCDOR_MGRDO)

      SELECT R1.ID_SJTO_IMPSTO,
             R.CDGO_IDNTFCCION_TPO,
             R.IDNTFCCION,
             R.PRMER_NMBRE,
             R.SGNDO_NMBRE,
             R.PRMER_APLLDO,
             R.SGNDO_APLLDO,
             R.PRNCPAL_S_N,
             R.CDGO_TPO_RSPNSBLE,
             R.PRCNTJE_PRTCPCION,
             R.ORGEN_DCMNTO,
             R.ID_PAIS_NTFCCION,
             R.ID_DPRTMNTO_NTFCCION,
             R.ID_MNCPIO_NTFCCION,
             R.DRCCION_NTFCCION,
             R.EMAIL,
             R.TLFNO,
             R.CLLAR,
             R.ACTVO,
             R.ID_TRCRO,
             R.INDCDOR_MGRDO
        FROM SI_I_SUJETOS_RESPONSABLE R
       WHERE R.ID_SJTO_IMPSTO = V_ID_SJTO_IMPSTO_PRDAL;
    COMMIT;
  END LOOP;

end TEMP_ACTLZA_PRDIOS_VAL;
/

