prompt --application/pages/page_00010
begin
wwv_flow_api.create_page(
 p_id=>10
,p_user_interface_id=>wwv_flow_api.id(22508582753660970)
,p_name=>'Cartera'
,p_page_mode=>'NON_MODAL'
,p_step_title=>'Cartera'
,p_allow_duplicate_submissions=>'N'
,p_autocomplete_on_off=>'OFF'
,p_page_template_options=>'#DEFAULT#'
,p_dialog_height=>'500'
,p_dialog_width=>'1024'
,p_dialog_max_width=>'1024'
,p_dialog_chained=>'N'
,p_last_updated_by=>'1064978129'
,p_last_upd_yyyymmddhh24miss=>'20250423223259'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(24669128994198704)
,p_plug_name=>'Cartera'
,p_region_template_options=>'#DEFAULT#'
,p_component_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(52128439135074801)
,p_plug_display_sequence=>20
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_query_type=>'SQL'
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
' select (select m.nmbre_impsto_sbmpsto from df_i_impuestos_subimpuesto m where m.id_impsto_sbmpsto =  a.id_impsto_sbmpsto) nmbre_impsto,',
'        a.vgncia,',
'        a.id_prdo,',
'        a.prdo,',
'        a.cdgo_mvmnto_orgn,',
'        a.id_orgen,',
'        to_char(a.fcha_ultmo_mvmnto,''DD/MM/YYYY'') fcha_vncmnto,',
'        initcap(a.dscrpcion_mvnt_fncro_estdo) dscrpcion_mvnt_fncro_estdo,',
'        a.vlor_sldo_cptal, ',
'        a.vlor_intres,',
'        (select nmbre from si_i_sujetos_sucursal s where a.id_sjto_scrsal = s.id_sjto_scrsal)  Sucursal,',
'        (select p.dscrpcion from df_i_periodos p where p.id_prdo = a.id_prdo) nmbre_prdo,',
'        upper(a.dscrpcion_prdcdad) dscrpcion_prdcdad,',
'       ''<center><span class="fa fa-eye" aria-hidden="true"></span></center>'' as "Conceptos",',
'        ''<center><span class="fa fa-eye" aria-hidden="true"></span></center>'' as "Movimientos"',
'   from v_gf_g_cartera_x_vigencia a',
'  where a.id_sjto_impsto = :P10_ID_SJTO_IMPSTO'))
,p_plug_source_type=>'NATIVE_IR'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_prn_content_disposition=>'ATTACHMENT'
,p_prn_document_header=>'APEX'
,p_prn_units=>'MILLIMETERS'
,p_prn_paper_size=>'A4'
,p_prn_width=>210
,p_prn_height=>297
,p_prn_orientation=>'HORIZONTAL'
,p_prn_page_header_font_color=>'#000000'
,p_prn_page_header_font_family=>'Helvetica'
,p_prn_page_header_font_weight=>'normal'
,p_prn_page_header_font_size=>'12'
,p_prn_page_footer_font_color=>'#000000'
,p_prn_page_footer_font_family=>'Helvetica'
,p_prn_page_footer_font_weight=>'normal'
,p_prn_page_footer_font_size=>'12'
,p_prn_header_bg_color=>'#9bafde'
,p_prn_header_font_color=>'#000000'
,p_prn_header_font_family=>'Helvetica'
,p_prn_header_font_weight=>'normal'
,p_prn_header_font_size=>'10'
,p_prn_body_bg_color=>'#efefef'
,p_prn_body_font_color=>'#000000'
,p_prn_body_font_family=>'Helvetica'
,p_prn_body_font_weight=>'normal'
,p_prn_body_font_size=>'10'
,p_prn_border_width=>.5
,p_prn_page_header_alignment=>'CENTER'
,p_prn_page_footer_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet(
 p_id=>wwv_flow_api.id(24669201259198705)
,p_max_row_count=>'1000000'
,p_show_nulls_as=>'-'
,p_pagination_type=>'ROWS_X_TO_Y'
,p_pagination_display_pos=>'BOTTOM_RIGHT'
,p_report_list_mode=>'TABS'
,p_show_detail_link=>'N'
,p_show_notify=>'Y'
,p_download_formats=>'CSV:HTML:EMAIL:XLS:PDF:RTF'
,p_owner=>'JCUAO'
,p_internal_uid=>24669201259198705
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24670366087198716)
,p_db_column_name=>'Conceptos'
,p_display_order=>10
,p_column_identifier=>'I'
,p_column_label=>'Conceptos'
,p_column_link=>'f?p=&APP_ID.:12:&SESSION.::&DEBUG.:RP,12:P12_FCHA_VNCMNTO,P12_ID_SJTO_IMPSTO,P12_PRDO,P12_VGNCIA,P12_ID_ORGEN:#FCHA_VNCMNTO#,&P10_ID_SJTO_IMPSTO.,#PRDO#,#VGNCIA#,#ID_ORGEN#'
,p_column_linktext=>'#Conceptos#'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_format_mask=>'PCT_GRAPH:::'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24670413296198717)
,p_db_column_name=>'Movimientos'
,p_display_order=>20
,p_column_identifier=>'J'
,p_column_label=>'Movimientos'
,p_column_link=>'f?p=&APP_ID.:11:&SESSION.::&DEBUG.:RP,11:P11_ID_SJTO_IMPSTO,P11_ID_PRDO,P11_VGNCIA,P11_ID_ORGEN:&P10_ID_SJTO_IMPSTO.,#ID_PRDO#,#VGNCIA#,#ID_ORGEN#'
,p_column_linktext=>'#Movimientos#'
,p_column_type=>'STRING'
,p_display_text_as=>'WITHOUT_MODIFICATION'
,p_format_mask=>'PCT_GRAPH:::'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24669337049198706)
,p_db_column_name=>'NMBRE_IMPSTO'
,p_display_order=>30
,p_column_identifier=>'A'
,p_column_label=>'Tributo'
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24669404165198707)
,p_db_column_name=>'VGNCIA'
,p_display_order=>40
,p_column_identifier=>'B'
,p_column_label=>'Vigencia'
,p_column_type=>'NUMBER'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24669524889198708)
,p_db_column_name=>'ID_PRDO'
,p_display_order=>50
,p_column_identifier=>'C'
,p_column_label=>'Periodo'
,p_column_type=>'NUMBER'
,p_display_text_as=>'HIDDEN'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(94611510826345508)
,p_db_column_name=>'DSCRPCION_PRDCDAD'
,p_display_order=>55
,p_column_identifier=>'N'
,p_column_label=>'Periodicidad'
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(94611612220345509)
,p_db_column_name=>'NMBRE_PRDO'
,p_display_order=>58
,p_column_identifier=>'O'
,p_column_label=>'Periodo'
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24669643543198709)
,p_db_column_name=>'PRDO'
,p_display_order=>60
,p_column_identifier=>'D'
,p_column_label=>'Periodo'
,p_column_type=>'NUMBER'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24669726115198710)
,p_db_column_name=>'FCHA_VNCMNTO'
,p_display_order=>70
,p_column_identifier=>'E'
,p_column_label=>'Fecha de Vencimiento'
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24669868965198711)
,p_db_column_name=>'DSCRPCION_MVNT_FNCRO_ESTDO'
,p_display_order=>80
,p_column_identifier=>'F'
,p_column_label=>'Estado'
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24669916414198712)
,p_db_column_name=>'VLOR_SLDO_CPTAL'
,p_display_order=>90
,p_column_identifier=>'G'
,p_column_label=>'Valor Saldo Capital'
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G990D00'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(24670048867198713)
,p_db_column_name=>'VLOR_INTRES'
,p_display_order=>100
,p_column_identifier=>'H'
,p_column_label=>unistr('Valor Inter\00E9s')
,p_column_type=>'NUMBER'
,p_column_alignment=>'RIGHT'
,p_format_mask=>'999G999G999G999G990D00'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(48993729924511001)
,p_db_column_name=>'CDGO_MVMNTO_ORGN'
,p_display_order=>110
,p_column_identifier=>'K'
,p_column_label=>unistr('C\00F3digo <br> Origen')
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(48993856149511002)
,p_db_column_name=>'ID_ORGEN'
,p_display_order=>120
,p_column_identifier=>'L'
,p_column_label=>'Origen'
,p_column_type=>'NUMBER'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_column(
 p_id=>wwv_flow_api.id(65784925849439002)
,p_db_column_name=>'SUCURSAL'
,p_display_order=>130
,p_column_identifier=>'M'
,p_column_label=>'Sucursal'
,p_column_type=>'STRING'
,p_column_alignment=>'CENTER'
);
wwv_flow_api.create_worksheet_rpt(
 p_id=>wwv_flow_api.id(24713217248309376)
,p_application_user=>'APXWS_DEFAULT'
,p_report_seq=>10
,p_report_alias=>'247133'
,p_status=>'PUBLIC'
,p_is_default=>'Y'
,p_report_columns=>'Movimientos:Conceptos:NMBRE_IMPSTO:SUCURSAL:VGNCIA:NMBRE_PRDO:DSCRPCION_MVNT_FNCRO_ESTDO:VLOR_SLDO_CPTAL:VLOR_INTRES:'
,p_sort_column_1=>'VGNCIA'
,p_sort_direction_1=>'DESC'
,p_sort_column_2=>'PRDO'
,p_sort_direction_2=>'ASC'
,p_sort_column_3=>'0'
,p_sort_direction_3=>'ASC'
,p_sort_column_4=>'0'
,p_sort_direction_4=>'ASC'
,p_sort_column_5=>'0'
,p_sort_direction_5=>'ASC'
,p_sort_column_6=>'0'
,p_sort_direction_6=>'ASC'
,p_sum_columns_on_break=>'VLOR_INTRES:VLOR_SLDO_CPTAL'
);
wwv_flow_api.create_worksheet_condition(
 p_id=>wwv_flow_api.id(70102931650690076)
,p_report_id=>wwv_flow_api.id(24713217248309376)
,p_name=>'Anulada'
,p_condition_type=>'HIGHLIGHT'
,p_allow_delete=>'Y'
,p_column_name=>'DSCRPCION_MVNT_FNCRO_ESTDO'
,p_operator=>'='
,p_expr=>'Anulada'
,p_condition_sql=>' (case when ("DSCRPCION_MVNT_FNCRO_ESTDO" = #APXWS_EXPR#) then #APXWS_HL_ID# end) '
,p_condition_display=>'#APXWS_COL_NAME# = ''Anulada''  '
,p_enabled=>'Y'
,p_highlight_sequence=>10
,p_row_bg_color=>'#FFDD44'
,p_row_font_color=>'#000000'
);
wwv_flow_api.create_worksheet_condition(
 p_id=>wwv_flow_api.id(70103352298690077)
,p_report_id=>wwv_flow_api.id(24713217248309376)
,p_name=>'Convenio'
,p_condition_type=>'HIGHLIGHT'
,p_allow_delete=>'Y'
,p_column_name=>'DSCRPCION_MVNT_FNCRO_ESTDO'
,p_operator=>'='
,p_expr=>'Convenio'
,p_condition_sql=>' (case when ("DSCRPCION_MVNT_FNCRO_ESTDO" = #APXWS_EXPR#) then #APXWS_HL_ID# end) '
,p_condition_display=>'#APXWS_COL_NAME# = ''Convenio''  '
,p_enabled=>'Y'
,p_highlight_sequence=>10
,p_row_bg_color=>'#99FF99'
);
wwv_flow_api.create_page_plug(
 p_id=>wwv_flow_api.id(72643416833794495)
,p_plug_name=>'&P10_DSCRPCION.'
,p_icon_css_classes=>'&P10_ICNO.'
,p_region_template_options=>'#DEFAULT#'
,p_plug_template=>wwv_flow_api.id(52124852663074800)
,p_plug_display_sequence=>10
,p_include_in_reg_disp_sel_yn=>'Y'
,p_plug_display_point=>'BODY'
,p_plug_query_options=>'DERIVED_REPORT_COLUMNS'
,p_attribute_01=>'N'
,p_attribute_02=>'HTML'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(24695320856268154)
,p_name=>'P10_ID_SJTO_IMPSTO'
,p_item_sequence=>10
,p_item_plug_id=>wwv_flow_api.id(72643416833794495)
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(24695768410268154)
,p_name=>'P10_ICNO'
,p_item_sequence=>20
,p_item_plug_id=>wwv_flow_api.id(72643416833794495)
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'Y'
);
wwv_flow_api.create_page_item(
 p_id=>wwv_flow_api.id(24696159002268155)
,p_name=>'P10_DSCRPCION'
,p_item_sequence=>30
,p_item_plug_id=>wwv_flow_api.id(72643416833794495)
,p_display_as=>'NATIVE_HIDDEN'
,p_attribute_01=>'Y'
);
end;
/
