
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RE_G_DOCUMENTOS_CNVNIO_CTA" ("ID_DCMNTO_CNVNIO_CTA", "ID_DCMNTO", "CDGO_CLNTE", "NMBRE_CLNTE", "ID_IMPSTO", "NMBRE_IMPSTO", "ID_IMPSTO_SBMPSTO", "NMBRE_IMPSTO_SBMPSTO", "ID_SJTO", "CDGO_SJTO_TPO", "DSCRPCION_SJTO_TPO", "IDNTFCCION_SJTO", "IDNTFCCION_SJTO_FRMTDA", "IDNTFCCION_ANTRIOR", "IDNTFCCION_ANTRIOR_FRMTDA", "FCHA_DCMNTO", "FCHA_VNCMNTO", "VLOR_TTAL_DBE", "VLOR_TTAL_HBER", "VLOR_TTAL", "VLOR_TTAL_DCMNTO", "INDCDOR_PGO_APLCDO", "DSCRPCION_INDCDOR_PGO_APLCDO", "INDCDOR_ENTRNO", "DSCRPCION_INDCDOR_ENTRNO", "ID_CNVNIO", "ID_CNVNIO_TPO", "DSCRPCION_CNVNIO_TPO", "NMRO_CNVNIO", "CDGO_CNVNIO_ESTDO", "DSCRPCION_CNVNIO_ESTDO", "FCHA_SLCTUD", "FCHA_PRMRA_CTA", "NMRO_CTAS", "CDGO_PRDCDAD_CTA", "DSCRPCION_PRDCDAD_CTA", "TTAL_CNVNIO", "VLOR_CTA_INCIAL", "NMRO_CTA", "VGNCIAS_CNVNIO") AS
  select a.id_dcmnto_cnvnio_cta,
		a.id_dcmnto,
		b.cdgo_clnte,
		b.nmbre_clnte,
		b.id_impsto,
		b.nmbre_impsto,
		b.id_impsto_sbmpsto,
		b.nmbre_impsto_sbmpsto,
        b.id_sjto,
		b.cdgo_sjto_tpo,
		b.dscrpcion_sjto_tpo,
		b.idntfccion_sjto,
		b.idntfccion_sjto_frmtda,
		b.idntfccion_antrior,
		b.idntfccion_antrior_frmtda,
		b.fcha_dcmnto,
		b.fcha_vncmnto,
		b.vlor_ttal_dbe,
		b.vlor_ttal_hber,
		b.vlor_ttal,
		b.vlor_ttal_dcmnto,
		b.indcdor_pgo_aplcdo,
        b.dscrpcion_indcdor_pgo_aplcdo,
		b.indcdor_entrno,
        b.dscrpcion_indcdor_entrno,
		a.id_cnvnio,
		c.id_cnvnio_tpo,
		c.dscrpcion_cnvnio_tpo,
		c.nmro_cnvnio,
		c.cdgo_cnvnio_estdo,
		c.dscrpcion_cnvnio_estdo,
		c.fcha_slctud,
		c.fcha_prmra_cta,
		c.nmro_cta nmro_ctas,
		c.cdgo_prdcdad_cta,
		c.dscrpcion_prdcdad_cta,
		c.ttal_cnvnio,
		c.vlor_cta_incial,
		a.nmro_cta,
        (select LISTAGG(vgncia, ', ') WITHIN GROUP (ORDER BY vgncia) vgncia from gf_g_convenios_cartera m where m.id_cnvnio = c.id_cnvnio)vgncias_cnvnio
   from re_g_documentos_cnvnio_cta 	a
   join v_re_g_documentos				b on a.id_dcmnto = b.id_dcmnto
   join v_gf_g_convenios				c on a.id_cnvnio = c.id_cnvnio;

