apiVersion: v1
kind: Secret
metadata:
  name: {{ include "apex-api.fullname" . }}-secret
  labels:
    {{- include "apex-api.labels" . | nindent 4 }}
  annotations:
    secrets-store.csi.x-k8s.io/provider: {{ .Values.secrets.provider | quote }}
    {{- if .Values.secrets.vaultOCID }}
    secrets-store.csi.x-k8s.io/vault-ocid: {{ .Values.secrets.vaultOCID | quote }}
    {{- end }}
type: Opaque
data:
  database-url: ""
  jwt-secret: ""
