
  CREATE TABLE "AD_D_INDICADOR_USO"
   (	"CDGO_INDCDOR_USO" VARCHAR2(2) CONSTRAINT "AD_D_MDLO_CDGO_INDCDOR_USO_NN" NOT NULL ENABLE,
	"NMBRE_INDCDOR_USO" VARCHAR2(100) CONSTRAINT "AD_D_MDLO_NMBRE_INDCDOR_USO_NN" NOT NULL ENABLE,
	 CONSTRAINT "AD_D_MDLO_CDGO_INDCDOR_USO_PK" PRIMARY KEY ("CDGO_INDCDOR_USO")
  USING INDEX  ENABLE
   ) ;

