
  CREATE TABLE "CB_G_PROCESOS_JURIDICO_LOTE"
   (	"ID_PRCSO_JRDCO_LTE" NUMBER(15,0) CONSTRAINT "CB_G_PRC_JR_LTE_ID_PR_JR_LT_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "CB_G_PRC_JR_LTE_COD_CLNTE_NN" NOT NULL ENABLE,
	"CNSCTVO_LTE" NUMBER(15,0) CONSTRAINT "CB_G_PRC_JR_LTE_CNSCTVO_LTE_NN" NOT NULL ENABLE,
	"FCHA_LTE" DATE CONSTRAINT "CB_G_PRC_JR_LTE_FCHA_LTE_NN" NOT NULL ENABLE,
	"OBSRVCION_LTE" VARCHAR2(1000) CONSTRAINT "CB_G_PRC_JR_LTE_OBSRVCN_LTE_NN" NOT NULL ENABLE,
	"TPO_LTE" VARCHAR2(3) CONSTRAINT "CB_G_PRC_JR_LTE_TPO_LTE_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER(15,0),
	"ID_FNCNRIO" NUMBER(15,0) CONSTRAINT "CB_G_PRC_JR_LTE_ID_FNCNRIO_NN" NOT NULL ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_LTE_TPO_LTE_CK" CHECK (tpo_lte in ('LIP','LPJ','LPE','LIM')) ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_LTE_ID_PR_JR_LT_PK" PRIMARY KEY ("ID_PRCSO_JRDCO_LTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_LTE_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_LTE_COD_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_LTE_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE
   ) ;

