
  CREATE TABLE "CB_G_PROCESOS_JURIDICO_SJTO"
   (	"ID_PRCSOS_JRDCO_SJTO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_CB_G_PROCESOS_JURIDICO_SJTO"."NEXTVAL" CONSTRAINT "CB_G_PRC_JR_SJ_ID_PR_JR_SJ_NN" NOT NULL ENABLE,
	"ID_PRCSOS_JRDCO" NUMBER(15,0) CONSTRAINT "CB_G_PRC_JR_SJ_ID_PRCS_JRD_NN" NOT NULL ENABLE,
	"ID_SJTO" NUMBER(15,0) CONSTRAINT "CB_G_PRC_JR_SJ_ID_SJTO_NN" NOT NULL ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_SJ_ID_PR_JR_SJ_PK" PRIMARY KEY ("ID_PRCSOS_JRDCO_SJTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_SJ_ID_SJTO_FK" FOREIGN KEY ("ID_SJTO")
	  REFERENCES "SI_C_SUJETOS" ("ID_SJTO") DISABLE,
	 CONSTRAINT "CB_G_PRC_JR_SJ_ID_PRCS_JRD_FK" FOREIGN KEY ("ID_PRCSOS_JRDCO")
	  REFERENCES "CB_G_PROCESOS_JURIDICO" ("ID_PRCSOS_JRDCO") ENABLE
   ) ;

