
  CREATE TABLE "CB_G_PRCSOS_JRDCO_DCMNT_LTE"
   (	"ID_PRCSO_JRDCO_DCMNTO_LTE" NUMBER CONSTRAINT "CB_G_PRC_JR_DC_LT_I_P_J_D_L_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "CB_G_PRC_JR_DC_LT_CDGO_CLNT_NN" NOT NULL ENABLE,
	"CDGO_PRCSO" VARCHAR2(3) CONSTRAINT "CB_G_PRC_JR_DC_LT_CDGO_PRCS_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "CB_G_PRC_JR_DC_LT_ID_ACT_TP_NN" NOT NULL ENABLE,
	"FCHA_LTE" TIMESTAMP (6) CONSTRAINT "CB_G_PRC_JR_DC_LT_FCHA_LTE_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "CB_G_PRC_JR_DC_LT_ID_USRIO_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(1000) CONSTRAINT "CB_G_PRC_JR_DC_LT_OBSRVCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_DC_LT_I_P_J_D_L_PK" PRIMARY KEY ("ID_PRCSO_JRDCO_DCMNTO_LTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_DC_LT_CDGO_CLNT_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_DC_LT_CDGO_PRCS_FK" FOREIGN KEY ("CDGO_PRCSO")
	  REFERENCES "GN_D_CODIGOS_PROCESO" ("CDGO_PRCSO") ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_DC_LT_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "CB_G_PRC_JR_DC_LT_ID_ACT_TP_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE
   ) ;

