
  CREATE TABLE "CB_G_PROCESOS_PERSUASIVO_JSON"
   (	"ID_PRCSOS_PRSSVO_JSON" NUMBER NOT NULL ENABLE,
	"ID_PRCSOS_SMU_SJTO" NUMBER NOT NULL ENABLE,
	"ID_SJTO" NUMBER NOT NULL ENABLE,
	"VLOR_TTAL_DDA" NUMBER(16,2) NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(50) NOT NULL ENABLE,
	"ID_PRCSOS_SMU_LTE" NUMBER NOT NULL ENABLE,
	"ID_PRCSO_TPO" NUMBER NOT NULL ENABLE,
	"ID_USRIO" NUMBER NOT NULL ENABLE,
	"INDCDOR_PRCSDO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER,
	 CONSTRAINT "CB_G_PC_PR_JS_PK" PRIMARY KEY ("ID_PRCSOS_PRSSVO_JSON")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PC_PR_JS_ID_PRCSO_TPO" FOREIGN KEY ("ID_PRCSO_TPO")
	  REFERENCES "CB_D_PROCESOS_TIPO" ("ID_PRCSO_TPO") ENABLE,
	 CONSTRAINT "CB_G_PC_PR_JS_ID_PRC_SMU_LOTE" FOREIGN KEY ("ID_PRCSOS_SMU_LTE")
	  REFERENCES "CB_G_PROCESOS_SIMU_LOTE" ("ID_PRCSOS_SMU_LTE") ENABLE,
	 CONSTRAINT "CB_G_PC_PR_JS_ID_PRC_SMU_SJTO" FOREIGN KEY ("ID_PRCSOS_SMU_SJTO")
	  REFERENCES "CB_G_PROCESOS_SIMU_SUJETO" ("ID_PRCSOS_SMU_SJTO") ENABLE,
	 CONSTRAINT "CB_G_PC_PR_JS_ID_SJTO" FOREIGN KEY ("ID_SJTO")
	  REFERENCES "SI_C_SUJETOS" ("ID_SJTO") ENABLE,
	 CONSTRAINT "CB_G_PC_PR_JS_ID_USRIO" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

