
  CREATE TABLE "CB_G_PROCESOS_JURIDICO"
   (	"ID_PRCSOS_JRDCO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_CB_G_PROCESOS_JURIDICO"."NEXTVAL" CONSTRAINT "CB_G_PRCS_JRDC_ID_PRCSO_JRD_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "CB_G_PRCS_JRDC_COD_CLNTE_NN" NOT NULL ENABLE,
	"NMRO_PRCSO_JRDCO" VARCHAR2(30) CONSTRAINT "CB_G_PRCS_JRDC_NMRO_PRCSO_JRDC" NOT NULL ENABLE,
	"FCHA" TIMESTAMP (6) CONSTRAINT "CB_G_PRCS_JRDC_FCHA_NN" NOT NULL ENABLE,
	"VLOR_TTAL_DDA" NUMBER(16,2) CONSTRAINT "CB_G_PRCS_JRDC_VLOR_TTAL_DDA" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER(15,0),
	"CDGO_PRCSOS_JRDCO_ESTDO" VARCHAR2(3) CONSTRAINT "CB_G_PRCS_JRDC_CDG_PRC_ESTD_NN" NOT NULL ENABLE,
	"ID_FNCNRIO" NUMBER(15,0) CONSTRAINT "CB_G_PRCS_JRDC_ID_FNCNRIO_NN" NOT NULL ENABLE,
	"MSVO" VARCHAR2(1) CONSTRAINT "CB_G_PRCS_JRDC_MSVO_NN" NOT NULL ENABLE,
	"ID_PRCSO_JRDCO_LTE" NUMBER(15,0) CONSTRAINT "CB_G_PRCS_JRDC_ID_PR_JR_LT_NN" NOT NULL ENABLE,
	"TPO_PLNTLLA" VARCHAR2(1),
	"ETPA_ACTUAL_MGRA" VARCHAR2(5),
	 CONSTRAINT "CB_G_PRCS_JRDC_TPO_PLNTLLA_CK" CHECK (tpo_plntlla in ('P','M')) ENABLE,
	 CONSTRAINT "CB_G_PRCS_JRDC_ID_PRCSO_JRD_PK" PRIMARY KEY ("ID_PRCSOS_JRDCO")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PRCS_JRDC_MSVO_CK" CHECK (msvo in ('N','S')) ENABLE,
	 CONSTRAINT "CB_G_PRCS_JRDC_CDG_PRC_ESTD_FK" FOREIGN KEY ("CDGO_PRCSOS_JRDCO_ESTDO")
	  REFERENCES "CB_D_PROCESOS_JRDCO_ESTDO" ("CDGO_PRCSOS_JRDCO_ESTDO") ENABLE,
	 CONSTRAINT "CB_G_PRCS_JRDC_COD_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "CB_G_PRCS_JRDC_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "CB_G_PRCS_JRDC_ID_INST_FLJO_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "CB_G_PRCS_JRDC_ID_PR_JR_LT_FK" FOREIGN KEY ("ID_PRCSO_JRDCO_LTE")
	  REFERENCES "CB_G_PROCESOS_JURIDICO_LOTE" ("ID_PRCSO_JRDCO_LTE") DISABLE
   ) ;

