
  CREATE TABLE "CB_G_PROCESOS_JRDCO_LTE_DTLLE"
   (	"ID_PRCSO_JRDCO_LTE_DTLLE" NUMBER(15,0) CONSTRAINT "CB_G_PR_JR_LT_DT_ID_P_J_L_D_NN" NOT NULL ENABLE,
	"ID_PRCSO_JRDCO_LTE" NUMBER(15,0) CONSTRAINT "CB_G_PR_JR_LT_DT_ID_PR_JR_L_NN" NOT NULL ENABLE,
	"ID_PRCSDO" NUMBER(15,0) CONSTRAINT "CB_G_PR_JR_LT_DT_ID_PRCSDO_NN" NOT NULL ENABLE,
	"OBSRVCIONES" CLOB,
	 CONSTRAINT "CB_G_PR_JR_LT_DT_ID_P_J_L_D_PK" PRIMARY KEY ("ID_PRCSO_JRDCO_LTE_DTLLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PR_JR_LT_DT_ID_PR_JR_L_FK" FOREIGN KEY ("ID_PRCSO_JRDCO_LTE")
	  REFERENCES "CB_G_PROCESOS_JURIDICO_LOTE" ("ID_PRCSO_JRDCO_LTE") DISABLE
   )
 LOB ("OBSRVCIONES") STORE AS SECUREFILE "SYS_LOB0000105764C00004$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

