
  CREATE TABLE "CB_G_PROCESOS_SIMU_SUJETO"
   (	"ID_PRCSOS_SMU_SJTO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_CB_G_PROCESOS_SIMU_SUJETO"."NEXTVAL" CONSTRAINT "CB_G_PR_SM_SJ_ID_PR_SMU_SJT_NN" NOT NULL ENABLE,
	"ID_PRCSOS_SMU_LTE" NUMBER(15,0) CONSTRAINT "CB_G_PR_SM_SJ_ID_PR_SMU_LTE_NN" NOT NULL ENABLE,
	"ID_SJTO" NUMBER(15,0) CONSTRAINT "CB_G_PR_SM_SJ_ID_SJTO_NN" NOT NULL ENABLE,
	"VLOR_TTAL_DDA" NUMBER(16,2) CONSTRAINT "CB_G_PR_SM_SJ_VLOR_TTAL_DDA_NN" NOT NULL ENABLE,
	"RSPNSBLES" VARCHAR2(1000) CONSTRAINT "CB_G_PR_SM_SJ_RSPNSBLES_FK" NOT NULL ENABLE,
	"FCHA_INGRSO" TIMESTAMP (6) CONSTRAINT "CB_G_PR_SM_SJ_FCHA_INGRSO_NN" NOT NULL ENABLE,
	"ID_CNSLTA_RGLA" NUMBER(15,0),
	"INDCDOR_PRCSDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "CB_G_PR_SM_SJ_INDCDOR_PRCSD_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(3) DEFAULT 'S',
	"ID_IMPSTO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	 CONSTRAINT "CB_G_PR_SM_SJ_ID_PR_SMU_SJT_PK" PRIMARY KEY ("ID_PRCSOS_SMU_SJTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PR_SM_SJ_INDCDOR_PRCSD_FK" CHECK (indcdor_prcsdo in ('S','N','E')) ENABLE,
	 CONSTRAINT "CB_G_PR_SM_SJ_ID_SJTO_FK" FOREIGN KEY ("ID_SJTO")
	  REFERENCES "SI_C_SUJETOS" ("ID_SJTO") DISABLE,
	 CONSTRAINT "CB_G_PR_SM_SJ_ID_PR_SMU_LTE_FK" FOREIGN KEY ("ID_PRCSOS_SMU_LTE")
	  REFERENCES "CB_G_PROCESOS_SIMU_LOTE" ("ID_PRCSOS_SMU_LTE") ENABLE,
	 CONSTRAINT "CB_G_PR_SM_SJ_ID_CNS_RGL_FK" FOREIGN KEY ("ID_CNSLTA_RGLA")
	  REFERENCES "GE_P_CONSULTA_MAESTRO" ("ID_CNSLTA_MSTRO") ENABLE
   ) ;

