
  CREATE TABLE "CB_G_PRCSS_SIMU_RSPNSBL_INX"
   (	"ID_PRCSOS_SMU_RSPNSBL_INX" NUMBER CONSTRAINT "CB_G_PR_SM_RS_IN_ID_P_S_R_I_NN" NOT NULL ENABLE,
	"ID_PRCSOS_SMU_SJTO_INXSTNTE" NUMBER CONSTRAINT "CB_G_PR_SM_RS_IN_ID_P_S_S_I_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(3),
	"IDNTFCCION" VARCHAR2(25) CONSTRAINT "CB_G_PR_SM_RS_IN_IDNTFCCION_NN" NOT NULL ENABLE,
	"PRMER_NMBRE" VARCHAR2(500) CONSTRAINT "CB_G_PR_SM_RS_IN_PRMER_NMBR_NN" NOT NULL ENABLE,
	"SGNDO_NMBRE" VARCHAR2(100),
	"PRMER_APLLDO" VARCHAR2(100) CONSTRAINT "CB_G_PR_SM_RS_IN_PRMR_APLLD_NN" NOT NULL ENABLE,
	"SGNDO_APLLDO" VARCHAR2(100),
	"ID_PAIS_NTFCCION" NUMBER,
	"ID_DPRTMNTO_NTFCCION" NUMBER,
	"ID_MNCPIO_NTFCCION" NUMBER,
	"DRCCION_NTFCCION" VARCHAR2(100),
	"EMAIL" VARCHAR2(320),
	"TLFNO" VARCHAR2(50),
	"CLLAR" VARCHAR2(50),
	"PRNCPAL_S_N" VARCHAR2(1) CONSTRAINT "CB_G_PR_SM_RS_IN_PRNCPL_S_N_NN" NOT NULL ENABLE,
	"CDGO_TPO_RSPNSBLE" VARCHAR2(3),
	"PRCNTJE_PRTCPCION" NUMBER(5,2) DEFAULT 0,
	 CONSTRAINT "CB_G_PR_SM_RS_IN_ID_P_S_R_I_PK" PRIMARY KEY ("ID_PRCSOS_SMU_RSPNSBL_INX")
  USING INDEX  ENABLE,
	 CONSTRAINT "CB_G_PR_SM_RS_IN_ID_P_S_S_I_FK" FOREIGN KEY ("ID_PRCSOS_SMU_SJTO_INXSTNTE")
	  REFERENCES "CB_G_PRCSS_SM_SJTO_INXSTNTE" ("ID_PRCSOS_SMU_SJTO_INXSTNTE") ENABLE
   ) ;

