
  CREATE GLOBAL TEMPORARY TABLE "CB_T_PROCESOS_JRDCO_MVMNTO"
   (	"ID_SJTO_IMPSTO" NUMBER,
	"ID_PRCSOS_JRDCO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"VGNCIA" NUMBER,
	"ID_PRDO" NUMBER,
	"ID_CNCPTO" NUMBER,
	"VLOR_CPTAL" NUMBER,
	"VLOR_INTRES" NUMBER,
	"CDGO_CLNTE" NUMBER(15,0),
	"ID_IMPSTO" NUMBER,
	"CDGO_MVMNTO_ORGN" VARCHAR2(3),
	"ID_ORGEN" NUMBER,
	"ID_MVMNTO_FNCRO" NUMBER,
	 CONSTRAINT "CB_T_PRC_JRD_MV_I_S_I_I_P_J_UN" UNIQUE ("ID_SJTO_IMPSTO", "ID_PRCSOS_JRDCO", "VGNCIA", "ID_PRDO") ENABLE
   ) ON COMMIT PRESERVE ROWS ;

