
  CREATE TABLE "CG_OPCIONES"
   (	"ID_OPCION" NUMBER DEFAULT "GENESYS"."SQ_CG_OPCIONES"."NEXTVAL" CONSTRAINT "CG_OPCIONES_ID_OPCION_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500) CONSTRAINT "CG_OPCIONES_DSCRPCION_NN" NOT NULL ENABLE,
	"ICNO" VARCHAR2(255),
	"APP_ID" VARCHAR2(100),
	"PAGE" NUMBER,
	"ORDEN" NUMBER,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "CG_OPCIONES_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "CG_OPCIONES_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "CG_OPCIONES_ID_OPCION_PK" PRIMARY KEY ("ID_OPCION")
  USING INDEX  ENABLE
   ) ;

