
  CREATE TABLE "CS_G_CONSULTAS_MAESTRO"
   (	"ID_CNSLTA_MSTRO" NUMBER CONSTRAINT "CS_D_CNSL_MSTRO_ID_CNSL_MST_NN" NOT NULL ENABLE,
	"ID_PRCSO_SQL" NUMBER CONSTRAINT "CS_D_CNSL_MSTRO_ID_PRCS_SQL_NN" NOT NULL ENABLE,
	"NMBRE_CNSLTA" VARCHAR2(100) CONSTRAINT "CS_D_CNSL_MSTRO_NMBRE_CNSLT_NN" NOT NULL ENABLE,
	"ID_SBCNSLTA_MSTRO" NUMBER,
	"TPO_CNDCION" VARCHAR2(1),
	"ID_CNSLTA_MSTRO_GNRAL" NUMBER,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "CS_D_CNSL_MSTRO_FCHA_DGTA_NN" NOT NULL ENABLE,
	"USRNME_DGTA" VARCHAR2(30) CONSTRAINT "CS_D_CNSL_MSTRO_USRNME_DGTA_NN" NOT NULL ENABLE,
	"FCHA_MDFCA" TIMESTAMP (6),
	"USRNME_MDFCA" VARCHAR2(30),
	 CONSTRAINT "CS_D_CNSL_MSTRO_ID_CNSL_MST_PK" PRIMARY KEY ("ID_CNSLTA_MSTRO")
  USING INDEX  ENABLE,
	 CONSTRAINT "CS_D_CNSL_MSTRO_ID_SBC_MSTR_FK" FOREIGN KEY ("ID_SBCNSLTA_MSTRO")
	  REFERENCES "CS_G_CONSULTAS_MAESTRO" ("ID_CNSLTA_MSTRO") ENABLE,
	 CONSTRAINT "CS_D_CNSL_MSTRO_ID_CN_MS_GN_FK" FOREIGN KEY ("ID_CNSLTA_MSTRO_GNRAL")
	  REFERENCES "CS_G_CONSULTAS_MAESTRO" ("ID_CNSLTA_MSTRO") ENABLE,
	 CONSTRAINT "CS_D_CNSL_MSTRO_ID_PRCS_SQL_FK" FOREIGN KEY ("ID_PRCSO_SQL")
	  REFERENCES "CS_D_PROCESOS_SQL" ("ID_PRCSO_SQL") ENABLE
   ) ;

