
  CREATE TABLE "DF_C_OFICINAS"
   (	"ID_OFCNA" NUMBER(15,0) CONSTRAINT "DF_C_OFIC_ID_OFCNA_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "DF_C_OFIC_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"NMBRE_OFCNA" VARCHAR2(50) CONSTRAINT "DF_C_OFIC_NMBRE_OFCNA_NN" NOT NULL ENABLE,
	"ID_OFCNA_PDRE" NUMBER(15,0),
	"ID_FNCNRIO" NUMBER(15,0),
	 CONSTRAINT "DF_C_OFIC_ID_OFCNA_PK" PRIMARY KEY ("ID_OFCNA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_OFIC_NMBRE_OFC_CDG_CLN_UN" UNIQUE ("NMBRE_OFCNA", "CDGO_CLNTE")
  USING INDEX (CREATE UNIQUE INDEX "DF_C_OFIC_NMBRE_OFCNA_UN" ON "DF_C_OFICINAS" ("NMBRE_OFCNA", "CDGO_CLNTE")
  )  ENABLE,
	 CONSTRAINT "DF_C_OFIC_ID_OFCNA_PDRE_FK" FOREIGN KEY ("ID_OFCNA_PDRE")
	  REFERENCES "DF_C_OFICINAS" ("ID_OFCNA") ENABLE,
	 CONSTRAINT "DF_C_OFIC_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

