
  CREATE TABLE "DF_C_FUNCIONARIOS_BITACORA"
   (	"ID_FNCNRIO_BTCRA" NUMBER(15,0) CONSTRAINT "DF_C_FNCNRO_BTCR_ID_FNCN_BT_NN" NOT NULL ENABLE,
	"ID_FNCNRIO" NUMBER(15,0) CONSTRAINT "DF_C_FNCNRO_BTCR_ID_FNCNRIO_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) CONSTRAINT "DF_C_FNCNRO_BTCR_FCHA_RGSTR_NN" NOT NULL ENABLE,
	"ESTDO" VARCHAR2(1) CONSTRAINT "DF_C_FNCNRO_BTCR_ESTDO_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(200),
	 CONSTRAINT "DF_C_FNCNRO_BTCR_ID_FNCN_BT_PK" PRIMARY KEY ("ID_FNCNRIO_BTCRA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_FNCNRO_BTCR_ESTDO_CK" CHECK ( estdo in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_C_FNCNRO_BTCR_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE
   ) ;

