
  CREATE TABLE "DF_C_PROCESOS"
   (	"ID_PRCSO" NUMBER CONSTRAINT "DF_C_PRCSOS_ID_PRCSO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "DF_C_PRCSOS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_PRCSO" VARCHAR2(5) CONSTRAINT "DF_C_PRCSOS_CDGO_PROCSO_NN" NOT NULL ENABLE,
	"NMBRE_PRCSO" VARCHAR2(100) CONSTRAINT "DF_C_PRCSOS_NMBRE_PROCSO_NN" NOT NULL ENABLE,
	"ID_PRCSO_PDRE" NUMBER,
	"ID_AREA" NUMBER CONSTRAINT "DF_C_AREA_PRCSO_ID_AREA_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "DF_C_SRIE_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_C_PRCSOS_CLNTE_CDGO_PRCS_UN" UNIQUE ("CDGO_CLNTE", "CDGO_PRCSO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_SRIE_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "DF_C_PROCESOS_CDGO_PRCSO_UN" UNIQUE ("CDGO_PRCSO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_PRCSOS_AR_NB_PR_CD_PR_UN" UNIQUE ("ID_AREA", "NMBRE_PRCSO", "CDGO_PRCSO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_PRCSOS_ID_PRCSO_PK" PRIMARY KEY ("ID_PRCSO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_AREA_PRCSO_ID_AREA_FK" FOREIGN KEY ("ID_AREA")
	  REFERENCES "DF_C_AREAS" ("ID_AREA") ENABLE,
	 CONSTRAINT "DF_C_PRCSOS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "DF_C_PRCSOS_ID_PRCSO_PDRE_FK" FOREIGN KEY ("ID_PRCSO_PDRE")
	  REFERENCES "DF_C_PROCESOS" ("ID_PRCSO") ENABLE
   ) ;

