
  CREATE TABLE "DF_C_IMAGENES_CLIENTE"
   (	"ID_IMGEN_CLNTE" NUMBER(15,0) CONSTRAINT "DF_CLNT_IMGEN_ID_IMGEN_CLNT_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "DF_CLNT_IMGEN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_DFNCION_CLNTE_CTGRIA" VARCHAR2(5) CONSTRAINT "DF_CLNT_IMGEN_CDGO_CTGRIA_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB CONSTRAINT "DF_CLNT_IMGEN_FILE_BLOB_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255),
	"FILE_MIMETYPE" VARCHAR2(50),
	"CDGO_IMGEN_CLNTE" VARCHAR2(3),
	 CONSTRAINT "DF_CLNT_IMGEN_ID_IMGEN_CLNT_PK" PRIMARY KEY ("ID_IMGEN_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "CDGO_IMGEN_CLNTE_UQ" UNIQUE ("CDGO_CLNTE", "CDGO_IMGEN_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_IMGNES_CLNTE_FLE_MMTPE_CK" CHECK (file_mimetype like 'image%') ENABLE,
	 CONSTRAINT "DF_CLNT_IMGEN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "DF_CLNT_IMGEN_CDGO_CTGRIA_FK" FOREIGN KEY ("ID_DFNCION_CLNTE_CTGRIA")
	  REFERENCES "DF_C_DEFINICIONES_CLNTE_CTGRIA" ("ID_DFNCION_CLNTE_CTGRIA") ENABLE
   )
 LOB ("FILE_BLOB") STORE AS SECUREFILE "SYS_LOB0000094601C00004$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

