
  CREATE TABLE "DF_C_GRUPOS_ACTO_ENTIDAD"
   (	"ID_GRP_ACTO_ENTDAD" NUMBER CONSTRAINT "DF_C_GRP_ACT_ENT_ID_CN_TP_EN_NN" NOT NULL ENABLE,
	"ID_GRPO_ACTO" NUMBER CONSTRAINT "DF_C_GRP_ACT_ENT_ID_GRP_ACT_NN" NOT NULL ENABLE,
	"ID_ENTDAD" NUMBER CONSTRAINT "DF_C_GRP_ACT_ENT_ID_ENTDAD_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "DF_C_GRP_ACT_ENT_ACTVO_NN" NOT NULL ENABLE,
	"INDCDOR_MGRDO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT "DF_C_GRP_ACT_ENT_ID_CN_TP_EN_PK" PRIMARY KEY ("ID_GRP_ACTO_ENTDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_GRP_ACT_ENT_GR_AC_ENT_UN" UNIQUE ("ID_GRPO_ACTO", "ID_ENTDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_GRP_ACT_ENT_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "DF_C_GRP_ACT_ENT_ID_GRP_ACT_FK" FOREIGN KEY ("ID_GRPO_ACTO")
	  REFERENCES "DF_C_GRUPOS_ACTO" ("ID_GRPO_ACTO") ENABLE,
	 CONSTRAINT "DF_C_GRP_ACT_ENT_ID_ENTDAD_FK" FOREIGN KEY ("ID_ENTDAD")
	  REFERENCES "DF_S_ENTIDADES" ("ID_ENTDAD") ENABLE
   ) ;

