
  CREATE TABLE "DF_C_PROCESOS_ACCION"
   (	"ID_PRCSO_ACCION" NUMBER CONSTRAINT "DF_C_PRCS_ACC_ID_PRCSO_ACC_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "DF_C_PRCS_ACC_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_PRCSO_ACCION" VARCHAR2(30) CONSTRAINT "DF_C_PRCS_ACC_CDGO_PRC_ACC_NN" NOT NULL ENABLE,
	"CDGO_PRCSO" VARCHAR2(5) CONSTRAINT "DF_C_PRCS_ACC_CDGO_PRCSO_NN" NOT NULL ENABLE,
	"ID_EVNTO" NUMBER CONSTRAINT "DF_C_PRCS_ACC_ID_EVNTO_NN" NOT NULL ENABLE,
	"ID_ACCION" NUMBER CONSTRAINT "DF_C_PRCS_ACC_ID_ACCION_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "DF_C_PRCS_ACC_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "DF_C_PRCS_ACC_ID_IMP_SBM_NN" NOT NULL ENABLE,
	"UNDAD_PRGRMA" VARCHAR2(300) CONSTRAINT "DF_C_PRCS_ACC_UNDAD_PRGRMA_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "DF_C_PRCS_ACC_ACTVO_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp,
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "DF_C_PRCS_ACC_USRIO_DGTA_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "DF_C_PRCS_ACC_FCHA_DGTA_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "DF_C_PRCS_ACC_CPRC_IMP_SBM_UN" UNIQUE ("CDGO_PRCSO", "ID_IMPSTO", "ID_IMPSTO_SBMPSTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_CDG_PRCS_ACC_UN" UNIQUE ("CDGO_PRCSO_ACCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_ID_PRCSO_ACC_PK" PRIMARY KEY ("ID_PRCSO_ACCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_ID_EVNTO_FK" FOREIGN KEY ("ID_EVNTO")
	  REFERENCES "DF_C_EVENTOS" ("ID_EVNTO") ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_ID_ACCION_FK" FOREIGN KEY ("ID_ACCION")
	  REFERENCES "DF_C_ACCIONES" ("ID_ACCION") ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "DF_C_PRCS_ACC_ID_IMP_SBM_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE
   ) ;

