
  CREATE TABLE "DF_C_BANCOS"
   (	"ID_BNCO" NUMBER(15,0) CONSTRAINT "DF_C_BANCOS_ID_BANCOS_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "DF_C_BANCOS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"NMBRE_BNCO" VARCHAR2(100) CONSTRAINT "DF_C_BANCOS_NMBRE_BANCOS_NN" NOT NULL ENABLE,
	"RCDDOR" VARCHAR2(1) CONSTRAINT "DE_C_BANCOS_RCDDOR_NN" NOT NULL ENABLE,
	"CDGO_BNCO" VARCHAR2(10),
	"ORDN" NUMBER,
	 CONSTRAINT "DF_C_BANCO_ORDN_UN" UNIQUE ("ORDN")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_BANCOS_ID_BANCOS_PK" PRIMARY KEY ("ID_BNCO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_BANCO_CDGO_BNCO_NN" UNIQUE ("CDGO_BNCO", "CDGO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "DE_C_BANCOS_RCDDOR_CK" CHECK (rcddor in ('N','S')) ENABLE,
	 CONSTRAINT "DF_C_BANCOS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

