
  CREATE TABLE "DF_C_EVENTOS"
   (	"ID_EVNTO" NUMBER CONSTRAINT "DF_C_EVENTOS_ID_EVNTO_NN" NOT NULL ENABLE,
	"CDGO_EVNTO" VARCHAR2(20) CONSTRAINT "DF_C_EVENTOS_CDGO_EVNTO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(20) CONSTRAINT "DF_C_EVENTOS_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	 CONSTRAINT "DF_C_EVENTOS_CDGO_EVNTO_UN" UNIQUE ("CDGO_EVNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_C_EVENTOS_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "DF_C_EVENTOS_ID_EVNTO_PK" PRIMARY KEY ("ID_EVNTO")
  USING INDEX  ENABLE
   ) ;

