
  CREATE TABLE "DF_C_CALENDARIO_CONFIGURACION"
   (	"ID_CLNDRIO" NUMBER CONSTRAINT "DF_CLNDRIO_CNFG_ID_CLNDR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "DF_CLNDRIO_CNFG_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"NMBRE_CLNDRIO" VARCHAR2(100),
	"DIAS_HBLES" VARCHAR2(15) CONSTRAINT "DF_CLNDRIO_CNFG_DIAS_HBLES_NN" NOT NULL ENABLE,
	"INDCDOR_ACTVO" VARCHAR2(1),
	"INDCDOR_PRNCPAL" VARCHAR2(1),
	 CONSTRAINT "DF_CLNDRIO_CNFG_IND_PPAL_CHK" CHECK (indcdor_prncpal in ('S','N')) ENABLE,
	 CONSTRAINT "DF_CLNDRIO_CNFG_IND_ACTVO_CHK" CHECK (indcdor_actvo in ('S','N')) ENABLE,
	 CONSTRAINT "DF_CLNDRIO_CNFG_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

