
  CREATE TABLE "DF_I_IMPUESTOS_ACTO_CONCEPTO"
   (	"ID_IMPSTO_ACTO_CNCPTO" NUMBER(15,0) CONSTRAINT "DF_I_IMPACTCON_IDIMPTOACTCN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "DF_I_IMPT_ACT_CONC_CDGO_CLN_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER(4,0) CONSTRAINT "DF_I_IMPT_ACT_CONC_VGNCIA_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER(*,0) CONSTRAINT "DF_I_IMPT_ACT_CONC_ID_PRDO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_ACTO" NUMBER(15,0) CONSTRAINT "DF_I_IMP_ACT_CON_ID_IMP_ACT_NN" NOT NULL ENABLE,
	"ID_CNCPTO" NUMBER(15,0) CONSTRAINT "DF_I_IMPT_ACT_CONC_ID_CNCPT_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "DF_I_IMPT_ACT_CONC_ACTVO_NN" NOT NULL ENABLE,
	"GNRA_INTRES_MRA" VARCHAR2(1) CONSTRAINT "DF_I_IMP_ACT_CON_GNR_INTMRA_NN" NOT NULL ENABLE,
	"INDCDOR_TRFA_CRCTRSTCAS" VARCHAR2(1) CONSTRAINT "DF_I_IMP_ACT_CON_IND_TRFCRC_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER(6,0),
	"FCHA_VNCMNTO" DATE,
	"ID_CNCPTO_INTRES_MRA" NUMBER(15,0),
	"ID_CNCPTO_INTRES_FNCCION" NUMBER,
	"ID_CNCPTO_INTRES_VNCDO" NUMBER,
	"ID_IMPSTO_ACTO_CNCPTO_RLCNAL" NUMBER DEFAULT NULL,
	"INDCDOR_MGRDO" VARCHAR2(1),
	"INDCDOR_CNCPTO_OBLGTRIO" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	 CONSTRAINT "DF_I_IMPACTCON_IDIMPTOACTCN_PK" PRIMARY KEY ("ID_IMPSTO_ACTO_CNCPTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_IMP_ACT_CON_GNR_INTMRA_CK" CHECK ( gnra_intres_mra in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_VGN_PRD_CNC_UN" UNIQUE ("VGNCIA", "ID_PRDO", "ID_CNCPTO", "ID_IMPSTO_ACTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_IMP_ACT_CON_IND_TRFCRC_CK" CHECK ( indcdor_trfa_crctrstcas in ('N','S')) ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CONC_ACTVO_CK" CHECK ( actvo in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CONC_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CONC_ID_CNCPT_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "DF_I_IMP_ACT_CON_ID_IMP_ACT_FK" FOREIGN KEY ("ID_IMPSTO_ACTO")
	  REFERENCES "DF_I_IMPUESTOS_ACTO" ("ID_IMPSTO_ACTO") ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CNC_ID_CPT_VN_FK" FOREIGN KEY ("ID_CNCPTO_INTRES_VNCDO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CNC_ID_CPT_FN_FK" FOREIGN KEY ("ID_CNCPTO_INTRES_FNCCION")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "DF_I_IMPACTCON_IDIMPTOACTCN_FK" FOREIGN KEY ("ID_IMPSTO_ACTO_CNCPTO_RLCNAL")
	  REFERENCES "DF_I_IMPUESTOS_ACTO_CONCEPTO" ("ID_IMPSTO_ACTO_CNCPTO") ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CNC_ID_CPT_IM_FK" FOREIGN KEY ("ID_CNCPTO_INTRES_MRA")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CONC_CDGO_CLN_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_CONC_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE
   ) ;

