
  CREATE TABLE "DF_I_SUJETOS_TIPO"
   (	"ID_SJTO_TPO" NUMBER CONSTRAINT "DF_I_SJT_TPO_ID_SJTO_TPO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "DF_I_SJT_TPO_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "DF_I_SJT_TPO_ID_IMPSTO_NN" NOT NULL ENABLE,
	"CDGO_SJTO_TPO" VARCHAR2(3) CONSTRAINT "DF_I_SJT_TPO_CDGO_SJTO_TPO_NN" NOT NULL ENABLE,
	"NMBRE_SJTO_TPO" VARCHAR2(100) CONSTRAINT "DF_I_SJT_TPO_NMBRE_SJTO_TPO_NN" NOT NULL ENABLE,
	"TRBJA_ACTVDAD" VARCHAR2(1),
	"FCHA_DSDE" DATE CONSTRAINT "DF_I_SJT_TPO_FCHA_DSDE_NN" NOT NULL ENABLE,
	"FCHA_HSTA" DATE CONSTRAINT "DF_I_SJT_TPO_FCHA_HSTA_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_I_SJT_TPO_ID_SJTO_TPO_PK" PRIMARY KEY ("ID_SJTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_SJT_TPO_TRBJA_ACTVDAD_CK" CHECK (trbja_actvdad in ('N','S')) ENABLE,
	 CONSTRAINT "DF_I_SJT_TPO_CDCL_IDIM_CDRG_UN" UNIQUE ("CDGO_CLNTE", "ID_IMPSTO", "CDGO_SJTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_SJT_TPO_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "DF_I_SJT_TPO_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

