
  CREATE TABLE "DF_I_ENTIDADES_NOVEDAD"
   (	"ID_ENTDAD_NVDAD" NUMBER CONSTRAINT "DF_I_ENTDD_NVD_ID_ENTDD_NVD_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "DF_I_ENTDD_NVD_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "DF_I_ENTDD_NVD_ID_IMPSTO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "DF_I_ENTDD_NVD_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "DF_I_ENTDD_NVD_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_I_ENTDD_NVD_ACTVO_CK" CHECK ( actvo in ('S','N')) ENABLE,
	 CONSTRAINT "DF_I_ENTDD_NVD_ID_ENTDD_NVD_PK" PRIMARY KEY ("ID_ENTDAD_NVDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_ENTDD_NVD_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "DF_I_ENTDD_NVD_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

