
  CREATE TABLE "DF_I_EXOGENA_ARCHV_ESTRCTRA"
   (	"ID_EXGNA_ARCHV_EST" NUMBER CONSTRAINT "DF_I_EXGN_AR_ES_ID_EX_AR_ES_NN" NOT NULL ENABLE,
	"ID_EXGNA_ARCHVO_TPO" NUMBER CONSTRAINT "DF_I_EXGN_AR_ES_ID_EX_AR_TP_NN" NOT NULL ENABLE,
	"NMRO_HOJA" VARCHAR2(10) CONSTRAINT "DF_I_EXGN_AR_ES_NMRO_HOJA_NN" NOT NULL ENABLE,
	"NMRO_CLMNA" VARCHAR2(10) CONSTRAINT "DF_I_EXGN_AR_ES_NMRO_CLMNA_NN" NOT NULL ENABLE,
	"NMBRE_CLMNA" VARCHAR2(20) CONSTRAINT "DF_I_EXGN_AR_ES_NMBRE_CLMNA_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100),
	"TPO_DATO" VARCHAR2(1) CONSTRAINT "DF_I_EXGN_AR_ES_TPO_DATO_NN" NOT NULL ENABLE,
	"TAMANO" VARCHAR2(3) CONSTRAINT "DF_I_EXGN_AR_ES_TAMANO_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_I_EXGN_AR_ES_ID_EX_AR_ES_PK" PRIMARY KEY ("ID_EXGNA_ARCHV_EST")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_EX_AR_ES_IDEXA_NH_NC_UN" UNIQUE ("ID_EXGNA_ARCHVO_TPO", "NMRO_HOJA", "NMBRE_CLMNA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_EXGN_AR_ES_ID_EX_AR_TP_FK" FOREIGN KEY ("ID_EXGNA_ARCHVO_TPO")
	  REFERENCES "DF_I_EXOGENA_ARCHIVO_TIPO" ("ID_EXGNA_ARCHVO_TPO") ENABLE
   ) ;

