
  CREATE TABLE "DF_I_CNCPTO_BNCOS_CNTA"
   (	"ID_CNCPTO_BNC_CTA" NUMBER CONSTRAINT "DF_I_CNT_BC_CT_ID_CPT_BC_CT_NN" NOT NULL ENABLE,
	"ID_BNCO_CNTA" NUMBER CONSTRAINT "DF_I_CNT_BC_CT_BNC_CNT_NN" NOT NULL ENABLE,
	"ID_CNCPTO" NUMBER CONSTRAINT "DF_I_CNT_BC_CNT_CNPTOS_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1),
	 CONSTRAINT "DF_I_CNT_BC_CT_BNC_CNT_CNPTO" UNIQUE ("ID_BNCO_CNTA", "ID_CNCPTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_CNT_BC_CT_ID_CPT_BC_CT_PK" PRIMARY KEY ("ID_CNCPTO_BNC_CTA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_CNT_BC_CNT_CNPTOS_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "DF_I_CNT_BC_CT_BNC_CNT_FK" FOREIGN KEY ("ID_BNCO_CNTA")
	  REFERENCES "DF_C_BANCOS_CUENTA" ("ID_BNCO_CNTA") ENABLE
   ) ;

