
  CREATE TABLE "DF_I_TASAS_BANCARIA"
   (	"ID_TSA_BNCRIA" NUMBER CONSTRAINT "DF_I_TASA_BANCA_ID_TSA_BANC_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "DF_I_TASA_BANCA_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "DF_I_TASA_BANCA_ID_IMPSTO_NN" NOT NULL ENABLE,
	"FCHA_DSDE" DATE CONSTRAINT "DF_I_TASA_BANCA_FCHA_DSDE_NN" NOT NULL ENABLE,
	"FCHA_HSTA" DATE CONSTRAINT "DF_I_TASA_BANCA_FCHA_HSTA_NN" NOT NULL ENABLE,
	"VLOR_TSA" NUMBER CONSTRAINT "DF_I_TASA_BANCA_VLOR_TSA_NN" NOT NULL ENABLE,
	"TSA_DRIA" NUMBER DEFAULT 0 CONSTRAINT "DF_I_TASA_BANCA_TSA_DRIA_NN" NOT NULL ENABLE,
	"ID_TSA_MRA_PDRE" NUMBER,
	 CONSTRAINT "DF_I_TASA_BANCA_TSA_DRIA_CK" CHECK (tsa_dria between 0 and 100) ENABLE,
	 CONSTRAINT "DF_I_TASA_BANCA_ID_TSA_BANC_PK" PRIMARY KEY ("ID_TSA_BNCRIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_TASA_BANCA_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "DF_I_TASA_BANCA_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

