
  CREATE TABLE "DF_I_IMPSTS_SBMPST_MTDT_VLR"
   (	"ID_IMPSTO_SBMPSTO_MTDTA_VLOR" NUMBER DEFAULT "GENESYS"."SQ_DF_I_IMPSTS_SBMPST_MTDT_VLR"."NEXTVAL" CONSTRAINT "DF_I_IM_SB_MT_VL_ID_I_S_M_V_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO_MTDTA" NUMBER CONSTRAINT "DF_I_IM_SB_MT_VL_ID_IM_SB_M_NN" NOT NULL ENABLE,
	"VLOR_DSPLAY" VARCHAR2(200) CONSTRAINT "DF_I_IM_SB_MT_VL_VLOR_DSPL_NN" NOT NULL ENABLE,
	"VLOR_RTURN" VARCHAR2(5) CONSTRAINT "DF_I_IM_SB_MT_VL_VLOR_RTURN_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_I_IM_SB_MT_VL_IM_DS_RT_UN" UNIQUE ("ID_IMPSTO_SBMPSTO_MTDTA", "VLOR_DSPLAY", "VLOR_RTURN")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_IM_SB_MT_VL_ID_I_S_M_V_PK" PRIMARY KEY ("ID_IMPSTO_SBMPSTO_MTDTA_VLOR")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_IM_SB_MT_VL_ID_IM_SB_M_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO_MTDTA")
	  REFERENCES "DF_I_IMPSTOS_SBMPSTO_MTDTA" ("ID_IMPSTO_SBMPSTO_MTDTA") ENABLE
   ) ;

