
  CREATE TABLE "DF_I_PERIODOS"
   (	"ID_PRDO" NUMBER(15,0) CONSTRAINT "DF_I_PERIODOS_ID_PRDO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "DF_I_PERIODOS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "DF_I_PERIODOS_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) CONSTRAINT "DF_I_PERIO_ID_IMPSTO_SBMPTO_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER(4,0) CONSTRAINT "DF_I_PERIODOS_VGNCIA_NN" NOT NULL ENABLE,
	"PRDO" NUMBER(2,0) CONSTRAINT "DF_I_PERIODOS_PRDO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "DF_I_PERIODOS_DSCRPCION_NN" NOT NULL ENABLE,
	"INDCDOR_CRRE_LQDCION" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "DF_I_PERIODOS_IND_CRRE_LQDC_NN" NOT NULL ENABLE,
	"INDCDOR_INCTVCION_PRDIOS" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "DF_I_PERIODOS_IND_INCT_PRDI_NN" NOT NULL ENABLE,
	"FCHA_VNCMNTO" DATE,
	"CDGO_PRDCDAD" VARCHAR2(5),
	"INDCDOR_MGRDO" VARCHAR2(1),
	 CONSTRAINT "DF_I_PERIODOS_CDGO_PRDCDAD_NN" CHECK (cdgo_prdcdad is not null) ENABLE,
	 CONSTRAINT "DF_I_PERIODOS_UN" UNIQUE ("CDGO_CLNTE", "ID_IMPSTO", "ID_IMPSTO_SBMPSTO", "VGNCIA", "PRDO", "CDGO_PRDCDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_PERIODOS_ID_PRDO_PK" PRIMARY KEY ("ID_PRDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_PERIODOS_IND_CRRE_LQDC_CK" CHECK ( indcdor_crre_lqdcion in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_I_PERIODOS_IND_INCT_PRDI_CK" CHECK ( indcdor_inctvcion_prdios in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_I_PERIO_ID_IMPSTO_SBMPTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") DISABLE,
	 CONSTRAINT "DF_I_PERIODOS_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") DISABLE,
	 CONSTRAINT "DF_I_PERIODOS_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") DISABLE,
	 CONSTRAINT "DF_I_PERIODOS_CDGO_PRDCDAD_FK" FOREIGN KEY ("CDGO_PRDCDAD")
	  REFERENCES "DF_S_PERIODICIDAD" ("CDGO_PRDCDAD") DISABLE,
	 CONSTRAINT "DF_I_PERIODOS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") DISABLE
   ) ;

