
  CREATE TABLE "DF_I_EXOGENA_ARCHV_ESTR_HJA"
   (	"ID_EXGNA_ARCHV_EST_HJA" NUMBER CONSTRAINT "DF_I_EX_AR_ESHJ_ID_EX_AR_ES_NN" NOT NULL ENABLE,
	"ID_EXGNA_ARCHVO_TPO" NUMBER CONSTRAINT "DF_I_EX_AR_ESHJ_ID_EX_AR_TP_NN" NOT NULL ENABLE,
	"NMRO_HOJA" VARCHAR2(10) CONSTRAINT "DF_I_EX_AR_ESHJ_NMRO_HOJA_NN" NOT NULL ENABLE,
	"NMBRE_HJA" VARCHAR2(100),
	"CDGO_HJA" VARCHAR2(3),
	 CONSTRAINT "DF_I_EX_AR_ESHJ_ID_EX_AR_ES_PK" PRIMARY KEY ("ID_EXGNA_ARCHV_EST_HJA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_EX_AR_ESHJ_IDEXAT_NMHJ_UN" UNIQUE ("ID_EXGNA_ARCHVO_TPO", "NMRO_HOJA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_EX_AR_ESHJ_ID_EX_AR_TP_FK" FOREIGN KEY ("ID_EXGNA_ARCHVO_TPO")
	  REFERENCES "DF_I_EXOGENA_ARCHIVO_TIPO" ("ID_EXGNA_ARCHVO_TPO") ENABLE
   ) ;

