
  CREATE TABLE "DF_I_IMPUESTOS_ACTO"
   (	"ID_IMPSTO_ACTO" NUMBER(15,0) CONSTRAINT "DF_I_IMPTO_ACT_ID_IPSTO_ACT_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "DF_I_IMPTO_ACT_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) CONSTRAINT "DF_I_IMPTO_ACT_ID_SBMPSTO_NN" NOT NULL ENABLE,
	"CDGO_IMPSTO_ACTO" VARCHAR2(5) CONSTRAINT "DF_I_IMPTO_ACT_CDG_IPST_ACT_NN" NOT NULL ENABLE,
	"NMBRE_IMPSTO_ACTO" VARCHAR2(250) CONSTRAINT "DF_I_IMPTO_ACT_NMBR_IPST_AC_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "DF_I_IMPTO_ACT_ACTVO_NN" NOT NULL ENABLE,
	"TPO_DIAS" VARCHAR2(1),
	"DIAS_MRGN_MRA" NUMBER(6,0) CONSTRAINT "DF_I_IMPTO_ACT_DIAS_MRGN_MR_NN" NOT NULL ENABLE,
	"TXTO_BSE_GRVBLE" VARCHAR2(60) CONSTRAINT "DF_I_IMPTO_ACT_TXTO_BSE_GRV_NN" NOT NULL ENABLE,
	"INDCDOR_LQDCION_PBLCO" VARCHAR2(1) CONSTRAINT "DF_I_IMPTO_ACT_IND_LQD_PBL_NN" NOT NULL ENABLE,
	"INDCDOR_RQRE_ASCSDA" VARCHAR2(1) CONSTRAINT "DF_I_IMPTO_ACT_IND_RQR_ASCD_NN" NOT NULL ENABLE,
	"CDGO_UNDAD_TMPO" VARCHAR2(2),
	"ID_IMPSTO_ACTO_PDRE" NUMBER,
	"INDCDOR_MGRDO" VARCHAR2(1),
	"INDCDOR_USA_FCHA_LQDCION" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	"INDCDR_USA_FCHA_LQDCION" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_IND_RQR_ASCD_CK" CHECK ( indcdor_rqre_ascsda in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_TPO_DIAS_CK" CHECK ( tpo_dias in ('H','C') ) ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_ACTVO_CK" CHECK ( actvo in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_ID_IPSTO_ACT_PK" PRIMARY KEY ("ID_IMPSTO_ACTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_IMPT_ACT_IMP_SBIMP_CDG_UN" UNIQUE ("ID_IMPSTO", "ID_IMPSTO_SBMPSTO", "CDGO_IMPSTO_ACTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_IND_LQD_PBL_CK" CHECK ( indcdor_lqdcion_pblco in ('N','S') ) ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_ID_SBMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "DF_I_IMPTO_ACT_CDG_UNDD_TMP_FK" FOREIGN KEY ("CDGO_UNDAD_TMPO")
	  REFERENCES "DF_S_UNIDADES_TIEMPO" ("CDGO_UNDAD_TMPO") ENABLE
   ) ;

