
  CREATE TABLE "DF_S_TRAMITES_TIPO"
   (	"CDGO_TRMTE_TPO" VARCHAR2(3) CONSTRAINT "DF_S_TRAMITES_TP_C_TRMT_TP_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "DF_S_TRAMITES_TP_DSCRPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_TRAMITES_TP_C_TRMT_TP_PK" PRIMARY KEY ("CDGO_TRMTE_TPO")
  USING INDEX  ENABLE
   ) ;

