
  CREATE TABLE "DF_S_ASEGURADORAS"
   (	"ID_ASGRDRA" NUMBER(15,0) CONSTRAINT "DF_S_ASEGURADORA_ID_ASGRDRA_NN" NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(25) CONSTRAINT "DF_S_ASEGURADORA_IDNTFCCION_NN" NOT NULL ENABLE,
	"NMBRE_ASGRDRA" VARCHAR2(200) CONSTRAINT "DF_S_ASEGURADORA_NMBRE_ASGR_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_ASEGURADORA_ID_ASGRDRA_PK" PRIMARY KEY ("ID_ASGRDRA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_ASEGURADORA_IDNTFCCION_UN" UNIQUE ("IDNTFCCION")
  USING INDEX  ENABLE
   ) ;

