
  CREATE TABLE "DF_S_NOVEDADES_PREDIO_ESTDO"
   (	"CDGO_NVDAD_ESTDO" VARCHAR2(3) CONSTRAINT "DF_S_NVD_PRD_EST_CDG_NV_EST_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(30) CONSTRAINT "DF_S_NVD_PRD_EST_DSCRPCION_NN" NOT NULL ENABLE,
	"CDGO_RSPSTA" VARCHAR2(3) CONSTRAINT "DF_S_NVD_PRD_EST_CDGO_RSPST_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_NVD_PRD_EST_CDG_NV_EST_PK" PRIMARY KEY ("CDGO_NVDAD_ESTDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_NVD_PRD_EST_CDGO_RSPST_FK" FOREIGN KEY ("CDGO_RSPSTA")
	  REFERENCES "PQ_D_RESPUESTAS" ("CDGO_RSPSTA") ENABLE
   ) ;

