
  CREATE TABLE "DF_S_CAJAS_BANCO"
   (	"ID_CJA_BNCO" NUMBER CONSTRAINT "DF_S_CAJAS_BNCO_ID_CJA_BCO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "DF_S_CAJAS_BNCO_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_BNCO" NUMBER CONSTRAINT "DF_S_CAJAS_BNCO_ID_BNCO_NN" NOT NULL ENABLE,
	"ID_BNCO_CNTA" NUMBER CONSTRAINT "DF_S_CAJAS_BNCO_ID_BCO_CTA_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "DF_S_CAJAS_BNCO_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "DF_S_CAJAS_BNCO_ID_USRIO_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_CAJAS_BNCO_ID_CJA_BCO_PK" PRIMARY KEY ("ID_CJA_BNCO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_CAJAS_BNCO_ID_BNCO_FK" FOREIGN KEY ("ID_BNCO")
	  REFERENCES "DF_C_BANCOS" ("ID_BNCO") ENABLE,
	 CONSTRAINT "DF_S_CAJAS_BNCO_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "DF_S_CAJAS_BNCO_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "DF_S_CAJAS_BNCO_ID_BCO_CTA_FK" FOREIGN KEY ("ID_BNCO_CNTA")
	  REFERENCES "DF_C_BANCOS_CUENTA" ("ID_BNCO_CNTA") ENABLE,
	 CONSTRAINT "DF_S_CAJAS_BNCO_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

