
  CREATE TABLE "DF_S_CRITICAS"
   (	"CDGO_CRTCA" VARCHAR2(5) CONSTRAINT "DF_S_CRTCA_CDGO_CRTCA_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500) CONSTRAINT "DF_S_CRTCA_DSCRPCION_NN" NOT NULL ENABLE,
	"CDGO_CRTCA_CTGRIA" VARCHAR2(5) CONSTRAINT "DF_S_CRTCA_CDGO_CRTC_CTGRIA_NN" NOT NULL ENABLE,
	"SQL" CLOB CONSTRAINT "DF_S_CRTCA_SQL_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_CRTCA_CDGO_CRTCA_PK" PRIMARY KEY ("CDGO_CRTCA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_CRTCA_CDGO_CRTC_CTGRIA_FK" FOREIGN KEY ("CDGO_CRTCA_CTGRIA")
	  REFERENCES "DF_S_CRITICAS_CATEGORIA" ("CDGO_CRTCA_CTGRIA") ENABLE
   )
 LOB ("SQL") STORE AS SECUREFILE "SYS_LOB0000086865C00004$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

