
  CREATE TABLE "DF_S_ENTIDADES"
   (	"ID_ENTDAD" NUMBER DEFAULT "GENESYS"."SQ_DF_S_ENTIDADES"."NEXTVAL" CONSTRAINT "DF_S_ENTDAD_ID_ENTDAD_NN" NOT NULL ENABLE,
	"CDGO_ENTDAD_TPO" VARCHAR2(3) CONSTRAINT "DF_S_ENTDAD_CDGO_ENTDAD_TPO_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(3) CONSTRAINT "DF_S_ENTDAD_CDGO_IDNRFCC_TPO_NN" NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(25) CONSTRAINT "DF_S_ENTDAD_IDNTFCCION_NN" NOT NULL ENABLE,
	"NMBRE_RZON_SCIAL" VARCHAR2(100) CONSTRAINT "DF_S_ENTDAD_NMBRE_RZON_SCIA_NN" NOT NULL ENABLE,
	"DRCCION" VARCHAR2(100) CONSTRAINT "DF_S_ENTDAD_DRCCION_NN" NOT NULL ENABLE,
	"ID_PAIS" NUMBER,
	"ID_DPRTMNTO" NUMBER,
	"ID_MNCPIO" NUMBER,
	"EMAIL" VARCHAR2(320),
	"TLFNO" VARCHAR2(50),
	"CLLAR" VARCHAR2(50),
	"INDCDOR_MNJA_CNTRO_ESE" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "DF_S_ENTDAD_IND_MN_CNTR_ESE_NN" NOT NULL ENABLE,
	"INDCDOR_MGRDO" VARCHAR2(1),
	"ACTVO" VARCHAR2(1) DEFAULT 'S' NOT NULL ENABLE,
	"INDCDOR_LQDCION_PBLCO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT "DF_S_ENTDAD_IND_MN_CNTR_ESE_CK" CHECK (indcdor_mnja_cntro_ese in ('S', 'N')) ENABLE,
	 CONSTRAINT "DF_S_ENTDAD_ID_ENTDAD_PK" PRIMARY KEY ("ID_ENTDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_ENTDAD_ID_MNCPIO_FK" FOREIGN KEY ("ID_MNCPIO")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "DF_S_ENTDAD_ID_PAIS_FK" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "DF_S_ENTDAD_CDGO_IDNRFCC_TPO_FK" FOREIGN KEY ("CDGO_IDNTFCCION_TPO")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE,
	 CONSTRAINT "DF_S_ENTDAD_CDGO_ENTDAD_TPO_FK" FOREIGN KEY ("CDGO_ENTDAD_TPO")
	  REFERENCES "DF_S_ENTIDADES_TIPO" ("CDGO_ENTDAD_TPO") ENABLE,
	 CONSTRAINT "DF_S_ENTDAD_ID_DPRTMNTO_FK" FOREIGN KEY ("ID_DPRTMNTO")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE
   ) ;

