
  CREATE TABLE "DF_S_METODOS_ASIGNACION"
   (	"CDGO_MTDO_ASGNCION" VARCHAR2(3) CONSTRAINT "DF_S_MTD_ASIG_COD_MTD_ASIG_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "DF_S_MTD_ASIG_DSCRPCION_NN" NOT NULL ENABLE,
	"EXPLCCION_MTDO" VARCHAR2(200),
	"FNCION" VARCHAR2(4000) CONSTRAINT "DF_S_MTD_ASIG_FNCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_MTD_ASIG_COD_MTD_ASIG_PK" PRIMARY KEY ("CDGO_MTDO_ASGNCION")
  USING INDEX  ENABLE
   ) ;

