
  CREATE TABLE "DF_S_PAISES"
   (	"ID_PAIS" NUMBER(15,0) CONSTRAINT "DF_S_PAISES_ID_PAIS_NN" NOT NULL ENABLE,
	"CDGO_PAIS" VARCHAR2(3) CONSTRAINT "DF_S_PAISES_CDGO_PAIS_NN" NOT NULL ENABLE,
	"NMBRE_PAIS" VARCHAR2(50) CONSTRAINT "DF_S_PAISES_NMBRE_PAIS_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_PAISES_ID_PAIS_PK" PRIMARY KEY ("ID_PAIS")
  USING INDEX  ENABLE
   ) ;

