
  CREATE TABLE "DF_S_INDICADORES_ECONOMICO"
   (	"ID_INDCDOR_ECNMCO" NUMBER(15,0) CONSTRAINT "DF_S_INDI_ECON_ID_INDC_ECNM_NN" NOT NULL ENABLE,
	"CDGO_INDCDOR_TPO" VARCHAR2(5) CONSTRAINT "DF_S_INDI_ECON_CDG_INDC_TIP_NN" NOT NULL ENABLE,
	"FCHA_DSDE" DATE CONSTRAINT "DF_S_INDI_ECON_FCHA_DSDE_NN" NOT NULL ENABLE,
	"FCHA_HSTA" DATE CONSTRAINT "DF_S_INDI_ECON_FCHA_HSTA_NN" NOT NULL ENABLE,
	"VLOR" NUMBER(16,2) CONSTRAINT "DF_S_INDI_ECON_VLOR_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_INDI_ECON_ID_INDC_ECNM_PK" PRIMARY KEY ("ID_INDCDOR_ECNMCO")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_IND_ECO_CD_IN_TP_FD_FH_UN" UNIQUE ("CDGO_INDCDOR_TPO", "FCHA_DSDE", "FCHA_HSTA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_INDI_ECON_CDG_INDC_TIP_FK" FOREIGN KEY ("CDGO_INDCDOR_TPO")
	  REFERENCES "DF_S_INDICADORES_TIPO" ("CDGO_INDCDOR_TPO") ENABLE
   ) ;

