
  CREATE TABLE "DF_S_SUJETOS_TIPO"
   (	"CDGO_SJTO_TPO" VARCHAR2(3) CONSTRAINT "DF_S_SJT_TPO_CDG_SJT_TPO_NN" NOT NULL ENABLE,
	"DSCRPCION_SJTO_TPO" VARCHAR2(50) CONSTRAINT "DF_S_SJT_TPO_DSC_SJT_TPO_NN" NOT NULL ENABLE,
	"TXTO_IDNTFCCION" VARCHAR2(50) DEFAULT NULL CONSTRAINT "DF_S_SJT_TPO_TXTO_INDTFC_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_SJT_TPO_CDG_SJT_TPO_PK" PRIMARY KEY ("CDGO_SJTO_TPO")
  USING INDEX  ENABLE
   ) ;

