
  CREATE TABLE "DF_S_VEHICULOS_HMLGA"
   (	"DSCRPCION_VHCLO_CLSE" VARCHAR2(50),
	"CDGO_VHCLO_CLSE" VARCHAR2(3),
	"DSCRPCION_VHCLO_MRCA" VARCHAR2(50),
	"CDGO_VHCLO_MRCA" VARCHAR2(10),
	"DSCRPCION_VHCLO_LNEA" VARCHAR2(200),
	"ID_VHCLO_LNEA" NUMBER,
	"CLNDRJE" NUMBER,
	"CPCDAD_CRGA" NUMBER,
	"CPCDAD_PSJRO" NUMBER,
	"MDLO" NUMBER(4,0),
	"GRPO" NUMBER
   ) ;

