
  CREATE TABLE "DF_S_DEFINICIONES"
   (	"CDGO_DFNCION" VARCHAR2(10) CONSTRAINT "DF_S_DEFIN_CDGO_DFNCION_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "DF_S_DEFIN_DSCRPCION_NN" NOT NULL ENABLE,
	"FMTO" VARCHAR2(1) CONSTRAINT "DF_S_DEFIN_FMTO_NN" NOT NULL ENABLE,
	"VLOR" VARCHAR2(50) CONSTRAINT "DF_S_DEFIN_VLOR_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_DEFIN_FMTO_CK" CHECK ( fmto in ('', '', '') ) ENABLE,
	 CONSTRAINT "DF_S_DEFIN_CDGO_DFNCION_PK" PRIMARY KEY ("CDGO_DFNCION")
  USING INDEX  ENABLE
   ) ;

