
  CREATE TABLE "DF_S_VEHICULOS_HOMOLOGA"
   (	"ID_VHCLO_HMLGA" NUMBER CONSTRAINT "DF_S_VH_HMLGA_ID_VH_HMLGA_NN" NOT NULL ENABLE,
	"VGNCIA_DSDE" NUMBER CONSTRAINT "DF_S_VH_HMLGA_VGCIA_DSDE_NN" NOT NULL ENABLE,
	"VGNCIA_HSTA" NUMBER CONSTRAINT "DF_S_VH_HMLGA_VGCIA_HSTA_NN" NOT NULL ENABLE,
	"CDGO_CLSE_ANTRIOR" VARCHAR2(3) CONSTRAINT "DF_S_VH_HMLGA_CDGO_CLSE_ANT_NN" NOT NULL ENABLE,
	"CDGO_CLSE_NVA" VARCHAR2(3) CONSTRAINT "DF_S_VH_HMLGA_CDGO_CLSE_NVA_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER CONSTRAINT "DF_S_VH_HMLGA_ORDEN_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_VH_HMLGA_ID_VH_HMLGA_PK" PRIMARY KEY ("ID_VHCLO_HMLGA")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_VH_HMLGA_VGCIA_HSTA_FK" FOREIGN KEY ("VGNCIA_HSTA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "DF_S_VH_HMLGA_CDGO_CLSE_NVA_FK" FOREIGN KEY ("CDGO_CLSE_NVA")
	  REFERENCES "DF_S_VEHICULOS_CLASE" ("CDGO_VHCLO_CLSE") ENABLE,
	 CONSTRAINT "DF_S_VH_HMLGA_CDGO_CLSE_ANT_FK" FOREIGN KEY ("CDGO_CLSE_ANTRIOR")
	  REFERENCES "DF_S_VEHICULOS_CLASE" ("CDGO_VHCLO_CLSE") ENABLE,
	 CONSTRAINT "DF_S_VH_HMLGA_VGCIA_DSDE_FK" FOREIGN KEY ("VGNCIA_DSDE")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE
   ) ;

