
  CREATE TABLE "DF_S_DESTINOS_IGAC"
   (	"CDGO_DSTNO_IGAC" VARCHAR2(10) CONSTRAINT "DF_S_DEST_IGAC_CDG_DSTN_IGA_NN" NOT NULL ENABLE,
	"NMBRE_DSTNO_IGAC" VARCHAR2(50) CONSTRAINT "DF_S_DEST_IGAC_NMB_DSTN_IGA_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_DEST_IGAC_CDG_DSTN_IGA_PK" PRIMARY KEY ("CDGO_DSTNO_IGAC")
  USING INDEX  ENABLE
   ) ;

