
  CREATE TABLE "DF_S_TERCEROS_TIPO"
   (	"CDGO_TRCRO_TPO" VARCHAR2(3) CONSTRAINT "DF_S_TRCRO_TPO_CDGO_TRC_TPO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "DF_S_TRCRO_TPO_DSCRPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "DF_S_TRCRO_TPO_CDGO_TRC_TPO_PK" PRIMARY KEY ("CDGO_TRCRO_TPO")
  USING INDEX  ENABLE
   ) ;

