
  CREATE TABLE "DF_S_VEHICULOS_TIPO_INGRESOS"
   (	"ID_TIPO_INGRESOS" NUMBER DEFAULT "GENESYS"."SEQ_TIPO_INGRESOS"."NEXTVAL" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"DSCRPCION_INGRSO" VARCHAR2(200),
	"TPO_INGRSO" VARCHAR2(2),
	"APLICA" VARCHAR2(1),
	"CDGO_MOTIVO" VARCHAR2(3) NOT NULL ENABLE,
	 PRIMARY KEY ("ID_TIPO_INGRESOS")
  USING INDEX  ENABLE,
	 CONSTRAINT "DF_S_VEHICULOS_TIPO_INGRESOS_FK" FOREIGN KEY ("CDGO_MOTIVO")
	  REFERENCES "SI_D_NOVEDADES_MOTIVO_VHCLO" ("CDGO_MOTIVO") ENABLE
   ) ;

