
  CREATE TABLE "DT_D_CONFIGURACIONES_GNRAL"
   (	"ID_CNFGRCION_GNRAL" NUMBER CONSTRAINT "DT_D_CONF_GNR_ID_CONF_GNRAL_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "DT_D_CONF_GNR_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"NMRO_RGSTRO_MXMO_SNCRNO" NUMBER DEFAULT 1000 CONSTRAINT "DT_D_CONF_GNR_NMR_RGT_MX_SN_NN" NOT NULL ENABLE,
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "DT_D_CONF_GNR_USER_DGT_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "DT_D_CONF_GNR_FCHA_DGT_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	"NMRO_JOB" NUMBER,
	"HORA_JOB" NUMBER,
	 CONSTRAINT "DT_D_CONF_GNR_ID_CONF_GNRAL_PK" PRIMARY KEY ("ID_CNFGRCION_GNRAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "DT_D_CONF_GNR_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

