
  CREATE TABLE "EBA_DEMO_CHART_BBALL"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CITY" VARCHAR2(20),
	"TEAM" VARCHAR2(30),
	"CONFERENCE" VARCHAR2(5),
	"WINS" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "EBA_DEMO_CHART_BBALL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

