
  CREATE TABLE "EBA_DEMO_CHART_STATS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(2),
	"COUNTRY" VARCHAR2(30),
	"EMPLOYEE" NUMBER,
	"EMPLOYER" NUMBER,
	"TOTAL" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "EBA_DEMO_CHART_STATS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

