
  CREATE TABLE "EBA_DEMO_MD_MILESTONES"
   (	"ID" NUMBER NOT NULL ENABLE,
	"PROJECT_ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(255) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(4000),
	"DUE_DATE" DATE NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	 CONSTRAINT "EBA_DEMO_MD_MILESTONES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "EBA_DEMO_MD_MSTONE_MD_FK" FOREIGN KEY ("PROJECT_ID")
	  REFERENCES "EBA_DEMO_MD_PROJECTS" ("ID") ON DELETE CASCADE ENABLE
   ) ;

