
  CREATE TABLE "EBA_GI_FLEX_PAGE_MAP"
   (	"ID" NUMBER,
	"FLEX_TABLE" VARCHAR2(128) NOT NULL ENABLE,
	"PAGE_ID" NUMBER NOT NULL ENABLE,
	"REGION_STATIC_ID" VARCHAR2(30) NOT NULL ENABLE,
	"FLEX_COLUMN_PREFIX" VARCHAR2(30) NOT NULL ENABLE,
	"REGION_TYPE" VARCHAR2(30) NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255),
	"CREATED" TIMESTAMP (6),
	"UPDATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6),
	 PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

