
  CREATE TABLE "EBA_DEMO_CHART_SAMPLE_NAMES"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SAMPLE_NAME" VARCHAR2(30) NOT NULL ENABLE,
	"SAMPLE_DATE" DATE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "EBA_DEMO_SAMPLES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

