
  CREATE TABLE "EBA_DEMO_MD_TEAM_MEMBERS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"USERNAME" VARCHAR2(255) NOT NULL ENABLE,
	"FULL_NAME" VARCHAR2(255) NOT NULL ENABLE,
	"EMAIL" VARCHAR2(255),
	"PROFILE" VARCHAR2(4000),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"UPDATED_BY" VARCHAR2(255) NOT NULL ENABLE,
	 CONSTRAINT "EBA_DEMO_MD_TEAM_MEMBERS_UK" UNIQUE ("USERNAME")
  USING INDEX  ENABLE,
	 CONSTRAINT "EBA_DEMO_MD_TEAM_MEMBERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

