
  CREATE TABLE "EBA_DEMO_CHART_STOCKS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ROW_VERSION_NUMBER" NUMBER,
	"STOCK_CODE" VARCHAR2(4),
	"STOCK_NAME" VARCHAR2(130),
	"PRICING_DATE" DATE,
	"PRICING_TIMESTAMP" TIMESTAMP (6),
	"PRICING_TIMESTAMP_TZ" TIMESTAMP (6) WITH TIME ZONE,
	"PRICING_TIMESTAMP_LTZ" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"OPENING_VAL" NUMBER,
	"HIGH" NUMBER,
	"LOW" NUMBER,
	"CLOSING_VAL" NUMBER,
	"VOLUME" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"CREATED_BY" VARCHAR2(255),
	"UPDATED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"UPDATED_BY" VARCHAR2(255),
	 CONSTRAINT "EBA_DEMO_CHART_STOCKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

