
  CREATE TABLE "ET_D_PROCESOS_ESTADO"
   (	"CDGO_PRCSO_ESTDO" VARCHAR2(3) CONSTRAINT "ET_D_PRCS_ESTDO_CDG_PRC_EST_NN" NOT NULL ENABLE,
	"DSCRPCION_ESTDO_PRCSO" VARCHAR2(100) CONSTRAINT "ET_D_PRCS_ESTDO_DSC_PRC_EST_NN" NOT NULL ENABLE,
	 CONSTRAINT "ET_D_PRCS_ESTDO_CDG_PRC_EST_PK" PRIMARY KEY ("CDGO_PRCSO_ESTDO")
  USING INDEX  ENABLE
   ) ;

