
  CREATE TABLE "ET_D_DATOS_TIPO"
   (	"CDGO_DTO_TPO" VARCHAR2(3) CONSTRAINT "ET_D_ARCHVO_DTO_CDGO_DTO_TP_NN" NOT NULL ENABLE,
	"DSCRPCION_DTO_TPO" VARCHAR2(100) CONSTRAINT "ET_D_ARCHVO_DTO_DSC_DTO_TPO_NN" NOT NULL ENABLE,
	 CONSTRAINT "ET_D_ARCHVO_DTO_CDGO_DTO_TP_PK" PRIMARY KEY ("CDGO_DTO_TPO")
  USING INDEX  ENABLE
   ) ;

