
  CREATE TABLE "ET_D_REGLAS_INTERMEDIA"
   (	"ID_RGLA_INTRMDIA" NUMBER(15,0) CONSTRAINT "ET_D_RGLA_INTER_ID_RG_INTER_NN" NOT NULL ENABLE,
	"ID_CRGA" NUMBER(15,0) CONSTRAINT "ET_D_RGLA_INTER_ID_CRGA_NN" NOT NULL ENABLE,
	"CRCTER_INCIAL" VARCHAR2(3),
	"CRCTER_FNAL" VARCHAR2(3),
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "ET_D_RGLA_INTER_DSCRPCION_NN" NOT NULL ENABLE,
	"CDGO_DTO_TPO" VARCHAR2(3),
	"PSCION" NUMBER(3,0),
	"NMBRE_CLMNA" VARCHAR2(30) CONSTRAINT "ET_D_RGLA_INTER_NMBRE_CLMNA_NN" NOT NULL ENABLE,
	"INDCDOR_VLDA" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "ET_D_RGLA_INTER_INDCDOR_VLD_NN" NOT NULL ENABLE,
	"VLOR1" VARCHAR2(30),
	"VLOR2" VARCHAR2(30),
	"ID_OPRDOR_TPO" NUMBER(2,0),
	"TMNO" NUMBER,
	"FRMATO" VARCHAR2(30),
	 CONSTRAINT "ET_D_RGLA_INTER_PSCION_NN" CHECK ( pscion is not null) ENABLE,
	 CONSTRAINT "ET_D_RGLA_INTER_ID_RG_INTER_PK" PRIMARY KEY ("ID_RGLA_INTRMDIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "ET_D_RGLA_INTR_ID_CRG_N_CLM_UN" UNIQUE ("ID_CRGA", "NMBRE_CLMNA")
  USING INDEX  ENABLE,
	 CONSTRAINT "ET_D_RGLA_INTER_ID_CRGA_FK" FOREIGN KEY ("ID_CRGA")
	  REFERENCES "ET_G_CARGA" ("ID_CRGA") ENABLE,
	 CONSTRAINT "ET_D_RGLA_INTER_CDGO_DTO_TP_FK" FOREIGN KEY ("CDGO_DTO_TPO")
	  REFERENCES "ET_D_DATOS_TIPO" ("CDGO_DTO_TPO") ENABLE,
	 CONSTRAINT "ET_D_RGLA_INTER_ID_OPRDOR_T_FK" FOREIGN KEY ("ID_OPRDOR_TPO")
	  REFERENCES "DF_S_OPERADORES_TIPO" ("ID_OPRDOR_TPO") ENABLE
   ) ;

