
  CREATE TABLE "ET_D_REGLAS_TRANSFORMACION"
   (	"ID_RGLA_TRNSFRMCION" NUMBER(15,0) CONSTRAINT "ET_D_RGL_TRNSFRM_ID_RGL_TRN_NN" NOT NULL ENABLE,
	"ID_CRGA" NUMBER(15,0) CONSTRAINT "ET_D_RGL_TRNSFRM_ID_CRGA_NN" NOT NULL ENABLE,
	"CLMNA_ORGEN" VARCHAR2(30),
	"ID_OPRDOR_TPO" NUMBER(2,0),
	"VLOR_INCIAL" VARCHAR2(30),
	"VLOR_TRNSFRMDO" VARCHAR2(30),
	 CONSTRAINT "ET_D_RGL_TRNSFRM_ID_RGL_TRN_PK" PRIMARY KEY ("ID_RGLA_TRNSFRMCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "ET_D_RGL_TRNSFRM_ID_CRGA_FK" FOREIGN KEY ("ID_CRGA")
	  REFERENCES "ET_G_CARGA" ("ID_CRGA") ENABLE,
	 CONSTRAINT "ET_D_RGL_TRNSFRM_ID_OPRD_TP_FK" FOREIGN KEY ("ID_OPRDOR_TPO")
	  REFERENCES "DF_S_OPERADORES_TIPO" ("ID_OPRDOR_TPO") ENABLE
   ) ;

