
  CREATE TABLE "ET_G_REGLAS_GESTION"
   (	"ID_RGLA_GSTION" NUMBER(15,0) CONSTRAINT "ET_D_RGLA_GSTION_ID_RG_GST_NN" NOT NULL ENABLE,
	"ID_CRGA" NUMBER(15,0) CONSTRAINT "ET_D_RGLA_GSTION_ID_CRGA_NN" NOT NULL ENABLE,
	"CLMNA_ORGEN" VARCHAR2(30),
	"NMBRE_TBLA_DSTNO" VARCHAR2(30),
	"NMBRE_CLMNA_DSTNO" VARCHAR2(30),
	"NMRO_ORDEN" NUMBER(3,0),
	"TPO_ORGEN" VARCHAR2(10) CONSTRAINT "ET_D_RGLA_GSTION_TPO_ORGEN_NN" NOT NULL ENABLE,
	"VLOR_FJO" VARCHAR2(30),
	"FRMTO" VARCHAR2(30),
	"CDGO_DTO_TPO" VARCHAR2(3) DEFAULT 'C',
	 CONSTRAINT "ET_D_RGLA_GSTION_ID_RG_GST_PK" PRIMARY KEY ("ID_RGLA_GSTION")
  USING INDEX  ENABLE,
	 CONSTRAINT "ET_D_RGLA_GSTION_TPO_ORGEN_CK" CHECK (tpo_orgen in ('COLUMNA','FIJO')) ENABLE,
	 CONSTRAINT "ET_G_RGLAS_GSTN_CDG_DTO_TPO_NN" CHECK ( cdgo_dto_tpo is not null ) ENABLE,
	 CONSTRAINT "ET_G_RGLAS_GSTN_CDG_DTO_TPO_FK" FOREIGN KEY ("CDGO_DTO_TPO")
	  REFERENCES "ET_D_DATOS_TIPO" ("CDGO_DTO_TPO") ENABLE,
	 CONSTRAINT "ET_D_RGLA_GSTION_ID_CRGA_FK" FOREIGN KEY ("ID_CRGA")
	  REFERENCES "ET_G_CARGA" ("ID_CRGA") ENABLE
   ) ;

