
  CREATE TABLE "ET_G_PROCESOS_CARGA"
   (	"ID_PRCSO_CRGA" NUMBER(15,0),
	"ID_CRGA" NUMBER(15,0) CONSTRAINT "ET_G_PRCS_CRGA_ID_CRGA_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "ET_G_PRCS_CRGA_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0),
	"VGNCIA" NUMBER(15,0),
	"FILE_BLOB" BLOB,
	"FILE_NAME" VARCHAR2(255),
	"FILE_MIMETYPE" VARCHAR2(100),
	"CDGO_PRCSO_ESTDO" VARCHAR2(3) DEFAULT 'SE',
	"ID_ADTRIA" NUMBER(15,0),
	"LNEAS_ENCBZDO" NUMBER(5,0) DEFAULT 0,
	"LNEAS_RSMEN" NUMBER(10,0) DEFAULT 0,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0),
	"ID_PRDO" NUMBER(15,0),
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp,
	"ID_USRIO" NUMBER NOT NULL ENABLE,
	"INDCDOR_PRCSDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "ET_G_PRCS_CRGA_INDCDR_PRCSD_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA_PDRE" NUMBER,
	 CONSTRAINT "ET_G_PRCS_CRGA_ID_USRIO_NN" CHECK ( id_usrio is not null ) ENABLE,
	 CONSTRAINT "ET_G_PRCS_INTRM_ID_PRCS_CRG_NN" CHECK (id_prcso_crga is not null ) ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_CDG_EST_PRCS_FK" FOREIGN KEY ("CDGO_PRCSO_ESTDO")
	  REFERENCES "ET_D_PROCESOS_ESTADO" ("CDGO_PRCSO_ESTDO") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_ID_PR_CR_PD_FK" FOREIGN KEY ("ID_PRCSO_CRGA_PDRE")
	  REFERENCES "ET_G_PROCESOS_CARGA" ("ID_PRCSO_CRGA") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_ID_CRGA_FK" FOREIGN KEY ("ID_CRGA")
	  REFERENCES "ET_G_CARGA" ("ID_CRGA") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_ID_SBIMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "ET_G_PRCS_CRGA_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   )
 LOB ("FILE_BLOB") STORE AS SECUREFILE "SYS_LOB0000094595C00006$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  CREATE UNIQUE INDEX "ET_G_PRCS_CRGA_FILE_NAME_UN" ON "ET_G_PROCESOS_CARGA" ("FILE_NAME", "CDGO_CLNTE")
  ;
  CREATE INDEX "ET_G_PROC_ID_IM" ON "ET_G_PROCESOS_CARGA" ("ID_PRCSO_CRGA", "CDGO_CLNTE", "ID_IMPSTO", "ID_IMPSTO_SBMPSTO")
  ;
ALTER TABLE "ET_G_PROCESOS_CARGA" ADD CONSTRAINT "ET_G_PRCS_CRGA_FILE_NAME_UN" UNIQUE ("FILE_NAME", "CDGO_CLNTE")
  USING INDEX "ET_G_PRCS_CRGA_FILE_NAME_UN"  ENABLE;
ALTER TABLE "ET_G_PROCESOS_CARGA" ADD CONSTRAINT "ET_G_PRCS_CRGA_ID_PROC_CRGA_PK" PRIMARY KEY ("ID_PRCSO_CRGA")
  USING INDEX "ET_G_PROC_ID_IM"  ENABLE;

