
  CREATE TABLE "FI_D_FUENTES_EXTERNA"
   (	"ID_FNTES_EXTRNA" NUMBER CONSTRAINT "FI_D_FNTES_EXTRNA_ID_FNTS_NN" NOT NULL ENABLE,
	"CDGO_FNTES_EXTRNA" VARCHAR2(5) CONSTRAINT "FI_D_FNTES_EXTRNA_CDGO_FNTS_NN" NOT NULL ENABLE,
	"DSCPCION_FNTES_EXTRNA" VARCHAR2(50) CONSTRAINT "FI_D_FNTES_EXTRNA_DSC_FNTES_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "FI_D_FNTES_EXTRNA_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "FI_D_FNTES_EXTRNA_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_D_FNTES_EXTRNA_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "FI_D_FNTES_EXTRNA_ID_FNTS_PK" PRIMARY KEY ("ID_FNTES_EXTRNA")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_FNTES_EXTRNA_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

