
  CREATE TABLE "FI_D_FUENTE_TPO_BSE_SANCION"
   (	"ID_FUENTE_TIPO_BASE" NUMBER CONSTRAINT "FI_D_FNT_T_B_SCN_ID_FNT_T_B_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "FI_D_FNT_T_B_SCN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_FUENTE" VARCHAR2(5) CONSTRAINT "FI_D_FNT_T_B_SCN_CDGO_FUENT_NN" NOT NULL ENABLE,
	"NMBRE_FUENTE" VARCHAR2(100) CONSTRAINT "FI_D_FNT_T_B_SCN_NMBRE_FUNT_NN" NOT NULL ENABLE,
	"ID_PRGRMA" NUMBER CONSTRAINT "FI_D_FNT_T_B_SCN_ID_PRGRMA_NN" NOT NULL ENABLE,
	"ID_SBPRGRMA" NUMBER CONSTRAINT "FI_D_FNT_T_B_SCN_ID_SBPRGRM_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "FI_D_FNT_T_B_SCN_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "FI_D_FNT_T_B_SCN_ID_IMPS_SB_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER CONSTRAINT "FI_D_FNT_T_B_SCN_ORDEN_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1),
	 CONSTRAINT "FI_D_FNT_T_B_SCN_CDGO_FUENT_UN" UNIQUE ("CDGO_FUENTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_FNT_T_B_SCN_ORDEN_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "FI_D_FNT_T_B_SCN_ID_FNT_T_B_PK" PRIMARY KEY ("ID_FUENTE_TIPO_BASE")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_FNT_T_B_SCN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "FI_D_FNT_T_B_SCN_ID_PRGRMA_FK" FOREIGN KEY ("ID_PRGRMA")
	  REFERENCES "FI_D_PROGRAMAS" ("ID_PRGRMA") ENABLE,
	 CONSTRAINT "FI_D_FNT_T_B_SCN_ID_IMPS_SB_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "FI_D_FNT_T_B_SCN_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "FI_D_FNT_T_B_SCN_ID_SBPRGRM_FK" FOREIGN KEY ("ID_SBPRGRMA")
	  REFERENCES "FI_D_SUBPROGRAMAS" ("ID_SBPRGRMA") ENABLE
   ) ;

