
  CREATE TABLE "FI_D_SANCIONES"
   (	"ID_SNCION" NUMBER CONSTRAINT "FI_D_SNCION_ID_SNCION_NN" NOT NULL ENABLE,
	"CDGO_SNCION" VARCHAR2(3) CONSTRAINT "FI_D_SNCION_COD_SNCION_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "FI_D_SNCION_DSCRPCION_NN" NOT NULL ENABLE,
	"NMBRE_SNCION" VARCHAR2(100) CONSTRAINT "FI_D_SNCION_NMBRE_SNCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "FI_D_SNCION_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_D_SNCION_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "FI_D_SNCION_ID_SNCION_PK" PRIMARY KEY ("ID_SNCION")
  USING INDEX  ENABLE
   ) ;

