
  CREATE TABLE "FI_D_PROGRAMAS_FUNCIONARIO"
   (	"ID_PRGRMA_FNCNRIO" NUMBER CONSTRAINT "FI_D_PGRMA_FNCNR_ID_PGR_FNC_NN" NOT NULL ENABLE,
	"ID_FNCNRIO" NUMBER CONSTRAINT "FI_D_PGRMA_FNCNR_ID_FNCNRIO_NN" NOT NULL ENABLE,
	"ID_PRGRMA" NUMBER CONSTRAINT "FI_D_PGRMA_FNCNR_ID_PRGRMA_NN" NOT NULL ENABLE,
	"ID_SBPRGRMA" NUMBER,
	"ACTVO" VARCHAR2(1) CONSTRAINT "FI_D_PGRMA_FNCNR_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_D_PGRMA_FNCNR_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "FI_D_PGRMA_FNCNR_ID_PGR_FNC_PK" PRIMARY KEY ("ID_PRGRMA_FNCNRIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_PGRMA_FNCNR_IDFN_IDPRG_UN" UNIQUE ("ID_FNCNRIO", "ID_PRGRMA")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_PGRMA_FNCNR_IDF_IDPIDS_UN" UNIQUE ("ID_FNCNRIO", "ID_PRGRMA", "ID_SBPRGRMA")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_PGRMA_FNCNR_ID_SBPRGRM_FK" FOREIGN KEY ("ID_SBPRGRMA")
	  REFERENCES "FI_D_SUBPROGRAMAS" ("ID_SBPRGRMA") ENABLE,
	 CONSTRAINT "FI_D_PGRMA_FNCNR_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "FI_D_PGRMA_FNCNR_ID_PRGRMA_FK" FOREIGN KEY ("ID_PRGRMA")
	  REFERENCES "FI_D_PROGRAMAS" ("ID_PRGRMA") ENABLE
   ) ;

