
  CREATE TABLE "FI_D_PROGRAMAS_SANCION"
   (	"ID_PRGRMA_SNCION" NUMBER CONSTRAINT "FI_D_PRGRM_SNCN_ID_PRG_SNCN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "FI_D_PRGRM_SNCN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_PRGRMA" NUMBER CONSTRAINT "FI_D_PRGRM_SNCN_ID_PRGRMA_NN" NOT NULL ENABLE,
	"VLR_SNCION" NUMBER CONSTRAINT "FI_D_PRGRM_SNCN_VLR_SNCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_D_PRGRM_SNCN_CD_CL_ID_PRG_UN" UNIQUE ("CDGO_CLNTE", "ID_PRGRMA")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_PRGRM_SNCN_ID_PRG_SNCN_PK" PRIMARY KEY ("ID_PRGRMA_SNCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_PRGRM_SNCN_ID_PRGRMA_FK" FOREIGN KEY ("ID_PRGRMA")
	  REFERENCES "FI_D_PROGRAMAS" ("ID_PRGRMA") ENABLE,
	 CONSTRAINT "FI_D_PRGRM_SNCN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

