
  CREATE TABLE "FI_D_TIPO_BASE_SANCION"
   (	"ID_TPO_BSE_SNCION" NUMBER CONSTRAINT "FI_D_TP_BS_SNCN_ID_TP_BS_SN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "FI_D_TP_BS_SNCN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_TPO_BSE_SNCION" VARCHAR2(3) CONSTRAINT "FI_D_TP_BS_SNCN_CD_TP_BS_SN_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(1000) CONSTRAINT "FI_D_TP_BS_SNCN_DSCRPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_D_TP_BS_SNCN_ID_TP_BS_SN_PK" PRIMARY KEY ("ID_TPO_BSE_SNCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_TP_BS_SNCN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

