
  CREATE TABLE "FI_D_FUENTES_EXTERNA_CARGA"
   (	"ID_FNTES_EXTRNA_CRGA" NUMBER CONSTRAINT "FI_D_FNT_CRGA_ID_FNT_CRGA_NN" NOT NULL ENABLE,
	"ID_FNTES_EXTRNA" NUMBER CONSTRAINT "FI_D_FNT_EXT_CRGA_ID_FNTS_NN" NOT NULL ENABLE,
	"ID_CRGA" NUMBER CONSTRAINT "FI_D_FNT_EXT_CRGA_ID_CRGA_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "FI_D_FNT_EXT_CRGA_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_D_FNT_EXT_CRGA_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "FI_D_FNT_CRGA_ID_FNT_CRGA_PK" PRIMARY KEY ("ID_FNTES_EXTRNA_CRGA")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_D_FNT_EXT_CRGA_ID_CRGA_FK" FOREIGN KEY ("ID_CRGA")
	  REFERENCES "ET_G_CARGA" ("ID_CRGA") ENABLE,
	 CONSTRAINT "FI_D_FNT_EXT_CRGA_ID_FNTS_FK" FOREIGN KEY ("ID_FNTES_EXTRNA")
	  REFERENCES "FI_D_FUENTES_EXTERNA" ("ID_FNTES_EXTRNA") ENABLE
   ) ;

