
  CREATE TABLE "FI_G_FUENTES_EXTERNA_DIAN"
   (	"ID_FNTE_EXTRNA_DIAN" NUMBER CONSTRAINT "FI_G_FN_EXT_DIAN_ID_FN_EX_D_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER,
	"NIT" NUMBER,
	"DGTO_VRFCCION" NUMBER,
	"TPO_CNTRBYNTE" VARCHAR2(50),
	"TPO_DCMNTO" VARCHAR2(100),
	"IDNTFCCION" NUMBER,
	"RZON_SCIAL" VARCHAR2(100),
	"NMBRE_CMRCIAL" VARCHAR2(100),
	"CDGO_MNCPIO" VARCHAR2(10),
	"DRCCION" VARCHAR2(100),
	"CRREO_ELCTRNICO" VARCHAR2(100),
	"APRTDO_AEREO" VARCHAR2(100),
	"TLFNO_1" NUMBER,
	"TLFNO_2" NUMBER,
	"ACTVDAD" VARCHAR2(100),
	"FCHA_INCIO_ACTVDAD" DATE,
	"ADMNSTRCION" VARCHAR2(50),
	"ID_SJTO_IMPSTO" NUMBER,
	"ID_FNTE_EXTRNA_CRGA" NUMBER CONSTRAINT "FI_G_FN_EXT_DIAN_ID_F_E_CA_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_G_FN_EXT_DIAN_ID_FN_EX_D_PK" PRIMARY KEY ("ID_FNTE_EXTRNA_DIAN")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_G_FN_EXT_DIAN_ID_F_E_CA_FK" FOREIGN KEY ("ID_FNTE_EXTRNA_CRGA")
	  REFERENCES "FI_G_FUENTE_EXTERNA_CARGA" ("ID_FNTE_EXTRNA_CRGA") ENABLE,
	 CONSTRAINT "FI_G_FN_EXT_DIAN_CDGO_CLNT_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "FI_G_FN_EXT_DIAN_ID_SJ_IMP_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") ENABLE
   ) ;

