
  CREATE TABLE "FI_G_EXPNDNTS_ANALISIS_OBSVCION"
   (	"ID_EXPDNTE_ANLSS_OBSVCN" NUMBER CONSTRAINT "FI_G_EXP_ANL_OB_ID_EX_AN_OB_NN" NOT NULL ENABLE,
	"ID_EXPDNTE_ANLSIS" NUMBER,
	"ID_FLJO_TREA" NUMBER CONSTRAINT "FI_G_EXP_ANL_OB_ID_FLJO_TRA_NN" NOT NULL ENABLE,
	"FCHA" TIMESTAMP (6),
	"ID_USRIO" NUMBER,
	"ASNTO_OBSRVCION" VARCHAR2(200),
	"OBSRVCION" VARCHAR2(3000),
	"INDCDOR_CNFRMDO" VARCHAR2(1) DEFAULT ('N'),
	"FCHA_OBSRVCION" TIMESTAMP (6),
	"FCHA_ULTMA_ACTLZCION" TIMESTAMP (6),
	 CONSTRAINT "FI_G_EXP_ANL_OB_INDDR_CNFRM_CH" CHECK (indcdor_cnfrmdo in ('S','N')) ENABLE,
	 CONSTRAINT "FI_G_EXP_ANL_OB_ID_EX_AN_OB_PK" PRIMARY KEY ("ID_EXPDNTE_ANLSS_OBSVCN")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_G_EXP_ANL_OB_ID_EXTE_ANS_FK" FOREIGN KEY ("ID_EXPDNTE_ANLSIS")
	  REFERENCES "FI_G_EXPEDIENTES_ANALISIS" ("ID_EXPDNTE_ANLSIS") ENABLE,
	 CONSTRAINT "FI_G_EXP_ANL_OB_ID_FLJO_TRA_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE,
	 CONSTRAINT "FI_G_EXP_ANL_OB_ID_USR_RCHZ_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

