
  CREATE TABLE "FI_G_FUENTES_ORIGEN"
   (	"ID_FUENTE_ORIGEN" NUMBER CONSTRAINT "FI_G_FUENTE_ORGN_ID_FNT_ORG_NN" NOT NULL ENABLE,
	"CDGO_FUENTE" VARCHAR2(4),
	"CDGO_CLNTE" NUMBER CONSTRAINT "FI_G_FUENTE_ORGN_CDGO_CLN_NN" NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(1000) CONSTRAINT "FI_G_FUENTE_ORGN_IDNTFCCN_NN" NOT NULL ENABLE,
	"RAZON_SOCIAL" VARCHAR2(1000),
	"CDGO_IMPSTO" VARCHAR2(3) CONSTRAINT "FI_G_FUENTE_ORGN_CDGO_IMP_NN" NOT NULL ENABLE,
	"VGNCIA" VARCHAR2(5) CONSTRAINT "FI_G_FUENTE_ORGN_VGNCIA_NN" NOT NULL ENABLE,
	"PRDO" VARCHAR2(5) CONSTRAINT "FI_G_FUENTE_ORIGEN_PRDO_NN" NOT NULL ENABLE,
	"CDGO_PRDCDAD" VARCHAR2(3) CONSTRAINT "FI_G_FUENTE_ORGN_CDG_PRCD_NN" NOT NULL ENABLE,
	"VLR_BASE" VARCHAR2(1000) CONSTRAINT "FI_G_FUENTE_ORGN_VLR_BASE_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER CONSTRAINT "FI_G_FUENTE_ORGN_ID_PRC_C_NN" NOT NULL ENABLE,
	"ID_PRCSO_INTRMDIA" NUMBER CONSTRAINT "FI_G_FUENTE_ORGN_ID_PRC_I_NN" NOT NULL ENABLE,
	"NMERO_LNEA" NUMBER CONSTRAINT "FI_G_FUENTE_ORGN_NMERO_LN_NN" NOT NULL ENABLE,
	"CDGO_EXGNA_TPO_RGSTRO" VARCHAR2(3),
	"FCHA_MATRCLA" VARCHAR2(1000),
	"FCHA_REGISTRO" TIMESTAMP (6) DEFAULT systimestamp,
	"CDGO_SBIMPSTO" VARCHAR2(3),
	"CDGO_TRBTO_ACTO" VARCHAR2(5),
	"NMRO_CNTRTO" VARCHAR2(1000),
	"OBJETO" VARCHAR2(1000),
	 CONSTRAINT "FI_G_FUENTE_ORGN_ID_FNT_ORG_PK" PRIMARY KEY ("ID_FUENTE_ORIGEN")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_G_FUENTE_ORGN_CDGO_CLN_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "FI_G_FUENTE_ORGN_ID_PRC_I_FK" FOREIGN KEY ("ID_PRCSO_INTRMDIA")
	  REFERENCES "ET_G_PROCESOS_INTERMEDIA" ("ID_PRCSO_INTRMDIA") ENABLE
   ) ;

