
  CREATE TABLE "FI_G_FISCALIZACION_EXPDNTE"
   (	"ID_FSCLZCION_EXPDNTE" NUMBER CONSTRAINT "FI_G_FSCLZCN_EXP_ID_FSC_EXP_NN" NOT NULL ENABLE,
	"ID_CNDDTO" NUMBER CONSTRAINT "FI_G_FSCLZCN_EXP_ID_CNDDTO_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER CONSTRAINT "FI_G_FSCLZCN_EXP_ID_INST_FL_NN" NOT NULL ENABLE,
	"CDGO_EXPDNTE_ESTDO" VARCHAR2(3) CONSTRAINT "FI_G_FSCLZCN_EXP_CD_EXP_EST_NN" NOT NULL ENABLE,
	"ID_EXPDNTE" NUMBER CONSTRAINT "FI_G_FSCLZCN_EXP_ID_EXPDNTE_NN" NOT NULL ENABLE,
	"FCHA_APRTRA" TIMESTAMP (6) DEFAULT sysdate CONSTRAINT "FI_G_FSCLZCN_EXP_FCHA_APRTR_NN" NOT NULL ENABLE,
	"FCHA_CRRE" TIMESTAMP (6),
	"ID_FNCNRIO" NUMBER CONSTRAINT "FI_G_FSCLZCN_EXP_ID_FNCNRIO_NN" NOT NULL ENABLE,
	"ID_FSCLZCION_EXPDNTE_PDRE" NUMBER,
	"NMRO_EXPDNTE" VARCHAR2(100) CONSTRAINT "FI_G_FSCLZCN_EXP_NMR_EXPDNT_NN" NOT NULL ENABLE,
	 CONSTRAINT "FI_G_FSCLZCN_EXP_ID_FSC_EXP_PK" PRIMARY KEY ("ID_FSCLZCION_EXPDNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "FI_G_FSCLZCN_EXP_ID_F_EX_PD_FK" FOREIGN KEY ("ID_FSCLZCION_EXPDNTE_PDRE")
	  REFERENCES "FI_G_FISCALIZACION_EXPDNTE" ("ID_FSCLZCION_EXPDNTE") ENABLE,
	 CONSTRAINT "FI_G_FSCLZCN_EXP_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "FI_G_FSCLZCN_EXP_ID_CNDDTO_FK" FOREIGN KEY ("ID_CNDDTO")
	  REFERENCES "FI_G_CANDIDATOS" ("ID_CNDDTO") ENABLE,
	 CONSTRAINT "FI_G_FSCLZCN_EXP_ID_INST_FL_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "FI_G_FSCLZCN_EXP_ID_EXPDNTE_FK" FOREIGN KEY ("ID_EXPDNTE")
	  REFERENCES "GD_G_EXPEDIENTES" ("ID_EXPDNTE") ENABLE,
	 CONSTRAINT "FI_G_FSCLZCN_EXP_CD_EXP_EST_FK" FOREIGN KEY ("CDGO_EXPDNTE_ESTDO")
	  REFERENCES "FI_D_EXPEDIENTE_ESTADO" ("CDGO_EXPDNTE_ESTDO") ENABLE
   ) ;

