
  CREATE TABLE "GD_D_TRD_SERIE"
   (	"ID_TRD_SRIE" NUMBER CONSTRAINT "GD_D_TRD_SERIE_ID_TRD_SRIE_NN" NOT NULL ENABLE,
	"ID_TRD" NUMBER CONSTRAINT "GD_D_TRD_SERIE_ID_TRD_NN" NOT NULL ENABLE,
	"ID_SRIE" NUMBER CONSTRAINT "GD_D_TRD_SERIE_ID_SRIE_NN" NOT NULL ENABLE,
	"ID_SBSRIE" NUMBER,
	"TMPO_GSTION" NUMBER CONSTRAINT "GD_D_TRD_SERIE_TMPO_GSTION_NN" NOT NULL ENABLE,
	"TMPO_CNTRAL" NUMBER CONSTRAINT "GD_D_TRD_SERIE_TMPO_CNTRAL_NN" NOT NULL ENABLE,
	"TMPO_HSTRCO" NUMBER CONSTRAINT "GD_D_TRD_SERIE_TMPO_HSTRCO_NN" NOT NULL ENABLE,
	"INDCDOR_DSPCCION_CT" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_CT_NN" NOT NULL ENABLE,
	"INDCDOR_DSPCCION_E" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_E_NN" NOT NULL ENABLE,
	"INDCDOR_DSPCCION_S" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_S_NN" NOT NULL ENABLE,
	"INDCDOR_DSPCCION_MD" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_MD_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(4000),
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "GD_D_TRD_SERIE_FCHA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_ID_TRD_SRIE_PK" PRIMARY KEY ("ID_TRD_SRIE")
  USING INDEX (CREATE UNIQUE INDEX "GD_D_TRD_SERIE_ID_TRD_SERIE_PK" ON "GD_D_TRD_SERIE" ("ID_TRD_SRIE")
  )  ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_S_CK" CHECK (indcdor_dspccion_s in ('S','N')) ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_MD_CK" CHECK (indcdor_dspccion_md in ('S','N')) ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_I_T_I_S_I_SB_UN" UNIQUE ("ID_TRD", "ID_SRIE", "ID_SBSRIE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_E_CK" CHECK (indcdor_dspccion_e in ('S','N')) ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_INDCD_DSP_CT_CK" CHECK (indcdor_dspccion_ct in ('S','N')) ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_ID_TRD_FK" FOREIGN KEY ("ID_TRD")
	  REFERENCES "GD_D_TRD" ("ID_TRD") ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_ID_SRIE_FK" FOREIGN KEY ("ID_SRIE")
	  REFERENCES "GD_D_SERIES" ("ID_SRIE") ENABLE,
	 CONSTRAINT "GD_D_TRD_SERIE_ID_SBSRIE_FK" FOREIGN KEY ("ID_SBSRIE")
	  REFERENCES "GD_D_SERIES" ("ID_SRIE") ENABLE
   ) ;

