
  CREATE TABLE "GD_D_DOCUMENTOS_TIPO"
   (	"ID_DCMNTO_TPO" NUMBER CONSTRAINT "GD_D_DCMNTO_TPO_ID_DCMNT_TP_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GD_D_DCMNTO_TPO_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_DCMNTO_TPO" VARCHAR2(10) CONSTRAINT "GD_D_DCMNTO_TPO_CDGO_DCM_TP_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(50) CONSTRAINT "GD_D_DCMNTO_TPO_NM_DCM_TP_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "GD_D_DCMNTO_TPO_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GD_D_DCMNTO_TPO_ID_DCMNT_TP_PK" PRIMARY KEY ("ID_DCMNTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_DCMNTO_TPO_CDGO_DCM_TP_UN" UNIQUE ("CDGO_DCMNTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_DCMNTO_TPO_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GD_D_DCMNTO_TPO_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

