
  CREATE TABLE "GD_D_SERIES"
   (	"ID_SRIE" NUMBER CONSTRAINT "GD_D_SRIE_ID_SRIE_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GD_D_SRIE_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_SRIE" VARCHAR2(50) CONSTRAINT "GD_D_SRIE_CDGO_SRIE_NN" NOT NULL ENABLE,
	"NMBRE_SRIE" VARCHAR2(100) CONSTRAINT "GD_D_SRIE_NMBRE_SRIE_NN" NOT NULL ENABLE,
	"ID_SRIE_PDRE" NUMBER,
	"FCHA_INCIO" TIMESTAMP (6) CONSTRAINT "GD_D_SRIE_FCHA_INCIO_NN" NOT NULL ENABLE,
	"FCHA_FIN" TIMESTAMP (6) CONSTRAINT "GD_D_SRIE_FCHA_FIN_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(1000) CONSTRAINT "GD_D_SRIE_OBSRVCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "GD_D_SRIE_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GD_D_SRIE_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GD_D_SRIE_ID_SRIE_PK" PRIMARY KEY ("ID_SRIE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_SRIE_CDGO_SRIE_UN" UNIQUE ("CDGO_SRIE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_SRIE_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GD_D_SRIE_ID_SRIE_PDRE_FK" FOREIGN KEY ("ID_SRIE_PDRE")
	  REFERENCES "GD_D_SERIES" ("ID_SRIE") ENABLE
   ) ;

