
  CREATE TABLE "GD_D_DOCUMENTOS_TIPO_MTDTA"
   (	"ID_DCMNTO_TPO_MTDTA" NUMBER CONSTRAINT "GD_D_DCM_TPO_MTD_ID_DC_TP_M_NN" NOT NULL ENABLE,
	"ID_DCMNTO_TPO" NUMBER CONSTRAINT "GD_D_DCM_TPO_MTD_ID_DCM_TPO_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(50) CONSTRAINT "GD_D_DCM_TPO_MTD_NMBRE_NN" NOT NULL ENABLE,
	"DTO_TPO" VARCHAR2(1) DEFAULT 'C' CONSTRAINT "GD_D_DCM_TPO_MTD_DTO_TPO_NN" NOT NULL ENABLE,
	"OBJTO_TPO" VARCHAR2(1) DEFAULT 'T' CONSTRAINT "GD_D_DCM_TPO_MTD_OBJTO_TPO_NN" NOT NULL ENABLE,
	"ORGEN_TPO" VARCHAR2(1),
	"ORGEN" VARCHAR2(4000),
	"INDCDOR_RQRDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GD_D_DCM_TPO_MTD_INDCD_RQRD_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GD_D_DCM_TPO_MTD_ACTVO_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER DEFAULT 1 CONSTRAINT "GD_D_DCM_TPO_MTD_ORDEN_NN" NOT NULL ENABLE,
	"INDCDOR_UNCO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GD_D_DCM_TPO_MTD_INDCDR_UNC_NN" NOT NULL ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_INDCD_RQRD_CK" CHECK (indcdor_rqrdo in ('S','N')) ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_OBJTO_TPO_CK" CHECK (objto_tpo in ('T','S','A')) ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_ID_D_T_NMB_UN" UNIQUE ("ID_DCMNTO_TPO", "NMBRE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_DTO_TPO_CK" CHECK (dto_tpo in ('C','N','D')) ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_INDCDR_UNC_CK" CHECK (indcdor_unco in ('S','N')) ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_OR_ID_DC_T_UN" UNIQUE ("ORDEN", "ID_DCMNTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_ID_DC_TP_M_PK" PRIMARY KEY ("ID_DCMNTO_TPO_MTDTA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_ORGEN_TPO_CK" CHECK (orgen_tpo in ('E','S')) ENABLE,
	 CONSTRAINT "GD_D_DCM_TPO_MTD_ID_DCM_TPO_FK" FOREIGN KEY ("ID_DCMNTO_TPO")
	  REFERENCES "GD_D_DOCUMENTOS_TIPO" ("ID_DCMNTO_TPO") ENABLE
   ) ;

