
  CREATE TABLE "GD_G_NORMATIVIDADES"
   (	"ID_NRMTVDAD" NUMBER CONSTRAINT "GD_G_NRMTVDDS_ID_NRMTVDDES_NN" NOT NULL ENABLE,
	"ID_NRMTVDDES_TPO" NUMBER CONSTRAINT "GD_G_NRMTVDDS_ID_NRMTVDD_TP_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GD_G_NRMTVDDS_COD_CLNTE_NN" NOT NULL ENABLE,
	"NMBRE_NRMTVA" VARCHAR2(100) CONSTRAINT "GD_G_NRMTVDDS_NMBRE_NRMTVA_NN" NOT NULL ENABLE,
	"NMRO_NRMTVA" VARCHAR2(10) CONSTRAINT "GD_G_NRMTVDDS_NMRO_NRMTVA_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(200) CONSTRAINT "GD_G_NRMTVDDS_DSCRPCION_NN" NOT NULL ENABLE,
	"FCHA_NRMTVA" TIMESTAMP (6) CONSTRAINT "GD_G_NRMTVDDS_FCHA_NRMTVA_NN" NOT NULL ENABLE,
	"FCHA_INCIO" TIMESTAMP (6) CONSTRAINT "GD_G_NRMTVDDS_FCHA_INCIO_NN" NOT NULL ENABLE,
	"FCHA_FNAL" TIMESTAMP (6) CONSTRAINT "GD_G_NRMTVDDS_FCHA_FNAL_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1),
	"FILE_BLOB" BLOB CONSTRAINT "GD_G_NRMTVDDS_FILE_BLOB_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255),
	"FILE_MIMETYPE" VARCHAR2(100),
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "GD_G_NRMTVDDS_USRIO_DGTA_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "GD_G_NRMTVDDS_FCHA_DGTA_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "GD_G_NRMTVDDS_ID_NRMTVDDES_PK" PRIMARY KEY ("ID_NRMTVDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_G_NRMTVDDS_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE
   ) ;

