
  CREATE TABLE "GD_G_EXPEDIENTES_DOCUMENTO"
   (	"ID_EXPDNTE_DCMNTO" NUMBER DEFAULT "GENESYS"."SQ_GD_G_EXPEDIENTES_DOCUMENTO"."NEXTVAL" CONSTRAINT "GD_G_EXP_DCM_ID_EXPDNT_DCMN_NN" NOT NULL ENABLE,
	"ID_EXPDNTE" NUMBER CONSTRAINT "GD_G_EXP_DCM_ID_EXPDNTE_NN" NOT NULL ENABLE,
	"ID_DCMNTO" NUMBER CONSTRAINT "GD_G_EXP_DCM_ID_DCMNTO_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "GD_G_EXP_DCM_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "GD_G_EXP_DCM_FCHA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GD_G_EXP_DCM_I_EXPDNT_I_DCT_UN" UNIQUE ("ID_EXPDNTE", "ID_DCMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_G_EXP_DCM_ID_EXPDNT_DCMN_PK" PRIMARY KEY ("ID_EXPDNTE_DCMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GD_G_EXP_DCM_ID_EXPDNTE_FK" FOREIGN KEY ("ID_EXPDNTE")
	  REFERENCES "GD_G_EXPEDIENTES" ("ID_EXPDNTE") ENABLE,
	 CONSTRAINT "GD_G_EXP_DCM_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

