
  CREATE TABLE "GF_D_SALDOS_FVOR_MVMNTS_TPO"
   (	"ID_SLDOS_FVOR_MVMNTO_TPO" NUMBER CONSTRAINT "GF_D_MVMN_TP_ID_MVMNT_TP_PK" NOT NULL ENABLE,
	"CDGO_MVMNTO" VARCHAR2(1) CONSTRAINT "GF_D_MVMN_TP_CDGO_MVMNTO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "GF_D_MVMN_TP_DSCRPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_D_MVMN_TP_CDGO_MVMNT_UN" UNIQUE ("CDGO_MVMNTO")
  USING INDEX (CREATE UNIQUE INDEX "GF_D_MVMN_TP_C_MVMNT_C_CLNT_UN" ON "GF_D_SALDOS_FVOR_MVMNTS_TPO" ("CDGO_MVMNTO")
  )  ENABLE,
	 CONSTRAINT "GF_D_MVMN_TP_ID_SL_FV_MV_TP_PK" PRIMARY KEY ("ID_SLDOS_FVOR_MVMNTO_TPO")
  USING INDEX  ENABLE
   ) ;

