
  CREATE TABLE "GF_D_TITULOS_JUDICIAL_AREA"
   (	"ID_TTLO_JDCIAL_AREA" NUMBER,
	"ID_AREA" NUMBER,
	"ACTVO" VARCHAR2(1) DEFAULT 'N',
	 CONSTRAINT "GF_D_TT_AR_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GF_D_TT_AR_ID_TTL_JDC_AREA_NN" CHECK ("ID_TTLO_JDCIAL_AREA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_D_TT_AR_ID_AREA_NN" CHECK ("ID_AREA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_D_TT_AR_ACTVO_NN" CHECK ("ACTVO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_D_TT_AR_ID_TTL_JDC_AREA_PK" PRIMARY KEY ("ID_TTLO_JDCIAL_AREA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_TT_AR_ID_AREA_FK" FOREIGN KEY ("ID_AREA")
	  REFERENCES "DF_C_AREAS" ("ID_AREA") ENABLE
   ) ;

