
  CREATE TABLE "GF_D_PRESCRPCNS_VLDCN_ASCDA"
   (	"ID_VLDCN_ASCDS" NUMBER CONSTRAINT "GF_D_PRC_VL_AS_ID_VLDC_ASDA_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GF_D_PRC_VL_AS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GF_D_PRC_VL_AS_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GF_D_PRC_VL_AS_ID_IMP_SBMP_NN" NOT NULL ENABLE,
	"ID_VLDCION" NUMBER CONSTRAINT "GF_D_PRC_VL_AS_ID_VLDC_NN" NOT NULL ENABLE,
	"RSPSTA_PSTVA" VARCHAR2(1000) CONSTRAINT "GF_D_PRC_VL_AS_RPTA_PTVA_NN" NOT NULL ENABLE,
	"RSPSTA_NGTVA" VARCHAR2(1000) CONSTRAINT "GF_D_PRC_VL_AS_RPTA_NGVA_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "GF_D_PRC_VL_AS_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_D_PRESCRIPCIONS_VLDCN_ASCDS" UNIQUE ("CDGO_CLNTE", "ID_IMPSTO", "ID_IMPSTO_SBMPSTO", "ID_VLDCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_PRC_VL_AS_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GF_D_PRC_VL_AS_ID_VLDC_ASDA_PK" PRIMARY KEY ("ID_VLDCN_ASCDS")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_PRC_VL_AS_ID_VLDC_FK" FOREIGN KEY ("ID_VLDCION")
	  REFERENCES "GF_D_PRESCRIPCIONES_VLDCION" ("ID_VLDCION") ENABLE,
	 CONSTRAINT "GF_D_PRC_VL_AS_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GF_D_PRC_VL_AS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_D_PRC_VL_AS_ID_IMP_SBMP_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE
   ) ;

