
  CREATE TABLE "GF_D_SALDOS_FAVOR_PARRAFO"
   (	"ID_SLDO_FVOR_PRRFO" NUMBER CONSTRAINT "GF_D_SL_FV_PR_ID_SL_FV_PRR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GF_D_SL_FV_PR_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_SLDO_FVOR_PRRFO" VARCHAR2(3) CONSTRAINT "GF_D_SL_FV_PR_CDGO_SL_FV_PR_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500) CONSTRAINT "GF_D_SL_FV_PR_DSCRPCION_NN" NOT NULL ENABLE,
	"PRRFO" CLOB CONSTRAINT "GF_D_SL_FV_PR_PRRFO_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER CONSTRAINT "GF_D_SL_FV_PR_ORDEN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_D_SL_FV_PR_CD_CL_C_S_F_P_UN" UNIQUE ("CDGO_CLNTE", "CDGO_SLDO_FVOR_PRRFO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_SL_FV_PR_ID_SL_FV_PRR_PK" PRIMARY KEY ("ID_SLDO_FVOR_PRRFO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_SL_FV_PR_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

