
  CREATE TABLE "GF_D_PRESCRIPCIONES_DCMNTO"
   (	"ID_PRSCRPCN_DCMNTO" NUMBER CONSTRAINT "GF_D_PRCS_DCMT_ID_PRSC_DCMT_NN" NOT NULL ENABLE,
	"ID_PRSCRPCION_TPO" NUMBER CONSTRAINT "GF_D_PRCS_DCMT_ID_PRSC_TPO_NN" NOT NULL ENABLE,
	"CDGO_RSPSTA" VARCHAR2(3),
	"ID_ACTOS_TPO_TREA" NUMBER CONSTRAINT "GF_D_PRCS_DCMT_ID_ACT_TP_TR_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA_CNFRMCION" NUMBER CONSTRAINT "GF_D_PRCS_DCMT_ID_FLJ_TR_CN_NN" NOT NULL ENABLE,
	"INDCDOR_RSLVE_PRSCRPCION" VARCHAR2(2) CONSTRAINT "GF_D_PRCS_DCMT_ID_IND_RS_PR_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER CONSTRAINT "GF_D_PRCS_DCMT_ID_ORDEN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_D_PRCS_DCMT_ID_PRSC_DCMT_PK" PRIMARY KEY ("ID_PRSCRPCN_DCMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_PRCS_DCMT_ID_IND_RS_PR_CK" CHECK (indcdor_rslve_prscrpcion in ('S', 'N')) ENABLE,
	 CONSTRAINT "GF_D_PRESCRIPCIONES_DCMNTO_UN" UNIQUE ("ID_PRSCRPCION_TPO", "CDGO_RSPSTA", "ID_ACTOS_TPO_TREA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_PRCS_DCMT_ID_PRSC_TPO_FK" FOREIGN KEY ("ID_PRSCRPCION_TPO")
	  REFERENCES "GF_D_PRESCRIPCIONES_TIPO" ("ID_PRSCRPCION_TPO") ENABLE,
	 CONSTRAINT "GF_D_PRCS_DCMT_CDGO_RSPSTA_FK" FOREIGN KEY ("CDGO_RSPSTA")
	  REFERENCES "GF_D_PRSCRPCNES_RSPSTA" ("CDGO_RSPSTA") ENABLE,
	 CONSTRAINT "GF_D_PRCS_DCMT_ID_ACT_TP_TR_FK" FOREIGN KEY ("ID_ACTOS_TPO_TREA")
	  REFERENCES "GN_D_ACTOS_TIPO_TAREA" ("ID_ACTOS_TPO_TREA") ENABLE,
	 CONSTRAINT "GF_D_PRCS_DCMT_ID_FLJ_TR_CN_FK" FOREIGN KEY ("ID_FLJO_TREA_CNFRMCION")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE
   ) ;

