
  CREATE TABLE "GF_D_PRESCRIPCIONES_PARRAFO"
   (	"ID_PRSCRPCION_PRRFO" NUMBER DEFAULT "GENESYS"."SQ_GF_D_PRESCRIPCIONES_PARRAFO"."NEXTVAL" CONSTRAINT "GF_D_PRSCRP_PR_ID_PRSCRP_PR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GF_D_PRSCRP_PR_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_PRRFO" VARCHAR2(3) CONSTRAINT "GF_D_PRSCRP_PR_CDGO_PRRFO_NN" NOT NULL ENABLE,
	"DSCRPCION_PRRFO" VARCHAR2(50) CONSTRAINT "GF_D_PRSCRP_PR_DSCRP_PRR_NN" NOT NULL ENABLE,
	"TXTO_PRRFO" CLOB CONSTRAINT "GF_D_PRSCRP_PR_TXTO_PRRFO_NN" NOT NULL ENABLE,
	"ID_RGLA_NGCIO_CLNTE_FNCION" NUMBER CONSTRAINT "GF_D_PRSCRP_PR_I_RG_NG_CL_F_NN" NOT NULL ENABLE,
	"INDCDR_CMPLE" VARCHAR2(1),
	"ACTVO" VARCHAR2(1),
	"CNSLTA_1" CLOB,
	"PRMTRO_1" CLOB,
	 CONSTRAINT "GF_D_PRSCRP_PR_ID_PRSCRP_PR_PK" PRIMARY KEY ("ID_PRSCRPCION_PRRFO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_D_PRSCRP_PR_INDCDR_CMPLE_CK" CHECK (indcdr_cmple in ('S', 'N')) ENABLE,
	 CONSTRAINT "GF_D_PRSCRP_PR_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GF_D_PRSCRP_PR_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_D_PRSCRP_PR_I_RG_NG_CL_F_FK" FOREIGN KEY ("ID_RGLA_NGCIO_CLNTE_FNCION")
	  REFERENCES "GN_D_RGLAS_NGCIO_CLNTE_FNC" ("ID_RGLA_NGCIO_CLNTE_FNCION") ENABLE
   ) ;

