
  CREATE TABLE "GF_D_TRAZA_ORIGEN"
   (	"CDGO_TRZA_ORGN" VARCHAR2(5) CONSTRAINT "GF_D_BLQ_ORG_CDGO_TRZ_ORGEN_NN" NOT NULL ENABLE,
	"DSCRIPCION" VARCHAR2(100) CONSTRAINT "GF_D_BLQ_ORG_DSCRPCION_NN" NOT NULL ENABLE,
	"NMBRE_TBLA" VARCHAR2(30) CONSTRAINT "GF_D_BLQ_ORG_NMBRE_TBLA_NN" NOT NULL ENABLE,
	"NMBRE_CLMNA" VARCHAR2(30) CONSTRAINT "GF_D_BLQ_ORG_NMBRE_CLMNA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_D_BLQ_ORG_CDGO_TRZ_ORGEN_PK" PRIMARY KEY ("CDGO_TRZA_ORGN")
  USING INDEX  ENABLE
   ) ;

