
  CREATE TABLE "GF_G_SLDOS_FVOR_SLCTUD_AJST"
   (	"ID_SLDO_FVOR_SLCTUD_AJST" NUMBER CONSTRAINT "GF_G_S_F_S_A_ID_SL_FV_SL_AJ_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR_SLCTUD" NUMBER CONSTRAINT "GF_G_S_F_S_A_ID_SL_FV_SLCTD_NN" NOT NULL ENABLE,
	"ID_AJSTE" NUMBER CONSTRAINT "GF_G_S_F_S_A_ID_AJSTE_NN" NOT NULL ENABLE,
	"CDGO_AJSTE_ESTDO" VARCHAR2(3) CONSTRAINT "GF_G_S_F_S_A_CDGO_AJST_ESTD_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(1000),
	 CONSTRAINT "GF_G_S_F_S_A_ID_SL_FV_SL_AJ_PK" PRIMARY KEY ("ID_SLDO_FVOR_SLCTUD_AJST")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_S_F_S_A_ID_AJSTE_FK" FOREIGN KEY ("ID_AJSTE")
	  REFERENCES "GF_G_AJUSTES" ("ID_AJSTE") ENABLE,
	 CONSTRAINT "GF_G_S_F_S_A_ID_SL_FV_SLCTD_FK" FOREIGN KEY ("ID_SLDO_FVOR_SLCTUD")
	  REFERENCES "GF_G_SALDOS_FAVOR_SOLICITUD" ("ID_SLDO_FVOR_SLCTUD") ENABLE,
	 CONSTRAINT "GF_G_S_F_S_A_CDGO_AJST_ESTD_FK" FOREIGN KEY ("CDGO_AJSTE_ESTDO")
	  REFERENCES "GF_D_AJUSTE_ESTADO" ("CDGO_AJSTE_ESTDO") ENABLE
   ) ;

