
  CREATE TABLE "GF_G_TITULOS_JDCIAL_SLCTUD"
   (	"ID_TTLO_JDCIAL_SLCTUD" NUMBER,
	"CDGO_TTLO_JDCIAL_SLCTUD_TPO" VARCHAR2(5),
	"FCHA_SLCTUD" DATE,
	"ID_USRIO" NUMBER,
	"INDCDOR_SLCTUD_APRBDA" VARCHAR2(1) DEFAULT 'N',
	"FCHA_RSPSTA" TIMESTAMP (6),
	"INDCDOR_SLCTUD_CNFRMCION" VARCHAR2(1) DEFAULT 'N',
	 CONSTRAINT "GF_G_TT_JD_SL_ID_USRIO_NN" CHECK ("ID_USRIO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_CD_TT_JD_SL_T_NN" CHECK ("CDGO_TTLO_JDCIAL_SLCTUD_TPO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_IND_SLC_APR_CK" CHECK (indcdor_slctud_aprbda in ('S', 'N')) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_IND_SLC_APR_NN" CHECK ("INDCDOR_SLCTUD_APRBDA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_IND_SLC_CNF_CK" CHECK (indcdor_slctud_cnfrmcion in ('S','N')) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_ID_TT_JD_SL_PK" PRIMARY KEY ("ID_TTLO_JDCIAL_SLCTUD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_FCHA_SLCTUD_NN" CHECK ("FCHA_SLCTUD" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_ID_TT_JD_SL_NN" CHECK ("ID_TTLO_JDCIAL_SLCTUD" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_CD_TT_JD_SL_T_FK" FOREIGN KEY ("CDGO_TTLO_JDCIAL_SLCTUD_TPO")
	  REFERENCES "GF_D_TTLOS_JDCIAL_SLCTUD_TP" ("CDGO_TTLO_JDCIAL_SLCTUD_TPO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_SL_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

