
  CREATE TABLE "GF_G_PRSCRPCNS_DCMNTO"
   (	"ID_DCMNTO" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_ID_DCMNTO_NN" NOT NULL ENABLE,
	"ID_PRSCRPCION" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_ID_PRSCRPCIN_NN" NOT NULL ENABLE,
	"ID_PRSCRPCION_SJTO_IMPSTO" NUMBER,
	"ID_FLJO_TREA" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_ID_FLJO_TREA_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_ID_ACTO_TPO_NN" NOT NULL ENABLE,
	"ID_PLNTLLA" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_ID_PLNTLLA_NN" NOT NULL ENABLE,
	"ID_RPRTE" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_ID_RPRTE_NN" NOT NULL ENABLE,
	"DCMNTO" CLOB CONSTRAINT "GF_G_PRSC_DCMN_DCMNTO_NN" NOT NULL ENABLE,
	"ID_USRIO_PRYCTO" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_ID_USR_PRYCT_NN" NOT NULL ENABLE,
	"ID_USRIO_ATRZO" NUMBER,
	"ID_ACTO" NUMBER,
	"ID_ACTO_RQRDO" NUMBER,
	"VLR_DCMNTO" NUMBER,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GF_G_PRSC_DCMN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_DCMNTO_PK" PRIMARY KEY ("ID_DCMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_PRS_SJ_IM_FK" FOREIGN KEY ("ID_PRSCRPCION_SJTO_IMPSTO")
	  REFERENCES "GF_G_PRSCRPCNES_SJTO_IMPSTO" ("ID_PRSCRPCION_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_ACTO_RQRD_FK" FOREIGN KEY ("ID_ACTO_RQRDO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_PLNTLLA_FK" FOREIGN KEY ("ID_PLNTLLA")
	  REFERENCES "GN_D_PLANTILLAS" ("ID_PLNTLLA") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_PRSCRPCIN_FK" FOREIGN KEY ("ID_PRSCRPCION")
	  REFERENCES "GF_G_PRESCRIPCIONES" ("ID_PRSCRPCION") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_FLJO_TREA_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_USR_PRYCT_FK" FOREIGN KEY ("ID_USRIO_PRYCTO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_USRI_ATRZ_FK" FOREIGN KEY ("ID_USRIO_ATRZO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_G_PRSC_DCMN_ID_RPRTE_FK" FOREIGN KEY ("ID_RPRTE")
	  REFERENCES "GN_D_REPORTES" ("ID_RPRTE") ENABLE
   )
 LOB ("DCMNTO") STORE AS SECUREFILE "SYS_LOB0000075185C00008$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

