
  CREATE TABLE "GF_G_SLDOS_FVR_DVLCION_DTLL"
   (	"ID_SLDOS_FVR_DVLCION_DTLL" NUMBER CONSTRAINT "GF_G_SL_FV_DV_DT_ID_S_F_C_D_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR_DVLCION" NUMBER CONSTRAINT "GF_G_SL_FV_DV_DT_ID_S_F_D_D_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR" NUMBER CONSTRAINT "GF_G_SL_FV_DV_DT_ID_SLD_FVR_NN" NOT NULL ENABLE,
	"VLOR_DVLCION" NUMBER CONSTRAINT "GF_G_SL_FV_DV_DT_VLR_DVLCN_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GF_G_SL_FV_DV_DT_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GF_G_SL_FV_DV_DT_ID_SBIMPST_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "GF_G_SL_FV_DV_DT_ID_SJT_IMP_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_G_SL_FV_DV_DT_ID_S_F_C_D_PK" PRIMARY KEY ("ID_SLDOS_FVR_DVLCION_DTLL")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SL_FV_DV_DT_ID_S_F_D_D_FK" FOREIGN KEY ("ID_SLDO_FVOR_DVLCION")
	  REFERENCES "GF_G_SALDOS_FAVOR_DEVLUCION" ("ID_SLDO_FVOR_DVLCION") ENABLE,
	 CONSTRAINT "GF_G_SL_FV_DV_DT_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_SL_FV_DV_DT_ID_SJT_IMP_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GF_G_SL_FV_DV_DT_ID_SBIMPST_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GF_G_SL_FV_DV_DT_ID_SLD_FVR_FK" FOREIGN KEY ("ID_SLDO_FVOR")
	  REFERENCES "GF_G_SALDOS_FAVOR" ("ID_SLDO_FVOR") ENABLE
   ) ;

