
  CREATE TABLE "GF_G_CONVENIOS_REVERSION"
   (	"ID_CNVNIO_RVRSION" NUMBER CONSTRAINT "GF_G_CNVN_RVRSN_ID_CNVN_RVR_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "GF_G_CNVN_RVRSN_ID_USRIO_NN" NOT NULL ENABLE,
	"ID_CNVNIO" NUMBER CONSTRAINT "GF_G_CNVN_RVRSN_ID_CNVN_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO_PDRE" NUMBER,
	"ID_INSTNCIA_FLJO_HJO" NUMBER,
	"ID_SLCTUD" NUMBER,
	"ID_ACTO" NUMBER,
	"FCHA_RGSTRO" TIMESTAMP (6),
	"FCHA_APLCCION" TIMESTAMP (6),
	"ID_USRIO_APLCCION" NUMBER,
	"CDGO_CNVNIO_RVRSION_ESTDO" VARCHAR2(3),
	"MTVO_RCHZO_RVRSION" VARCHAR2(4000),
	"ID_USRIO_RCHZO" NUMBER,
	"FCHA_RCHZO" TIMESTAMP (6) DEFAULT systimestamp,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_CNVN_RVR_PK" PRIMARY KEY ("ID_CNVNIO_RVRSION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_FLJ_I_HJ_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO_HJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_SLCTUD_FK" FOREIGN KEY ("ID_SLCTUD")
	  REFERENCES "PQ_G_SOLICITUDES" ("ID_SLCTUD") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_CNVN_FK" FOREIGN KEY ("ID_CNVNIO")
	  REFERENCES "GF_G_CONVENIOS" ("ID_CNVNIO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_USRIO_AP_FK" FOREIGN KEY ("ID_USRIO_APLCCION")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_CDG_RVR_EST_FK" FOREIGN KEY ("CDGO_CNVNIO_RVRSION_ESTDO")
	  REFERENCES "GF_D_CONVENIOS_RVRSION_ESTDO" ("CDGO_CNVNIO_RVRSION_ESTDO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_USRIO_RC_FK" FOREIGN KEY ("ID_USRIO_RCHZO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_RVRSN_ID_FLJ_I_PD_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO_PDRE")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE
   ) ;

