
  CREATE TABLE "GF_G_TITULOS_JDCIAL_VGNCIA"
   (	"ID_TTLO_JDCIAL_VGNCIA" NUMBER,
	"ID_TTLO_JDCIAL_IMPSTO" NUMBER,
	"VGNCIA" NUMBER,
	"ID_PRDO" NUMBER DEFAULT 0,
	"PRDO" NUMBER DEFAULT 0,
	"VLOR_CPTAL" NUMBER DEFAULT 0,
	"VLOR_INTRES" NUMBER DEFAULT 0,
	"VLOR_DSCTO" NUMBER DEFAULT 0,
	"VLOR_TTAL" NUMBER DEFAULT 0,
	"VLOR_TTAL_TTLO" NUMBER DEFAULT 0,
	"ID_ORGEN" NUMBER,
	"VLOR_TTAL_APLCAR" NUMBER,
	"VLOR_TTAL_APLCCION" NUMBER,
	"VLOR_DSCNTO_APLCCION" NUMBER,
	"TPO_DCMNTO" VARCHAR2(5),
	"CDGO_MVMNTO_ORGN" VARCHAR2(5),
	"FCHA_PRYCCION" TIMESTAMP (6),
	"ID_INSTNCIA_FLJO" NUMBER,
	"ID_IMPSTO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER,
	"CDGO_MVMNTO_TPO" VARCHAR2(5),
	 CONSTRAINT "GF_G_TT_JD_VG_VLOR_TTAL_NN" CHECK ("VLOR_TTAL" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_VLOR_TTL_TTLO_NN" CHECK ("VLOR_TTAL_TTLO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_VGNCIA_NN" CHECK ("VGNCIA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_VLOR_DSCTO_NN" CHECK ("VLOR_DSCTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_PRDO_NN" CHECK ("PRDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_ID_PRDO_NN" CHECK ("ID_PRDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_ID_TT_JD_VG_PK" PRIMARY KEY ("ID_TTLO_JDCIAL_VGNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_FCHA_PRYCCION_NN" CHECK ("FCHA_PRYCCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_ID_TT_JD_VG_NN" CHECK ("ID_TTLO_JDCIAL_VGNCIA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_VLOR_CPTAL_NN" CHECK ("VLOR_CPTAL" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_VLOR_INTRES_NN" CHECK ("VLOR_INTRES" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_ID_TT_JD_IMP_FK" FOREIGN KEY ("ID_TTLO_JDCIAL_IMPSTO")
	  REFERENCES "GF_G_TITULOS_JDCIAL_IMPSTO" ("ID_TTLO_JDCIAL_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_VG_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE
   ) ;

