
  CREATE TABLE "GF_G_SLDO_FVOR_SLCTUD_ESTDO"
   (	"ID_SLDO_FVOR_SLCTUD_ESTDO" NUMBER CONSTRAINT "GF_D_ST_SAL_FV_ID_ST_SAL_FR_NN" NOT NULL ENABLE,
	"CDGO" VARCHAR2(3) CONSTRAINT "GF_G_SL_FV_SL_ES_CDGO_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(30) CONSTRAINT "GF_G_SL_FV_SL_ES_NMBRE_NN" NOT NULL ENABLE,
	"CDGO_RSPSTA" VARCHAR2(3),
	 CONSTRAINT "GF_G_SL_FV_SL_ES_IDEST_CDGO_UN" UNIQUE ("CDGO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SL_FV_SL_ES_ID_SF_S_ES_PK" PRIMARY KEY ("ID_SLDO_FVOR_SLCTUD_ESTDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SL_FV_SL_ES_CDGO_RSPTA_FK" FOREIGN KEY ("CDGO_RSPSTA")
	  REFERENCES "PQ_D_RESPUESTAS" ("CDGO_RSPSTA") ENABLE
   ) ;

