
  CREATE TABLE "GF_G_TITULOS_JDCIAL_ANLSIS"
   (	"ID_TTLO_JDCIAL_ANLSIS" NUMBER,
	"ID_TTLO_JDCIAL" NUMBER,
	"ID_EMBRGO_RSLCION" NUMBER,
	"CDGO_TTLO_JDCIAL_SLCTUD_TPO" VARCHAR2(5),
	"ID_USRIO" NUMBER,
	"INDCDOR_APLCCION" VARCHAR2(1),
	"FCHA" DATE,
	"ID_ESTDO_CRTRA" NUMBER,
	 CONSTRAINT "GF_G_TT_JD_AN_INDCDR_APLCCN_CK" CHECK (indcdor_aplccion in ('C','M')) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_TT_JD_AN_PK" PRIMARY KEY ("ID_TTLO_JDCIAL_ANLSIS")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_TTL_JDCIAL_NN" CHECK ("ID_TTLO_JDCIAL" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_USRIO_NN" CHECK ("ID_USRIO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_TT_JD_AN_NN" CHECK ("ID_TTLO_JDCIAL_ANLSIS" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_CD_TT_JD_SL_T_FK" FOREIGN KEY ("CDGO_TTLO_JDCIAL_SLCTUD_TPO")
	  REFERENCES "GF_D_TTLOS_JDCIAL_SLCTUD_TP" ("CDGO_TTLO_JDCIAL_SLCTUD_TPO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_EMB_RSCION_FK" FOREIGN KEY ("ID_EMBRGO_RSLCION")
	  REFERENCES "MC_G_EMBARGOS_RESOLUCION" ("ID_EMBRGOS_RSLCION") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_ESTD_CRTR_FK" FOREIGN KEY ("ID_ESTDO_CRTRA")
	  REFERENCES "MC_D_ESTADOS_CARTERA" ("ID_ESTDOS_CRTRA") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_TTL_JDCIAL_FK" FOREIGN KEY ("ID_TTLO_JDCIAL")
	  REFERENCES "GF_G_TITULOS_JUDICIAL" ("ID_TTLO_JDCIAL") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_AN_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

