
  CREATE TABLE "GF_G_TITULOS_JDCL_FRCCNMNTO_DTLLE"
   (	"ID_TTLO_JDCIAL_FRCCN_DTLLE" NUMBER NOT NULL ENABLE,
	"ID_TTLO_JDCIAL_FRCCN" NUMBER NOT NULL ENABLE,
	"VGNCIA" NUMBER,
	"ID_PRDO" NUMBER,
	"VLOR" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "GF_G_TT_JD_FR_DT_ID_TJD_FR_DT_PK" PRIMARY KEY ("ID_TTLO_JDCIAL_FRCCN_DTLLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_TT_JD_FR_DT_ID_TT_JD_FR_FK" FOREIGN KEY ("ID_TTLO_JDCIAL_FRCCN")
	  REFERENCES "GF_G_TITULOS_JDCL_FRCCNMNTO" ("ID_TTLO_JDCIAL_FRCCN") ENABLE
   ) ;

