
  CREATE TABLE "GF_G_TITULOS_JUDICIAL_TRASLADO"
   (	"ID_TTLO_JDCIAL_TRSLDO" NUMBER NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER,
	"ID_TTLO_JDCIAL" NUMBER NOT NULL ENABLE,
	"ID_AREA" NUMBER NOT NULL ENABLE,
	"ID_USRIO" NUMBER,
	"OBSRVCNES" VARCHAR2(1000),
	"FCHA_TRSLDO" DATE,
	 CONSTRAINT "GF_G_TT_JD_TR_ID_USRIO" CHECK ("ID_USRIO" is not null) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_TR_FCHA_TRSLDO" CHECK ("FCHA_TRSLDO" is not null) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_TR_ID_TT_JD_TR" PRIMARY KEY ("ID_TTLO_JDCIAL_TRSLDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_TT_JD_TR_ID_INSTNCIA_FLJO" CHECK ("ID_INSTNCIA_FLJO" is not null) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_TR_ID_AREA" FOREIGN KEY ("ID_AREA")
	  REFERENCES "DF_C_AREAS" ("ID_AREA") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_TR_ID_TT_JD" FOREIGN KEY ("ID_TTLO_JDCIAL")
	  REFERENCES "GF_G_TITULOS_JUDICIAL" ("ID_TTLO_JDCIAL") ENABLE
   ) ;

