
  CREATE TABLE "GF_G_EXENCIONES_SOLICITUD"
   (	"ID_EXNCION_SLCTUD" NUMBER CONSTRAINT "GF_G_EXCN_SLCT_ID_EXNCN_SLC_NN" NOT NULL ENABLE,
	"CDGO_EXNCION_ORGEN" VARCHAR2(3) CONSTRAINT "GF_G_EXCN_SLCT_CDGO_EXC_ORG_NN" NOT NULL ENABLE,
	"ID_ORGEN" NUMBER CONSTRAINT "GF_G_EXCN_SLCT_ID_ORGN_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "GF_G_EXCN_SLCT_ID_SJTO_IMPS_NN" NOT NULL ENABLE,
	"CDGO_EXNCION_ESTDO" VARCHAR2(3) CONSTRAINT "GF_G_EXCN_SLCT_CDG_EXNC_EST_NN" NOT NULL ENABLE,
	"ID_USRIO_RGSTRA" NUMBER CONSTRAINT "GF_G_EXCN_SLCT_ID_USR_RGSTR_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "GF_G_EXCN_SLCT_FCHA_RGSTRA_NN" NOT NULL ENABLE,
	"ID_USRIO_RSPSTA" NUMBER,
	"FCHA_RSPSTA" TIMESTAMP (6),
	"ID_USRIO_PRYCTA" NUMBER,
	"FCHA_PRYCCION" TIMESTAMP (6),
	"OBSRVCION_RCHZO" VARCHAR2(100),
	"ID_AJSTE" NUMBER,
	"ID_LQDCION" NUMBER,
	"ID_DCMNTO" NUMBER,
	"ID_PLNTLLA" NUMBER,
	"ID_ACTO" NUMBER,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_EXNCN_SLC_PK" PRIMARY KEY ("ID_EXNCION_SLCTUD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_AJSTE_FK" FOREIGN KEY ("ID_AJSTE")
	  REFERENCES "GF_G_AJUSTES" ("ID_AJSTE") ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_LQDCION_FK" FOREIGN KEY ("ID_LQDCION")
	  REFERENCES "GI_G_LIQUIDACIONES" ("ID_LQDCION") DISABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_SJTO_IMPS_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_CDGO_EXC_ORG_FK" FOREIGN KEY ("CDGO_EXNCION_ORGEN")
	  REFERENCES "GF_D_EXENCIONES_ORIGEN" ("CDGO_EXNCION_ORGEN") ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_PLNTLLA_FK" FOREIGN KEY ("ID_PLNTLLA")
	  REFERENCES "GN_D_PLANTILLAS" ("ID_PLNTLLA") ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_USRI_PRYC_FK" FOREIGN KEY ("ID_USRIO_PRYCTA")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") DISABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_USR_RSPST_FK" FOREIGN KEY ("ID_USRIO_RSPSTA")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_DCMNTO_FK" FOREIGN KEY ("ID_DCMNTO")
	  REFERENCES "RE_G_DOCUMENTOS" ("ID_DCMNTO") ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_CDG_EXNC_EST_FK" FOREIGN KEY ("CDGO_EXNCION_ESTDO")
	  REFERENCES "GF_D_EXENCIONES_ESTADO" ("CDGO_EXNCION_ESTDO") ENABLE,
	 CONSTRAINT "GF_G_EXCN_SLCT_ID_USR_RGSTR_FK" FOREIGN KEY ("ID_USRIO_RGSTRA")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

