
  CREATE TABLE "GF_G_TTLOS_JDCIAL_DCMNT_EST"
   (	"ID_TTLO_JDCIAL_DCMNTO_ESTDO" NUMBER,
	"ID_TTLO_JDCIAL_DCMNTO" NUMBER,
	"ID_FLJO_TREA_ESTDO" NUMBER,
	"ID_USRIO" NUMBER,
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp,
	 CONSTRAINT "GF_G_T_J_DC_ES_I_TT_J_AC_ES_NN" CHECK ("ID_TTLO_JDCIAL_DCMNTO_ESTDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_ID_TT_JD_DCM_NN" CHECK ("ID_TTLO_JDCIAL_DCMNTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_I_TT_J_AC_ES_PK" PRIMARY KEY ("ID_TTLO_JDCIAL_DCMNTO_ESTDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_ID_FL_TRE_ES_NN" CHECK ("ID_FLJO_TREA_ESTDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_ID_USRIO_NN" CHECK ("ID_USRIO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_FCHA_NN" CHECK ("FCHA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_ID_FL_TRE_ES_FK" FOREIGN KEY ("ID_FLJO_TREA_ESTDO")
	  REFERENCES "WF_D_FLUJOS_TAREA_ESTADO" ("ID_FLJO_TREA_ESTDO") ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_ID_TT_JD_DCM_FK" FOREIGN KEY ("ID_TTLO_JDCIAL_DCMNTO")
	  REFERENCES "GF_G_TITULOS_JDCIAL_DCMNTO" ("ID_TTLO_JDCIAL_DCMNTO") ENABLE,
	 CONSTRAINT "GF_G_T_J_DC_ES_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

