
  CREATE TABLE "GF_G_PRSCRPCNES_SJTO_IMPSTO"
   (	"ID_PRSCRPCION_SJTO_IMPSTO" NUMBER CONSTRAINT "GF_G_PRS_SJT_IM_ID_PR_SJ_IM_NN" NOT NULL ENABLE,
	"ID_PRSCRPCION" NUMBER CONSTRAINT "GF_G_PRS_SJT_IM_ID_PRSCRPCN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GF_G_PRS_SJT_IM_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GF_G_PRS_SJT_IM_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GF_G_PRS_SJT_IM_ID_IMPS_SBM_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "GF_G_PRS_SJT_IM_ID_SJT_IMPT_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_G_PRESCRIPCINS_SJT_IMPST_UN" UNIQUE ("ID_PRSCRPCION", "ID_IMPSTO", "ID_IMPSTO_SBMPSTO", "ID_SJTO_IMPSTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_PRS_SJT_IM_ID_PR_SJ_IM_PK" PRIMARY KEY ("ID_PRSCRPCION_SJTO_IMPSTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_PRS_SJT_IM_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_G_PRS_SJT_IM_ID_SJT_IMPT_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GF_G_PRS_SJT_IM_ID_PRSCRPCN_FK" FOREIGN KEY ("ID_PRSCRPCION")
	  REFERENCES "GF_G_PRESCRIPCIONES" ("ID_PRSCRPCION") ENABLE,
	 CONSTRAINT "GF_G_PRS_SJT_IM_ID_IMPS_SBM_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GF_G_PRS_SJT_IM_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE
   ) ;

