
  CREATE TABLE "GF_G_SALDOS_FAVOR_MVIMIENTO"
   (	"ID_SLDO_FVOR_MVMNTO" NUMBER CONSTRAINT "GF_G_SL_FV_MV_ID_SL_FV_MV_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR_SLCTUD" NUMBER CONSTRAINT "GF_G_SL_FV_MV_ID_SL_FV_SL_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR" NUMBER CONSTRAINT "GF_G_SL_FV_MV_ID_SLDO_FVOR_NN" NOT NULL ENABLE,
	"ID_MVMNTO_TPO" NUMBER CONSTRAINT "GF_G_SL_FV_MV_CDG_MVMNT_TPO_NN" NOT NULL ENABLE,
	"VLOR_DBE" NUMBER DEFAULT 0,
	"VLOR_HBER" NUMBER DEFAULT 0,
	"FCHA_MVMNTO" DATE DEFAULT sysdate CONSTRAINT "GF_G_SL_FV_MV_FCHA_MVMNTO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_G_SL_FV_MV_VLOR_DBE_CK" CHECK ( vlor_dbe >= 0 ) ENABLE,
	 CONSTRAINT "GF_G_SL_FV_MV_ID_SL_FV_MV_PK" PRIMARY KEY ("ID_SLDO_FVOR_MVMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SL_FV_MV_VLOR_HBER_CK" CHECK ( vlor_hber >= 0 ) ENABLE,
	 CONSTRAINT "GF_G_SL_FV_MV_ID_SLDO_FVOR_FK" FOREIGN KEY ("ID_SLDO_FVOR")
	  REFERENCES "GF_G_SALDOS_FAVOR" ("ID_SLDO_FVOR") ENABLE,
	 CONSTRAINT "GF_G_SL_FV_MV_CDG_MVMNT_TPO_FK" FOREIGN KEY ("ID_MVMNTO_TPO")
	  REFERENCES "GF_D_SALDOS_FVOR_MVMNTS_TPO" ("ID_SLDOS_FVOR_MVMNTO_TPO") ENABLE,
	 CONSTRAINT "GF_G_SL_FV_MV_ID_SL_FV_SL_FK" FOREIGN KEY ("ID_SLDO_FVOR_SLCTUD")
	  REFERENCES "GF_G_SALDOS_FAVOR_SOLICITUD" ("ID_SLDO_FVOR_SLCTUD") ENABLE
   ) ;

