
  CREATE TABLE "GF_G_TITULOS_JUDICIAL"
   (	"ID_TTLO_JDCIAL" NUMBER,
	"CDGO_CLNTE" NUMBER,
	"ID_TTLO_JDCIAL_CRGDO" NUMBER,
	"NMRO_TTLO_JDCIAL" VARCHAR2(100),
	"FCHA_CNSTTCION" DATE,
	"VLOR" NUMBER,
	"ID_TTLO_JDCIAL_AREA" NUMBER,
	"CDGO_IDNTFCCION_TPO_DMNDDO" VARCHAR2(5),
	"IDNTFCCION_DMNDDO" VARCHAR2(100),
	"NMBRE_DMNDDO" VARCHAR2(200),
	"ID_INSTNCIA_FLJO" NUMBER,
	"CDGO_TTLO_JDCIAL_ESTDO" VARCHAR2(5),
	"CNSCTVO_EMBRGO" NUMBER,
	"ID_EMBRGO_RSLCION" NUMBER,
	"NMRO_TTLO_PDRE" VARCHAR2(100),
	"ID_TTLO_PDRE" NUMBER,
	"ID_INSTNCIA_FLJO_PDRE" NUMBER,
	"ID_SLCTUD" NUMBER,
	"CDGO_ENTDAD_CNSGNNTE" NUMBER,
	"ID_BNCO_CNSGNNTE" NUMBER,
	"CDGO_ENTDAD_RCDDR" NUMBER,
	"ID_BNCO_RCDDR" NUMBER,
	"ID_FNCNRIO" NUMBER,
	"CDGO_TTLO_JDCIAL_ESTDO_INCIAL" VARCHAR2(5),
	"INDCDOR_MGDO" VARCHAR2(1) DEFAULT 'N',
	"ID_USRIO_RGSTRO" NUMBER(15,0),
	 CONSTRAINT "GF_G_TTLO_JDCIAL_IDNT_DMNDD_NN" CHECK ("IDNTFCCION_DMNDDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ENTD_CNS_NN" CHECK ("CDGO_ENTDAD_CNSGNNTE" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_BNCO_CN_NN" CHECK ("ID_BNCO_CNSGNNTE" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_BNCO_RC_NN" CHECK ("ID_BNCO_RCDDR" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_NMBR_DMNDD_NN" CHECK ("NMBRE_DMNDDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_CDG_ID_DMD_NN" CHECK ("CDGO_IDNTFCCION_TPO_DMNDDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_TTL_JDC_NN" CHECK ("ID_TTLO_JDCIAL" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ENTD_RCDR_NN" CHECK ("CDGO_ENTDAD_RCDDR" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_CDGO_CLNTE_NN" CHECK ("CDGO_CLNTE" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_NMR_TTL_JD_NN" CHECK ("NMRO_TTLO_JDCIAL" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_TTL_JDC_PK" PRIMARY KEY ("ID_TTLO_JDCIAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_TT_JD_A_NN" CHECK ("ID_TTLO_JDCIAL_AREA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_NO_TT_JD_PK_01" UNIQUE ("NMRO_TTLO_JDCIAL") DISABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_FCHA_CNST_NN" CHECK ("FCHA_CNSTTCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_CDGO_ESTDO_NN" CHECK ("CDGO_TTLO_JDCIAL_ESTDO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_VLOR_NN" CHECK ("VLOR" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_CDGO_ESTDO_FK" FOREIGN KEY ("CDGO_TTLO_JDCIAL_ESTDO")
	  REFERENCES "GF_D_TITULOS_JUDICIAL_ESTDO" ("CDGO_TTLO_JDCIAL_ESTDO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_CDG_ID_TP_FK" FOREIGN KEY ("CDGO_IDNTFCCION_TPO_DMNDDO")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_BNCO_CN_FK" FOREIGN KEY ("ID_BNCO_CNSGNNTE")
	  REFERENCES "DF_C_BANCOS" ("ID_BNCO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_BNCO_RC_FK" FOREIGN KEY ("ID_BNCO_RCDDR")
	  REFERENCES "DF_C_BANCOS" ("ID_BNCO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_EMB_RSL_FK" FOREIGN KEY ("ID_EMBRGO_RSLCION")
	  REFERENCES "MC_G_EMBARGOS_RESOLUCION" ("ID_EMBRGOS_RSLCION") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_FLJ_I_H_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_FLJ_I_P_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO_PDRE")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_TT_JD_A_FK" FOREIGN KEY ("ID_TTLO_JDCIAL_AREA")
	  REFERENCES "DF_C_AREAS" ("ID_AREA") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_TT_JD_C_FK" FOREIGN KEY ("ID_TTLO_JDCIAL_CRGDO")
	  REFERENCES "GF_G_TITULOS_JUDICIAL_CRGDO" ("ID_TTLO_JDCIAL_CRGDO") ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_TT_PDRE_FK" FOREIGN KEY ("ID_TTLO_PDRE")
	  REFERENCES "GF_G_TITULOS_JUDICIAL" ("ID_TTLO_JDCIAL") ENABLE
   ) ;

