
  CREATE TABLE "GF_G_AJUSTES_CARGUE_LOTE"
   (	"ID_AJS_CRG_LTE" NUMBER CONSTRAINT "GF_G_AJ_CR_LTE_ID_AJ_CR_LT_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GF_G_AJ_CR_LTE_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GF_G_AJ_CR_LTE_ID_IMPS_SBM_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "GF_G_AJ_CR_LTE_ID_USRIO_NN" NOT NULL ENABLE,
	"NMRO_RGSTROS" NUMBER,
	"NMRO_SJTOS_VLDOS" NUMBER,
	"NMRO_AJSTES_GNRAR" NUMBER,
	"NMRO_AJSTES_GNRDOS" NUMBER,
	"CDGO_LTE_ESTDO" VARCHAR2(3) DEFAULT 'RGS',
	"FILE_BLOB" BLOB,
	"FILE_NAME" VARCHAR2(250),
	"FILE_MIMETYPE" VARCHAR2(100),
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp,
	"FCHA_INCIO_PRCSO" TIMESTAMP (6),
	"FCHA_FIN_PRCSO" TIMESTAMP (6),
	 CONSTRAINT "GF_G_AJ_CR_LTE_ID_AJ_CR_LT_PK" PRIMARY KEY ("ID_AJS_CRG_LTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_AJ_CR_LTE_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_AJ_CR_LTE_ID_IMPS_SBM_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GF_G_AJ_CR_LTE_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

