
  CREATE TABLE "GF_G_CONVENIOS_FINALIZACION"
   (	"ID_CNVNIO_FNLZCION" NUMBER CONSTRAINT "GF_G_CNVN_FNLCN_ID_FNLZCN_NN" NOT NULL ENABLE,
	"ID_CNVNIO" NUMBER CONSTRAINT "GF_G_CNVN_FNLCN_ID_CNVN_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "GF_G_CNVN_FNLCN_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "GF_G_CNVN_FNLCN_FCHA_NN" NOT NULL ENABLE,
	"ID_ACTO" NUMBER,
	"OBSRVCION" VARCHAR2(2000),
	 CONSTRAINT "GF_G_CNVN_FNLCN_ID_CNVN_FNL_PK" PRIMARY KEY ("ID_CNVNIO_FNLZCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_CNVN_FNLCN_ID_CNVN_FK" FOREIGN KEY ("ID_CNVNIO")
	  REFERENCES "GF_G_CONVENIOS" ("ID_CNVNIO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_FNLCN_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GF_G_CNVN_FNLCN_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE
   ) ;

