
  CREATE TABLE "GF_G_PRSCRPCNES_VGNCIA"
   (	"ID_PRSCRPCION_VGNCIA" NUMBER CONSTRAINT "GF_G_PRS_VGN_ID_PRSCR_VGN_NN" NOT NULL ENABLE,
	"ID_PRSCRPCION_SJTO_IMPSTO" NUMBER CONSTRAINT "GF_G_PRS_VGN_ID_PRS_SJT_IMP_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GF_G_PRS_VGN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER CONSTRAINT "GF_G_PRS_VGN_VGNCIA_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER CONSTRAINT "GF_G_PRS_VGN_ID_PRDO_NN" NOT NULL ENABLE,
	"INDCDOR_APRBDO" VARCHAR2(1) DEFAULT 'P' CONSTRAINT "GF_G_PRS_VGN_INDCDOR_APRBDO_NN" NOT NULL ENABLE,
	"APLCDO" VARCHAR2(1),
	"ID_AJSTE" NUMBER,
	"INDCDOR_MNJA_ORGEN" VARCHAR2(1) DEFAULT 'N',
	"ID_LQDCION" NUMBER,
	 CONSTRAINT "GF_G_PRS_VGN_INDCDOR_APRBDO_CK" CHECK (indcdor_aprbdo in ('P', 'S', 'N')) ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_ID_PRSCR_VGN_PK" PRIMARY KEY ("ID_PRSCRPCION_VGNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_APLCDO_CK" CHECK (aplcdo in ('R', 'S', 'N', 'E')) ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_INDCDOR_M_ORGN_CK" CHECK (indcdor_mnja_orgen in ('N', 'S')) ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_LQDCION_UN" UNIQUE ("ID_LQDCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_ID_PRS_SJT_IMP_FK" FOREIGN KEY ("ID_PRSCRPCION_SJTO_IMPSTO")
	  REFERENCES "GF_G_PRSCRPCNES_SJTO_IMPSTO" ("ID_PRSCRPCION_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_ID_AJSTE_FK" FOREIGN KEY ("ID_AJSTE")
	  REFERENCES "GF_G_AJUSTES" ("ID_AJSTE") ENABLE,
	 CONSTRAINT "GF_G_PRS_VGN_ID_LQDCION_FK" FOREIGN KEY ("ID_LQDCION")
	  REFERENCES "GI_G_LIQUIDACIONES" ("ID_LQDCION") ENABLE
   ) ;

