
  CREATE TABLE "GF_G_MVMNTOS_CNCPTO_CNSLDDO"
   (	"ID_MVMNTO_CNCPTO_CNSLDDO" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_ID_MV_CN_CNS_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_ID_SBIMPSTO_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_ID_SJT_IMPT_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_VGNCIA_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_ID_PRDO_NN" NOT NULL ENABLE,
	"ID_CNCPTO" NUMBER CONSTRAINT "GF_G_MV_CN_CNS_ID_CNCPTO_NN" NOT NULL ENABLE,
	"FCHA_VNCMNTO" TIMESTAMP (6),
	"FCHA_ULTMO_MVMNTO" TIMESTAMP (6) CONSTRAINT "GF_G_MV_CN_CNS_FCHA_ULT_MV_NN" NOT NULL ENABLE,
	"CDGO_MVNT_FNCRO_ESTDO" VARCHAR2(3) CONSTRAINT "GF_G_MV_CN_CNS_CD_FCT_ESTD_NN" NOT NULL ENABLE,
	"VLOR_SLDO_CPTAL" NUMBER DEFAULT 0 CONSTRAINT "GF_G_MV_CN_CNS_VLR_SLD_CP_NN" NOT NULL ENABLE,
	"VLOR_INTRES" NUMBER DEFAULT 0 CONSTRAINT "GF_G_MV_CN_CNS_VLR_INTRES_NN" NOT NULL ENABLE,
	"INDCDOR_MVMNTO_BLQDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GF_G_MV_CN_CNS_ESTDO_BLQDO_NN" NOT NULL ENABLE,
	"GNRA_INTRES_MRA" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GF_G_MV_CN_CNS_GN_INTR_MRA_NN" NOT NULL ENABLE,
	"CDGO_MVMNTO_ORGN" VARCHAR2(3),
	"ID_ORGEN" NUMBER,
	"ID_MVMNTO_FNCRO" NUMBER,
	"ID_IMPSTO_ACTO_CNCPTO" NUMBER,
	"INDCDOR_DTRMNDA" VARCHAR2(1) DEFAULT 'N',
	"ID_DTRMNCION" NUMBER,
	"FCHA_DTRMNCION" DATE,
	"INDCDOR_MNDMNTO_PGO" VARCHAR2(1) DEFAULT 'N',
	"ID_PRCSO_JRDCO" NUMBER,
	"FCHA_MNDMNTO_PGO" DATE,
	"ID_SJTO_SCRSAL" NUMBER DEFAULT null,
	"CDNA" VARCHAR2(50),
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_MVMNT_FNC_NN" CHECK (id_mvmnto_fncro is not null) ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_GN_INTR_MRA_CK" CHECK ( gnra_intres_mra in ('N','S') ) ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ESTDO_BLQDO_CK" CHECK ("INDCDOR_MVMNTO_BLQDO"='N' OR "INDCDOR_MVMNTO_BLQDO"='S') ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_IMP_AC_CN_NN" CHECK (id_impsto_acto_cncpto is not null) ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_MV_CN_CNS_PK" PRIMARY KEY ("ID_MVMNTO_CNCPTO_CNSLDDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_SJT_IMPT_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_IMP_AC_CN_FK" FOREIGN KEY ("ID_IMPSTO_ACTO_CNCPTO")
	  REFERENCES "DF_I_IMPUESTOS_ACTO_CONCEPTO" ("ID_IMPSTO_ACTO_CNCPTO") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_CDG_MVMT_OR_FK" FOREIGN KEY ("CDGO_MVMNTO_ORGN")
	  REFERENCES "GF_D_MOVIMIENTO_ORIGEN" ("CDGO_MVMNTO_ORGN") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_CNCPTO_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_SBIMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_CD_FCT_ESTD_FK" FOREIGN KEY ("CDGO_MVNT_FNCRO_ESTDO")
	  REFERENCES "GF_D_MVMNTO_FNCRO_ESTDO" ("CDGO_MVNT_FNCRO_ESTDO") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_ID_MVMNT_FNC_FK" FOREIGN KEY ("ID_MVMNTO_FNCRO")
	  REFERENCES "GF_G_MOVIMIENTOS_FINANCIERO" ("ID_MVMNTO_FNCRO") ENABLE,
	 CONSTRAINT "GF_G_MV_CN_CNS_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE
   ) ;

