
  CREATE TABLE "GF_G_TITULOS_JDCIAL_IMPSTO"
   (	"ID_TTLO_JDCIAL_IMPSTO" NUMBER,
	"ID_TTLO_JDCIAL" NUMBER,
	"ID_IMPSTO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER,
	"ID_SJTO_RSPNSBLE" NUMBER,
	"ID_DCMNTO" NUMBER,
	"ID_INSTNCIA_FLJO" NUMBER,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_TT_JD_IM_NN" CHECK ("ID_TTLO_JDCIAL_IMPSTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_TT_JD_IM_PK" PRIMARY KEY ("ID_TTLO_JDCIAL_IMPSTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_SJT_RSP_NN" CHECK ("ID_SJTO_RSPNSBLE" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_SJT_IMPST_NN" CHECK ("ID_SJTO_IMPSTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_IMPS_SBMP_NN" CHECK ("ID_IMPSTO_SBMPSTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_IMPSTO_NN" CHECK ("ID_IMPSTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_TTLO_JDCIAL_ID_DCMNTO_FK" FOREIGN KEY ("ID_DCMNTO")
	  REFERENCES "RE_G_DOCUMENTOS" ("ID_DCMNTO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_IMPS_SBMP_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_SJT_IMPST_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_TT_JD_IM_ID_TTL_JDC_FK" FOREIGN KEY ("ID_TTLO_JDCIAL")
	  REFERENCES "GF_G_TITULOS_JUDICIAL" ("ID_TTLO_JDCIAL") ENABLE
   ) ;

