
  CREATE TABLE "GF_G_SLDOS_FVOR_SLCTUD_DTLL"
   (	"ID_SLDO_FVOR_SLCTUD_DTLLE" NUMBER CONSTRAINT "GF_G_SL_FV_SL_DT_ID_S_F_S_D_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR_SLCTUD" NUMBER CONSTRAINT "GF_G_SL_FV_SL_DT_ID_SL_FV_S_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR" NUMBER CONSTRAINT "GF_G_SL_FV_SL_DT_ID_SLDO_FV_NN" NOT NULL ENABLE,
	"INDCDOR_RCNCDO" VARCHAR2(1) CONSTRAINT "GF_G_SL_FV_SL_DT_INDCD_RCNC_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_G_SL_FV_SL_DT_INDCD_RCNC_CK" CHECK (indcdor_rcncdo in ('N','S')) ENABLE,
	 CONSTRAINT "GF_G_SL_FV_SL_DT_ID_S_F_S_D_PK" PRIMARY KEY ("ID_SLDO_FVOR_SLCTUD_DTLLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SL_FV_SD_ID_SF_SL_I_SF_UN" UNIQUE ("ID_SLDO_FVOR_SLCTUD", "ID_SLDO_FVOR")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SL_FV_SL_DT_ID_SL_FV_S_FK" FOREIGN KEY ("ID_SLDO_FVOR_SLCTUD")
	  REFERENCES "GF_G_SALDOS_FAVOR_SOLICITUD" ("ID_SLDO_FVOR_SLCTUD") ENABLE,
	 CONSTRAINT "GF_G_SL_FV_SL_DT_ID_SLDO_FV_FK" FOREIGN KEY ("ID_SLDO_FVOR")
	  REFERENCES "GF_G_SALDOS_FAVOR" ("ID_SLDO_FVOR") ENABLE
   ) ;

