
  CREATE TABLE "GF_G_AJUSTES"
   (	"ID_AJSTE" NUMBER DEFAULT "GENESYS"."SQ_GF_G_AJUSTES"."NEXTVAL" CONSTRAINT "GF_G_AJSTE_ID_AJSTE_NN" NOT NULL DISABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "GF_G_AJSTE_COD_CLNTE_NN" NOT NULL DISABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "GF_G_AJSTE_ID_IMPSTO_NN" NOT NULL DISABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) CONSTRAINT "GF_G_AJSTE_ID_IMPT_SBIMP_NN" NOT NULL DISABLE,
	"ID_SJTO_IMPSTO" NUMBER(15,0) CONSTRAINT "GF_G_AJSTE_ID_SJTO_IMPT_NN" NOT NULL DISABLE,
	"ORGEN" VARCHAR2(1) CONSTRAINT "GF_G_AJSTE_ORGEN_AJSTE_NN" NOT NULL DISABLE,
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "GF_G_AJSTE_FCHA_AJSTE_NN" NOT NULL DISABLE,
	"TPO_AJSTE" VARCHAR2(2) CONSTRAINT "GF_G_AJSTE_TPO_AJSTE_NN" NOT NULL DISABLE,
	"VLOR" NUMBER(16,0) CONSTRAINT "GF_G_AJSTE_VLOR_AJSTE_NN" NOT NULL DISABLE,
	"ID_AJSTE_MTVO" NUMBER(15,0) CONSTRAINT "GF_G_AJSTE_CDGO_MTVO_AJST_NN" NOT NULL DISABLE,
	"OBSRVCION" VARCHAR2(4000) CONSTRAINT "GF_G_AJSTE_OBSRVCION_AJSTE_NN" NOT NULL DISABLE,
	"CDGO_AJSTE_ESTDO" VARCHAR2(5) CONSTRAINT "GF_G_AJSTE_CDGO_ESTDO_AJST_NN" NOT NULL DISABLE,
	"FCHA_APLCCION" TIMESTAMP (6),
	"TPO_DCMNTO_SPRTE" VARCHAR2(50) CONSTRAINT "GF_G_AJSTE_TPO_DCMNTO_SPRTE_NN" NOT NULL DISABLE,
	"NMRO_DCMTO_SPRTE" VARCHAR2(50) CONSTRAINT "GF_G_AJSTE_NMR_DCMNTO_SPRTE_NN" NOT NULL DISABLE,
	"FCHA_DCMNTO_SPRTE" TIMESTAMP (6) CONSTRAINT "GF_G_AJSTE_FCH_DCMNTO_SPRTE_NN" NOT NULL DISABLE,
	"NMRO_SLCTUD" NUMBER(15,0),
	"ID_USRIO" NUMBER(15,0) CONSTRAINT "GF_G_AJSTE_ID_USRIO_NN" NOT NULL DISABLE,
	"ID_INSTNCIA_FLJO" NUMBER NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER NOT NULL ENABLE,
	"OBSRVCION_NA_NAP" VARCHAR2(4000),
	"ID_INSTNCIA_FLJO_PDRE" NUMBER DEFAULT NULL,
	"NUMRO_AJSTE" NUMBER NOT NULL ENABLE,
	"IND_AJSTE_PRCSO" VARCHAR2(2),
	"FCHA_PRYCCION_INTRS" TIMESTAMP (6),
	"ID_AJSTE_MGRDO" NUMBER,
	"INDCDOR_INTRFAZ" VARCHAR2(1) DEFAULT 'N',
	"VLOR_INTRES" NUMBER(16,0),
	 CONSTRAINT "GF_G_AJSTE_TPO_AJSTE_CK" CHECK (tpo_ajste in ('DB', 'CR')) DISABLE,
	 CONSTRAINT "GF_G_AJSTE_INDCDOR_INTRFAZ_CK" CHECK ( indcdor_intrfaz in ( 'S' , 'N' )) ENABLE,
	 CONSTRAINT "GF_G_AJSTE_ORGEN_AJSTE_CK" CHECK (orgen in ('A', 'M')) DISABLE,
	 CONSTRAINT "GF_G_AJSTE_ID_AJSTE_PK" PRIMARY KEY ("ID_AJSTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_AJSTE_COD_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") DISABLE,
	 CONSTRAINT "GF_G_AJSTE_CDGO_MTVO_AJST_FK" FOREIGN KEY ("ID_AJSTE_MTVO")
	  REFERENCES "GF_D_AJUSTE_MOTIVO" ("ID_AJSTE_MTVO") DISABLE,
	 CONSTRAINT "GF_G_AJSTE_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") DISABLE,
	 CONSTRAINT "GF_G_AJSTE_CDGO_ESTDO_AJST_FK" FOREIGN KEY ("CDGO_AJSTE_ESTDO")
	  REFERENCES "GF_D_AJUSTE_ESTADO" ("CDGO_AJSTE_ESTDO") DISABLE,
	 CONSTRAINT "GF_G_AJSTE_ID_IMPT_SBIMP_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") DISABLE,
	 CONSTRAINT "GF_G_AJSTE_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") DISABLE,
	 CONSTRAINT "GF_G_AJSTE_ID_SJTO_IMPT_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GF_G_AJST_ID_INSTNC_FLJ_PDR_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO_PDRE")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE
   ) ;

