
  CREATE TABLE "GF_G_SALDOS_FAVOR_SOPORTE"
   (	"ID_SLDO_FVOR_SPRTE" NUMBER CONSTRAINT "GF_G_SLD_FVR_SP_ID_SL_SO_FV_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR" NUMBER CONSTRAINT "GF_G_SLD_FVR_SP_ID_SL_FV_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB CONSTRAINT "GF_G_SLD_FVR_SP_FLE_BLOB_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255) CONSTRAINT "GF_G_SLD_FVR_SP_FLE_NAME_NN" NOT NULL ENABLE,
	"FILE_MIMETYPE" VARCHAR2(255) CONSTRAINT "GF_G_SLD_FVR_SP_FLE_MTYP_NN" NOT NULL ENABLE,
	"NMRO_RSLCION" VARCHAR2(20),
	"FCHA_RSLCION" DATE,
	"FILE_BFILE" BFILE,
	 CONSTRAINT "GF_G_SLD_FVR_SP_ID_SL_SO_FV_PK" PRIMARY KEY ("ID_SLDO_FVOR_SPRTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SLD_FVR_SP_ID_SL_FV_FK" FOREIGN KEY ("ID_SLDO_FVOR")
	  REFERENCES "GF_G_SALDOS_FAVOR" ("ID_SLDO_FVOR") ENABLE
   ) ;

