
  CREATE TABLE "GF_G_MOVIMIENTOS_FINANCIERO"
   (	"ID_MVMNTO_FNCRO" NUMBER(*,0) DEFAULT "GENESYS"."SQ_GF_G_MOVIMIENTOS_FINANCIERO"."NEXTVAL" CONSTRAINT "GF_G_MVMT_FNC_ID_MVTO_FNC_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "GF_G_MVMT_FNC_COD_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "GF_G_MVMT_FNC_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) CONSTRAINT "GF_G_MVMT_FNC_ID_SBIMPSTO_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER(15,0) CONSTRAINT "GF_G_MVMT_FNC_ID_SJTO_IMPT_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER(4,0) CONSTRAINT "GF_G_MVMT_FNC_VGNCIA_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER(15,0) CONSTRAINT "GF_G_MVMT_FNC_ID_PRDO_NN" NOT NULL ENABLE,
	"CDGO_PRDCDAD" VARCHAR2(5) CONSTRAINT "GF_G_MVMT_FNC_CDG_PRDCDAD_NN" NOT NULL ENABLE,
	"CDGO_MVMNTO_ORGN" VARCHAR2(3) CONSTRAINT "GF_G_MVMT_FNC_CDG_MVMT_OR_NN" NOT NULL ENABLE,
	"ID_ORGEN" NUMBER CONSTRAINT "GF_G_MVMT_FNC_ID_ORGEN_NN" NOT NULL ENABLE,
	"NMRO_MVMNTO_FNCRO" NUMBER(15,0) CONSTRAINT "GF_G_MVMT_FNC_NMRO_NN" NOT NULL ENABLE,
	"FCHA_MVMNTO" TIMESTAMP (6) CONSTRAINT "GF_G_MVMT_FNC_FCHA_MVNTO_NN" NOT NULL ENABLE,
	"CDGO_MVNT_FNCRO_ESTDO" VARCHAR2(3) CONSTRAINT "GF_G_MVMT_FNC_CDG_FCT_ESTDO_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER(15,0),
	"INDCDOR_MVMNTO_BLQDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GF_G_MVMT_FNC_ESTDO_BLQDO_NN" NOT NULL ENABLE,
	"ID_MVMNTO_TRZA_BLQUEO" NUMBER,
	"ID_MVMNTO_TRZA_ULTMA" NUMBER,
	"INDCDOR_MGRDO" VARCHAR2(1),
	"ID_SJTO_SCRSAL" NUMBER DEFAULT null,
	 CONSTRAINT "GF_G_MVMT_FNC_ESTDO_BLQDO_CK" CHECK ("INDCDOR_MVMNTO_BLQDO"='N' OR "INDCDOR_MVMNTO_BLQDO"='S') ENABLE,
	 CONSTRAINT "GF_G_MOVIMIENTOS_ID_ORGEN_NN" CHECK ("ID_ORGEN" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_ID_MVTO_FNC_PK" PRIMARY KEY ("ID_MVMNTO_FNCRO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_CDG_MVMT_OR_FK" FOREIGN KEY ("CDGO_MVMNTO_ORGN")
	  REFERENCES "GF_D_MOVIMIENTO_ORIGEN" ("CDGO_MVMNTO_ORGN") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_CDG_FCT_ESTDO_FK" FOREIGN KEY ("CDGO_MVNT_FNCRO_ESTDO")
	  REFERENCES "GF_D_MVMNTO_FNCRO_ESTDO" ("CDGO_MVNT_FNCRO_ESTDO") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_ID_MVMT_TRZ_U_FK" FOREIGN KEY ("ID_MVMNTO_TRZA_ULTMA")
	  REFERENCES "GF_G_MOVIMIENTOS_TRAZA" ("ID_MVMNTO_TRZA") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_COD_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_ID_MVMTO_TRZA_FK" FOREIGN KEY ("ID_MVMNTO_TRZA_BLQUEO")
	  REFERENCES "GF_G_MOVIMIENTOS_TRAZA" ("ID_MVMNTO_TRZA") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_ID_SBIMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_CDG_PRDCDAD_FK" FOREIGN KEY ("CDGO_PRDCDAD")
	  REFERENCES "DF_S_PERIODICIDAD" ("CDGO_PRDCDAD") ENABLE,
	 CONSTRAINT "GF_G_MVMT_FNC_ID_SJTO_IMPT_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE
   ) ;

