
  CREATE TABLE "GF_G_CONVENIOS_CARTERA_JY"
   (	"ID_CNVNIO_CRTRA" NUMBER NOT NULL ENABLE,
	"ID_CNVNIO" NUMBER NOT NULL ENABLE,
	"VGNCIA" NUMBER NOT NULL ENABLE,
	"ID_PRDO" NUMBER NOT NULL ENABLE,
	"ID_CNCPTO" NUMBER NOT NULL ENABLE,
	"VLOR_CPTAL" NUMBER(16,0) NOT NULL ENABLE,
	"VLOR_INTRES" NUMBER(16,0) NOT NULL ENABLE,
	"ID_ORGEN" NUMBER NOT NULL ENABLE,
	"CDGO_MVMNTO_ORGEN" VARCHAR2(3) NOT NULL ENABLE,
	"INDCDOR_MGRDO" VARCHAR2(1)
   ) ;

