
  CREATE TABLE "GF_G_CNVNIOS_MDFCCN_EXTRCT"
   (	"ID_CNVNIO_MDFCCION_EXTRCTO" NUMBER CONSTRAINT "GF_G_CN_MD_EX_ID_CN_MD_EX_NN" NOT NULL ENABLE,
	"ID_CNVNIO_MDFCCION" NUMBER CONSTRAINT "GF_G_CN_MD_EX_ID_CNVNIO_MD_NN" NOT NULL ENABLE,
	"NMRO_CTA" NUMBER CONSTRAINT "GF_G_CN_MD_EX_NMRO_CTA_NN" NOT NULL ENABLE,
	"FCHA_VNCMNTO" DATE CONSTRAINT "GF_G_CN_MD_EX_FCHA_VNCMNTO_NN" NOT NULL ENABLE,
	"VLOR_TTAL" NUMBER(16,0) CONSTRAINT "GF_G_CN_MD_EX_VLOR_TTAL_NN" NOT NULL ENABLE,
	"VLOR_FNCNCION" NUMBER(16,0) CONSTRAINT "GF_G_CN_MD_EX_VLOR_FNCCN_NN" NOT NULL ENABLE,
	"VLOR_CPTAL" NUMBER(16,0) CONSTRAINT "GF_G_CN_MD_EX_VLOR_CPTAL_NN" NOT NULL ENABLE,
	"VLOR_INTRES" NUMBER(16,0) CONSTRAINT "GF_G_CN_MD_EX_VLOR_INTRES_NN" NOT NULL ENABLE,
	"INDCDOR_CTA_PGDA" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GF_G_CN_MD_EX_IND_CTA_PGD_NN" NOT NULL ENABLE,
	"ID_DCMNTO_CTA" NUMBER,
	"FCHA_PGO_CTA" DATE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GF_G_CN_MD_EX_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GF_G_CN_MD_EX_IND_CTA_PGD_CK" CHECK (indcdor_cta_pgda in ('S', 'N')) ENABLE,
	 CONSTRAINT "GF_G_CN_MD_EX_ID_CN_MD_EX_PK" PRIMARY KEY ("ID_CNVNIO_MDFCCION_EXTRCTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_CN_MD_EX_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GF_G_CN_MD_EX_ID_DCMT_CTA_FK" FOREIGN KEY ("ID_DCMNTO_CTA")
	  REFERENCES "RE_G_DOCUMENTOS" ("ID_DCMNTO") ENABLE,
	 CONSTRAINT "GF_G_CN_MD_EX_ID_CNVNIO_MD_FK" FOREIGN KEY ("ID_CNVNIO_MDFCCION")
	  REFERENCES "GF_G_CONVENIOS_MODIFICACION" ("ID_CNVNIO_MDFCCION") ENABLE
   ) ;

