
  CREATE TABLE "GF_G_SLDOS_FVR_DCMN_OBSRVCN"
   (	"ID_SLDOS_FVR_DCMN_OBSRVCN" NUMBER CONSTRAINT "GF_G_SL_FV_DC_OB_ID_S_F_D_O_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR_SLCTUD" NUMBER CONSTRAINT "GF_G_SL_FV_DC_ID_SL_FV_SLCT_NN" NOT NULL ENABLE,
	"ID_SLDO_FVOR_DCMNTO" NUMBER,
	"OBSRVCION" VARCHAR2(100) CONSTRAINT "GF_G_SL_FV_DC_OBSRVCION_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "GF_G_SL_FV_DC_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT sysdate CONSTRAINT "GF_G_SL_FV_DC_FCHA_RGSTRO_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER,
	 CONSTRAINT "GF_G_SL_FV_DC_OB_ID_S_F_D_O_PK" PRIMARY KEY ("ID_SLDOS_FVR_DCMN_OBSRVCN")
  USING INDEX  ENABLE,
	 CONSTRAINT "GF_G_SL_FV_DC_ID_SL_FV_SLCT_FK" FOREIGN KEY ("ID_SLDO_FVOR_SLCTUD")
	  REFERENCES "GF_G_SALDOS_FAVOR_SOLICITUD" ("ID_SLDO_FVOR_SLCTUD") ENABLE,
	 CONSTRAINT "GF_G_SL_FV_DC_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

