
  CREATE TABLE "GF_T_TITULOS_JDCIAL_MVMNTO"
   (	"ID_TTLO_JDCIAL_MVMNTO" NUMBER,
	"ID_TTLO_JDCIAL" NUMBER,
	"ID_IMPSTO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER,
	"VGNCIA" NUMBER,
	"ID_PRDO" NUMBER,
	"ID_CNCPTO" NUMBER,
	"CNTDAD" NUMBER,
	 CONSTRAINT "GF_T_TTLO_JD_MV_ID_TT_JD_MV_NN" CHECK ("ID_TTLO_JDCIAL_MVMNTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GF_T_TTLO_JD_MV_ID_CNCPTO_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "GF_T_TTLO_JD_MV_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GF_T_TTLO_JD_MV_ID_IMP_SBMP_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GF_T_TTLO_JD_MV_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GF_T_TTLO_JD_MV_ID_SJTO_IMP_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "GF_T_TTLO_JD_MV_ID_TTL_JDCL_FK" FOREIGN KEY ("ID_TTLO_JDCIAL")
	  REFERENCES "GF_G_TITULOS_JUDICIAL" ("ID_TTLO_JDCIAL") ENABLE,
	 CONSTRAINT "GF_T_TTLO_JD_MV_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE
   ) ;

