
  CREATE TABLE "GF_T_CONVENIOS_VALOR_SANCION"
   (	"NMRO_ACRDO" NUMBER,
	"NMRO_CTA" NUMBER,
	"VLOR_SNCION" NUMBER,
	 CONSTRAINT "GF_T_CON_VAL_SAN_PK" PRIMARY KEY ("NMRO_ACRDO", "NMRO_CTA")
  USING INDEX  ENABLE
   ) ;

