
  CREATE TABLE "GI_D_FORMULARIOS_REGION"
   (	"ID_FRMLRIO_RGION" NUMBER CONSTRAINT "GI_D_FRMLR_RGN_ID_FRMLR_RGN_NN" NOT NULL ENABLE,
	"ID_FRMLRIO" NUMBER CONSTRAINT "GI_D_FRMLR_RGN_ID_FRMLRIO_NN" NOT NULL ENABLE,
	"ID_FRMLRIO_RGION_PDRE" NUMBER,
	"CDGO_RGION_TPO" VARCHAR2(3) CONSTRAINT "GI_D_FRMLR_RGN_CDGO_RGN_TP_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(1000) CONSTRAINT "GI_D_FRMLR_RGN_DSCRPCION_NN" NOT NULL ENABLE,
	"INDCDOR_INCIA_NVA_FLA" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_D_FRMLR_RGN_IND_IN_NV_FL_NN" NOT NULL ENABLE,
	"NMRO_CLMNA" NUMBER,
	"AMPLCION_CLMNA" NUMBER,
	"INDCDOR_EDTBLE" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GI_D_FRMLR_RGN_INDCDR_EDTBL_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER DEFAULT 1 CONSTRAINT "GI_D_FRMLR_RGN_ORDEN_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_D_FRMLR_RGN_ACTVO_NN" NOT NULL ENABLE,
	"NMRO_FLA_MIN" NUMBER DEFAULT null,
	"NMRO_FLA_MAX" NUMBER DEFAULT null,
	"INDCDOR_FSCLZCION" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_D_FRMLR_RGN_INCDR_FSCZCN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_ID_FRMLR_RGN_PK" PRIMARY KEY ("ID_FRMLRIO_RGION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_INCDR_FSCZCN_CK" CHECK (indcdor_fsclzcion in ('S', 'N')) ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_INDCDR_EDTBL_CK" CHECK (indcdor_edtble in ('S','N')) ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_IND_IN_NV_FL_CK" CHECK (indcdor_incia_nva_fla in ('S','N')) ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_ID_FRM_RG_PD_FK" FOREIGN KEY ("ID_FRMLRIO_RGION_PDRE")
	  REFERENCES "GI_D_FORMULARIOS_REGION" ("ID_FRMLRIO_RGION") ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_CDGO_RGN_TP_FK" FOREIGN KEY ("CDGO_RGION_TPO")
	  REFERENCES "GI_D_REGIONES_TIPO" ("CDGO_RGION_TPO") ENABLE,
	 CONSTRAINT "GI_D_FRMLR_RGN_ID_FRMLRIO_FK" FOREIGN KEY ("ID_FRMLRIO")
	  REFERENCES "GI_D_FORMULARIOS" ("ID_FRMLRIO") ENABLE
   ) ;

