
  CREATE TABLE "GI_D_SANCIONES_TIPO"
   (	"CDGO_SNCION_TPO" VARCHAR2(4) CONSTRAINT "GI_D_SANCIONES_TIPO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "GI_D_SANCIONES_TIPO_DSCRPCN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_SANCIONES_TIPO_PK" PRIMARY KEY ("CDGO_SNCION_TPO")
  USING INDEX  ENABLE
   ) ;

