
  CREATE TABLE "GI_D_DCLRCNES_RPRTE_ELMNTO"
   (	"ID_DCLRCION_RPRTE_ELMNTO" NUMBER DEFAULT "GENESYS"."SQ_GI_D_DCLRCNES_RPRTE_ELMNTO"."NEXTVAL" CONSTRAINT "GI_D_DCL_RPT_ELM_ID_DC_RP_E_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_D_DCL_RPT_ELM_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_ELMNTO" VARCHAR2(3) CONSTRAINT "GI_D_DCL_RPT_ELM_CDGO_ELMNT_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(50) CONSTRAINT "GI_D_DCL_RPT_ELM_NMBRE_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_D_DCL_RPT_ELM_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_DCL_RPT_ELM_ID_DC_RP_E_PK" PRIMARY KEY ("ID_DCLRCION_RPRTE_ELMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_DCL_RPT_ELM_ACTVO_CK" CHECK (actvo in('S','N')) ENABLE,
	 CONSTRAINT "GI_D_DCL_RPT_ELM_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_D_DCL_RPT_ELM_CDGO_ELMNT_FK" FOREIGN KEY ("CDGO_ELMNTO")
	  REFERENCES "GI_D_DECLARACIONES_ELEMENTO" ("CDGO_ELMNTO") ENABLE
   ) ;

