
  CREATE TABLE "GI_D_DCLRCN_ORGN_TPO"
   (	"CDGO_DCLRCN_ORGN_TPO" NUMBER,
	"DSCRPCION" VARCHAR2(400),
	 CONSTRAINT "GI_D_DCLRCN_ORGN_TPO_CDGO_DCLRCN_ORGN_TP_NN" CHECK ("CDGO_DCLRCN_ORGN_TPO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_D_DCLRCN_ORGN_TPO_DSCRPION_NN" CHECK ("DSCRPCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_D_DCLRCN_ORGN_TPO_CDGO_DCLRCN_ORGN_TP_PK" PRIMARY KEY ("CDGO_DCLRCN_ORGN_TPO")
  USING INDEX  ENABLE
   ) ;

