
  CREATE TABLE "GI_D_RENTAS_ESTADO"
   (	"CDGO_RNTA_ESTDO" VARCHAR2(3) CONSTRAINT "GI_D_RNTAS_ESTD_CDG_RNT_EST_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(30) CONSTRAINT "GI_D_RNTAS_ESTD_DSCRPION_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_RNTAS_ESTD_CDG_RNT_EST_PK" PRIMARY KEY ("CDGO_RNTA_ESTDO")
  USING INDEX  ENABLE
   ) ;

