
  CREATE TABLE "GI_D_PLUSVALIA_CONFIGURCION"
   (	"ID_PLSVLIA_CNFGRCION" NUMBER CONSTRAINT "GI_D_PLSV_CNFG_ID_PLSV_CNFG_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_D_PLSV_CNFG_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GI_D_PLSV_CNFG_ID_IMPSTO_NN" NOT NULL ENABLE,
	"INDCDOR_MDFCA_ARCHVO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GI_D_PLSV_CNFG_IND_MDF_ARCH_NN" NOT NULL ENABLE,
	"BNCO_RCDDOR" VARCHAR2(50) CONSTRAINT "GI_D_PLSV_CNFG_BNCO_RCDDOR_NN" NOT NULL ENABLE,
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "GI_D_PLSV_CNFG_USRIO_DGTA_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "GI_D_PLSV_CNFG_FCHA_DGTA_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "GI_D_PLSV_CNFG_ID_PLSV_CNFG_PK" PRIMARY KEY ("ID_PLSVLIA_CNFGRCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_PLSV_CNFG_IND_MDF_ARCH_CK" CHECK (indcdor_mdfca_archvo in ('S','N')) ENABLE,
	 CONSTRAINT "GI_D_PLSV_CNFG_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_D_PLSV_CNFG_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE
   ) ;

