
  CREATE TABLE "GI_D_DECLARACIONES_ITEM_CLCLO"
   (	"ID_DCLRCION_ITEM_CLCLO" NUMBER(15,0) CONSTRAINT "GI_D_DL_IT_CLO_ID_DC_IT_CLO_NN" NOT NULL ENABLE,
	"ID_DCLRCION_ITEM" NUMBER(15,0) CONSTRAINT "GI_D_DL_IT_CLO_ID_DCLRC_IT_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER(6,0),
	"ID_DCLRCION_ITEM_RLCNDO" NUMBER(15,0) CONSTRAINT "GI_D_DL_IT_CLO_ID_DC_IT_RDO_NN" NOT NULL ENABLE,
	"OPRCION" VARCHAR2(50),
	"MLJE" NUMBER(4,3),
	"TPO_CLCLO" VARCHAR2(1),
	"NMBRE_FNCION" VARCHAR2(30),
	 CONSTRAINT "GI_D_DL_IT_CLO_MLJE_CK" CHECK (mlje between 0 and 1) ENABLE,
	 CONSTRAINT "GI_D_DL_IT_CLO_TPO_CLCLO_CK" CHECK (tpo_clclo in ('F','G')) ENABLE,
	 CONSTRAINT "GI_D_DL_IT_CLO_ID_DC_IT_CLO_PK" PRIMARY KEY ("ID_DCLRCION_ITEM_CLCLO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_DL_IT_CLO_ID_DCLRC_IT_FK" FOREIGN KEY ("ID_DCLRCION_ITEM")
	  REFERENCES "GI_D_DECLARACIONES_ITEM" ("ID_DCLRCION_ITEM") ENABLE
   ) ;

