
  CREATE TABLE "GI_D_PREDIOS_VGN_ACT_CTSTRL"
   (	"ID_PRDIO_VGN_ACT_CTS" NUMBER CONSTRAINT "GI_D_PRD_VAC_ID_PRD_VAC_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_D_PRD_VAC_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GI_D_PRD_VAC_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GI_D_PRD_VAC_ID_SBIMPSTO_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER CONSTRAINT "GI_D_PRD_VAC_VGNCIA_NN" NOT NULL ENABLE,
	"INDCDOR_ACTLZDA" VARCHAR2(1) CONSTRAINT "GI_D_PRD_VAC_IND_ACT_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "GI_D_PRD_VAC_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" DATE,
	 CONSTRAINT "GI_D_PRD_VAC_ID_PRD_VAC_PK" PRIMARY KEY ("ID_PRDIO_VGN_ACT_CTS")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_PRD_VAC_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GI_D_PRD_VAC_ID_SBIMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GI_D_PRD_VAC_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_D_PRD_VAC_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

