
  CREATE TABLE "GI_D_FORMULARIOS_INSTRUCTIVO"
   (	"ID_FRMLRIO_INSTRCTVO" NUMBER CONSTRAINT "GI_D_FRM_INS_ID_FRMLR_INSTR_NN" NOT NULL ENABLE,
	"ID_FRMLRIO" NUMBER CONSTRAINT "GI_D_FRM_INS_ID_FRMLRIO_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB,
	"FILE_NAME" VARCHAR2(250),
	"FILE_MIMETYPE" VARCHAR2(100),
	 CONSTRAINT "GI_D_FRM_INS_ID_FR_UN" UNIQUE ("ID_FRMLRIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_FRM_INS_ID_FRMLR_INSTR_PK" PRIMARY KEY ("ID_FRMLRIO_INSTRCTVO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_FRM_INS_ID_FRMLRIO_FK" FOREIGN KEY ("ID_FRMLRIO")
	  REFERENCES "GI_D_FORMULARIOS" ("ID_FRMLRIO") ENABLE
   ) ;

