
  CREATE TABLE "GI_D_ATIPICAS_REFERENCIA"
   (	"ID_ATPCA_RFRNCIA" NUMBER(15,0) CONSTRAINT "GI_D_ATPC_RFRNC_ID_ATPC_RFR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "GI_D_ATPC_RFRNC_CO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "GI_D_ATPC_RFRNC_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) CONSTRAINT "GI_D_ATPC_RFRNC_ID_SBIMPSTO_NN" NOT NULL ENABLE,
	"RFRNCIA_IGAC" VARCHAR2(25) CONSTRAINT "GI_D_ATPC_RFRNC_RFRNCIA_IGC_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(200) CONSTRAINT "GI_D_ATPC_RFRNC_DSCRPCION_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER(15,0) CONSTRAINT "GI_D_ATPC_RFRNC_ID_PRDO_NN" NOT NULL ENABLE,
	"ID_PRDIO_DSTNO" NUMBER(15,0),
	"CDGO_ESTRTO" VARCHAR2(3),
	"ID_PRDIO_USO_SLO" NUMBER(15,0),
	 CONSTRAINT "GI_D_ATPC_RFRNC_ID_ATPC_RFR_PK" PRIMARY KEY ("ID_ATPCA_RFRNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_ATPC_RFRNC_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GI_D_ATPC_RFRNC_ID_USO_SLO_FK" FOREIGN KEY ("ID_PRDIO_USO_SLO")
	  REFERENCES "DF_C_PREDIOS_USO_SUELO" ("ID_PRDIO_USO_SLO") ENABLE,
	 CONSTRAINT "GI_D_ATPC_RFRNC_ID_SBIMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GI_D_ATPC_RFRNC_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GI_D_ATPC_RFRNC_CO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_D_ATPC_RFRNC_CDGO_ESTRTO_FK" FOREIGN KEY ("CDGO_ESTRTO")
	  REFERENCES "DF_S_ESTRATOS" ("CDGO_ESTRTO") ENABLE,
	 CONSTRAINT "GI_D_ATPC_RFRNC_ID_PD_DSTNO_FK" FOREIGN KEY ("ID_PRDIO_DSTNO")
	  REFERENCES "DF_I_PREDIOS_DESTINO" ("ID_PRDIO_DSTNO") ENABLE
   ) ;

