
  CREATE TABLE "GI_D_HOMOLOGACIONES"
   (	"ID_HMLGCION" NUMBER CONSTRAINT "GI_D_HMLGCNES_ID_HMLGCION_NN" NOT NULL ENABLE,
	"CDGO_HMLGCION" VARCHAR2(3) CONSTRAINT "GI_D_HMLGCNES_CDGO_HMLGCION_NN" NOT NULL ENABLE,
	"CDGO_OBJTO_TPO" VARCHAR2(3) CONSTRAINT "GI_D_HMLGCNES_CDGO_OBJTO_TP_NN" NOT NULL ENABLE,
	"NMBRE_OBJTO" VARCHAR2(1000) CONSTRAINT "GI_D_HMLGCNES_NMBRE_OBJTO_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(4000),
	 CONSTRAINT "GI_D_HMLGCNES_CDGO_OBJTO_TP_CK" CHECK (cdgo_objto_tpo in ('T', 'P', 'F')) ENABLE,
	 CONSTRAINT "GI_D_HMLGCNES_ID_HMLGCION_PK" PRIMARY KEY ("ID_HMLGCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_HMLGCNES_CD_OB_TP_NM_O_UN" UNIQUE ("CDGO_OBJTO_TPO", "NMBRE_OBJTO")
  USING INDEX  ENABLE
   ) ;

