
  CREATE TABLE "GI_D_HMLGCNES_PRPDAD"
   (	"ID_HMLGCION_PRPDAD" NUMBER CONSTRAINT "GI_D_HMLG_PRPD_ID_HMLG_PRPD_NN" NOT NULL ENABLE,
	"ID_HMLGCION" NUMBER CONSTRAINT "GI_D_HMLG_PRPD_ID_HMLGCION_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(4000),
	"INDCDOR_OBLGTRIO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GI_D_HMLG_PRPD_INDCDR_OBLGT_NN" NOT NULL ENABLE,
	"CDGO_PRPDAD" VARCHAR2(50) CONSTRAINT "GI_D_HMLG_PRPD_CDGO_PRPDAD_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_HMLG_PRPD_INDCDR_OBLGT_CK" CHECK (indcdor_oblgtrio in ('S', 'N')) ENABLE,
	 CONSTRAINT "GI_D_HMLG_PRPD_ID_HMLG_PRPD_PK" PRIMARY KEY ("ID_HMLGCION_PRPDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_HMLG_PRPD_ID_HML_CDGPR_UN" UNIQUE ("ID_HMLGCION", "CDGO_PRPDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_HMLG_PRPD_ID_HMLGCION_FK" FOREIGN KEY ("ID_HMLGCION")
	  REFERENCES "GI_D_HOMOLOGACIONES" ("ID_HMLGCION") ENABLE
   ) ;

