
  CREATE TABLE "GI_D_LIQUIDACIONES_MTV_AJST"
   (	"ID_LQDCION_MTV_AJST" NUMBER DEFAULT "GENESYS"."SQ_GI_D_LIQUIDACIONES_MTV_AJST"."NEXTVAL" CONSTRAINT "GI_D_LQD_MT_AJ_I_LQDC_MT_AJ_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_D_LQD_MT_AJ_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GI_D_LQD_MT_AJ_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GI_D_LQD_MT_AJ_ID_IMP_SBMPT_NN" NOT NULL ENABLE,
	"TPO_AJSTE" VARCHAR2(2) CONSTRAINT "GI_D_LQD_MT_AJ_TPO_AJSTE_NN" NOT NULL ENABLE,
	"ID_AJSTE_MTVO" NUMBER CONSTRAINT "GI_D_LQD_MT_AJ_ID_AJSTE_MTV_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_LQD_MT_AJ_TPO_AJSTE_CK" CHECK ( tpo_ajste in ( 'DB' , 'CR' )) ENABLE,
	 CONSTRAINT "GI_D_LQD_MT_AJ_I_LQDC_MT_AJ_PK" PRIMARY KEY ("ID_LQDCION_MTV_AJST")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_LQD_MT_AJ_TPO_AJSTE_UN" UNIQUE ("CDGO_CLNTE", "ID_IMPSTO", "ID_IMPSTO_SBMPSTO", "TPO_AJSTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_LQD_MT_AJ_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GI_D_LQD_MT_AJ_ID_IMP_SBMPT_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GI_D_LQD_MT_AJ_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_D_LQD_MT_AJ_ID_AJSTE_MTV_FK" FOREIGN KEY ("ID_AJSTE_MTVO")
	  REFERENCES "GF_D_AJUSTE_MOTIVO" ("ID_AJSTE_MTVO") ENABLE
   ) ;

