
  CREATE TABLE "GI_D_ATRIBUTOS_TIPO_PRPDAD"
   (	"ID_ATRBTO_TPO_PRPDAD" NUMBER DEFAULT "GENESYS"."GI_D_ATRIBUTOS_TIPO_PRPDAD_SQ"."NEXTVAL" CONSTRAINT "GI_D_ATR_TPO_P_ID_AT_TP_PR_NN" NOT NULL ENABLE,
	"CDGO_ATRBTO_TPO" VARCHAR2(3) CONSTRAINT "GI_D_ATR_TPO_P_CDGO_AT_TPO_NN" NOT NULL ENABLE,
	"CDGO_PRPDAD" VARCHAR2(10) CONSTRAINT "GI_D_ATR_TPO_P_CDGO_PRPDAD_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(255) CONSTRAINT "GI_D_ATR_TPO_P_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_D_ATR_TPO_P_ACTVO_NN" NOT NULL ENABLE,
	"FNCION_PRPDAD" VARCHAR2(255),
	"INDCDOR_VLOR" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GI_D_ATR_TPO_P_INDCDOR_VLOR_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_ATR_TPO_P_INDCDOR_VLOR_CK" CHECK (indcdor_vlor in ('S','N')) ENABLE,
	 CONSTRAINT "GI_D_ATR_TPO_P_ID_AT_TP_PR_PK" PRIMARY KEY ("ID_ATRBTO_TPO_PRPDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_ATRB_T_PRP_C_ATR_T_C_P_UN" UNIQUE ("CDGO_ATRBTO_TPO", "CDGO_PRPDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_ATR_TPO_P_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GI_D_ATR_TPO_P_CDGO_AT_TPO_FK" FOREIGN KEY ("CDGO_ATRBTO_TPO")
	  REFERENCES "GI_D_ATRIBUTOS_TIPO" ("CDGO_ATRBTO_TPO") ENABLE
   ) ;

