
  CREATE TABLE "GI_D_SBMPSTS_ADJNTO_TP_FRMT"
   (	"ID_SBMPTO_ADJNTO_TPO_FRMTO" NUMBER CONSTRAINT "GI_D_SBP_AD_T_F_ID_SB_A_T_F_NN" NOT NULL ENABLE,
	"ID_SBMPTO_ADJNTO_TPO" NUMBER CONSTRAINT "GI_D_SBP_AD_T_F_ID_IM_AD_TP_NN" NOT NULL ENABLE,
	"FRMTO" VARCHAR2(100) CONSTRAINT "GI_D_SBP_AD_T_F_FRMTO_NN" NOT NULL ENABLE,
	"TMNO_MXMO" NUMBER CONSTRAINT "GI_D_SBP_AD_T_F_TMO_MXMO_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_D_SBP_AD_T_F_ACTVO_NN" NOT NULL ENABLE,
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "GI_D_SBP_AD_T_F_USER_DGT_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "GI_D_SBP_AD_T_F_FCHA_DGT_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "GI_D_SBP_AD_T_F_ID_SB_A_T_F_PK" PRIMARY KEY ("ID_SBMPTO_ADJNTO_TPO_FRMTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_SBP_AD_T_F_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GI_D_SBP_AD_T_F_FRMTO_FK" FOREIGN KEY ("FRMTO")
	  REFERENCES "DF_S_FORMATOS_TIPO" ("CDGO_FRMTO_TPO") ENABLE,
	 CONSTRAINT "GI_D_SBP_AD_T_F_ID_IM_AD_TP_FK" FOREIGN KEY ("ID_SBMPTO_ADJNTO_TPO")
	  REFERENCES "GI_D_SUBIMPUESTOS_ADJNTO_TP" ("ID_SBMPTO_ADJNTO_TPO") ENABLE
   ) ;

