
  CREATE TABLE "GI_D_DCLRCN_VGNC_FRMLR_AUT_TPO"
   (	"CDGO_TPO_AUTRZCION" VARCHAR2(5) CONSTRAINT "GI_D_DCVGFR_AUTP_CDG_TP_AUT_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "GI_D_DCVGFR_AUTP_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_D_DCVGFR_AUTP_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_DCVGFR_AUTP_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GI_D_DCVGFR_AUTP_CDG_TP_AUT_PK" PRIMARY KEY ("CDGO_TPO_AUTRZCION")
  USING INDEX  ENABLE
   ) ;

