
  CREATE TABLE "GI_D_ACTIVIDADES_ECONOMICA"
   (	"ID_ACTVDAD_ECNMCA" NUMBER CONSTRAINT "GI_D_ACTV_ECNM_ID_ACTV_ECNM_NN" NOT NULL ENABLE,
	"ID_ACTVDAD_ECNMCA_TPO" NUMBER CONSTRAINT "GI_D_ACTV_ECNM_ID_ACT_EC_TP_NN" NOT NULL ENABLE,
	"CDGO_ACTVDAD_ECNMCA" VARCHAR2(4) CONSTRAINT "GI_D_ACTV_ECNM_CDGO_ACT_ECN_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(1000) CONSTRAINT "GI_D_ACTV_ECNM_DSCRPCION_NN" NOT NULL ENABLE,
	"TRFA" NUMBER CONSTRAINT "GI_D_ACTV_ECNM_TARIFA_NN" NOT NULL ENABLE,
	"FCHA_DSDE" DATE CONSTRAINT "GI_D_ACTV_ECNM_FCHA_DSDE_NN" NOT NULL ENABLE,
	"FCHA_HSTA" DATE CONSTRAINT "GI_D_ACTV_ECNM_FCHA_HSTA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_D_ACTV_ECNM_ID_ACTV_ECNM_PK" PRIMARY KEY ("ID_ACTVDAD_ECNMCA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_D_ACTV_ECNM_ID_ACT_EC_TP_FK" FOREIGN KEY ("ID_ACTVDAD_ECNMCA_TPO")
	  REFERENCES "GI_D_ACTIVIDADES_ECNMCA_TPO" ("ID_ACTVDAD_ECNMCA_TPO") ENABLE
   ) ;

