
  CREATE TABLE "GI_G_DCLRCNES_LCNCIA"
   (	"ID_DCLRCION_LCNCIA" NUMBER CONSTRAINT "GI_G_DCLR_LCNC_ID_DCLR_LCNC_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_G_DCLR_LCNC_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "GI_G_DCLR_LCNC_ID_SJT_IMPST_NN" NOT NULL ENABLE,
	"RDCDO_LCNCIA" VARCHAR2(100) CONSTRAINT "GI_G_DCLR_LCNC_RDCDO_LCNCIA_NN" NOT NULL ENABLE,
	"LCNCIA" VARCHAR2(100) CONSTRAINT "GI_G_DCLR_LCNC_LCNCIA_NN" NOT NULL ENABLE,
	"FCHA_EXPDCION" DATE CONSTRAINT "GI_G_DCLR_LCNC_FCHA_EXPDCIN_NN" NOT NULL ENABLE,
	"FCHA_VCMNTO" DATE,
	 CONSTRAINT "GI_G_DCLR_LCNC_ID_DCLR_LCNC_PK" PRIMARY KEY ("ID_DCLRCION_LCNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCLR_LCNC_CDGO_CLN_LCN_UN" UNIQUE ("CDGO_CLNTE", "LCNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCLR_LCNC_CDG_CL_RD_LC_UN" UNIQUE ("CDGO_CLNTE", "RDCDO_LCNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCLR_LCNC_ID_SJT_IMPST_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GI_G_DCLR_LCNC_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

