
  CREATE TABLE "GI_G_ADJUNTOS_VEHICULO"
   (	"ID_ADJNTOS_VHCLO" NUMBER DEFAULT "GENESYS"."SQ_GI_G_ADJUNTOS_VEHICULO"."NEXTVAL",
	"ID_SJTO_IMPSTO" NUMBER,
	"FILE_BLOB" BLOB,
	"FILE_NAME" VARCHAR2(255),
	"FILE_MIMETYPE" VARCHAR2(100),
	"FCHA" TIMESTAMP (6) DEFAULT sysdate,
	"ESTDO" VARCHAR2(1),
	"ORGN" VARCHAR2(3),
	 CONSTRAINT "GI_G_ADJN_VHCLO_ID_ADJ_VH_PK" PRIMARY KEY ("ID_ADJNTOS_VHCLO")
  USING INDEX  ENABLE
   ) ;

