
  CREATE TABLE "GI_G_DCLRCNES_NVDAD"
   (	"ID_NVDAD" NUMBER,
	"ID_DCLRCION" NUMBER,
	"ID_NVDAD_TPO" NUMBER,
	"FCHA_NVDAD" TIMESTAMP (6) DEFAULT sysdate,
	"CDGO_ESTDO" VARCHAR2(10) DEFAULT 'PS',
	"USER_DGTA" VARCHAR2(100),
	"FCHA_DGTA" TIMESTAMP (6),
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "GI_G_DCLR_NVDAD_USER_DGTA_NN" CHECK ("USER_DGTA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_FCHA_DGTA_NN" CHECK ("FCHA_DGTA" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_ID_DCLRCNE_NN" CHECK ("ID_DCLRCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_ID_NVDAD_TP_NN" CHECK ("ID_NVDAD_TPO" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_ID_NVDAD_NN" CHECK ("ID_NVDAD" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_FCHA_NVDAD_NN" CHECK ("FCHA_NVDAD" IS NOT NULL) ENABLE,
	 CONSTRAINT "GI_G_DCLR_CDGO_ESTDO_CK" CHECK (cdgo_estdo in ('PS','AP', 'CN')) ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_ID_NVDAD_PK" PRIMARY KEY ("ID_NVDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_ID_DCLRCNE_FK" FOREIGN KEY ("ID_DCLRCION")
	  REFERENCES "GI_G_DECLARACIONES" ("ID_DCLRCION") ENABLE,
	 CONSTRAINT "GI_G_DCLR_NVDAD_ID_NVDAD_TP_FK" FOREIGN KEY ("ID_NVDAD_TPO")
	  REFERENCES "GI_D_DCLRCNES_NVDAD_TPO" ("ID_NVDAD_TPO") ENABLE
   ) ;

