
  CREATE TABLE "GI_G_DECLARACIONES_ANTICIPO"
   (	"ID_DCLRCION_ANTICIPO" NUMBER CONSTRAINT "GI_G_DCLRCN_ANT_ID_DCLR_ANT_NN" NOT NULL ENABLE,
	"ID_DCLRCION" NUMBER CONSTRAINT "GI_G_DCLRCN_ANT_ID_DCLRION_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500),
	"VLRO_PGO" NUMBER,
	"APLCDO" VARCHAR2(1) CONSTRAINT "GI_G_DCLRCN_ANT_APLCDO_NN" NOT NULL ENABLE,
	"FLA" NUMBER,
	"ID_DCLRCION_RGSTRDA" NUMBER CONSTRAINT "GI_G_DCLRCN_ANT_ID_DCLRN_RG_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_DCLRCN_ANT_APLCDO_CK" CHECK (aplcdo in ('S','N')) ENABLE,
	 CONSTRAINT "GI_G_DCLRCN_ANT_ID_DCLR_ANT_PK" PRIMARY KEY ("ID_DCLRCION_ANTICIPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCLRCN_ANT_ID_DCLRION_FK" FOREIGN KEY ("ID_DCLRCION")
	  REFERENCES "GI_G_DECLARACIONES" ("ID_DCLRCION") ENABLE,
	 CONSTRAINT "GI_G_DCLRCN_ANT_ID_DCLRN_RG_FK" FOREIGN KEY ("ID_DCLRCION_RGSTRDA")
	  REFERENCES "GI_G_DECLARACIONES" ("ID_DCLRCION") ENABLE
   ) ;

