
  CREATE TABLE "GI_G_RENTAS_ADJNTO"
   (	"ID_RNTA_ADJNTO" NUMBER DEFAULT "GENESYS"."SQ_GI_G_RENTAS_ADJNTO"."NEXTVAL" CONSTRAINT "GI_G_RNTA_ADJNTO_ID_RNT_ADJ_NN" NOT NULL ENABLE,
	"ID_RNTA" NUMBER CONSTRAINT "GI_G_RNTA_ADJNTO_ID_RNTA_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(1000) CONSTRAINT "GI_G_RNTA_ADJNTO_OBSRVCION_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB CONSTRAINT "GI_G_RNTA_ADJNTO_FILE_BLOB_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255),
	"FILE_MIMETYPE" VARCHAR2(100),
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "GI_G_RNTA_ADJNTO_USER_DGT_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "GI_G_RNTA_ADJNTO_FCHA_DGT_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	"ID_SBMPTO_ADJNTO_TPO" NUMBER CONSTRAINT "GI_G_RNTA_ADJNTO_ID_SB_AD_T_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_RNTA_ADJNTO_ID_RNT_ADJ_PK" PRIMARY KEY ("ID_RNTA_ADJNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_RNTA_ADJNTO_ID_SB_AD_T_FK" FOREIGN KEY ("ID_SBMPTO_ADJNTO_TPO")
	  REFERENCES "GI_D_SUBIMPUESTOS_ADJNTO_TP" ("ID_SBMPTO_ADJNTO_TPO") ENABLE,
	 CONSTRAINT "GI_G_RNTA_ADJNTO_ID_RNTA_FK" FOREIGN KEY ("ID_RNTA")
	  REFERENCES "GI_G_RENTAS" ("ID_RNTA") ENABLE
   )
 LOB ("FILE_BLOB") STORE AS SECUREFILE "SYS_LOB0000140313C00004$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

