
  CREATE TABLE "GI_G_DCLRCNES_AUTRZCNES_LTE"
   (	"ID_DCLRCION_AUTRZCION_LTE" NUMBER CONSTRAINT "GI_G_DCL_AU_LT_ID_DCL_AU_LT_NN" NOT NULL ENABLE,
	"ID_DCLRCION" NUMBER CONSTRAINT "GI_G_DCL_AU_LT_ID_DCLRCION_NN" NOT NULL ENABLE,
	"CDGO_RSPSTA" VARCHAR2(1) DEFAULT 'P' CONSTRAINT "GI_G_DCL_AU_LT_CDGO_RSPSTA_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_G_DCL_AU_LT_ACTVO_ATRZD_NN" NOT NULL ENABLE,
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "GI_G_DCL_AU_LT_USER_DGTA_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "GI_G_DCL_AU_LT_FCHA_DGTA_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "GI_G_DCL_AU_LT_CDGO_RSPSTA_CK" CHECK (cdgo_rspsta in ('P', 'A', 'R')) ENABLE,
	 CONSTRAINT "GI_G_DCL_AU_LT_ID_DCL_AU_LT_PK" PRIMARY KEY ("ID_DCLRCION_AUTRZCION_LTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCL_AU_LT_ACTVO_ATRZD_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GI_G_DCL_AU_LT_ID_DCLRCION_FK" FOREIGN KEY ("ID_DCLRCION")
	  REFERENCES "GI_G_DECLARACIONES" ("ID_DCLRCION") ENABLE
   ) ;

