
  CREATE TABLE "GI_G_OBRAS"
   (	"ID_OBRA" NUMBER CONSTRAINT "GI_G_OBRAS_ID_OBRA_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_G_OBRAS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GI_G_OBRAS_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GI_G_OBRAS_ID_IMPST_SBMPSTO_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER CONSTRAINT "GI_G_OBRAS_ID_PRDO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(200) CONSTRAINT "GI_G_OBRAS_DSCRPCION_NN" NOT NULL ENABLE,
	"VLOR_TTAL" NUMBER CONSTRAINT "GI_G_OBRAS_VLOR_TTAL_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "GI_G_OBRAS_FCHA_RGSTRO_NN" NOT NULL ENABLE,
	"ID_MTDO_DSTRBCION" NUMBER CONSTRAINT "GI_G_OBRAS_ID_MTDO_DSTRBCN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_OBRAS_ID_OBRA_PK" PRIMARY KEY ("ID_OBRA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_OBRAS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_G_OBRAS_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GI_G_OBRAS_ID_MTDO_DSTRBCN_FK" FOREIGN KEY ("ID_MTDO_DSTRBCION")
	  REFERENCES "DF_S_METODOS_DISTRIBUCION" ("ID_MTDO_DSTRBCION") ENABLE,
	 CONSTRAINT "GI_G_OBRAS_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GI_G_OBRAS_ID_IMPST_SBMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE
   ) ;

