
  CREATE TABLE "GI_G_PLUSVALIA_AUDITORIA"
   (	"ID_PLSVLIA_ADTRIA" NUMBER CONSTRAINT "GI_G_PLS_AUD_ID_PLSVL_ADTR_NN" NOT NULL ENABLE,
	"ID_PLSVLIA_DTLLE" NUMBER CONSTRAINT "GI_G_PLS_AUD_ID_PLSVLIA_DTL_NN" NOT NULL ENABLE,
	"ID_PRCSO_PLSVLIA" NUMBER CONSTRAINT "GI_G_PLS_AUD_ID_PRCSO_PLSVL_NN" NOT NULL ENABLE,
	"CDGO_PRDIAL" VARCHAR2(30),
	"AREA_OBJTO" NUMBER,
	"MTRCLA_INMBLRIA" VARCHAR2(50),
	"PRPTRIO" VARCHAR2(100),
	"VLOR_P1" NUMBER,
	"VLOR_P2" NUMBER,
	"AREA" NUMBER,
	"CLSFCCION_ZNA" NUMBER,
	"CMNA" NUMBER,
	"DRCCION" VARCHAR2(100),
	"HCHO_GNRDOR" VARCHAR2(100),
	"PRDIO_FRA_ESTDIO" NUMBER,
	"VLOR_PLSVLIA" NUMBER,
	"VLOR_TTAL_PLSVLIA" NUMBER,
	"VLOR_PLSVLIA_ACTLZDA" NUMBER,
	"USER_MDFCA" NUMBER CONSTRAINT "GI_G_PLS_AUD_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA_MDFCA" TIMESTAMP (6) CONSTRAINT "GI_G_PLS_AUD_FCHA_MDFCCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_PLS_AUD_ID_PLSVL_ADTR_PK" PRIMARY KEY ("ID_PLSVLIA_ADTRIA")
  USING INDEX  ENABLE
   ) ;

