
  CREATE TABLE "GI_G_LIQUIDACIONES_DECL_ITEM"
   (	"ID_LQDCION_DCL_ITEM" NUMBER(15,0) CONSTRAINT "GI_G_LQD_D_ITM_ID_LQD_D_ITM_NN" NOT NULL ENABLE,
	"ID_LQDCION" NUMBER(15,0) CONSTRAINT "GI_G_LQD_D_ITM_ID_LQDCION_NN" NOT NULL ENABLE,
	"ID_DCLRCION_ITEM" NUMBER(15,0) CONSTRAINT "GI_G_LQD_D_ITM_ID_DCL_ITEM_NN" NOT NULL ENABLE,
	"VLOR_ITEM" NUMBER(16,2),
	 CONSTRAINT "GI_G_LQD_D_ITM_ID_LQD_D_ITM_PK" PRIMARY KEY ("ID_LQDCION_DCL_ITEM")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_LQD_D_ITM_ID_LQDCION_FK" FOREIGN KEY ("ID_LQDCION")
	  REFERENCES "GI_G_LIQUIDACIONES" ("ID_LQDCION") DISABLE,
	 CONSTRAINT "GI_G_LQD_D_ITM_ID_DCL_ITEM_FK" FOREIGN KEY ("ID_DCLRCION_ITEM")
	  REFERENCES "GI_D_DECLARACIONES_ITEM" ("ID_DCLRCION_ITEM") ENABLE
   ) ;

