
  CREATE TABLE "GI_G_DECLARACIONES_PRIVADA_OL"
   (	"ID_DCLRCION_PRVDA_OL" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_DC_PR_OL_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_SBIMPSTO" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_IMP_SBIM_NN" NOT NULL ENABLE,
	"NMRO_FRMLRIO" NUMBER(15,0),
	"VGNCIA" NUMBER(4,0) CONSTRAINT "GI_G_DCL_PRV_OL_VGNCIA_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_PRDO_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_SJT_IMPT_NN" NOT NULL ENABLE,
	"FCHA_PRSNTCION" TIMESTAMP (6) CONSTRAINT "GI_G_DCL_PRV_OL_FCHA_PRSNTC_NN" NOT NULL ENABLE,
	"TPO_DCLRCION" VARCHAR2(1),
	"ID_DCLRCION_ANTRIOR" NUMBER(15,0),
	"RZON_SCIAL" VARCHAR2(100) CONSTRAINT "GI_G_DCL_PRV_OL_RZON_SCIAL_NN" NOT NULL ENABLE,
	"ID_TPO_FRMLRIO" NUMBER(12,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_TPO_FRML_NN" NOT NULL ENABLE,
	"ID_PAIS" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_PAIS_NN" NOT NULL ENABLE,
	"ID_DPRTMNTO" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_DPRTMNTO_NN" NOT NULL ENABLE,
	"ID_MNCPIO" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_MNCPIO_NN" NOT NULL ENABLE,
	"DRCCION" VARCHAR2(200),
	"DRCCION_NTFCCION" VARCHAR2(100),
	"ID_PAIS_NTFCCION" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_PAIS_NTF_NN" NOT NULL ENABLE,
	"ID_DPRTMNTO_NTFCCION" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_DPRT_NTF_NN" NOT NULL ENABLE,
	"ID_MNCPIO_NTFCCION" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRV_OL_ID_MNCP_NTF_NN" NOT NULL ENABLE,
	"EMAIL" VARCHAR2(320),
	"TLFNO" VARCHAR2(50),
	"ID_SJTO_RSPNSBLE" NUMBER(15,0) CONSTRAINT "GI_G_DCL_PRVD_OL_ID_SJT_RSP_NN" NOT NULL ENABLE,
	"CDGO_TPO_IDNTFCCION_RSPNSBLE" VARCHAR2(3) CONSTRAINT "GI_G_DCL_PRVD_OL_TPO_IDT_RS_NN" NOT NULL ENABLE,
	"DGTO_VRFCCION" VARCHAR2(1),
	"FCHA_VNCMNTO" TIMESTAMP (6),
	"FCHA_RGSTRO" TIMESTAMP (6),
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_DC_PR_OL_PK" PRIMARY KEY ("ID_DCLRCION_PRVDA_OL")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_IMP_SBIM_FK" FOREIGN KEY ("ID_SBIMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_SJT_IMPT_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_DPRT_NTF_FK" FOREIGN KEY ("ID_DPRTMNTO_NTFCCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRVD_OL_ID_SJT_RSP_FK" FOREIGN KEY ("ID_SJTO_RSPNSBLE")
	  REFERENCES "SI_I_SUJETOS_RESPONSABLE" ("ID_SJTO_RSPNSBLE") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_DPRTMNTO_FK" FOREIGN KEY ("ID_DPRTMNTO")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_MNCP_NTF_FK" FOREIGN KEY ("ID_MNCPIO_NTFCCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_PAIS_FK" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_PAIS_NTF_FK" FOREIGN KEY ("ID_PAIS_NTFCCION")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_MNCPIO_FK" FOREIGN KEY ("ID_MNCPIO")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRV_OL_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "GI_G_DCL_PRVD_OL_TPO_IDT_RS_FK" FOREIGN KEY ("CDGO_TPO_IDNTFCCION_RSPNSBLE")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE
   ) ;

