
  CREATE TABLE "GI_G_EXONERACIONES"
   (	"ID_EXNRCION" NUMBER CONSTRAINT "GI_G_EXNRCN_ID_EXNRCION_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_G_EXNRCN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) CONSTRAINT "GI_G_EXNRCN_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) CONSTRAINT "GI_G_EXNRCN_ID_SBIMPSTO_NN" NOT NULL ENABLE,
	"CDGO_EXNRCION_TPO" VARCHAR2(3) CONSTRAINT "GI_G_EXNRCN_CDGO_EXNRC_TPO_NN" NOT NULL ENABLE,
	"NMRO_RSLCION" VARCHAR2(10) CONSTRAINT "GI_G_EXNRCN_NMRO_RSLCION_NN" NOT NULL ENABLE,
	"FCHA_RSLCION" DATE CONSTRAINT "GI_G_EXNRCN_FCHA_RSLCION_NN" NOT NULL ENABLE,
	"INDCDOR_EXNRCION_TDOS_CNCPTOS" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GI_G_EXNRC_IND_EXN_TDS_CNCP_NN" NOT NULL ENABLE,
	"PRCNTJE_EXNRCION" NUMBER DEFAULT 100,
	"FILE_BLOB" BLOB,
	"FILE_NAME" VARCHAR2(250),
	"FILE_MIMETYPE" VARCHAR2(100),
	 CONSTRAINT "GI_G_EXNRCN_ID_EXNRCION_PK" PRIMARY KEY ("ID_EXNRCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_EXNRCN_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GI_G_EXNRCN_ID_SBIMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GI_G_EXNRCN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_G_EXNRCN_CDGO_EXNRC_TPO_FK" FOREIGN KEY ("CDGO_EXNRCION_TPO")
	  REFERENCES "DF_S_EXONERACION_TIPO" ("CDGO_EXNRCION_TPO") ENABLE
   ) ;

