
  CREATE TABLE "GI_G_LIQUIDACIONES_AD_PRSNA"
   (	"ID_LQDCION_ADCNAL_PRSNA" NUMBER(15,0) CONSTRAINT "GI_G_LQDC_ESTB_ID_LQDC_ESTB_NN" NOT NULL ENABLE,
	"ID_LQDCION" NUMBER(15,0) CONSTRAINT "GI_G_LQDC_ESTB_ID_LQDCION_NN" NOT NULL ENABLE,
	"ID_ACTVDAD_ECNMCA_CLS" NUMBER(15,0),
	"FCHA_NTFCCION" TIMESTAMP (6),
	"ID_OFCNA_ORGN" NUMBER(15,0),
	"NMRO_NTFCCION" VARCHAR2(50),
	"LUGAR_EXPDCION" VARCHAR2(200),
	"ID_PAIS_EXPDCION" NUMBER(15,0),
	"ID_DPRTMNTO_EXPDCION" NUMBER(15,0),
	"ID_MNCPIO_EXPDCION" NUMBER(15,0),
	"NMRO_MTRCLA" VARCHAR2(50),
	"EXTRNJRO" VARCHAR2(1) DEFAULT 'N',
	"INDCDOR_MXTO" VARCHAR2(1) DEFAULT 'N',
	"ID_SJTO_TPO" NUMBER(15,0),
	 CONSTRAINT "GI_G_LQDC_ESTB_INDCDOR_MXTO_CK" CHECK (indcdor_mxto in ('S','N')) ENABLE,
	 CONSTRAINT "GI_G_LQDC_PRSN_ID_LQDC_ESTB_PK" PRIMARY KEY ("ID_LQDCION_ADCNAL_PRSNA")
  USING INDEX (CREATE UNIQUE INDEX "GI_G_LQDC_ESTB_ID_LQDC_ESTB_PK" ON "GI_G_LIQUIDACIONES_AD_PRSNA" ("ID_LQDCION_ADCNAL_PRSNA")
  )  ENABLE,
	 CONSTRAINT "GI_G_LQDC_ESTB_EXTRNJRO" CHECK (extrnjro in ('S','N')) ENABLE,
	 CONSTRAINT "GI_G_LQDC_PRSN_ID_DPTM_EXPD_FK" FOREIGN KEY ("ID_DPRTMNTO_EXPDCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "GI_G_LQDC_PRSN_ID_LQDCION_FK" FOREIGN KEY ("ID_LQDCION")
	  REFERENCES "GI_G_LIQUIDACIONES" ("ID_LQDCION") DISABLE,
	 CONSTRAINT "GI_G_LQDC_PRSN_CDG_ACT_ECNM_FK" FOREIGN KEY ("ID_ACTVDAD_ECNMCA_CLS")
	  REFERENCES "DF_C_ACTIVIDADES_ECNMCA_CLS" ("ID_ACTVDAD_ECNMCA_CLS") ENABLE,
	 CONSTRAINT "GI_G_LQDC_ESTB_ID_SJTO_TPO_FK" FOREIGN KEY ("ID_SJTO_TPO")
	  REFERENCES "DF_I_SUJETOS_TIPO" ("ID_SJTO_TPO") ENABLE,
	 CONSTRAINT "GI_G_LQDC_PRSN_ID_PAIS_EXPD_FK" FOREIGN KEY ("ID_PAIS_EXPDCION")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "GI_G_LQDC_PRSN_ID_OFCNA_ORG_FK" FOREIGN KEY ("ID_OFCNA_ORGN")
	  REFERENCES "DF_C_OFICINAS" ("ID_OFCNA") ENABLE,
	 CONSTRAINT "GI_G_LQDC_PRSN_ID_MNCP_EXPD_FK" FOREIGN KEY ("ID_MNCPIO_EXPDCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE
   ) ;

