
  CREATE TABLE "GI_G_CERTIFICADOS_DECLARACION"
   (	"ID_CRTFCDO_DCL" NUMBER DEFAULT "GENESYS"."SQ_GI_G_CERTIFICADO_DCLARACION"."NEXTVAL" CONSTRAINT "GI_G_CRT_DCLRCN_ID_CRTF_DCL_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_G_CRT_DCLRCN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "GI_G_CRT_DCLRCN_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "GI_G_CRT_DCLRCN_ID_IMP_SB_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "GI_G_CRT_DCLRCN_ID_SJTO_IMPS_NN" NOT NULL ENABLE,
	"FCHA_OFCIO" TIMESTAMP (6) CONSTRAINT "GI_G_CRT_DCLRCN_FCHA_OFCIO_NN" NOT NULL ENABLE,
	"CNSCTVO" NUMBER CONSTRAINT "GI_G_CRT_DCLRCN_CNSCTVO_NN" NOT NULL ENABLE,
	"NMRO_CTROL" NUMBER CONSTRAINT "GI_G_CRT_DCLRCN_NMRO_CTROL_NN" NOT NULL ENABLE,
	"USRIO_DGTA" VARCHAR2(50),
	"FCHA_DGTA" TIMESTAMP (6),
	"USRIO_MDFCA" VARCHAR2(50),
	"FCHA_MDFCA" TIMESTAMP (6),
	"INDCDOR_ACTVO" VARCHAR2(1) DEFAULT 's',
	"ID_PLNTLLA" NUMBER(15,0),
	"VGNCIA" NUMBER,
	"ID_PRDO" NUMBER,
	"ID_DCLRCION" NUMBER,
	 CONSTRAINT "GI_G_CRT_DCLRCN_INDCDR_ACTVO_CK" CHECK (indcdor_actvo in('s','n')) ENABLE,
	 CONSTRAINT "GI_G_CRT_DCLRCN_ID_OFC_DCLC_PK" PRIMARY KEY ("ID_CRTFCDO_DCL")
  USING INDEX  ENABLE,
	 FOREIGN KEY ("ID_PLNTLLA")
	  REFERENCES "GN_D_PLANTILLAS" ("ID_PLNTLLA") ENABLE,
	 CONSTRAINT "GI_G_CRT_DCLRCN_ID_DCLRCION_FK" FOREIGN KEY ("ID_DCLRCION")
	  REFERENCES "GI_G_DECLARACIONES" ("ID_DCLRCION") ENABLE,
	 CONSTRAINT "GI_G_CRT_DCLRCN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_G_CRT_DCLRCN_ID_IMP_SB_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GI_G_CRT_DCLRCN_ID_SJTO_IMPS_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "GI_G_CRT_DCLRCN_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE
   ) ;

