
  CREATE TABLE "GI_G_DCLRCNES_MVMNTO_FNNCRO"
   (	"ID_DCLRCION_MVMNTO_FNNCRO" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_ID_DCL_MV_FN_NN" NOT NULL ENABLE,
	"ID_DCLRCION" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_ID_DCLRCION_NN" NOT NULL ENABLE,
	"ID_MVMNTO_DTLLE" NUMBER,
	"ID_CNCPTO" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_ID_CNCPTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_ACTO_CNCPTO" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_ID_IMP_AC_CN_NN" NOT NULL ENABLE,
	"VLOR_DBE" NUMBER DEFAULT 0 CONSTRAINT "GI_G_DCL_MV_FN_VLOR_DBE_NN" NOT NULL ENABLE,
	"VLOR_HBER" NUMBER DEFAULT 0 CONSTRAINT "GI_G_DCL_MV_FN_VLOR_HBER_NN" NOT NULL ENABLE,
	"CDGO_CNCPTO_TPO" VARCHAR2(3) CONSTRAINT "GI_G_DCL_MV_FN_CDGO_CTO_TPO_NN" NOT NULL ENABLE,
	"ID_CNCPTO_RLCNAL" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_ID_CNCP_RLCL_NN" NOT NULL ENABLE,
	"ID_DSCNTO_RGLA" NUMBER,
	"PRCNTJE_DSCNTO" NUMBER DEFAULT 0 CONSTRAINT "GI_G_DCL_MV_FN_PRCNTJE_DSCN_NN" NOT NULL ENABLE,
	"ID_FRMLRIO_RGION" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_ID_FRML_RGN_NN" NOT NULL ENABLE,
	"ID_FRMLRIO_RGION_ATRBTO" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_ID_FR_RG_AT_NN" NOT NULL ENABLE,
	"FLA" NUMBER CONSTRAINT "GI_G_DCL_MV_FN_FLA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_VLOR_HBER_CK" CHECK (vlor_hber >= 0) ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_VLOR_DBE_CK" CHECK (vlor_dbe >= 0) ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_CDGO_CTO_TPO_CK" CHECK (cdgo_cncpto_tpo in ('C','I','D')) ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_DCL_MV_FN_PK" PRIMARY KEY ("ID_DCLRCION_MVMNTO_FNNCRO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_DCLRCION_FK" FOREIGN KEY ("ID_DCLRCION")
	  REFERENCES "GI_G_DECLARACIONES" ("ID_DCLRCION") ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_FR_RG_AT_FK" FOREIGN KEY ("ID_FRMLRIO_RGION_ATRBTO")
	  REFERENCES "GI_D_FRMLRIOS_RGION_ATRBTO" ("ID_FRMLRIO_RGION_ATRBTO") ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_DSCO_RGLA_FK" FOREIGN KEY ("ID_DSCNTO_RGLA")
	  REFERENCES "RE_G_DESCUENTOS_REGLA" ("ID_DSCNTO_RGLA") ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_MVMO_DTLL_FK" FOREIGN KEY ("ID_MVMNTO_DTLLE")
	  REFERENCES "GF_G_MOVIMIENTOS_DETALLE" ("ID_MVMNTO_DTLLE") DISABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_IMP_AC_CN_FK" FOREIGN KEY ("ID_IMPSTO_ACTO_CNCPTO")
	  REFERENCES "DF_I_IMPUESTOS_ACTO_CONCEPTO" ("ID_IMPSTO_ACTO_CNCPTO") ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_CNCP_RLCL_FK" FOREIGN KEY ("ID_CNCPTO_RLCNAL")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "GI_G_DCL_MV_FN_ID_CNCPTO_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE
   ) ;

