
  CREATE TABLE "GI_G_TITULOS_EJCTVO_ANLDO"
   (	"ID_TITULO_EJCTVO_ANLDO" NUMBER DEFAULT "GENESYS"."SQ_GI_G_TITULOS_EJCTVO_ANLDO"."NEXTVAL" CONSTRAINT "GI_G_TTL_EJ_AN_ID_TTL_EJ_AN_NN" NOT NULL ENABLE,
	"ID_TTLO_EJCTVO" NUMBER CONSTRAINT "GI_G_TTL_EJ_AN_ID_TTLO_EJCT_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(1000) CONSTRAINT "GI_G_TTL_EJ_AN_OBSRVCION_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "GI_G_TTL_EJ_AN_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA" DATE DEFAULT sysdate CONSTRAINT "GI_G_TTL_EJ_AN_FCHA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_TTL_EJ_AN_ID_TTL_EJ_AN_PK" PRIMARY KEY ("ID_TITULO_EJCTVO_ANLDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_TTL_EJ_AN_ID_TTLO_EJCT_FK" FOREIGN KEY ("ID_TTLO_EJCTVO")
	  REFERENCES "GI_G_TITULOS_EJECUTIVO" ("ID_TTLO_EJCTVO") ENABLE,
	 CONSTRAINT "GI_G_TTL_EJ_AN_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

