
  CREATE TABLE "GI_G_INFORMACION_METADATA"
   (	"ID_INFRMCION_MTDTA" NUMBER DEFAULT "GENESYS"."SQ_GI_G_INFORMACION_METADATA"."NEXTVAL" CONSTRAINT "GI_G_INFCION_MTDT_ID_INF_MT_NN" NOT NULL ENABLE,
	"ID_ORGEN" NUMBER CONSTRAINT "GI_G_INFCION_MTDT_ID_ORGEN_NN" NOT NULL ENABLE,
	"ID_PRCSO_ORGEN" NUMBER,
	"ID_IMPSTOS_SBMPSTO_MTDTA" NUMBER CONSTRAINT "GI_G_INFCION_MTDT_ID_I_S_MT_NN" NOT NULL ENABLE,
	"VLOR" VARCHAR2(4000) CONSTRAINT "GI_G_INFCION_MTDT_VLOR_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_INFCION_MTDT_ID_INF_MT_PK" PRIMARY KEY ("ID_INFRMCION_MTDTA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_INFCION_MTDT_ID_PRC_OR_FK" FOREIGN KEY ("ID_PRCSO_ORGEN")
	  REFERENCES "DF_S_PROCESOS" ("ID_PRCSO") ENABLE,
	 CONSTRAINT "GI_G_INFCION_MTDT_ID_I_S_MT_PK" FOREIGN KEY ("ID_IMPSTOS_SBMPSTO_MTDTA")
	  REFERENCES "DF_I_IMPSTOS_SBMPSTO_MTDTA" ("ID_IMPSTO_SBMPSTO_MTDTA") ENABLE
   ) ;

