
  CREATE TABLE "GI_G_DECLARACIONES_ADICIONAL"
   (	"ID_DCLRCION_ADCNAL" NUMBER(15,0) CONSTRAINT "GI_G_DCL_ADCNAL_ID_DCL_ADCN_NN" NOT NULL ENABLE,
	"ID_DCLRCION_PRVDA" NUMBER(15,0),
	"CDGO_CLNTE" NUMBER(15,0),
	"ID_IMPSTO" NUMBER(15,0),
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0),
	"ID_TPO_FRMLRIO" NUMBER(15,0),
	"VGNCIA" NUMBER(15,0),
	"ID_PRDO" NUMBER(15,0),
	"DECLARACION_FLEX_N01" NUMBER,
	"DECLARACION_FLEX_N02" NUMBER,
	"DECLARACION_FLEX_N03" NUMBER,
	"DECLARACION_FLEX_N04" NUMBER,
	"DECLARACION_FLEX_D01" TIMESTAMP (6),
	"DECLARACION_FLEX_D02" TIMESTAMP (6),
	"DECLARACION_FLEX_D03" TIMESTAMP (6),
	"DECLARACION_FLEX_D04" TIMESTAMP (6),
	"DECLARACION_FLEX_01" VARCHAR2(500),
	"DECLARACION_FLEX_02" VARCHAR2(500),
	"DECLARACION_FLEX_03" VARCHAR2(500),
	"DECLARACION_FLEX_04" VARCHAR2(500),
	"DECLARACION_FLEX_05" VARCHAR2(500),
	"DECLARACION_FLEX_06" VARCHAR2(500),
	"DECLARACION_FLEX_07" VARCHAR2(500),
	"DECLARACION_FLEX_08" VARCHAR2(500),
	"DECLARACION_FLEX_CLOB" CLOB,
	 CONSTRAINT "GI_G_DCL_ADCNAL_ID_DCL_ADCN_PK" PRIMARY KEY ("ID_DCLRCION_ADCNAL")
  USING INDEX  ENABLE
   )
 LOB ("DECLARACION_FLEX_CLOB") STORE AS SECUREFILE "SYS_LOB0000094589C00025$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

