
  CREATE TABLE "GI_G_DETERMINACION_AD_PRSNA"
   (	"ID_DTRMNCION_AD_PRSNA" NUMBER CONSTRAINT "GI_G_DTMN_PRSN_ID_DTRM_PRSN_NN" NOT NULL ENABLE,
	"ID_DTRMNCION" NUMBER CONSTRAINT "GI_G_DTMN_PRSN_ID_DTRMNCION_NN" NOT NULL ENABLE,
	"ID_ACTVDAD_ECNMCA_CLS" NUMBER,
	"FCHA_NTFCCION" TIMESTAMP (6),
	"ID_OFCNA_ORGN" NUMBER,
	"NMRO_NTFCCION" VARCHAR2(50),
	"LUGAR_EXPDCION" VARCHAR2(200),
	"ID_PAIS_EXPDCION" NUMBER,
	"ID_DPRTMNTO_EXPDCION" NUMBER,
	"ID_MNCPIO_EXPDCION" NUMBER,
	"NMRO_MTRCLA" VARCHAR2(50),
	"EXTRNJRO" VARCHAR2(1) DEFAULT 'N',
	"INDCDOR_MXTO" VARCHAR2(1) DEFAULT 'N',
	"ID_SJTO_TPO" NUMBER,
	 CONSTRAINT "GI_G_DTMN_PRSN_ID_DTRM_PRSN_PK" PRIMARY KEY ("ID_DTRMNCION_AD_PRSNA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_INDCDOR_MXTO_CK" CHECK (indcdor_mxto in ('S','N')) ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_EXTRNJRO_CK" CHECK (extrnjro in ('S','N')) ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_ID_MNCP_EXPD_FK" FOREIGN KEY ("ID_MNCPIO_EXPDCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_ID_SJTO_TPO_FK" FOREIGN KEY ("ID_SJTO_TPO")
	  REFERENCES "DF_I_SUJETOS_TIPO" ("ID_SJTO_TPO") ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_ID_OFCNA_ORG_FK" FOREIGN KEY ("ID_OFCNA_ORGN")
	  REFERENCES "DF_C_OFICINAS" ("ID_OFCNA") ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_ID_DPTM_EXPD_FK" FOREIGN KEY ("ID_DPRTMNTO_EXPDCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_ID_DTRMNCION_FK" FOREIGN KEY ("ID_DTRMNCION")
	  REFERENCES "GI_G_DETERMINACIONES" ("ID_DTRMNCION") ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_ID_PAIS_EXPD_FK" FOREIGN KEY ("ID_PAIS_EXPDCION")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "GI_G_DTMN_PRSN_CDG_ACT_ECNM_FK" FOREIGN KEY ("ID_ACTVDAD_ECNMCA_CLS")
	  REFERENCES "DF_C_ACTIVIDADES_ECNMCA_CLS" ("ID_ACTVDAD_ECNMCA_CLS") ENABLE
   ) ;

