
  CREATE TABLE "GI_G_TITULO_RESPONSABLE"
   (	"ID_TTLO_RSPNSBLE" NUMBER(15,0) CONSTRAINT "GI_G_TTLO_RSPN_ID_TTLO_RSPN_NN" NOT NULL ENABLE,
	"ID_TTLO_EJCTVO" NUMBER(15,0) CONSTRAINT "GI_G_TTLO_RSPN_ID_TTLO_EJCT_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(3) CONSTRAINT "GI_G_TTLO_RSPN_CDGO_IND_TPO_NN" NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(25) CONSTRAINT "GI_G_TTLO_RSPN_IDNTFCCION_NN" NOT NULL ENABLE,
	"PRMER_NMBRE" VARCHAR2(100) CONSTRAINT "GI_G_TTLO_RSPN_PRMER_NMBRE_NN" NOT NULL ENABLE,
	"SGNDO_NMBRE" VARCHAR2(100),
	"PRMER_APLLDO" VARCHAR2(100) CONSTRAINT "GI_G_TTLO_RSPN_PRMER_APLLDO_NN" NOT NULL ENABLE,
	"SGNDO_APLLDO" VARCHAR2(100),
	"DRCCION" VARCHAR2(100),
	"ID_PAIS" NUMBER(15,0),
	"ID_DPRTMNTO" NUMBER(15,0),
	"ID_MNCPIO" NUMBER(15,0),
	"DRCCION_NTFCCION" VARCHAR2(100),
	"ID_PAIS_NTFCCION" NUMBER(15,0),
	"ID_DPRTMNTO_NTFCCION" NUMBER(15,0),
	"ID_MNCPIO_NTFCCION" NUMBER(15,0),
	"EMAIL" VARCHAR2(320),
	"TLFNO" VARCHAR2(50),
	"PRNCPAL_S_N" VARCHAR2(1) CONSTRAINT "GI_G_TTLO_RSPN_PRNCPAL_S_N_NN" NOT NULL ENABLE,
	"CDGO_TPO_RSPNSBLE" VARCHAR2(3),
	"PRCNTJE_PRTCPCION" NUMBER(5,2) DEFAULT 0,
	 CONSTRAINT "GI_G_TTLO_RSPN_PRNCPAL_S_N_CK" CHECK (prncpal_s_n in ('N','S')) ENABLE,
	 CONSTRAINT "GI_G_TTLO_RSPN_ID_TTLO_RSPN_PK" PRIMARY KEY ("ID_TTLO_RSPNSBLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_TTLO_RSPN_ID_PAIS_FK" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "GI_G_TTLO_RSPN_ID_MNCPIO_FK" FOREIGN KEY ("ID_MNCPIO")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "GI_G_TTLO_IMPST_ID_PAIS_NTF_FK" FOREIGN KEY ("ID_PAIS_NTFCCION")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "GI_G_TTLO_RSPN_ID_DPRTMNTO_FK" FOREIGN KEY ("ID_DPRTMNTO")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "GI_G_TTLO_RSPN_CDGO_IND_TPO_FK" FOREIGN KEY ("CDGO_IDNTFCCION_TPO")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE,
	 CONSTRAINT "GI_G_TTLO_IMPST_ID_DPRT_NTF_FK" FOREIGN KEY ("ID_DPRTMNTO_NTFCCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "GI_G_TTLO_RSPN_ID_TTLO_EJCT_FK" FOREIGN KEY ("ID_TTLO_EJCTVO")
	  REFERENCES "GI_G_TITULOS_EJECUTIVO_2" ("ID_TTLO_EJCTVO") ENABLE,
	 CONSTRAINT "GI_G_TTLO_IMPST_ID_MNC_NTFC_FK" FOREIGN KEY ("ID_MNCPIO_NTFCCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE
   ) ;

