
  CREATE TABLE "GI_G_DECLARACIONES_DETALLE_OL"
   (	"ID_DCLRCION_DTLLE_OL" NUMBER(15,0) CONSTRAINT "GI_G_DL_DTL_OL_ID_DL_DTL_OL_NN" NOT NULL ENABLE,
	"ID_DCLRCION_PRVDA_OL" NUMBER(15,0) CONSTRAINT "GI_G_DL_DTL_OL_ID_DL_PRVD_O_NN" NOT NULL ENABLE,
	"ID_DCLRCION_ITEM" NUMBER(15,0) CONSTRAINT "GI_G_DL_DTL_OL_ID_DL_ITEM_NN" NOT NULL ENABLE,
	"CDGO_ITEM" VARCHAR2(3) CONSTRAINT "GI_G_DL_DTL_OL_CDGO_ITEM_NN" NOT NULL ENABLE,
	"DSCRPCION_ITEM" VARCHAR2(200) CONSTRAINT "GI_G_DL_DTL_OL_DSCRPC_ITEM_NN" NOT NULL ENABLE,
	"VLOR" NUMBER(16,2),
	 CONSTRAINT "GI_G_DL_DTL_OL_ID_DL_DTL_OL_PK" PRIMARY KEY ("ID_DCLRCION_DTLLE_OL")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_DL_DTL_OL_ID_DL_ITEM_FK" FOREIGN KEY ("ID_DCLRCION_ITEM")
	  REFERENCES "GI_D_DECLARACIONES_ITEM" ("ID_DCLRCION_ITEM") ENABLE,
	 CONSTRAINT "GI_G_DL_DTL_OL_ID_DL_PRVD_O_FK" FOREIGN KEY ("ID_DCLRCION_PRVDA_OL")
	  REFERENCES "GI_G_DECLARACIONES_PRIVADA_OL" ("ID_DCLRCION_PRVDA_OL") ENABLE
   ) ;

