
  CREATE TABLE "GI_G_RENTAS_ACTO_CONCEPTO"
   (	"ID_RNTA_ACTO_CNCPTO" NUMBER DEFAULT "GENESYS"."SG_GI_G_RENTAS_ACTO_CONCEPTO"."NEXTVAL" CONSTRAINT "GI_G_RNT_ACT_CNC_ID_RN_AC_C_NN" NOT NULL ENABLE,
	"ID_RNTA_ACTO" NUMBER CONSTRAINT "GI_G_RNT_ACT_CNC_ID_RNT_ACT_NN" NOT NULL ENABLE,
	"ID_IMPSTO_ACTO_CNCPTO" NUMBER CONSTRAINT "GI_G_RNT_ACT_CNC_ID_IM_AT_C_NN" NOT NULL ENABLE,
	"BSE_CNCPTO" NUMBER CONSTRAINT "GI_G_RNT_ACT_CNC_BSE_CNCPTO_NN" NOT NULL ENABLE,
	"TRFA" NUMBER CONSTRAINT "GI_G_RNT_ACT_CNC_TRFA_NN" NOT NULL ENABLE,
	"TXTO_TRFA" VARCHAR2(20) CONSTRAINT "GI_G_RNT_ACT_CNC_TXTO_TRFA_NN" NOT NULL ENABLE,
	"VLOR_LQDDO" NUMBER CONSTRAINT "GI_G_RNT_ACT_CNC_VLOR_LQDDO_NN" NOT NULL ENABLE,
	"VLOR_INTRES" NUMBER,
	"FCHA_VNCMNTO" TIMESTAMP (6),
	"VLOR_TRFA" NUMBER DEFAULT 1 CONSTRAINT "GI_G_RNT_ACT_CNC_VLOR_BSE_NN" NOT NULL ENABLE,
	"VLOR_INDCDOR" NUMBER DEFAULT 1 CONSTRAINT "GI_G_RNT_ACT_CNC_VLOR_INDCDOR_NN" NOT NULL ENABLE,
	"INDCDOR_MGRDO" VARCHAR2(1),
	"BSE_INCIAL" NUMBER,
	"BSE_FNAL" NUMBER,
	"FCHA_DGTA" TIMESTAMP (6),
	"FCHA_MDFCA" TIMESTAMP (6),
	"USER_DGTA" VARCHAR2(100),
	"USER_MDFCA" VARCHAR2(100),
	"PRCNTJE_BSE_LQDCION" NUMBER,
	"FCTOR" NUMBER DEFAULT 1,
	 CONSTRAINT "GI_G_RNT_ACT_CNC_ID_RN_AC_C_PK" PRIMARY KEY ("ID_RNTA_ACTO_CNCPTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_RNT_ACT_CNC_ID_IM_AT_C_FK" FOREIGN KEY ("ID_IMPSTO_ACTO_CNCPTO")
	  REFERENCES "DF_I_IMPUESTOS_ACTO_CONCEPTO" ("ID_IMPSTO_ACTO_CNCPTO") ENABLE,
	 CONSTRAINT "GI_G_RNT_ACT_CNC_ID_RNT_ACT_FK" FOREIGN KEY ("ID_RNTA_ACTO")
	  REFERENCES "GI_G_RENTAS_ACTO" ("ID_RNTA_ACTO") ENABLE
   ) ;

