
  CREATE TABLE "GI_G_RNTAS_USRIO_SN_ATRZCN"
   (	"ID_USRIO_RNTA_SN_ATRZCION" NUMBER CONSTRAINT "GI_G_RNT_SN_ATRZ_ID_USR_SN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GI_G_RNT_SN_ATRZ_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER(15,0) CONSTRAINT "GI_G_RNT_SN_ATRZ_ID_USRIO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) CONSTRAINT "GI_G_RNT_SN_ATRZ_ID_SBIMPSTO_NN" NOT NULL ENABLE,
	"FCHA_INCIO" TIMESTAMP (6),
	"FCHA_FNAL" TIMESTAMP (6),
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "GI_G_RNT_SN_ATRZ_USRIO_DGTA_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "GI_G_RNT_SN_ATRZ_FCHA_DGTA_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "GI_G_RNT_SN_ATRZ_ID_USR_SN_PK" PRIMARY KEY ("ID_USRIO_RNTA_SN_ATRZCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_RNT_SN_ATRZ_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "GI_G_RNT_SN_ATRZ_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GI_G_RNT_SN_ATRZ_ID_SBIMPSTO_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE
   ) ;

