
  CREATE TABLE "GI_G_TITULOS_EJCTVO_CNCPTO"
   (	"ID_TTLO_EJCTVO_CNCPTO" NUMBER DEFAULT "GENESYS"."SQ_GI_G_TITULOS_EJCTVO_CNCPTO"."NEXTVAL" CONSTRAINT "GI_G_TT_EJ_CN_ID_TT_EJ_CN_NN" NOT NULL ENABLE,
	"ID_TTLO_EJCTVO" NUMBER CONSTRAINT "GI_G_TT_EJ_CN_ID_TTLO_EJCTV_NN" NOT NULL ENABLE,
	"ID_IMPSTO_ACTO_CNCPTO" NUMBER CONSTRAINT "GI_G_TT_EJ_CN_ID_IM_AC_CN_NN" NOT NULL ENABLE,
	"VLOR_CPTAL" NUMBER CONSTRAINT "GI_G_TT_EJ_CN_VLOR_CPTAL_NN" NOT NULL ENABLE,
	"VLOR_INTRES" NUMBER CONSTRAINT "GI_G_TT_EJ_CN_VLOR_INTRES_NN" NOT NULL ENABLE,
	 CONSTRAINT "GI_G_TT_EJ_CN_ID_TT_EJ_CN_PK" PRIMARY KEY ("ID_TTLO_EJCTVO_CNCPTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_G_TT_EJ_CN_ID_TTLO_EJCTV_FK" FOREIGN KEY ("ID_TTLO_EJCTVO")
	  REFERENCES "GI_G_TITULOS_EJECUTIVO" ("ID_TTLO_EJCTVO") ENABLE,
	 CONSTRAINT "GI_G_TT_EJ_CN_ID_IM_AC_CN_FK" FOREIGN KEY ("ID_IMPSTO_ACTO_CNCPTO")
	  REFERENCES "DF_I_IMPUESTOS_ACTO_CONCEPTO" ("ID_IMPSTO_ACTO_CNCPTO") ENABLE
   ) ;

