
  CREATE TABLE "GI_I_LIQUIDACION_2024"
   (	"CDGO_CLNTE" NUMBER(15,0),
	"ID_IMPSTO" NUMBER(15,0),
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0),
	"VGNCIA" NUMBER(4,0),
	"CDGO_MRCA" VARCHAR2(10),
	"CDGO_LNEA" NUMBER(15,0),
	"MDLO" NUMBER(4,0),
	"CDGO_CLSE" VARCHAR2(4),
	"CDGO_BLNDJE" VARCHAR2(4),
	"CLNDRJE" NUMBER,
	"AVLUO" NUMBER,
	"AVLUO_CLCLDO" NUMBER,
	"VLOR_LQDDO" NUMBER,
	"GRUPO" NUMBER,
	"N_MESES" NUMBER,
	"TRFA" NUMBER,
	"AVLUO_2024" NUMBER,
	"APROBADO" VARCHAR2(2),
	"FCHA" DATE,
	"OBSERVACION" VARCHAR2(1000),
	"ID_SJTO_IMPSTO" NUMBER,
	"PLACA" VARCHAR2(10)
   ) ;

