
  CREATE TABLE "GI_RE_DCL_ARCHVOS_TRZA"
   (	"ID_DCL_ARC" NUMBER,
	"NMRO_CNSCTVO" NUMBER CONSTRAINT "GI_RE_DCL_ARC_TRZ_ID_DCL_NN" NOT NULL ENABLE,
	"CDGO_ESTDO_CRGA" VARCHAR2(2) CONSTRAINT "GI_RE_DCL_ARC_TRZ_CD_STD_CG_NN" NOT NULL ENABLE,
	"USRNME_DGTA" VARCHAR2(100),
	"FCHA_DGTA" TIMESTAMP (6) DEFAULT systimestamp,
	"USRNME_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	"OBSRVCION" VARCHAR2(100),
	 CONSTRAINT "GI_RE_DCL_ARC_TRZ_ID_DCL_AR_PK" PRIMARY KEY ("ID_DCL_ARC")
  USING INDEX  ENABLE,
	 CONSTRAINT "GI_RE_DCL_ARC_TRZ_CD_STD_CG_FK" FOREIGN KEY ("CDGO_ESTDO_CRGA")
	  REFERENCES "GI_RE_DCL_ARCHVOS_ESTDO" ("CDGO_ESTDO_CRGA") ENABLE
   ) ;

