
  CREATE TABLE "GJ_D_RECURSOS_AJUSTE_MOTIVO"
   (	"ID_RCRSO_AJSTE_MTVO" NUMBER CONSTRAINT "GJ_D_RC_AJST_MT_ID_RC_AJ_MT_NN" NOT NULL ENABLE,
	"ID_RCRSO_TIPO_CLNTE" NUMBER CONSTRAINT "GJ_D_RC_AJST_MT_ID_RC_TP_C_NN" NOT NULL ENABLE,
	"ID_AJSTE_MTVO" NUMBER CONSTRAINT "GJ_D_RC_AJST_MT_ID_AJS_MTV_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GJ_D_RC_AJST_MT_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GJ_D_RC_AJST_MT_ID_RC_AJ_MT_PK" PRIMARY KEY ("ID_RCRSO_AJSTE_MTVO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_RC_AJST_MT_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GJ_D_RC_AJ_MT_I_R_T_C_I_A_M_UN" UNIQUE ("ID_RCRSO_TIPO_CLNTE", "ID_AJSTE_MTVO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_RC_AJST_MT_ID_RC_TP_C_FK" FOREIGN KEY ("ID_RCRSO_TIPO_CLNTE")
	  REFERENCES "GJ_D_RECURSOS_TIPO_CLIENTE" ("ID_RCRSO_TIPO_CLNTE") ENABLE,
	 CONSTRAINT "GJ_D_RC_AJST_MT_ID_AJS_MTV_FK" FOREIGN KEY ("ID_AJSTE_MTVO")
	  REFERENCES "GF_D_AJUSTE_MOTIVO" ("ID_AJSTE_MTVO") ENABLE
   ) ;

