
  CREATE TABLE "GJ_D_ACTOS_TIPO_RESOLUCION"
   (	"ID_ACTO_TPO_RSLCION" NUMBER CONSTRAINT "GJ_D_ACTS_TP_RSL_ID_AC_TP_R_NN" NOT NULL ENABLE,
	"ID_RCRSO_TIPO_CLNTE" NUMBER CONSTRAINT "GJ_D_ACTS_TP_RSL_ID_RC_TP_C_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "GJ_D_ACTS_TP_RSL_ID_ACT_TPO_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GJ_D_ACTS_TP_RSL_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GJ_D_ACTS_TP_RSL_ID_AC_TP_R_PK" PRIMARY KEY ("ID_ACTO_TPO_RSLCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_ACTS_TP_RSL_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GJ_D_AC_TP_R_I_R_T_C_I_AC_T_UN" UNIQUE ("ID_RCRSO_TIPO_CLNTE", "ID_ACTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_ACTS_TP_RSL_ID_RC_TP_C_FK" FOREIGN KEY ("ID_RCRSO_TIPO_CLNTE")
	  REFERENCES "GJ_D_RECURSOS_TIPO_CLIENTE" ("ID_RCRSO_TIPO_CLNTE") ENABLE,
	 CONSTRAINT "GJ_D_ACTS_TP_RSL_ID_ACT_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE
   ) ;

