
  CREATE TABLE "GJ_D_MOTIVOS_CLIENTE"
   (	"ID_MTVO_CLNTE" NUMBER CONSTRAINT "GJ_D_MTVS_CLNT_ID_MTV_CLNTE_NN" NOT NULL ENABLE,
	"ID_MTVO" NUMBER CONSTRAINT "GJ_D_MTVS_CLNT_ID_MTVO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GJ_D_MTVS_CLNT_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"A_I_R" VARCHAR2(1) CONSTRAINT "GJ_D_MTVS_CLNT_A_I_R_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GJ_D_MTVS_CLNT_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GJ_D_MTVS_CLNT_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GJ_D_MTVS_CLNT_ID_MTV_CLNTE_PK" PRIMARY KEY ("ID_MTVO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_MTVS_CLNT_A_I_R_CK" CHECK (a_i_r in ('A','I','R')) ENABLE,
	 CONSTRAINT "GJ_D_MTVS_CL_ID_M_C_C_A_I_R_UN" UNIQUE ("ID_MTVO", "CDGO_CLNTE", "A_I_R")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_MTVS_CLNT_ID_MTVO_FK" FOREIGN KEY ("ID_MTVO")
	  REFERENCES "GJ_D_MOTIVOS" ("ID_MTVO") ENABLE,
	 CONSTRAINT "GJ_D_MTVS_CLNT_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

