
  CREATE TABLE "GJ_D_RECURSO_TIPO_ACTO_TIPO"
   (	"ID_RCRSO_TPO_ACTO_TPO" NUMBER CONSTRAINT "GJ_D_R_TP_AC_TP_ID_R_T_AC_T_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "GJ_D_R_TP_AC_TP_ID_ACTO_TPO_NN" NOT NULL ENABLE,
	"ID_RCRSO_TIPO_CLNTE" NUMBER CONSTRAINT "GJ_D_R_TP_AC_TP_ID_RC_TP_CL_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GJ_D_R_TP_AC_TP_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GJ_D_R_TP_AC_TP_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GJ_D_R_TP_AC_TP_ID_R_T_AC_T_PK" PRIMARY KEY ("ID_RCRSO_TPO_ACTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_R_TP_A_T_I_A_T_I_R_T_C_UN" UNIQUE ("ID_ACTO_TPO", "ID_RCRSO_TIPO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_R_TP_AC_TP_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "GJ_D_R_TP_AC_TP_ID_RC_TP_CL_FK" FOREIGN KEY ("ID_RCRSO_TIPO_CLNTE")
	  REFERENCES "GJ_D_RECURSOS_TIPO_CLIENTE" ("ID_RCRSO_TIPO_CLNTE") ENABLE
   ) ;

