
  CREATE TABLE "GJ_D_PARAMETROS"
   (	"ID_PRMTRO" NUMBER CONSTRAINT "GJ_D_PRMTROS_ID_PRMTRO_NN" NOT NULL ENABLE,
	"ID_RCRSO_TPO_ACCION" NUMBER CONSTRAINT "GJ_D_PRMTROS_ID_RCR_TPO_ACC_NN" NOT NULL ENABLE,
	"ID_TREA_ITEM" NUMBER,
	"NMBRE_PRMTRO" VARCHAR2(255) CONSTRAINT "GJ_D_PRMTROS_NMBR_PRMT_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GJ_D_PRMTROS_ACTVO_NN" NOT NULL ENABLE,
	"TPO_ORGN" VARCHAR2(1) DEFAULT 'I' CONSTRAINT "GJ_D_PRMTROS_ITM_TPO_ORGN_NN" NOT NULL ENABLE,
	"ORGEN" VARCHAR2(4000),
	 CONSTRAINT "GJ_D_PRMTROS_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GJ_D_PRMTROS_ITM_TPO_ORGN_CK" CHECK (tpo_orgn in ('E','I','F','A')) ENABLE,
	 CONSTRAINT "GJ_D_PRMTROS_ID_PRMTRO_PK" PRIMARY KEY ("ID_PRMTRO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_D_PRMTROS_ID_RCR_TPO_ACC_FK" FOREIGN KEY ("ID_RCRSO_TPO_ACCION")
	  REFERENCES "GJ_D_RECURSOS_TIPO_ACCION" ("ID_RCRSO_TPO_ACCION") ENABLE,
	 CONSTRAINT "GJ_D_PRMTROS_ID_TR_ITM_FK" FOREIGN KEY ("ID_TREA_ITEM")
	  REFERENCES "GJ_D_TAREAS_ITEM" ("ID_TREA_ITEM") ENABLE
   ) ;

