
  CREATE TABLE "GJ_G_RECURSOS_DOCUMENTO_DET"
   (	"ID_RCRSO_DCMNTO_DET" NUMBER CONSTRAINT "GJ_G_RCS_DCM_DT_ID_RC_DC_DT_NN" NOT NULL ENABLE,
	"ID_RCRSO_DCMNTO" NUMBER CONSTRAINT "GJ_G_RCS_DCM_DT_ID_RC_DCMNT_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER CONSTRAINT "GJ_G_RCS_DCM_DT_ORDEN_NN" NOT NULL ENABLE,
	"DCMNTO" CLOB CONSTRAINT "GJ_G_RCS_DCM_DT_DCMNTO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GJ_G_RCS_DCM_DT_ID_RC_DC_DT_PK" PRIMARY KEY ("ID_RCRSO_DCMNTO_DET")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_G_RCS_DCM_DT_ID_RC_DCMNT_FK" FOREIGN KEY ("ID_RCRSO_DCMNTO")
	  REFERENCES "GJ_G_RECURSOS_DOCUMENTO" ("ID_RCRSO_DCMNTO") ENABLE
   ) ;

