
  CREATE TABLE "GJ_G_RCRSOS_ACCN_VGNC_CNCPT"
   (	"ID_RCRSO_ACCION_VGNC_CNCPTO" NUMBER CONSTRAINT "GJ_RCR_A_VG_C_ID_RC_AC_VG_C_NN" NOT NULL ENABLE,
	"ID_RCRSO_ACCION" NUMBER CONSTRAINT "GJ_RCR_A_VG_C_ID_RC_ACC_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER CONSTRAINT "GJ_RCR_A_VG_C_VGNCIA_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER,
	"ID_CNCPTO" NUMBER,
	"VLOR_SLDO_CPTAL" NUMBER,
	"VLOR_AJSTE" NUMBER,
	 CONSTRAINT "GJ_RCR_A_VG_C_ID_RC_AC_VG_C_PK" PRIMARY KEY ("ID_RCRSO_ACCION_VGNC_CNCPTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GJ_RCR_A_VG_C_ID_RC_ACC_FK" FOREIGN KEY ("ID_RCRSO_ACCION")
	  REFERENCES "GJ_G_RECURSOS_ACCION" ("ID_RCRSO_ACCION") ENABLE,
	 CONSTRAINT "GJ_RCR_A_VG_C_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GJ_RCR_A_VG_C_ID_CNCPTO_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE
   ) ;

