
  CREATE TABLE "GN_D_EVENTOS"
   (	"ID_EVNTO" NUMBER CONSTRAINT "GN_D_EVENTOS_ID_EVNTO_NN" NOT NULL ENABLE,
	"ID_PRCSO" NUMBER CONSTRAINT "GN_D_EVENTOS_ID_PRCSO_NN" NOT NULL ENABLE,
	"CDGO_EVNTO" VARCHAR2(3) CONSTRAINT "GN_D_EVENTOS_CDGO_EVNTO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "GN_D_EVENTOS_DSCRPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_EVENTOS_CDGO_EVNTO_UN" UNIQUE ("CDGO_EVNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_EVENTOS_ID_EVNTO_PK" PRIMARY KEY ("ID_EVNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_EVENTOS_ID_PRCSO_FK" FOREIGN KEY ("ID_PRCSO")
	  REFERENCES "DF_S_PROCESOS" ("ID_PRCSO") ENABLE
   ) ;

