
  CREATE TABLE "GN_D_REPORTE_CLIENTE"
   (	"ID_RPRTE_CLNTE" NUMBER(15,0) CONSTRAINT "GN_D_RPRT_CLNT_ID_RPRT_CLNT_NN" NOT NULL ENABLE,
	"ID_RPRTE" NUMBER(15,0) CONSTRAINT "GN_D_RPRT_CLNT_ID_RPRTE_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "GN_D_RPRT_CLNT_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "GN_D_RPRT_CLNT_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_RPRT_CLNT_ID_RPRT_CLNT_PK" PRIMARY KEY ("ID_RPRTE_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_RPRT_CLNT_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GN_G_RPRT_CLNT_RPRTE_CLNTE_UN" UNIQUE ("ID_RPRTE", "CDGO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_RPRT_CLNT_ID_RPRTE_FK" FOREIGN KEY ("ID_RPRTE")
	  REFERENCES "GN_D_REPORTES" ("ID_RPRTE") ENABLE,
	 CONSTRAINT "GN_D_RPRT_CLNT_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

