
  CREATE TABLE "GN_D_PLANTILLAS_CONSULTA"
   (	"ID_PLNTLLA_CNSLTA" NUMBER(15,0) CONSTRAINT "GN_D_PLN_CNS_ID_PLNT_CNSLTA_NN" NOT NULL ENABLE,
	"ID_PLNTLLA" NUMBER(15,0) CONSTRAINT "GN_D_PLN_CNS_ID_PLNTLLA_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500) CONSTRAINT "GN_D_PLN_CNS_DSCRPCION_NN" NOT NULL ENABLE,
	"CNSLTA" CLOB CONSTRAINT "GN_D_PLN_CNS_CNSLTA_NN" NOT NULL ENABLE,
	"PRMTROS" VARCHAR2(1000),
	"DSCRPCION_CRTA" VARCHAR2(25) NOT NULL ENABLE,
	"TPO_CNSLTA" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GN_D_PLN_CNS_TPO_CNSLTA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_PLN_CNS_DSCRPCION_CRTA_NN" CHECK (dscrpcion_crta IS NOT NULL) ENABLE,
	 CONSTRAINT "GN_D_PLN_CNS_ID_PLNT_CNSLTA_PK" PRIMARY KEY ("ID_PLNTLLA_CNSLTA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_PLN_CNS_TPO_CNSLTA_CK" CHECK (tpo_cnslta in ('S','P')) ENABLE,
	 CONSTRAINT "GN_D_PLN_CNS_ID_PLNTLLA_FK" FOREIGN KEY ("ID_PLNTLLA")
	  REFERENCES "GN_D_PLANTILLAS" ("ID_PLNTLLA") ENABLE
   )
 LOB ("CNSLTA") STORE AS SECUREFILE "SYS_LOB0000094613C00004$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

