
  CREATE TABLE "GN_D_EVENTOS_PROPIEDAD"
   (	"ID_EVNTO_PRPDAD" NUMBER CONSTRAINT "GN_D_EVNT_PRPDAD_ID_EVN_PRP_NN" NOT NULL ENABLE,
	"ID_EVNTO" NUMBER CONSTRAINT "GN_D_EVNT_PRPDAD_ID_EVNTO_NN" NOT NULL ENABLE,
	"CDGO_PRPDAD" VARCHAR2(3) CONSTRAINT "GN_D_EVNT_PRPDAD_CDGO_PRPDD_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "GN_D_EVNT_PRPDAD_DSCRPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_EVNT_PRPDAD_ID_EVN_PRP_PK" PRIMARY KEY ("ID_EVNTO_PRPDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_EVNT_PRPDAD_I_EVN_C_PR_UN" UNIQUE ("ID_EVNTO", "CDGO_PRPDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_EVNT_PRPDAD_ID_EVNTO_FK" FOREIGN KEY ("ID_EVNTO")
	  REFERENCES "GN_D_EVENTOS" ("ID_EVNTO") ENABLE
   ) ;

