
  CREATE TABLE "GN_D_PROCESOS_ADJUNTO_TIPO"
   (	"ID_PRCSOS_ADJNTO_TPO" NUMBER CONSTRAINT "GN_D_PRCS_ADJNT_ID_PR_AD_TP_NN" NOT NULL ENABLE,
	"CDGO_PRCSO" VARCHAR2(5) CONSTRAINT "GN_D_PRCS_ADJNT_CDGO_PRCSO_NN" NOT NULL ENABLE,
	"ID_ADJNTO_TPO" NUMBER CONSTRAINT "GN_D_PRCS_ADJNT_ID_ADJ_TPO_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GN_D_PRCS_ADJNT_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_PRCS_ADJNT_ID_PR_AD_TP_PK" PRIMARY KEY ("ID_PRCSOS_ADJNTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_PRCS_ADJN_ID_PRC_AD_TP_UN" UNIQUE ("CDGO_PRCSO", "ID_ADJNTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_PRCS_ADJNT_ACTVO_CK" CHECK ( actvo in ('S', 'N') ) ENABLE,
	 CONSTRAINT "GN_D_PRCS_ADJNT_CDGO_PRCSO_FK" FOREIGN KEY ("CDGO_PRCSO")
	  REFERENCES "DF_C_PROCESOS" ("CDGO_PRCSO") ENABLE,
	 CONSTRAINT "GN_D_PRCS_ADJNT_ID_ADJ_TPO_FK" FOREIGN KEY ("ID_ADJNTO_TPO")
	  REFERENCES "GN_D_ADJUNTOS_TIPO" ("ID_ADJNTO_TPO") ENABLE
   ) ;

