
  CREATE TABLE "GN_D_REPORTES_AUDITORIA"
   (	"ID_RPRTE_AUDTRIA" NUMBER CONSTRAINT "GN_D_RPRTE_AUDTRIA_ID_RPRTE_AUDTRIA_NN" NOT NULL ENABLE,
	"ID_RPRTE" NUMBER CONSTRAINT "GN_D_RPRTE_AUDTRIA_ID_RPRTE_NN" NOT NULL ENABLE,
	"USERNAME_DIGITA" VARCHAR2(100) CONSTRAINT "GN_D_RPRTE_AUDTRIA_USER_DIGITA_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) CONSTRAINT "GN_D_RPRTE_AUDTRIA_FECH_DIGITA_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	"DSCRPCION" VARCHAR2(4000) CONSTRAINT "GN_D_RPRTE_AUDTRIA_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1),
	 CONSTRAINT "GN_D_RPRTE_AUDTRIA_ID_RPRTE_AUDTRIA_PK" PRIMARY KEY ("ID_RPRTE_AUDTRIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_RPRTE_AUDTRIA_ACTVO" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "GN_D_RPRTE_AUDTRIA_ID_RPRTE_FK" FOREIGN KEY ("ID_RPRTE")
	  REFERENCES "GN_D_REPORTES" ("ID_RPRTE") ENABLE
   ) ;

