
  CREATE TABLE "GN_D_REPORTES_X_USUARIOS"
   (	"ID_RPRTE_X_USRIO" NUMBER,
	"ID_RPRTE" NUMBER,
	"TPO" VARCHAR2(1) CONSTRAINT "GN_D_RPRTS_X_USRS_TPO_NN" NOT NULL ENABLE,
	"ID_ORGEN" NUMBER CONSTRAINT "GN_D_RPRTS_X_USRS_ORGN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_RPRTS_X_USRS_RPRT_ORGN_UN" UNIQUE ("ID_RPRTE", "ID_ORGEN")
  USING INDEX  ENABLE,
	 PRIMARY KEY ("ID_RPRTE_X_USRIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_RPRTS_X_USRS_RPRT_NN" FOREIGN KEY ("ID_RPRTE")
	  REFERENCES "GN_D_REPORTES" ("ID_RPRTE") ENABLE
   ) ;

