
  CREATE TABLE "GN_D_PLANTILLAS"
   (	"ID_PLNTLLA" NUMBER(15,0) CONSTRAINT "GN_D_PLNTLLS_ID_PLNTLLA_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "GN_D_PLNTLLS_COD_CLNTE_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "GN_D_PLNTLLS_ID_ACTO_TPO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "GN_D_PLNTLLS_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "GN_D_PLNTLLS_ACTVO_NN" NOT NULL ENABLE,
	"DFCTO" VARCHAR2(1) DEFAULT NULL NOT NULL ENABLE,
	"ID_RPRTE" NUMBER,
	"FCHA_INCIO" DATE,
	"FCHA_FIN" DATE,
	"ID_PRCSO" NUMBER DEFAULT 10 CONSTRAINT "GN_D_PLNTLLAS_ID_PRCSO_NN" NOT NULL ENABLE,
	"TPO_PLNTLLA" VARCHAR2(1) DEFAULT 'P' CONSTRAINT "GN_D_PLNTLLAS_TPO_PLNTLLA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_PLNTLLS_ID_PLNTLLA_PK" PRIMARY KEY ("ID_PLNTLLA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_PLNTLLS_ACTVO_CK" CHECK ( actvo in ('S','N') ) ENABLE,
	 CONSTRAINT "GN_D_PLNTLLAS_TPO_PLNTLLA_CK" CHECK (tpo_plntlla in ('P','M')) ENABLE,
	 CONSTRAINT "GN_D_PLNTLLS_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "GN_D_PLNTLLS_ID_RPRTE_FK" FOREIGN KEY ("ID_RPRTE")
	  REFERENCES "GN_D_REPORTES" ("ID_RPRTE") ENABLE,
	 CONSTRAINT "GN_D_PLNTLLS_COD_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GN_D_PLNTLLAS_ID_PRCSO_FK" FOREIGN KEY ("ID_PRCSO")
	  REFERENCES "DF_S_PROCESOS" ("ID_PRCSO") ENABLE
   ) ;

