
  CREATE TABLE "GN_D_EXPRESIONES_VALIDACION"
   (	"ID_EXPRSION_VLDCION" NUMBER DEFAULT "GENESYS"."SQ_GN_D_EXPRESIONES_VALIDACION"."NEXTVAL" CONSTRAINT "GN_D_EXP_VLD_ID_EXP_VLD_NN" NOT NULL ENABLE,
	"CDGO_EXPRSION_VLDCION" VARCHAR2(3) CONSTRAINT "GN_D_EXP_VLD_CDGO_EXP_VLD_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER,
	"EXPRSION" VARCHAR2(4000) CONSTRAINT "GN_D_EXP_VLD_EXPRSION_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(4000),
	"MNSJE" VARCHAR2(4000),
	 CONSTRAINT "GN_D_EXP_VLD_CD_EX_VL_CD_CL_UN" UNIQUE ("CDGO_EXPRSION_VLDCION", "CDGO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_EXP_VLD_ID_EXP_VLD_PK" PRIMARY KEY ("ID_EXPRSION_VLDCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_EXP_VLD_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

