
  CREATE TABLE "GN_D_PLANTILLAS_PARRAFO"
   (	"ID_PLNTLLA_PRRFO" NUMBER(15,0) CONSTRAINT "GN_D_PLN_PRR_ID_PLNT_PRRFO_NN" NOT NULL ENABLE,
	"ID_PLNTLLA" NUMBER(15,0) CONSTRAINT "GN_D_PLN_PRR_ID_PLNTLLA_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500) CONSTRAINT "GN_D_PLN_PRR_DSCRPCION_NN" NOT NULL ENABLE,
	"PRRFO" CLOB CONSTRAINT "GN_D_PLN_PRR_IPRRFO_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER(3,0) CONSTRAINT "GN_D_PLN_PRR_ORDEN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_PLN_PRR_ID_PLNT_PRRFO_PK" PRIMARY KEY ("ID_PLNTLLA_PRRFO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_PLN_PRR_ID_PLNTLLA_FK" FOREIGN KEY ("ID_PLNTLLA")
	  REFERENCES "GN_D_PLANTILLAS" ("ID_PLNTLLA") ENABLE
   )
 LOB ("PRRFO") STORE AS SECUREFILE "SYS_LOB0000094616C00004$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

