
  CREATE TABLE "GN_D_REGLAS_NEGOCIO_CLIENTE"
   (	"ID_RGLA_NGCIO_CLNTE" NUMBER CONSTRAINT "GN_D_RG_NG_CL_ID_RGL_NG_CLN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "GN_D_RG_NG_COD_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"ID_RGLA_NGCIO" NUMBER CONSTRAINT "GN_D_RG_NG_ID_RGLA_NGCIO_NN" NOT NULL ENABLE,
	"INDCDOR_EDTA_RGLA" VARCHAR2(1) DEFAULT 'N',
	"DSCRPCION" VARCHAR2(1000) CONSTRAINT "GN_D_RG_NG_DSCRPCION_NN" NOT NULL ENABLE,
	"FCHA_INCIO" DATE CONSTRAINT "GN_D_RG_NG_FCHA_INCIO_NN" NOT NULL ENABLE,
	"FCHA_FIN" DATE CONSTRAINT "GN_D_RG_NG_FCHA_FIN_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_RG_NG_CL_ID_RGL_NG_CLN_PK" PRIMARY KEY ("ID_RGLA_NGCIO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_RG_NG_ID_IND_EDTA_RGLA_CK" CHECK (indcdor_edta_rgla in ('S','N')) ENABLE,
	 CONSTRAINT "GN_D_RG_NG_ID_IMPSTO_SB_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "GN_D_RG_NG_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "GN_D_RG_NG_COD_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GN_D_RG_NG_ID_RGLA_NGCIO_FK" FOREIGN KEY ("ID_RGLA_NGCIO")
	  REFERENCES "GN_D_REGLAS_NEGOCIO" ("ID_RGLA_NGCIO") ENABLE
   ) ;

