
  CREATE TABLE "GN_D_RGLAS_NGCIO_CLNTE_FNC"
   (	"ID_RGLA_NGCIO_CLNTE_FNCION" NUMBER CONSTRAINT "GN_D_RG_NG_CL_F_I_RG_N_CL_F_NN" NOT NULL ENABLE,
	"ID_RGLA_NGCIO_CLNTE" NUMBER CONSTRAINT "GN_D_RG_NG_CL_F_ID_RG_NG_CL_NN" NOT NULL ENABLE,
	"ID_FNCION" NUMBER CONSTRAINT "GN_D_RG_NG_CL_F_ID_FNCION_NN" NOT NULL ENABLE,
	"ORDEN_AGRPCION" NUMBER DEFAULT 1,
	"CMPRTA_LGCA" VARCHAR2(3) DEFAULT 'AND',
	"INDCDOR_CMPLE_VLDCCION" VARCHAR2(1) DEFAULT 'S',
	"RSPSTA_PSTVA" VARCHAR2(1000) CONSTRAINT "GN_D_RG_NG_CL_F_RSPST_PSTV_NN" NOT NULL ENABLE,
	"RSPSTA_NGTVA" VARCHAR2(1000) CONSTRAINT "GN_D_RG_NG_CL_F_RSPST_NGTV_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S',
	"ORDEN" NUMBER DEFAULT 0,
	 CONSTRAINT "GN_D_RG_NG_CL_F_I_RG_N_CL_F_PK" PRIMARY KEY ("ID_RGLA_NGCIO_CLNTE_FNCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_RG_NG_CL_F_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "GN_D_RG_NG_CL_F_IND_CMP_VLD_CK" CHECK (indcdor_cmple_vldccion in ('S','N')) ENABLE,
	 CONSTRAINT "GN_D_RG_NG_CL_F_CMPRTA_LGCA_CK" CHECK (cmprta_lgca in ('AND','OR')) ENABLE,
	 CONSTRAINT "GN_D_RG_NG_CL_F_ID_FNCION_FK" FOREIGN KEY ("ID_FNCION")
	  REFERENCES "GN_D_FUNCIONES" ("ID_FNCION") ENABLE,
	 CONSTRAINT "GN_D_RG_NG_CL_F_ID_RG_NG_CL_FK" FOREIGN KEY ("ID_RGLA_NGCIO_CLNTE")
	  REFERENCES "GN_D_REGLAS_NEGOCIO_CLIENTE" ("ID_RGLA_NGCIO_CLNTE") ENABLE
   ) ;

