
  CREATE TABLE "GN_D_ACTOS_TIPO_TAREA"
   (	"ID_ACTOS_TPO_TREA" NUMBER CONSTRAINT "GN_D_ACT_TP_TR_ID_ACT_T_TRA_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER(15,0) CONSTRAINT "GN_D_ACT_TP_TR_ID_FLJO_TREA_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "GN_D_ACT_TP_TR_ID_ACTO_TP_NN" NOT NULL ENABLE,
	"NTFCCION_ATMTCA" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "GN_D_ACT_TP_TR_NTFCCN_ATMTC_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO_RQRDO" NUMBER,
	"UNDAD_DRCION" VARCHAR2(3),
	"DRCION" NUMBER(4,0),
	"DIA_TPO" VARCHAR2(1),
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GN_D_ACT_TP_ACTVO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) DEFAULT 1 CONSTRAINT "GN_D_ACT_TP_TR_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"INDCDOR_OBLGTRIO" VARCHAR2(1) DEFAULT 'S',
	 CONSTRAINT "GN_D_ACT_TP_TR_ID_ACT_T_TRA_PK" PRIMARY KEY ("ID_ACTOS_TPO_TREA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_TR_INDC_OBLGTR_CK" CHECK (indcdor_oblgtrio in ('S', 'N')) ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_DIA_TPO_CK" CHECK (dia_tpo in ('H','C')) ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_TR_NTFCCN_ATMTC_CK" CHECK (ntfccion_atmtca in ('S','N')) ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_UNIDAD_DRCION_CK" CHECK (undad_drcion in ('MN','HR','DI','SM','MS')) ENABLE,
	 CONSTRAINT "GN_D_CTOS_TPO_TREA_I_A_T_I_F_T" UNIQUE ("ID_ACTO_TPO", "ID_FLJO_TREA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_TR_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_TR_ID_ACTO_TP_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_TR_ID_ACT_TP_RQ_FK" FOREIGN KEY ("ID_ACTO_TPO_RQRDO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "GN_D_ACT_TP_TR_ID_FLJO_TREA_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE
   ) ;

