
  CREATE TABLE "GN_D_CODIGOS_PROCESO"
   (	"CDGO_PRCSO" VARCHAR2(20) CONSTRAINT "GN_D_CDGOS_PRCSO_CDGO_PRCSO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "GN_D_CDGOS_PRCSO_DSCRPCION_NN" NOT NULL ENABLE,
	"ID_CRGA" NUMBER CONSTRAINT "GN_D_CDGOS_PRCSO_ID_CRGA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_CDGOS_PRCSO_CDGO_PRCSO_PK" PRIMARY KEY ("CDGO_PRCSO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_CDGOS_PRCSO_ID_CRGA_FK" FOREIGN KEY ("ID_CRGA")
	  REFERENCES "ET_G_CARGA" ("ID_CRGA") ENABLE
   ) ;

