
  CREATE TABLE "GN_D_ADJUNTOS_TIPO"
   (	"ID_ADJNTO_TPO" NUMBER CONSTRAINT "GN_D_ADJNTOS_TPO_ID_ADJ_TPO_NN" NOT NULL ENABLE,
	"CDGO_ADJNTO_TPO" VARCHAR2(5) CONSTRAINT "GN_D_ADJNTOS_TPO_CG_ADJ_TPO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "GN_D_ADJNTOS_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "GN_D_ADJNTOS_INDCDOR_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GN_D_ADJNTOS_TPO_ID_ADJ_TPO_PK" PRIMARY KEY ("ID_ADJNTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_ADJNTOS_CDGO_ADJNTO_UN" UNIQUE ("CDGO_ADJNTO_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_D_ADJNTOS_INDCDOR_ACTVO_CK" CHECK ( actvo in ('S', 'N') ) ENABLE
   ) ;

