
  CREATE TABLE "GN_G_ACTOS_VIGENCIA"
   (	"ID_ACTO_VGNCIA" NUMBER DEFAULT "GENESYS"."SQ_GN_G_ACTOS_VIGENCIA"."NEXTVAL" CONSTRAINT "GN_G_ACTO_VGNCIA_ID_ACT_VGN_NN" NOT NULL ENABLE,
	"ID_ACTO" NUMBER CONSTRAINT "GN_G_ACTO_VGNCIA_ID_ACTO_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "GN_G_ACTO_VGNCIA_ID_SJT_IMP_NN" NOT NULL ENABLE,
	"VGNCIA" NUMBER CONSTRAINT "GN_G_ACTO_VGNCIA_VGNCIA_NN" NOT NULL ENABLE,
	"ID_PRDO" NUMBER CONSTRAINT "GN_G_ACTO_VGNCIA_ID_PRDO_NN" NOT NULL ENABLE,
	"VLOR_CPTAL" NUMBER CONSTRAINT "GN_G_ACTO_VGNCIA_VLOR_CPTAL" NOT NULL ENABLE,
	"VLOR_INTRES" NUMBER CONSTRAINT "GN_G_ACTO_VGNCIA_VLOR_INTRES" NOT NULL ENABLE,
	 CONSTRAINT "GN_G_ACTO_VGNCIA_ID_ACT_VGN_PK" PRIMARY KEY ("ID_ACTO_VGNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "GN_G_ACTO_VGNCIA_ID_SJT_IMP_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "GN_G_ACTO_VGNCIA_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "GN_G_ACTO_VGNCIA_ID_PRDO_FK" FOREIGN KEY ("ID_PRDO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "GN_G_ACTO_VGNCIA_VGNCIA_FK" FOREIGN KEY ("VGNCIA")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE
   ) ;

