
  CREATE TABLE "GN_G_REGENERAR_ACTOS_TRAZA"
   (	"ID_RGNRAR_ACTO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_GN_G_REGENERAR_ACTOS_TRAZA"."NEXTVAL" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_COD_CLNTE" NOT NULL ENABLE,
	"ID_ACTO" NUMBER(15,0) CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_ID_ACTO" NOT NULL ENABLE,
	"NMRO_ACTO" VARCHAR2(30) CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_NMRO_ACTO" NOT NULL ENABLE,
	"FCHA_ACTO" TIMESTAMP (6) CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_FCHA_ACTO" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_ID_ACTO_TPO" NOT NULL ENABLE,
	"ANIO" NUMBER(4,0) CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_ANIO" NOT NULL ENABLE,
	"ID_DCMNTO" NUMBER(10,0),
	"FCHA_RGNRAR" TIMESTAMP (6) CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_FCHA_RGNRAR" NOT NULL ENABLE,
	"ID_USRIO_RGNRAR" NUMBER(15,0) CONSTRAINT "GN_G_ACTOS_TRZA_ID_USRIO_RGNRAR" NOT NULL ENABLE,
	"CDGO_ERROR" NUMBER,
	"MNSJE_ERROR" VARCHAR2(200),
	"ID_PTCION" NUMBER,
	 CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_COD_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "GN_G_ACTOS_TRZA_ID_USRIO_RGNRAR_FK" FOREIGN KEY ("ID_USRIO_RGNRAR")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;
  CREATE INDEX "GN_G_RGNRAR_ACTOS_TRZA_ID_RGNRAR_ACTO_IDX" ON "GN_G_REGENERAR_ACTOS_TRAZA" ("ID_RGNRAR_ACTO", "ID_ACTO", "NMRO_ACTO", "FCHA_ACTO", "ID_ACTO_TPO")
  ;
ALTER TABLE "GN_G_REGENERAR_ACTOS_TRAZA" ADD CONSTRAINT "GN_G_RGNRAR_ACTOS_TRZA_ID_RGNRAR_ACTO_PK" PRIMARY KEY ("ID_RGNRAR_ACTO")
  USING INDEX "GN_G_RGNRAR_ACTOS_TRZA_ID_RGNRAR_ACTO_IDX"  ENABLE;

