
  CREATE TABLE "GN_T_REPORTES_PARAMETRO2"
   (	"ID" NUMBER DEFAULT "GENESYS"."SEQ_GN_T_REPORTES_PARAMETRO2"."NEXTVAL",
	"ID_RPRTE_PRMTRO" VARCHAR2(50),
	"DTA" CLOB,
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp,
	 CONSTRAINT "GN_T_REPORTES_PARAMETRO2_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   )
 LOB ("DTA") STORE AS SECUREFILE "SYS_LOB0000117547C00003$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

