
  CREATE TABLE "GTI_MAIL_CONF"
   (	"COD_MAIL_CONF" NUMBER CONSTRAINT "GTI_MAIL_CONF_COD_MAIL_CONF_NN" NOT NULL ENABLE,
	"COD_CIA" NUMBER CONSTRAINT "GTI_MAIL_CONF_COD_CIA_NN" NOT NULL ENABLE,
	"SMTP_SERVER" VARCHAR2(30) CONSTRAINT "GTI_MAIL_CONF_SMTP_SERVER_NN" NOT NULL ENABLE,
	"SMTP_PORT" VARCHAR2(30) CONSTRAINT "GTI_MAIL_CONF_SMTP_PORT_NN" NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100),
	"PASSWORD" VARCHAR2(100),
	"SMTP_DOMAIN" VARCHAR2(100),
	"USERNAME_DIGITA" VARCHAR2(100) DEFAULT user CONSTRAINT "GTI_MAIL_CONF_USER_DIGITA_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "GTI_MAIL_CONF_FECHA_DIGITA_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	 CONSTRAINT "GTI_MAIL_CONF_COD_MAIL_CONF_PK" PRIMARY KEY ("COD_MAIL_CONF")
  USING INDEX  ENABLE,
	 CONSTRAINT "GTI_MAIL_CONF_COD_CIA_FK" FOREIGN KEY ("COD_CIA")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

