
  CREATE TABLE "GTI_EMAIL_ESTADO"
   (	"COD_ESTADO" NUMBER CONSTRAINT "GTI_EMAIL_ESTADO_COD_ESTADO_NN" NOT NULL ENABLE,
	"NOM_ESTADO" VARCHAR2(15) CONSTRAINT "GTI_EMAIL_ESTADO_NOM_ESTADO_NN" NOT NULL ENABLE,
	 CONSTRAINT "GTI_EMAIL_ESTADO_COD_ESTADO_PK" PRIMARY KEY ("COD_ESTADO")
  USING INDEX  ENABLE
   ) ;

