
  CREATE TABLE "GTI_EMAIL"
   (	"COD_MAIL" NUMBER CONSTRAINT "GTI_EMAIL_COD_MAIL_NN" NOT NULL ENABLE,
	"COD_CIA" NUMBER CONSTRAINT "GTI_MAIL_COD_CIA_NN" NOT NULL ENABLE,
	"COD_ESTADO" NUMBER DEFAULT 1 CONSTRAINT "GTI_EMAIL_COD_ESTADO_NN" NOT NULL ENABLE,
	"DESDE" VARCHAR2(50) CONSTRAINT "GTI_EMAIL_DESDE_NN" NOT NULL ENABLE,
	"PARA" VARCHAR2(500) CONSTRAINT "GTI_EMAIL_PARA_NN" NOT NULL ENABLE,
	"CC" VARCHAR2(500),
	"CCO" VARCHAR2(500),
	"SUBJECT" VARCHAR2(500),
	"MESSAGE_PLAIN" VARCHAR2(4000),
	"MESSAGE_HTML" VARCHAR2(4000),
	"USERNAME_DIGITA" VARCHAR2(30) CONSTRAINT "GTI_MAIL_USERNAME_DIGITA_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) CONSTRAINT "GTI_MAIL_FECHA_DIGITA_NN" NOT NULL ENABLE,
	 CONSTRAINT "GTI_EMAIL_COD_MAIL_PK" PRIMARY KEY ("COD_MAIL")
  USING INDEX  ENABLE,
	 CONSTRAINT "GTI_EMAIL_COD_ESTADO_FK" FOREIGN KEY ("COD_ESTADO")
	  REFERENCES "GTI_EMAIL_ESTADO" ("COD_ESTADO") ENABLE,
	 CONSTRAINT "GTI_MAIL_COD_CIA_FK" FOREIGN KEY ("COD_CIA")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

