
  CREATE TABLE "IP_G_PERSONAS_ANOTACION"
   (	"ID_PERSONA" NUMBER,
	"ID_ANOTACION" NUMBER NOT NULL ENABLE,
	"ID_TIPO_DEA" VARCHAR2(2),
	"ID_TIPO_DOCUMENTO" VARCHAR2(20),
	"ID_DOCUMENTO" VARCHAR2(50),
	"ID_APELLIDO1" VARCHAR2(50),
	"ID_APELLIDO2" VARCHAR2(50),
	"ID_NOMBRE" VARCHAR2(50),
	"ID_PORCENTAJE" VARCHAR2(50),
	 PRIMARY KEY ("ID_PERSONA")
  USING INDEX  ENABLE,
	 FOREIGN KEY ("ID_ANOTACION")
	  REFERENCES "IP_G_ANOTACIONES" ("ID_ANOTACION") ENABLE
   ) ;

