
  CREATE TABLE "LISTADO_EJECUTORIA"
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 94796 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
	"NUMERO_FACTURA" VARCHAR2(25),
	"REFERENCIA" VARCHAR2(25),
	"PRCSDO" VARCHAR2(2) DEFAULT 'N' NOT NULL ENABLE,
	"DCMNTO" CLOB,
	"FCHA_VNCMNTO_TRMNOS" DATE,
	"ID_ACTO_EJECUTORIA" VARCHAR2(25),
	 CONSTRAINT "LISTADO_EJECUTORIA_UK2" UNIQUE ("ID_ACTO_EJECUTORIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "LISTADO_EJECUTORIA_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE,
	 CONSTRAINT "LISTADO_EJECUTORIA_UK1" UNIQUE ("NUMERO_FACTURA")
  USING INDEX  ENABLE
   ) ;

