
  CREATE TABLE "MA_D_ENVIOS_MEDIO"
   (	"CDGO_ENVIO_MDIO" VARCHAR2(3) CONSTRAINT "MA_D_ENV_MDIO_CDGO_ENV_MD_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500) CONSTRAINT "MA_D_ENV_MDIO_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "MA_D_ENV_MDIO_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "MA_D_ENV_MDIO_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "MA_D_ENV_MDIO_CDGO_ENV_MD_PK" PRIMARY KEY ("CDGO_ENVIO_MDIO")
  USING INDEX  ENABLE
   ) ;

