
  CREATE TABLE "MA_G_ENVIOS_PRGRMDO_MDIO_PF"
   (	"ID_ENVIO_PRGRMD_MD_PF" NUMBER DEFAULT "GENESYS"."SQ_MA_G_ENVIOS_PRGRMDO_MDIO_PF"."NEXTVAL" CONSTRAINT "MA_D_E_P_MD_PR_ID_ENV_P_M_P_NN" NOT NULL ENABLE,
	"ID_ENVIO_PRGRMDO_MDIO" NUMBER CONSTRAINT "MA_D_E_P_MD_PR_ID_ENV_P_MD_NN" NOT NULL ENABLE,
	"ID_ENVIO_MDIO_CNFGRCION_PF" NUMBER CONSTRAINT "MA_D_E_P_MD_PR_ID_EN_M_C_PF_NN" NOT NULL ENABLE,
	"VLOR" VARCHAR2(500),
	 CONSTRAINT "MA_D_E_P_MD_PR_ID_ENV_P_M_P_PK" PRIMARY KEY ("ID_ENVIO_PRGRMD_MD_PF")
  USING INDEX  ENABLE,
	 CONSTRAINT "MA_D_E_P_MD_PR_ID_ENV_P_MD_FK" FOREIGN KEY ("ID_ENVIO_PRGRMDO_MDIO")
	  REFERENCES "MA_G_ENVIOS_PROGRAMADO_MDIO" ("ID_ENVIO_PRGRMDO_MDIO") ENABLE,
	 CONSTRAINT "MA_D_E_P_MD_PR_ID_EN_M_C_PF_FK" FOREIGN KEY ("ID_ENVIO_MDIO_CNFGRCION_PF")
	  REFERENCES "MA_D_ENVIOS_MDIO_CNFGRCN_PF" ("ID_ENVIO_MDIO_CNFGRCION_PF") ENABLE
   ) ;

