
  CREATE TABLE "MA_G_ENVIOS_PROGRAMADO_MDIO"
   (	"ID_ENVIO_PRGRMDO_MDIO" NUMBER DEFAULT "GENESYS"."SQ_MA_G_ENVIOS_PROGRAMADO_MDIO"."NEXTVAL" CONSTRAINT "MA_G_ENV_PRG_MDIO_ID_E_P_MD_NN" NOT NULL ENABLE,
	"ID_ENVIO_PRGRMDO" NUMBER CONSTRAINT "MA_G_ENV_PRG_MDIO_ID_E_PGMD_NN" NOT NULL ENABLE,
	"CDGO_ENVIO_MDIO" VARCHAR2(3) CONSTRAINT "MA_G_ENV_PRG_MDIO_CDGO_EN_M_NN" NOT NULL ENABLE,
	"ASNTO" VARCHAR2(500),
	"TXTO_MNSJE" CLOB,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "MA_G_ENV_PRG_MDIO_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "MA_G_ENV_PRG_MDIO_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "MA_G_ENV_PRG_MD_I_E_P_C_E_M_UN" UNIQUE ("ID_ENVIO_PRGRMDO", "CDGO_ENVIO_MDIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "MA_G_ENV_PRG_MDIO_ID_E_P_MD_PK" PRIMARY KEY ("ID_ENVIO_PRGRMDO_MDIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "MA_G_ENV_PRG_MDIO_ID_E_PGMD_FK" FOREIGN KEY ("ID_ENVIO_PRGRMDO")
	  REFERENCES "MA_G_ENVIOS_PROGRAMADO" ("ID_ENVIO_PRGRMDO") ENABLE,
	 CONSTRAINT "MA_G_ENV_PRG_MDIO_CDGO_EN_M_FK" FOREIGN KEY ("CDGO_ENVIO_MDIO")
	  REFERENCES "MA_D_ENVIOS_MEDIO" ("CDGO_ENVIO_MDIO") ENABLE
   )
 LOB ("TXTO_MNSJE") STORE AS SECUREFILE "SYS_LOB0000075195C00005$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

