
  CREATE TABLE "MC_D_TIPOS_MDDA_CTLAR"
   (	"ID_TPOS_MDDA_CTLAR" NUMBER(15,0) CONSTRAINT "MC_D_TPO_MC_ID_TPO_MDD_CTLR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "MC_D_TPO_MC_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_TPOS_MDDA_CTLAR" VARCHAR2(3) CONSTRAINT "MC_D_TPO_MC_CDGO_TPO_MC_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "MC_D_TPO_MC_DSCPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "MC_D_TPO_MC_ACTVO_NN" NOT NULL ENABLE,
	"PRMTE_SCSTRO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "MC_D_TPO_MC_PRMTE_SCSTRO_NN" NOT NULL ENABLE,
	"TPO_IMPRSION_OFCIO" VARCHAR2(3),
	 CONSTRAINT "MC_D_TPO_MC_ID_TPO_MDD_CTLR_PK" PRIMARY KEY ("ID_TPOS_MDDA_CTLAR")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_D_TPO_MC_CD_TP_MC_CD_CL_UN" UNIQUE ("CDGO_TPOS_MDDA_CTLAR", "CDGO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_D_TPO_MC_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "MC_D_TPO_MC_PRMTE_SCSTRO_CK" CHECK (prmte_scstro in ('S','N')) ENABLE,
	 CONSTRAINT "MC_D_TPO_MC_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

