
  CREATE TABLE "MC_D_ENTIDADES_TIPO"
   (	"CDGO_ENTDAD_TPO" VARCHAR2(3) CONSTRAINT "MC_D_ENTDDS_TPO_CDG_ENTD_TP_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "MC_D_ENTDDS_TPO_DSCRPCION_NN" NOT NULL ENABLE,
	"TPO_IMPRSION_OFCIO" VARCHAR2(3) CONSTRAINT "MC_D_ENTDDS_TPO_TPO_IMP_OFC_NN" NOT NULL ENABLE,
	 CONSTRAINT "MC_D_ENTDDS_TPO_TPO_IMP_OFC_CK" CHECK (tpo_imprsion_ofcio in ('IND','GEN')) ENABLE,
	 CONSTRAINT "MC_D_ENTDDS_TPO_CDG_ENTD_TP_PK" PRIMARY KEY ("CDGO_ENTDAD_TPO")
  USING INDEX  ENABLE
   ) ;

