
  CREATE TABLE "MC_D_PROPIEDADES_BIEN_ENTIDAD"
   (	"ID_PRPDDES_BIEN_ENTDAD" NUMBER(15,0) CONSTRAINT "MC_D_PR_BN_EN_ID_PRP_BN_ENT_NN" NOT NULL ENABLE,
	"ID_PRPDDES_BIEN" NUMBER(15,0) CONSTRAINT "MC_D_PR_BN_EN_ID_PRPDD_BIEN_NN" NOT NULL ENABLE,
	"ID_ENTDDES" NUMBER(15,0) CONSTRAINT "MC_D_PR_BN_EN_ID_ENTDDES_NN" NOT NULL ENABLE,
	 CONSTRAINT "MC_D_PR_BN_EN_ID_PR_BI_EN_UN" UNIQUE ("ID_PRPDDES_BIEN", "ID_ENTDDES")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_D_PR_BN_EN_ID_PRP_BN_ENT_PK" PRIMARY KEY ("ID_PRPDDES_BIEN_ENTDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_D_PR_BN_EN_ID_PRPDD_BIEN_FK" FOREIGN KEY ("ID_PRPDDES_BIEN")
	  REFERENCES "MC_D_PROPIEDADES_BIEN" ("ID_PRPDDES_BIEN") ENABLE,
	 CONSTRAINT "MC_D_PR_BN_EN_ID_ENTDDES_FK" FOREIGN KEY ("ID_ENTDDES")
	  REFERENCES "MC_D_ENTIDADES" ("ID_ENTDDES") ENABLE
   ) ;

