
  CREATE TABLE "MC_D_ESTADOS_LOTE"
   (	"CDGO_ESTDO_LTE" VARCHAR2(3) CONSTRAINT "mc_d_estdos_lte_cdgo_estdo_nn" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(30) CONSTRAINT "mc_d_estdos_lte_dscrpcion_nn" NOT NULL ENABLE,
	 CONSTRAINT "MC_D_ESTDOS_LTE_CDGO_ESTDO_PK" PRIMARY KEY ("CDGO_ESTDO_LTE")
  USING INDEX  ENABLE
   ) ;

