
  CREATE TABLE "MC_G_SECUESTRE_DILIGENCIA"
   (	"ID_SCSTRE_DLGNCIA" NUMBER(15,0) DEFAULT "GENESYS"."SQ_MC_G_SECUESTRE_DILIGENCIA"."NEXTVAL" CONSTRAINT "MC_G_SCSTR_DLG_ID_SCSTR_DLG_NN" NOT NULL ENABLE,
	"ID_SCSTRE_GSTION" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_DLG_ID_SCSTR_GST_NN" NOT NULL ENABLE,
	"FCHA_DLGNCIA" DATE CONSTRAINT "MC_G_SCSTR_DLG_FCHA_DLGNCIA_NN" NOT NULL ENABLE,
	"IDNTFCCION_DPSTRIO" NUMBER(15,0),
	"NMBRE_DPSTRIO" VARCHAR2(100),
	"HNRRIOS_SCSTRE" NUMBER(20,0),
	"OBSRVCION" VARCHAR2(2000),
	"ID_FNCNRIO" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_DLG_ID_FNCNRIO_NN" NOT NULL ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DLG_ID_SCSTR_DLG_PK" PRIMARY KEY ("ID_SCSTRE_DLGNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DLG_ID_SCSTR_GST_FK" FOREIGN KEY ("ID_SCSTRE_GSTION")
	  REFERENCES "MC_G_SECUESTRE_GESTION" ("ID_SCSTRE_GSTION") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DLG_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE
   ) ;

