
  CREATE TABLE "MC_G_EMBRGO_DSMBRGO_ERROR"
   (	"ID_EMBRGO_DSMBRGO_ERROR" NUMBER CONSTRAINT "MC_G_MBRG_DSMBRG_RRR_D_MBRG_DSMBRG_RRR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER,
	"ID_EMBRGOS_RSLCION" NUMBER,
	"ID_DSMBRGOS_RSLCION" NUMBER,
	"ID_SLCTD_OFCIO" NUMBER,
	"ID_DSMBRGO_OFCIO" NUMBER,
	"O_MNSJE_RSPSTA" VARCHAR2(4000),
	"O_CDGO_RSPSTA" NUMBER,
	"FCHA" TIMESTAMP (6),
	"NMBRE_UP" VARCHAR2(200),
	 CONSTRAINT "MC_G_MBRG_DSMBRG_RRR_D_MBRG_DSMBRG_RRR_PK" PRIMARY KEY ("ID_EMBRGO_DSMBRGO_ERROR")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_EMBRGO_DSMBRGO_ERROR_ID_EMBRGOS_RSLCION_FK" FOREIGN KEY ("ID_EMBRGOS_RSLCION")
	  REFERENCES "MC_G_EMBARGOS_RESOLUCION" ("ID_EMBRGOS_RSLCION") ENABLE,
	 CONSTRAINT "MC_G_EMBRGO_DSMBRGO_ERROR_ID_DSMBRGO_OFCIO_FK" FOREIGN KEY ("ID_DSMBRGO_OFCIO")
	  REFERENCES "MC_G_DESEMBARGOS_OFICIO" ("ID_DSMBRGO_OFCIO") ENABLE,
	 CONSTRAINT "MC_G_EMBRGO_DSMBRGO_ERROR_ID_DSMBRGOS_RSLCION_FK" FOREIGN KEY ("ID_DSMBRGOS_RSLCION")
	  REFERENCES "MC_G_DESEMBARGOS_RESOLUCION" ("ID_DSMBRGOS_RSLCION") ENABLE,
	 CONSTRAINT "MC_G_EMBRGO_DSMBRGO_ERROR_ID_SLCTD_OFCIO_FK" FOREIGN KEY ("ID_SLCTD_OFCIO")
	  REFERENCES "MC_G_SOLICITUDES_Y_OFICIOS" ("ID_SLCTD_OFCIO") ENABLE,
	 CONSTRAINT "MC_G_EMBRGO_DSMBRGO_ERROR_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

