
  CREATE TABLE "MC_G_DESEMBARGOS_POBLACION"
   (	"NMRO_ACTO" NUMBER,
	"FCHA_ACTO" TIMESTAMP (6),
	"DSCRPCION_TIPO_EMBARGO" VARCHAR2(4000),
	"IDNTFCCION" VARCHAR2(4000),
	"ID_INSTNCIA_FLJO" NUMBER,
	"ID_FLJO_TREA" NUMBER,
	"CDGO_CLNTE" NUMBER,
	"ID_EMBRGOS_RSLCION" NUMBER,
	"ID_EMBRGOS_CRTRA" NUMBER,
	"ID_TPOS_MDDA_CTLAR" NUMBER,
	"IDNTFCCION_SJTO" VARCHAR2(4000),
	"CDGO_CSAL" VARCHAR2(10),
	"DESCRIPCION_CSAL_DSMBRGO" VARCHAR2(4000),
	"ESTDO" VARCHAR2(4000) DEFAULT 'e'
   ) ;

