
  CREATE TABLE "MC_G_EMBRGOS_OFCIO_JSON"
   (	"ID_EMBRGOS_OFCIO_JSON" NUMBER CONSTRAINT "MC_G_MBRGS_FC_JSN_ID_MBRGS_FC_JSN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER,
	"JSON_RSLCION" CLOB,
	 CONSTRAINT "MC_G_MBRGS_FC_JSN_ID_MBRGS_FC_JSN_PK" PRIMARY KEY ("ID_EMBRGOS_OFCIO_JSON")
  USING INDEX  ENABLE
   ) ;

