
  CREATE TABLE "MC_G_SECUESTRE_GESTION"
   (	"ID_SCSTRE_GSTION" NUMBER(15,0) DEFAULT "GENESYS"."SQ_MC_G_SECUESTRE_GESTION"."NEXTVAL" CONSTRAINT "MC_G_SCSTR_GST_ID_SCSTR_GST_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_GST_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_GST_ID_INST_FLJO_NN" NOT NULL ENABLE,
	"FCHA_SCSTRE" DATE CONSTRAINT "MC_G_SCSTR_GST_FCHA_SCSTRE_NN" NOT NULL ENABLE,
	"FCHA_DLGNCIA" DATE,
	"ID_SCSTRS_AUXLR" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_GST_ID_SCSTR_AUX_NN" NOT NULL ENABLE,
	"ID_SCSTRE" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_GST_ID_SCSTRE_NN" NOT NULL ENABLE,
	"ID_SLCTD_OFCIO" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_GST_ID_SLC_OFC_NN" NOT NULL ENABLE,
	"ID_FNCNRIO" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_GST_ID_FNCNRIO_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "MC_G_SCSTR_GST_ACTVO_NN" NOT NULL ENABLE,
	"ID_LTE_MDDA_CTLAR" NUMBER(15,0),
	 CONSTRAINT "MC_G_SCSTR_GST_ID_SCSTR_GST_PK" PRIMARY KEY ("ID_SCSTRE_GSTION")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_ID_LTE_MC_FK" FOREIGN KEY ("ID_LTE_MDDA_CTLAR")
	  REFERENCES "MC_G_LOTES_MDDA_CTLAR" ("ID_LTE_MDDA_CTLAR") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_ID_SLC_OFC_FK" FOREIGN KEY ("ID_SLCTD_OFCIO")
	  REFERENCES "MC_G_SOLICITUDES_Y_OFICIOS" ("ID_SLCTD_OFCIO") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_ID_INST_FLJO_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_ID_SCSTR_AUX_FK" FOREIGN KEY ("ID_SCSTRS_AUXLR")
	  REFERENCES "MC_D_SECUESTRES_AUXILIAR" ("ID_SCSTRS_AUXLR") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_GST_ID_SCSTRE_FK" FOREIGN KEY ("ID_SCSTRE")
	  REFERENCES "MC_D_SECUESTRES" ("ID_SCSTRE") ENABLE
   ) ;

