
  CREATE TABLE "MC_G_EMBARGOS_CARTERA"
   (	"ID_EMBRGOS_CRTRA" NUMBER(15,0) DEFAULT "GENESYS"."SQ_MC_G_EMBARGOS_CARTERA"."NEXTVAL" CONSTRAINT "MC_G_EMB_CRTRA_ID_EMB_CRTRA_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "MC_G_EMB_CRTRA_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_CRTRA" NUMBER(15,0) CONSTRAINT "MC_G_EMB_CRTRA_CDGO_CRTRA_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER(15,0),
	"ID_ESTDOS_CRTRA" NUMBER(2,0) CONSTRAINT "MC_G_EMB_CRTRA_ID_EST_CRT_NN" NOT NULL ENABLE,
	"FCHA_INGRSO" DATE CONSTRAINT "MC_G_EMB_CRTRA_FCHA_INGRSO_NN" NOT NULL ENABLE,
	"ID_LTE_MDDA_CTLAR" NUMBER(15,0),
	"ID_TPOS_MDDA_CTLAR" NUMBER(15,0) CONSTRAINT "MC_G_EMB_CRTRA_ID_TP_MC_NN" NOT NULL ENABLE,
	"VLOR_MDDA_CTLAR" NUMBER(16,2) DEFAULT 0,
	 CONSTRAINT "MC_G_EMB_CRTRA_VLR_MDD_CTLR_CK" CHECK ( vlor_mdda_ctlar >= 0 ) DISABLE,
	 CONSTRAINT "MC_G_EMB_CRTRA_ID_EMB_CRTRA_PK" PRIMARY KEY ("ID_EMBRGOS_CRTRA")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_EMB_CRTRA_ID_LTE_MC_FK" FOREIGN KEY ("ID_LTE_MDDA_CTLAR")
	  REFERENCES "MC_G_LOTES_MDDA_CTLAR" ("ID_LTE_MDDA_CTLAR") ENABLE,
	 CONSTRAINT "MC_G_EMB_CRTRA_ID_EST_CRT_FK" FOREIGN KEY ("ID_ESTDOS_CRTRA")
	  REFERENCES "MC_D_ESTADOS_CARTERA" ("ID_ESTDOS_CRTRA") ENABLE,
	 CONSTRAINT "MC_G_EMB_CRTRA_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "MC_G_EMB_CRTRA_ID_INST_FLJO_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "MC_G_EMB_CRTRA_ID_TP_MC_FK" FOREIGN KEY ("ID_TPOS_MDDA_CTLAR")
	  REFERENCES "MC_D_TIPOS_MDDA_CTLAR" ("ID_TPOS_MDDA_CTLAR") ENABLE
   ) ;

