
  CREATE TABLE "MC_G_DSMBRGS_REMANENTE"
   (	"ID_DSMBRGOS_RMNTE" NUMBER,
	"ID_EMBRGO_RMNTE" NUMBER,
	"ID_FNCNRIO" NUMBER,
	"ID_INSTNCIA_FLJO" NUMBER,
	"ID_SLCTUD" NUMBER,
	"NMRO_OFCIO_JZGDO" VARCHAR2(35),
	"FCHA_OFCIO_JZGDO" DATE,
	"NMRO_RDCDO_JZGDO" VARCHAR2(35),
	 CONSTRAINT "MC_G_DSMB_RMT_ID_EMB_RT_NN" CHECK ("ID_EMBRGO_RMNTE" IS NOT NULL) ENABLE,
	 CONSTRAINT "MC_G_DSMB_RMT_ID_DSMB_RT_PK" PRIMARY KEY ("ID_DSMBRGOS_RMNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_DSMB_RMT_ID_DSMB_RT_NN" CHECK ("ID_DSMBRGOS_RMNTE" IS NOT NULL) ENABLE,
	 CONSTRAINT "MC_G_DSMB_RMT_ID_EMB_RT_FK" FOREIGN KEY ("ID_EMBRGO_RMNTE")
	  REFERENCES "MC_G_EMBARGOS_REMANENTE" ("ID_EMBRGOS_RMNTE") ENABLE,
	 CONSTRAINT "MC_G_DSMB_RMT_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "MC_G_DSMB_RMT_ID_INST_FLJ_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "MC_G_DSMB_RMT_ID_SLCTUD_FK" FOREIGN KEY ("ID_SLCTUD")
	  REFERENCES "PQ_G_SOLICITUDES" ("ID_SLCTUD") ENABLE
   ) ;

