
  CREATE TABLE "MC_G_SECUESTRE_DOCUMENTOS"
   (	"ID_SCSTRE_DCMNTO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_MC_G_SECUESTRE_DOCUMENTOS"."NEXTVAL" CONSTRAINT "MC_G_SCSTR_DC_ID_SCSTR_DC_NN" NOT NULL ENABLE,
	"ID_SCSTRE_GSTION" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_DC_ID_SCSTR_GST_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_DC_ID_FLJO_TREA_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_DC_ID_ACTO_TPO_NN" NOT NULL ENABLE,
	"ID_PLNTLLA" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_DC_ID_PLNTLLA_NN" NOT NULL ENABLE,
	"DCMNTO" CLOB,
	"ID_FNCNRIO" NUMBER(15,0) CONSTRAINT "MC_G_SCSTR_DC_ID_FNCNRIO_NN" NOT NULL ENABLE,
	"ID_ACTO" NUMBER(15,0),
	"NMRO_ACTO" VARCHAR2(30),
	"FCHA_ACTO" TIMESTAMP (6),
	 CONSTRAINT "MC_G_SCSTR_DC_ID_SCSTR_DC_PK" PRIMARY KEY ("ID_SCSTRE_DCMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DC_ID_PLNTLLA_FK" FOREIGN KEY ("ID_PLNTLLA")
	  REFERENCES "GN_D_PLANTILLAS" ("ID_PLNTLLA") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DC_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DC_ID_FLJO_TREA_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DC_ID_SCSTR_GST_FK" FOREIGN KEY ("ID_SCSTRE_GSTION")
	  REFERENCES "MC_G_SECUESTRE_GESTION" ("ID_SCSTRE_GSTION") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DC_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "MC_G_SCSTR_DC_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE
   )
 LOB ("DCMNTO") STORE AS SECUREFILE "SYS_LOB0000105954C00006$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

