
  CREATE TABLE "MC_G_LOTES_MDDA_CTLAR_DTLLE"
   (	"ID_LTE_MDDA_CTLAR_DTLLE" NUMBER(15,0) DEFAULT "GENESYS"."SQ_MC_G_LOTES_MDDA_CTLAR_DTLLE"."NEXTVAL" CONSTRAINT "MC_G_LT_MD_CT_DT_ID_L_M_C_D_NN" NOT NULL ENABLE,
	"ID_LTE_MDDA_CTLAR" NUMBER(15,0) CONSTRAINT "MC_G_LT_MD_CT_DT_ID_L_MD_CT_NN" NOT NULL ENABLE,
	"ID_PRCSDO" NUMBER(15,0) CONSTRAINT "MC_G_LT_MD_CT_DT_ID_PRCSDO_NN" NOT NULL ENABLE,
	"OBSRVCIONES" CLOB,
	 CONSTRAINT "MC_G_LT_MD_CT_DT_ID_L_M_C_D_PK" PRIMARY KEY ("ID_LTE_MDDA_CTLAR_DTLLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_LT_MD_CT_DT_ID_L_MD_CT_FK" FOREIGN KEY ("ID_LTE_MDDA_CTLAR")
	  REFERENCES "MC_G_LOTES_MDDA_CTLAR" ("ID_LTE_MDDA_CTLAR") ENABLE
   )
 LOB ("OBSRVCIONES") STORE AS SECUREFILE "SYS_LOB0000075167C00004$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

