
  CREATE TABLE "MC_G_DESEMBARGOS_OFICIO"
   (	"ID_DSMBRGO_OFCIO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_MC_G_DESEMBARGOS_OFICIO"."NEXTVAL" CONSTRAINT "MC_G_DSMB_OFI_ID_DSMB_OFCIO_NN" NOT NULL ENABLE,
	"ID_DSMBRGOS_RSLCION" NUMBER(15,0) CONSTRAINT "MC_G_DSMB_OFI_ID_DSMB_RSLCN_NN" NOT NULL ENABLE,
	"ID_SLCTD_OFCIO" NUMBER(15,0),
	"ID_ACTO" NUMBER(15,0),
	"FCHA_ACTO" TIMESTAMP (6),
	"NMRO_ACTO" VARCHAR2(30),
	"ID_PLNTLLA" NUMBER(15,0),
	"DCMNTO_DSMBRGO" CLOB,
	"ESTADO_RVCTRIA" VARCHAR2(1) DEFAULT 'N',
	"GNRA_OFCIO" VARCHAR2(1) DEFAULT 'N',
	"RSLCNES_IMPRSN" VARCHAR2(4000),
	 CONSTRAINT "MC_G_DSMB_OFI_ID_DSMB_OFCIO_PK" PRIMARY KEY ("ID_DSMBRGO_OFCIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_DSMB_OFI_ESTAD_RVCTRIA_CK" CHECK (estado_rvctria in ('N','S')) ENABLE,
	 CONSTRAINT "MC_G_DSMB_OFI_ID_DSMB_RSLCN_FK" FOREIGN KEY ("ID_DSMBRGOS_RSLCION")
	  REFERENCES "MC_G_DESEMBARGOS_RESOLUCION" ("ID_DSMBRGOS_RSLCION") ENABLE,
	 CONSTRAINT "MC_G_DSMB_OFI_ID_SLCTD_OFC_FK" FOREIGN KEY ("ID_SLCTD_OFCIO")
	  REFERENCES "MC_G_SOLICITUDES_Y_OFICIOS" ("ID_SLCTD_OFCIO") ENABLE,
	 CONSTRAINT "MC_G_DSMB_OFI_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "MC_G_DSMB_OFI_ID_PLNTLLA_FK" FOREIGN KEY ("ID_PLNTLLA")
	  REFERENCES "GN_D_PLANTILLAS" ("ID_PLNTLLA") ENABLE
   )
 LOB ("DCMNTO_DSMBRGO") STORE AS SECUREFILE "SYS_LOB0000105935C00008$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

