
  CREATE TABLE "MC_G_EMBARGOS_SIMU_LOTE"
   (	"ID_EMBRGOS_SMU_LTE" NUMBER(15,0) DEFAULT "GENESYS"."SQ_MC_G_EMBARGOS_SIMU_LOTE"."NEXTVAL" CONSTRAINT "MC_G_EMB_SM_LT_ID_EMB_SM_LT_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "MC_G_EMB_SM_LT_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"FCHA_LTE" TIMESTAMP (6) CONSTRAINT "MC_G_EMB_SM_LT_FCHA_LTE_PK" NOT NULL ENABLE,
	"ID_FNCNRIO" NUMBER(15,0) CONSTRAINT "MC_G_EMB_SM_LT_ID_FNCNRIO_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(100),
	"ID_TPOS_MDDA_CTLAR" NUMBER(15,0) CONSTRAINT "MC_G_EMB_SM_LT_ID_TP_MC_NN" NOT NULL ENABLE,
	 CONSTRAINT "MC_G_EMB_SM_LT_ID_EMB_SM_LT_PK" PRIMARY KEY ("ID_EMBRGOS_SMU_LTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "MC_G_EMB_SM_LT_ID_FNCNRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "MC_G_EMB_SM_LT_ID_TP_MC_FK" FOREIGN KEY ("ID_TPOS_MDDA_CTLAR")
	  REFERENCES "MC_D_TIPOS_MDDA_CTLAR" ("ID_TPOS_MDDA_CTLAR") ENABLE,
	 CONSTRAINT "MC_G_EMB_SM_LT_CDGO_CLNTE_PK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

