
  CREATE TABLE "MC_G_DSMBRGS_RSLCION_JSON"
   (	"ID_DSMBRGS_RSLCION_JSON" NUMBER CONSTRAINT "MC_G_DSMBRGS_RSLCN_JSON_ID_MBRGS_RSLCN_JSN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER,
	"JSON_RSLCION" CLOB,
	"JSON_ITEM" CLOB,
	 CONSTRAINT "MC_G_DSMBRGS_RSLCION_JSON_ID_MBRGS_RSLCN_JSN_PK" PRIMARY KEY ("ID_DSMBRGS_RSLCION_JSON")
  USING INDEX  ENABLE
   ) ;

