
  CREATE TABLE "MG_D_COLUMNAS"
   (	"ID_CLMNA" NUMBER DEFAULT "GENESYS"."SQ_MG_D_COLUMNAS"."NEXTVAL" CONSTRAINT "MG_D_CLMN_ID_CLMNA_NN" NOT NULL ENABLE,
	"ID_ENTDAD" NUMBER CONSTRAINT "MG_D_CLMN_ID_ENTDAD_NN" NOT NULL ENABLE,
	"NMBRE_CLMNA_DSTNO" VARCHAR2(30),
	"ORGEN_TPO" VARCHAR2(2) DEFAULT 'TO' CONSTRAINT "MG_D_CLMN_ORGEN_TPO_NN" NOT NULL ENABLE,
	"NMBRE_CLMNA_ORGEN" VARCHAR2(30),
	"DSCRPCION" VARCHAR2(300),
	"EJMPLO" VARCHAR2(4000),
	"VLOR_FJO" VARCHAR2(30),
	"DTO_TPO" VARCHAR2(3) CONSTRAINT "MG_D_CLMN_DTO_TPO_NN" NOT NULL ENABLE,
	"LNGTUD" NUMBER,
	"FRMTO" VARCHAR2(20),
	"INDCDOR_RQRDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "MG_D_CLMN_IND_RQRDO_NN" NOT NULL ENABLE,
	"INDCDOR_RQRE_HMLGCION" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "MG_D_CLMN_IND_RQRE_HMLGCION_NN" NOT NULL ENABLE,
	"NMBRE_UP" VARCHAR2(4000),
	 CONSTRAINT "MG_D_CLMN_ID_CLMNA_PK" PRIMARY KEY ("ID_CLMNA")
  USING INDEX  ENABLE,
	 CONSTRAINT "MG_D_CLMN_ORGEN_TPO_CK" CHECK (orgen_tpo in ('TO','VF','UP')) ENABLE,
	 CONSTRAINT "MG_D_CLMN_IND_RQRDO_CK" CHECK (indcdor_rqrdo in ('S','N')) ENABLE,
	 CONSTRAINT "MG_D_CLMN_DTO_TPO_CK" CHECK (dto_tpo in ('C','N', 'F')) ENABLE,
	 CONSTRAINT "MG_D_CLMN_IND_RQRE_HMLGCION_CK" CHECK (indcdor_rqre_hmlgcion in ('S','N')) ENABLE,
	 CONSTRAINT "MG_D_CLMN_ID_ENTDAD_FK" FOREIGN KEY ("ID_ENTDAD")
	  REFERENCES "MG_D_ENTIDADES" ("ID_ENTDAD") ENABLE
   ) ;

