
  CREATE TABLE "MG_G_ENTIDADES_ESPCFCCION"
   (	"ID_ENTDAD_ESPCFCCION" NUMBER DEFAULT "GENESYS"."SQ_MG_G_ENTIDADES_ESPCFCCION"."NEXTVAL" CONSTRAINT "MG_G_ENT_ESP_ID_ENTD_ESPC_NN" NOT NULL ENABLE,
	"ID_PRCSO_ESPCFCCION" NUMBER CONSTRAINT "MG_G_ENT_ESP_ID_PRCS_ESPC_NN" NOT NULL ENABLE,
	"ID_ENTDAD" NUMBER CONSTRAINT "MG_G_ENT_ESP_ID_ENTDAD_NN" NOT NULL ENABLE,
	"INDCDOR_PRCSDO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "MG_G_ENT_ESP_INDCDOR_PRCSDO_NN" NOT NULL ENABLE,
	"INDCDOR_ESPCFCCION" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "MG_G_ENT_ESP_INDCDR_ESPCFCN_NN" NOT NULL ENABLE,
	 CONSTRAINT "MG_G_ENT_ESP_ID_ENTD_ESPC_PK" PRIMARY KEY ("ID_ENTDAD_ESPCFCCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "MG_G_ENT_ESP_INDCDR_ESPCFCN_CK" CHECK (indcdor_espcfccion in ('S', 'N')) ENABLE,
	 CONSTRAINT "MG_G_ENT_ESP_INDCDOR_PRCSDO_CK" CHECK (indcdor_prcsdo in ('S','T','P')) ENABLE,
	 CONSTRAINT "MG_G_ENT_ESP_ID_ENTDAD_FK" FOREIGN KEY ("ID_ENTDAD")
	  REFERENCES "MG_D_ENTIDADES" ("ID_ENTDAD") ENABLE,
	 CONSTRAINT "MG_G_ENT_ESP_ID_PRCS_ESPC_FK" FOREIGN KEY ("ID_PRCSO_ESPCFCCION")
	  REFERENCES "MG_G_PROCESOS_ESPCFCCION" ("ID_PRCSO_ESPCFCCION") ENABLE
   ) ;

