
  CREATE TABLE "MG_G_PROCESOS_INSTANCIA"
   (	"ID_PRCSO_INSTNCIA" NUMBER DEFAULT "GENESYS"."SQ_MG_G_PROCESOS_INSTANCIA"."NEXTVAL" CONSTRAINT "MG_G_PRCSO_INSTC_ID_PRC_INS_NN" NOT NULL ENABLE,
	"ID_PRCSO" NUMBER CONSTRAINT "MG_G_PRCSO_INSTC_ID_PRCSO_NN" NOT NULL ENABLE,
	"ID_SUB_PRCSO" NUMBER,
	"FCHA_INCIO" TIMESTAMP (6) DEFAULT NULL,
	"FCHA_FIN" TIMESTAMP (6),
	"ID_USRIO" NUMBER,
	"TTAL_EXTSOS" NUMBER,
	"TTAL_ERROR" NUMBER,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp,
	 CONSTRAINT "MG_G_PRCSO_INSTC_ID_PRC_INS_PK" PRIMARY KEY ("ID_PRCSO_INSTNCIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "MG_G_PRCSO_INSTC_ID_PRCSO_FK" FOREIGN KEY ("ID_PRCSO")
	  REFERENCES "MG_D_PROCESOS" ("ID_PRCSO") ENABLE,
	 CONSTRAINT "MG_G_PRCSO_INSTC_ID_SUB_PRC_FK" FOREIGN KEY ("ID_SUB_PRCSO")
	  REFERENCES "MG_D_PROCESOS" ("ID_PRCSO") ENABLE
   ) ;

