
  CREATE TABLE "MG_G_SUJETOS_LIQUIDA"
   (	"IDNTFCCION" VARCHAR2(25) CONSTRAINT "MG_G_SUJETO_LQDA_IDNTFCCION_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER,
	"ID_LQDCION" NUMBER,
	"VGNCIA" NUMBER,
	"ID_PRDO" NUMBER,
	"CDGO_LQDCION_ESTDO" VARCHAR2(1) DEFAULT 'L',
	"ID_DCLRCION" NUMBER
   ) ;

