
  CREATE TABLE "NT_D_CAUSALES"
   (	"CDGO_CSAL" VARCHAR2(3) CONSTRAINT "NT_D_CSLES_CDGO_CSAL_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "NT_D_CSLES_DSCRPCION_NN" NOT NULL ENABLE,
	"INDCDOR_NTFCDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "NT_D_CSLES_INDCDOR_NTFCDO_NN" NOT NULL ENABLE,
	 CONSTRAINT "NT_D_CSLES_CDGO_CSAL_PK" PRIMARY KEY ("CDGO_CSAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_D_CSLES_INDCDOR_NTFCDO_CK" CHECK (indcdor_ntfcdo in ('S','N')) ENABLE
   ) ;

