
  CREATE TABLE "NT_D_ACTO_MEDIO_ORDEN"
   (	"ID_ACTO_MDIO_ORDEN" NUMBER CONSTRAINT "NT_D_ACT_MD_ORD_ID_ACT_MD_O_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER CONSTRAINT "NT_D_ACT_MD_ORD_ID_ACTO_TPO_NN" NOT NULL ENABLE,
	"ID_MDIO" NUMBER CONSTRAINT "NT_D_ACT_MD_ORD_ID_MDIO_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER CONSTRAINT "NT_D_ACT_MD_ORD_ORDEN_NN" NOT NULL ENABLE,
	"UNDAD_DRCION" VARCHAR2(3) CONSTRAINT "NT_D_ACT_MD_ORD_UNDD_DRCION_NN" NOT NULL ENABLE,
	"DRCION" NUMBER(4,0) CONSTRAINT "NT_D_ACT_MD_ORD_DRCION_NN" NOT NULL ENABLE,
	"DIA_TPO" VARCHAR2(1) CONSTRAINT "NT_D_ACT_MD_ORD_DIA_TPO_NN" NOT NULL ENABLE,
	"INDCDOR_AUTMTCO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"ID_ENVIO_PRGRMDO" NUMBER,
	 CONSTRAINT "NT_D_ACT_MD_ORD_IND_AUT_CK" CHECK (indcdor_autmtco in ('S','N')) ENABLE,
	 CONSTRAINT "NT_D_ACT_MD_ORD_ID_ACT_MD_O_PK" PRIMARY KEY ("ID_ACTO_MDIO_ORDEN")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_D_ACT_MD_ORD_UNDD_DRCION_CK" CHECK (undad_drcion in ('MN','HR','DI','SM','MS')) ENABLE,
	 CONSTRAINT "NT_D_ACT_MD_ORD_DIA_TPO_CK" CHECK (dia_tpo in ('H','C')) ENABLE,
	 CONSTRAINT "NT_D_ACT_MD_ORD_ID_MDIO_FK" FOREIGN KEY ("ID_MDIO")
	  REFERENCES "NT_D_MEDIO" ("ID_MDIO") ENABLE,
	 CONSTRAINT "NT_D_ACT_MD_ORD_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE,
	 CONSTRAINT "NT_D_ACT_MD_ORD_ID_ENV_PGD_FK" FOREIGN KEY ("ID_ENVIO_PRGRMDO")
	  REFERENCES "MA_G_ENVIOS_PROGRAMADO" ("ID_ENVIO_PRGRMDO") ENABLE
   ) ;

