
  CREATE TABLE "NT_D_LOTE_DETALLE"
   (	"ID_LTE_DTLLE" NUMBER CONSTRAINT "NT_D_LTE_DTLL_ID_NTF_LTE_D_NN" NOT NULL ENABLE,
	"ID_LTE" NUMBER CONSTRAINT "NT_D_LTE_DTLL_ID_LTE_D_NN" NOT NULL ENABLE,
	"ID_ACTO" NUMBER(15,0) CONSTRAINT "NT_D_LTE_DTLL_ID_ACTO_NN" NOT NULL ENABLE,
	"ID_ACTO_RSPNSBLE" NUMBER CONSTRAINT "NT_D_LTE_DTLL_ID_ACTO_RSPN_NN" NOT NULL ENABLE,
	"ID_NTFCCION_RSPNSBLE" NUMBER,
	"NMRO_GUIA" VARCHAR2(100),
	"CDGO_CSAL_ENTDAD" VARCHAR2(3),
	"FCHA_NTFCCION" TIMESTAMP (6),
	"NMRO_IDNTFCCION" VARCHAR2(25),
	"NMBRE_NTFCCION" VARCHAR2(250),
	"ORDEN_SRVCIO" VARCHAR2(25),
	"NMBRE_EVDNCIA_CMPLTO" VARCHAR2(250),
	"INDCDOR_PRCSDO" VARCHAR2(1) DEFAULT 'N',
	"INTNTOS_PRCSO" NUMBER DEFAULT 0,
	 CONSTRAINT "NT_D_LTE_DTLL_ID_NTF_LTE_D_PK" PRIMARY KEY ("ID_LTE_DTLLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_D_LTE_DTLL_INDCDOR_PRCSDO_CK" CHECK (indcdor_prcsdo in ('S', 'N')) ENABLE,
	 CONSTRAINT "NT_D_LTE_DTLL_ID_ACTO_RSPN_FK" FOREIGN KEY ("ID_ACTO_RSPNSBLE")
	  REFERENCES "GN_G_ACTOS_RESPONSABLE" ("ID_ACTO_RSPNSBLE") DISABLE,
	 CONSTRAINT "NT_D_LTE_DTLL_ID_LTE_D_FK" FOREIGN KEY ("ID_LTE")
	  REFERENCES "NT_G_LOTE" ("ID_LTE") ENABLE,
	 CONSTRAINT "NT_D_LTE_DTLL_I_NTFCCN_RSP_FK" FOREIGN KEY ("ID_NTFCCION_RSPNSBLE")
	  REFERENCES "NT_G_NTFCCNES_RSPNSBLE" ("ID_NTFCCION_RSPNSBLE") ENABLE
   ) ;

