
  CREATE TABLE "NT_D_ENTIDAD"
   (	"CDGO_ENTDAD" VARCHAR2(3) CONSTRAINT "NT_D_ENTIDAD_CDGO_ENTDAD_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "NT_D_ENTIDAD_DSCRPCION_NN" NOT NULL ENABLE,
	"NIT" VARCHAR2(20) CONSTRAINT "NT_D_ENTIDAD_NIT_NN" NOT NULL ENABLE,
	"PGNA_WB" VARCHAR2(100),
	 CONSTRAINT "NT_D_ENTIDAD_CDGO_ENTDAD_PK" PRIMARY KEY ("CDGO_ENTDAD")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_D_ENTIDAD_NIT_UN" UNIQUE ("NIT")
  USING INDEX  ENABLE
   ) ;

