
  CREATE TABLE "NT_G_PRENSA"
   (	"ID_PRNSA" NUMBER CONSTRAINT "NT_G_PRENSA_ID_PRNSA_NN" NOT NULL ENABLE,
	"ID_NTFCION_MDIO_EVDNCIA" NUMBER CONSTRAINT "NT_G_PRENSA_ID_NT_MD_EVD_NN" NOT NULL ENABLE,
	"UBCCION" VARCHAR2(500),
	"FCHA_RGSTRO" TIMESTAMP (6),
	 CONSTRAINT "NT_G_PRENSA_ID_PRNSA_PK" PRIMARY KEY ("ID_PRNSA")
  USING INDEX  ENABLE
   ) ;

