
  CREATE TABLE "NT_G_NOTIFICACIONES_DETALLE"
   (	"ID_NTFCCION_DTLLE" NUMBER CONSTRAINT "NT_G_NTFCN_DTL_ID_NTC_DTLLE_NN" NOT NULL ENABLE,
	"ID_NTFCCION" NUMBER CONSTRAINT "NT_G_NTFCN_DTL_ID_NTFCCION_NN" NOT NULL ENABLE,
	"ID_MDIO" NUMBER CONSTRAINT "NT_G_NTFCN_DTL_ID_MEDIO_NN" NOT NULL ENABLE,
	"ID_ENTDAD_CLNTE_MDIO" NUMBER,
	"FCHA_GNRCION" TIMESTAMP (6) CONSTRAINT "NT_G_NTFCN_DTL_ID_FCH_GNRCI_NN" NOT NULL ENABLE,
	"FCHA_PRCSMNTO" TIMESTAMP (6),
	"FCHA_FIN_TRMNO" TIMESTAMP (6),
	"ID_FNCNRIO_GNRCION" NUMBER(15,0),
	"ID_FNCNRIO_PRCSMNTO" NUMBER(15,0),
	 CONSTRAINT "NT_G_NTFCN_DTL_ID_NTC_DTLLE_PK" PRIMARY KEY ("ID_NTFCCION_DTLLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_G_NTFCN_DTL_ID_FNCR_PRCS_FK" FOREIGN KEY ("ID_FNCNRIO_PRCSMNTO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "NT_G_NTFCN_DTL_ID_MEDIO_FK" FOREIGN KEY ("ID_MDIO")
	  REFERENCES "NT_D_MEDIO" ("ID_MDIO") ENABLE,
	 CONSTRAINT "NT_G_NTFCN_DTL_ID_FNCR_GNRC_FK" FOREIGN KEY ("ID_FNCNRIO_GNRCION")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "NT_G_NTFCN_DTL_ID_NTFCCION_FK" FOREIGN KEY ("ID_NTFCCION")
	  REFERENCES "NT_G_NOTIFICACIONES" ("ID_NTFCCION") ENABLE,
	 CONSTRAINT "NT_G_NTFCN_DTL_ID_EN_C_MDIO_FK" FOREIGN KEY ("ID_ENTDAD_CLNTE_MDIO")
	  REFERENCES "NT_D_ENTIDAD_CLIENTE_MEDIO" ("ID_ENTDAD_CLNTE_MDIO") ENABLE
   ) ;

