
  CREATE TABLE "NT_G_NOTIFICACION_GUIA"
   (	"ID_NTFCCION_GUIA" NUMBER CONSTRAINT "NT_G_NTFCCN_G_ID_NTF_GUIA_NN" NOT NULL ENABLE,
	"ID_LTE_DTLLE" NUMBER CONSTRAINT "NT_G_NTFCCN_G_ID_LTE_DTLLE_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER CONSTRAINT "NT_G_NTFCCN_G_I_PRC_CRG_D_NN" NOT NULL ENABLE,
	"ID_PRCSO_INTRMDIA" NUMBER CONSTRAINT "NT_G_NTFCCN_G_I_PR_CR_IN_D_NN" NOT NULL ENABLE,
	"NMERO_LNEA" NUMBER CONSTRAINT "NT_G_NTFCCN_G_NMERO_LNEA_NN" NOT NULL ENABLE,
	"NMRO_GUIA" VARCHAR2(100),
	"CDGO_CSAL_ENTDAD" VARCHAR2(3),
	"FCHA_NTFCCION" TIMESTAMP (6),
	"NMRO_IDNTFCCION" VARCHAR2(25),
	"NMBRE_NTFCCION" VARCHAR2(250),
	"ORDEN_SRVCIO" VARCHAR2(25),
	"NMBRE_EVDNCIA_CMPLTO" VARCHAR2(250),
	 CONSTRAINT "NT_G_NTFCCN_G_ID_NTF_GUIA_PK" PRIMARY KEY ("ID_NTFCCION_GUIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_G_NTFCCN_G_I_PR_CR_IN_D_FK" FOREIGN KEY ("ID_PRCSO_INTRMDIA")
	  REFERENCES "ET_G_PROCESOS_INTERMEDIA" ("ID_PRCSO_INTRMDIA") ENABLE
   ) ;

