
  CREATE TABLE "NT_G_NTFCCNES_RSPNSBLE"
   (	"ID_NTFCCION_RSPNSBLE" NUMBER CONSTRAINT "NT_G_NTFC_RSPSBL_ID_NTF_RSP_NN" NOT NULL ENABLE,
	"ID_NTFCCION_DTLLE" NUMBER CONSTRAINT "NT_G_NTFC_RSPSBL_ID_NT_DTLL_NN" NOT NULL ENABLE,
	"ID_ACTO_RSPNSBLE" NUMBER CONSTRAINT "NT_G_NTFC_RSPSBL_ID_ACTO_RS_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(1) CONSTRAINT "NT_G_NTFC_RSPSBL_CDGO_I_TPO_NN" NOT NULL ENABLE,
	"NMRO_IDNTFCCION" VARCHAR2(25) CONSTRAINT "NT_G_NTFC_RSPSBL_NMRO_IDNTF_NN" NOT NULL ENABLE,
	"PRMER_NMBRE" VARCHAR2(100) CONSTRAINT "NT_G_NTFC_RSPSBL_PRMR_NMBR_NN" NOT NULL ENABLE,
	"SGNDO_NMBRE" VARCHAR2(100),
	"PRMER_APLLDO" VARCHAR2(100) CONSTRAINT "NT_G_NTFC_RSPSBL_PRMR_APLLD_NN" NOT NULL ENABLE,
	"SGNDO_APLLDO" VARCHAR2(100),
	"DRCCION_NTFCCION" VARCHAR2(100) CONSTRAINT "NT_G_NTFC_RSPSBL_DRCC_NTFCN_NN" NOT NULL ENABLE,
	"ID_PAIS_NTFCCION" NUMBER(15,0) CONSTRAINT "NT_G_NTFC_RSPSBL_I_PAIS_NTF_NN" NOT NULL ENABLE,
	"ID_DPRTMNTO_NTFCCION" NUMBER(15,0) CONSTRAINT "NT_G_NTFC_RSPSBL_I_DPRT_NTF_NN" NOT NULL ENABLE,
	"ID_MNCPIO_NTFCCION" NUMBER(15,0),
	"EMAIL" VARCHAR2(320),
	"TLFNO" VARCHAR2(50),
	"ID_NTFCION_MDIO_EVDNCIA" NUMBER,
	"INDCDOR_NTFCDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "NT_G_NTFC_RSPSBL_IND_NTFCDO_NN" NOT NULL ENABLE,
	"ID_FNCNRIO" NUMBER(15,0),
	"FCHA_NTFCCION" TIMESTAMP (6),
	"CDGO_CSAL" VARCHAR2(3),
	 CONSTRAINT "NT_G_NTFC_RSPSBL_ID_NTF_RSP_PK" PRIMARY KEY ("ID_NTFCCION_RSPNSBLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_G_NT_RSP_I_A_RSPN_I_NT_D_UN" UNIQUE ("ID_NTFCCION_DTLLE", "ID_ACTO_RSPNSBLE")
  USING INDEX  ENABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_IND_NTFCDO_CK" CHECK (indcdor_ntfcdo in ('S','N')) ENABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_ID_NT_DTLL_FK" FOREIGN KEY ("ID_NTFCCION_DTLLE")
	  REFERENCES "NT_G_NOTIFICACIONES_DETALLE" ("ID_NTFCCION_DTLLE") ENABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_I_PAIS_NTF_FK" FOREIGN KEY ("ID_PAIS_NTFCCION")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_ID_ACTO_RS_FK" FOREIGN KEY ("ID_ACTO_RSPNSBLE")
	  REFERENCES "GN_G_ACTOS_RESPONSABLE" ("ID_ACTO_RSPNSBLE") DISABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_I_DPRT_NTF_FK" FOREIGN KEY ("ID_DPRTMNTO_NTFCCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_CDGO_CSAL_FK" FOREIGN KEY ("CDGO_CSAL")
	  REFERENCES "NT_D_CAUSALES" ("CDGO_CSAL") ENABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_ID_FNCRIO_FK" FOREIGN KEY ("ID_FNCNRIO")
	  REFERENCES "DF_C_FUNCIONARIOS" ("ID_FNCNRIO") ENABLE,
	 CONSTRAINT "NT_G_NTFC_RSPSBL_I_MNC_NTFC_FK" FOREIGN KEY ("ID_MNCPIO_NTFCCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE
   ) ;

