
  CREATE TABLE "NT_G_CORREO_CERTIFICADO"
   (	"ID_CRREO_CERTIFICADO" NUMBER CONSTRAINT "NT_G_CRREO_CRT_ID_COR_CRTCD_NN" NOT NULL ENABLE,
	"ID_NTFCION_MDIO_EVDNCIA" NUMBER CONSTRAINT "NT_G_CRREO_CRT_I_NT_MD_EVDC_NN" NOT NULL ENABLE,
	"NMRO_ORDEN" NUMBER,
	"NMRO_GUIA" VARCHAR2(100),
	"CDGO_CSAL_ENTDAD" VARCHAR2(3) CONSTRAINT "NT_G_CRREO_CRT_CD_CSL_ENTDD_NN" NOT NULL ENABLE,
	"NMRO_IDNTFCCION" VARCHAR2(25),
	"NMBRE_NTFCCION" VARCHAR2(250),
	 CONSTRAINT "NT_G_CRREO_CRT_ID_COR_CRTCD_PK" PRIMARY KEY ("ID_CRREO_CERTIFICADO")
  USING INDEX  ENABLE
   ) ;

