
  CREATE TABLE "PQ_D_ESTADOS"
   (	"ID_ESTDO" NUMBER CONSTRAINT "PQ_D_ESTADOS_ID_ESTADO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "PQ_D_ESTADOS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "PQ_D_ESTADOS_DSCRPCION_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER CONSTRAINT "PQ_D_ESTADOS_ORDEN_NN" NOT NULL ENABLE,
	 CONSTRAINT "PQ_D_ESTADOS_ORDEN_CDG_CLN_UN" UNIQUE ("ORDEN", "CDGO_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_D_ESTADOS_ID_ESTADO_PK" PRIMARY KEY ("ID_ESTDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_D_ESTADOS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

