
  CREATE TABLE "PQ_D_ACTOS_TIPO_MOTIVO"
   (	"ID_ACTO_TPO_MTVO" NUMBER CONSTRAINT "PQ_D_AC_TP_MT_ID_AC_TP_MT_NN" NOT NULL ENABLE,
	"ID_MTVO" NUMBER CONSTRAINT "PQ_D_AC_TP_MT_ID_MTVO_NN" NOT NULL ENABLE,
	"ID_ACTO_TPO" NUMBER DEFAULT NULL CONSTRAINT "PQ_D_AC_TP_MT_ID_ACTO_TPO_NN" NOT NULL ENABLE,
	"INDCDOR_NTFCCION_ATMTCO" VARCHAR2(1) DEFAULT 'N',
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "PQ_D_AC_TP_MT_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "PQ_D_AC_TP_MT_ID_AC_TP_MT_PK" PRIMARY KEY ("ID_ACTO_TPO_MTVO")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_D_AC_TP_MT_IND_NTF_ATM_CK" CHECK ("INDCDOR_NTFCCION_ATMTCO"='S' OR "INDCDOR_NTFCCION_ATMTCO"='N') ENABLE,
	 CONSTRAINT "PQ_D_AC_TP_MT_ACTVO_CK" CHECK ("ACTVO"='S' OR "ACTVO"='N') ENABLE,
	 CONSTRAINT "PQ_D_AC_TP_MT_ID_MTVO_FK" FOREIGN KEY ("ID_MTVO")
	  REFERENCES "PQ_D_MOTIVOS" ("ID_MTVO") ENABLE,
	 CONSTRAINT "PQ_D_AC_TP_MT_ID_ACTO_TPO_FK" FOREIGN KEY ("ID_ACTO_TPO")
	  REFERENCES "GN_D_ACTOS_TIPO" ("ID_ACTO_TPO") ENABLE
   ) ;

