
  CREATE TABLE "PQ_D_DOCUMENTOS"
   (	"CDGO_DCMNTO" VARCHAR2(3) CONSTRAINT "PQ_D_DOCUMENTOS_CDGO_DCMNTO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "PQ_D_DOCUMENTOS_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "PQ_D_DOCUMENTOS_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "PQ_D_DOCUMENTOS_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "PQ_D_DOCUMENTOS_CDGO_DCMNTO_PK" PRIMARY KEY ("CDGO_DCMNTO")
  USING INDEX  ENABLE
   ) ;

