
  CREATE TABLE "PQ_G_SOLICITUDES_CIERRE"
   (	"ID_SLCTUD_CIERRE" NUMBER CONSTRAINT "PQ_G_SLC_CR_ID_SL_CR_NN" NOT NULL ENABLE,
	"ID_SLCTUD" NUMBER CONSTRAINT "PQ_G_SLC_CR_ID_SLCTUD_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "PQ_G_SLC_CR_FCHA_RGSTRO_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "PQ_G_SLC_CR_ID_USRIO_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(4000) CONSTRAINT "PQ_G_SLC_CR_OBSRVCION_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB,
	"FILE_BFILE" BFILE,
	"FILE_NAME" VARCHAR2(255),
	"FILE_MIMETYPE" VARCHAR2(100),
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "PQ_G_SLC_CR_USER_DGT_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "PQ_G_SLC_CR_FCHA_DGT_NN" NOT NULL ENABLE,
	 CONSTRAINT "PQ_G_SLC_CR_ID_SL_CR_PK" PRIMARY KEY ("ID_SLCTUD_CIERRE")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_G_SLC_CR_ID_SLCTUD_FK" FOREIGN KEY ("ID_SLCTUD")
	  REFERENCES "PQ_G_SOLICITUDES" ("ID_SLCTUD") ENABLE,
	 CONSTRAINT "PQ_G_SLC_CR_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

