
  CREATE TABLE "PQ_G_RADICADOR"
   (	"ID_RDCDOR" NUMBER CONSTRAINT "PQ_G_RADICADOR_ID_RDCDOR_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(3) CONSTRAINT "PQ_G_RADICADOR_CDG_IDNTF_TP_NN" NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(25) CONSTRAINT "PQ_G_RADICADOR_IDNTFCCION_NN" NOT NULL ENABLE,
	"PRMER_NMBRE" VARCHAR2(100) CONSTRAINT "PQ_G_RADICADOR_PRMR_NMBRE_NN" NOT NULL ENABLE,
	"SGNDO_NMBRE" VARCHAR2(100),
	"PRMER_APLLDO" VARCHAR2(100) CONSTRAINT "PQ_G_RADICADOR_PRMER_APLLD_NN" NOT NULL ENABLE,
	"SGNDO_APLLDO" VARCHAR2(100),
	"INDCDOR_MGRDO" VARCHAR2(1),
	 CONSTRAINT "PQ_G_RADICADOR_ID_RDCDOR_PK" PRIMARY KEY ("ID_RDCDOR")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_G_RADICADOR_CDG_IDNTF_TP_FK" FOREIGN KEY ("CDGO_IDNTFCCION_TPO")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE
   ) ;

