
  CREATE TABLE "PQ_G_DOCUMENTO_CAMBIO_ESTRATO"
   (	"ID_DCMNTO" NUMBER CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_ID_DCMNT_NN" NOT NULL ENABLE,
	"ID_SLCTUD" NUMBER CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_ID_SLCTDS_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_FLE_BLB_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255) CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_FL_NM_NN" NOT NULL ENABLE,
	"FILE_MIMETYPE" VARCHAR2(200) CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_FL_MMTYP_NN" NOT NULL ENABLE,
	"FILE_BFILE" BFILE,
	"OBSRVCION" VARCHAR2(4000),
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_FCH_NN" NOT NULL ENABLE,
	"INDCDOR_ACTLZAR" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_INDCDR_AC_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_ACTV_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER(15,0),
	 CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_ACTV_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_INDCDR_ACTLZR_CK" CHECK (indcdor_actlzar in('S','N')) ENABLE
   ) ;
  CREATE UNIQUE INDEX "PQ_G_DCMNTS_CMB_STRT_ID_DCMNTO_PK" ON "PQ_G_DOCUMENTO_CAMBIO_ESTRATO" ("ID_DCMNTO")
  ;
ALTER TABLE "PQ_G_DOCUMENTO_CAMBIO_ESTRATO" ADD CONSTRAINT "PQ_G_DCMNTS_CMB_STRT_ID_DCMNTO_PK" PRIMARY KEY ("ID_DCMNTO")
  USING INDEX "PQ_G_DCMNTS_CMB_STRT_ID_DCMNTO_PK"  ENABLE;

