
  CREATE TABLE "PQ_G_QUEJAS_RECLAMO"
   (	"ID_QJA_RCLMO" NUMBER DEFAULT "GENESYS"."SQ_PQ_G_QUEJAS_RECLAMO"."NEXTVAL" CONSTRAINT "PQ_G_QJA_RCLM_ID_QJA_RCLMO_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "PQ_G_QJA_RCLM_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_TPO" NUMBER CONSTRAINT "PQ_G_QJA_RCLM_ID_TPO_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER CONSTRAINT "PQ_G_QJA_RCLM_ID_INST_FLJO_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO_PDRE" NUMBER,
	"ID_SLCTUD" NUMBER CONSTRAINT "PQ_G_QJA_RCLM_ID_SLCTUD_NN" NOT NULL ENABLE,
	"RSPSTA" CLOB,
	"ID_DCMNTO" NUMBER,
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "PQ_G_NVD_PRS_AD_USER_DGT_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "PQ_G_NVD_PRS_AD_FCHA_DGT_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	 CONSTRAINT "PQ_G_QJA_RCLM_ID_QJA_RCLMO_PK" PRIMARY KEY ("ID_QJA_RCLMO")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_G_QJA_RCLM_ID_INST_FLJO_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "PQ_G_QJA_RCLM_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "PQ_G_QJA_RCLM_ID_TPO_FK" FOREIGN KEY ("ID_TPO")
	  REFERENCES "PQ_D_TIPOS" ("ID_TPO") ENABLE,
	 CONSTRAINT "PQ_G_QJA_RCLM_ID_INS_FJ_PD_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO_PDRE")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "PQ_G_QJA_RCLM_ID_SLCTUD_FK" FOREIGN KEY ("ID_SLCTUD")
	  REFERENCES "PQ_G_SOLICITUDES" ("ID_SLCTUD") ENABLE
   ) ;

