
  CREATE TABLE "PQ_G_DOCUMENTOS_HIST"
   (	"ID_DCMNTO_HIST" NUMBER CONSTRAINT "PQ_G_DCM_HST_ID_DCM_HIST_NN" NOT NULL ENABLE,
	"ID_DCMNTO" NUMBER CONSTRAINT "PQ_G_DCM_HST_ID_DCMNTO_NN" NOT NULL ENABLE,
	"ID_SLCTUD" NUMBER CONSTRAINT "PQ_G_DCM_HST_ID_SLCTDES_NN" NOT NULL ENABLE,
	"ID_MTVO_DCMNTO" NUMBER CONSTRAINT "PQ_G_DCM_HST_ID_DCMNTO_MTVO_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB CONSTRAINT "PQ_G_DCM_HST_FILE_BLOB_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255) CONSTRAINT "PQ_G_DCM_HST_FILE_NAME_NN" NOT NULL ENABLE,
	"FILE_MIMETYPE" VARCHAR2(200) CONSTRAINT "PQ_G_DCM_HST_FILE_MIMETYPE_NN" NOT NULL ENABLE,
	"FILE_BFILE" BFILE,
	"OBSRVCION" VARCHAR2(4000),
	"FCHA" TIMESTAMP (6) CONSTRAINT "PQ_G_DCM_HST_FCHA_NN" NOT NULL ENABLE,
	"INDCDOR_ACTLZAR" VARCHAR2(1) CONSTRAINT "PQ_G_DCM_HST_INDCDOR_ACTLZAR_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "PQ_G_DCM_HST_ACTVO_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp,
	"ID_USRIO_RGSTRA" NUMBER,
	 CONSTRAINT "PQ_G_DCM_HST_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "PQ_G_DCM_HST_INDCDOR_ACTLZAR_CK" CHECK (indcdor_actlzar in(  'S','N')) ENABLE,
	 CONSTRAINT "PQ_G_DCM_HST_ID_DCM_HIST_PK" PRIMARY KEY ("ID_DCMNTO_HIST")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_G_DCM_HST_ID_SLCTDES_FK" FOREIGN KEY ("ID_SLCTUD")
	  REFERENCES "PQ_G_SOLICITUDES" ("ID_SLCTUD") ENABLE,
	 CONSTRAINT "PQ_G_DCM_HST_ID_DCMNTO_MTVO_FK" FOREIGN KEY ("ID_MTVO_DCMNTO")
	  REFERENCES "PQ_D_MOTIVOS_DOCUMENTO" ("ID_MTVO_DCMNTO") ENABLE,
	 CONSTRAINT "PQ_G_DCM_HST_ID_USR_RGS_FK" FOREIGN KEY ("ID_USRIO_RGSTRA")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

