
  CREATE TABLE "PQ_G_SOLICITUDES"
   (	"ID_SLCTUD" NUMBER CONSTRAINT "PQ_G_SLCTDES_ID_SLCTDES_NN" NOT NULL ENABLE,
	"ID_ESTDO" NUMBER CONSTRAINT "PQ_G_SLCTDES_ID_ESTDO_NN" NOT NULL ENABLE,
	"ID_TPO" NUMBER CONSTRAINT "PQ_G_SLCTDES_ID_TPO_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "PQ_G_SLCTDES_ID_USRIO_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER CONSTRAINT "PQ_G_SLCTDES_ID_INSTNCA_FLJ_NN" NOT NULL ENABLE,
	"ID_RDCDOR" NUMBER CONSTRAINT "PQ_G_SLCTDES_ID_RDCDOR_NN" NOT NULL ENABLE,
	"ID_UNDAD_PRDCTRA" NUMBER(15,0),
	"ANIO" NUMBER(4,0) CONSTRAINT "PQ_G_SLCTDES_ANIO_NN" NOT NULL ENABLE,
	"NMRO_RDCDO" NUMBER,
	"NMRO_RDCDO_DSPLAY" VARCHAR2(30),
	"FCHA_RDCDO" TIMESTAMP (6) DEFAULT systimestamp,
	"ID_SLCTUD_BSE" NUMBER,
	"FCHA_REAL" TIMESTAMP (6),
	"FCHA_PRYCTDA" TIMESTAMP (6),
	"FCHA_LMTE_LEY" TIMESTAMP (6),
	"CDGO_CLNTE" NUMBER DEFAULT NULL CONSTRAINT "PQ_G_SLCTDES_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"NMRO_FLIO" NUMBER DEFAULT NULL CONSTRAINT "PQ_G_SLCTDES_NMRO_FLIO_NN" NOT NULL ENABLE,
	"ID_PRSNTCION_TPO" NUMBER DEFAULT NULL CONSTRAINT "PQ_G_SLCTDES_ID_PRSNTCN_TP_NN" NOT NULL ENABLE,
	"CDGO_RSPSTA" VARCHAR2(3),
	"FCHA_INCIO" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "PQ_G_SLCTDES_FCHA_INCIO_NN" NOT NULL ENABLE,
	"INDCDOR_MGRDO" VARCHAR2(1),
	"OBSRVCION_RSPSTA" VARCHAR2(2000),
	"INDCDOR_DCMNTO_PNDNTE" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	 CONSTRAINT "PQ_G_SLCTDS_IND_DCTO_PDNTE_CK" CHECK (indcdor_dcmnto_pndnte in ('S','N')) ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_SLCTDES_PK" PRIMARY KEY ("ID_SLCTUD")
  USING INDEX  ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_INSTNCA_FLJ_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_SLCTUD_BSE_FK" FOREIGN KEY ("ID_SLCTUD_BSE")
	  REFERENCES "PQ_G_SOLICITUDES" ("ID_SLCTUD") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_PRSNTCN_TP_FK" FOREIGN KEY ("ID_PRSNTCION_TPO")
	  REFERENCES "PQ_D_PRESENTACIONES_TIPO" ("ID_PRSNTCION_TPO") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_ESTDO_FK" FOREIGN KEY ("ID_ESTDO")
	  REFERENCES "PQ_D_ESTADOS" ("ID_ESTDO") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_CDGO_RSPSTA_FK" FOREIGN KEY ("CDGO_RSPSTA")
	  REFERENCES "PQ_D_RESPUESTAS" ("CDGO_RSPSTA") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_RDCDOR_FK" FOREIGN KEY ("ID_RDCDOR")
	  REFERENCES "PQ_G_RADICADOR" ("ID_RDCDOR") ENABLE,
	 CONSTRAINT "PQ_G_SLCTDES_ID_TPO_FK" FOREIGN KEY ("ID_TPO")
	  REFERENCES "PQ_D_TIPOS" ("ID_TPO") ENABLE
   ) ;

