
  CREATE TABLE "RE_D_RECAUDOS_FORMA_PAGO"
   (	"CDGO_FRMA_PGO" VARCHAR2(2),
	"DSCRPCION_FRMA_PGO" VARCHAR2(100),
	"ACTVO" VARCHAR2(1) DEFAULT 'S',
	 CONSTRAINT "RE_D_RCDS_FRM_PG_CDG_FRM_PG_PK" PRIMARY KEY ("CDGO_FRMA_PGO")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_D_RCDS_FRM_PG_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE
   ) ;

