
  CREATE TABLE "RE_D_CNFGRCNES_ASBNCRIA"
   (	"ID_CNFGRCION_ASBNCRIA" NUMBER DEFAULT "GENESYS"."SQ_RE_D_CNFGRCNES_ASBNCRIA"."NEXTVAL" CONSTRAINT "RE_D_CNFG_ASB_ID_CNF_ASB_NN" NOT NULL ENABLE,
	"TPO_RGSTRO" VARCHAR2(2) CONSTRAINT "RE_D_CNFG_ASB_TPO_RGSTRO_NN" NOT NULL ENABLE,
	"CDGO_TPO_ASBNCRIA" VARCHAR2(6) CONSTRAINT "RE_D_CNFG_ASB_CDGO_TPO_ASB_NN" NOT NULL ENABLE,
	"CDGO_ATRBTO_ASBNCRIA" VARCHAR2(30) CONSTRAINT "RE_D_CNFG_ASB_CDGO_ATR_ASB_NN" NOT NULL ENABLE,
	"CRCTER_INCIAL" NUMBER(3,0) CONSTRAINT "RE_D_CNFG_ASB_CRCTER_INCIAL_NN" NOT NULL ENABLE,
	"CRCTER_FNAL" NUMBER(3,0) CONSTRAINT "RE_D_CNFG_ASB_CRCTER_FNAL_NN" NOT NULL ENABLE,
	"CDGO_DTO_TPO" VARCHAR2(3) CONSTRAINT "RE_D_CNFG_ASB_CDGO_DTO_TPO_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_D_CNFG_ASB_ID_CNF_ASB_PK" PRIMARY KEY ("ID_CNFGRCION_ASBNCRIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_D_CNFG_ASB_TPO_RGSTRO_CK" CHECK ( tpo_rgstro in ( '01' ,'05' , '06' ,'08' , '09')) ENABLE,
	 CONSTRAINT "RE_D_CNFG_ASB_CDGO_ATR_ASB_FK" FOREIGN KEY ("CDGO_ATRBTO_ASBNCRIA")
	  REFERENCES "RE_D_ATRIBUTOS_ASOBANCARIA" ("CDGO_ATRBTO_ASBNCRIA") ENABLE,
	 CONSTRAINT "RE_D_CNFG_ASB_CDGO_DTO_TPO_FK" FOREIGN KEY ("CDGO_DTO_TPO")
	  REFERENCES "ET_D_DATOS_TIPO" ("CDGO_DTO_TPO") ENABLE,
	 CONSTRAINT "RE_D_CNFG_ASB_CDGO_TPO_ASB_FK" FOREIGN KEY ("CDGO_TPO_ASBNCRIA")
	  REFERENCES "RE_D_TIPOS_ASOBANCARIA" ("CDGO_TPO_ASBNCRIA") ENABLE
   ) ;

