
  CREATE TABLE "RE_D_RECAUDO_ORIGEN_TIPO"
   (	"CDGO_RCDO_ORGN_TPO" VARCHAR2(3) CONSTRAINT "RE_D_RC_ORG_TP_CD_RC_ORG_TP_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "RE_D_RC_ORG_TP_DSCPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_D_RC_ORG_TP_CD_RC_ORG_TP_PK" PRIMARY KEY ("CDGO_RCDO_ORGN_TPO")
  USING INDEX  ENABLE
   ) ;

