
  CREATE TABLE "RE_D_RECAUDO_TIPO"
   (	"CDGO_RCDO_TPO" VARCHAR2(3) CONSTRAINT "RE_D_RC_TP_CD_RC_TP_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(50) CONSTRAINT "RE_D_RC_TP_DSCPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_D_RC_TP_CD_RC_TP_PK" PRIMARY KEY ("CDGO_RCDO_TPO")
  USING INDEX  ENABLE
   ) ;

