
  CREATE TABLE "RE_D_DOCUMENTO_LOTE_TIPO"
   (	"CDGO_DCMNTO_LTE_TPO" VARCHAR2(5) CONSTRAINT "RE_D_DCMT_LTE_TP_CDG_DCM_TP_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "RE_D_DCMT_LTE_TP_DSCPCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_D_DCMT_LTE_TP_CDG_DCM_TP_PK" PRIMARY KEY ("CDGO_DCMNTO_LTE_TPO")
  USING INDEX  ENABLE
   ) ;

