
  CREATE TABLE "RE_G_RECAUDOS_LTE_CNCLCION"
   (	"ID_RCDO_LTE_CNCLCION" NUMBER CONSTRAINT "RE_G_RDS_LT_CN_ID_RDO_LT_C_NN" NOT NULL ENABLE,
	"ID_RCDO_ARCHVO_CNCLCION" NUMBER CONSTRAINT "RE_G_RDS_LT_CN_ID_RDO_A_C_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "RE_G_RDS_LT_CN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "RE_G_RDS_LT_ID_IMPSTO_NN" NOT NULL ENABLE,
	"NMRO_LTE" NUMBER CONSTRAINT "RE_G_RDS_LT_CN_NMRO_LTE_NN" NOT NULL ENABLE,
	"FCHA_CNCLCION" TIMESTAMP (6) CONSTRAINT "RE_G_RDS_LT_CN_FCHA_CNCLCN_NN" NOT NULL ENABLE,
	"ID_BNCO" NUMBER CONSTRAINT "RE_G_RDS_LT_CN_ID_BNCO_NN" NOT NULL ENABLE,
	"ID_BNCO_CNTA" NUMBER CONSTRAINT "RE_G_RDS_LT_CN_ID_BCO_CTA_NN" NOT NULL ENABLE,
	"TTAL_RCDOS" NUMBER,
	"VLOR_LTE" NUMBER,
	"VLOR_TTAL_CNCPTOS" NUMBER,
	"INDCDOR_TRNSCCION" VARCHAR2(3) CONSTRAINT "RE_G_RDS_LT_FD_INDCDR_TRNS_NN" NOT NULL ENABLE,
	"FCHA_RCDO" TIMESTAMP (6) CONSTRAINT "RE_G_RDS_LT_CN_FCHA_RCDO_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_G_RDS_LT_CN_ID_BCO_CTA_FK" FOREIGN KEY ("ID_BNCO_CNTA")
	  REFERENCES "DF_C_BANCOS_CUENTA" ("ID_BNCO_CNTA") ENABLE,
	 CONSTRAINT "RE_G_RDS_LT_CN_ID_RDO_A_C_FK" FOREIGN KEY ("ID_RCDO_ARCHVO_CNCLCION")
	  REFERENCES "RE_G_RECAUDOS_ARCHVO_CNCLCN" ("ID_RCDO_ARCHVO_CNCLCION") ENABLE,
	 CONSTRAINT "RE_G_RDS_LT_CN_ID_BNCO_FK" FOREIGN KEY ("ID_BNCO")
	  REFERENCES "DF_C_BANCOS" ("ID_BNCO") ENABLE,
	 CONSTRAINT "RE_G_RDS_LT_CN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "RE_G_RDS_LT_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE
   ) ;
  CREATE INDEX "RE_G_RECAUDOS_LTE_CNCLCION_AUX" ON "RE_G_RECAUDOS_LTE_CNCLCION" ("ID_RCDO_LTE_CNCLCION", "FCHA_RCDO")
  ;
ALTER TABLE "RE_G_RECAUDOS_LTE_CNCLCION" ADD CONSTRAINT "RE_G_RDS_LT_CN_ID_RDO_LT_C_PK" PRIMARY KEY ("ID_RCDO_LTE_CNCLCION")
  USING INDEX "RE_G_RECAUDOS_LTE_CNCLCION_AUX"  ENABLE;

