
  CREATE TABLE "RE_G_RECAUDOS_FORMA_PAGO"
   (	"ID_RCDO_FRMA_PGO" NUMBER CONSTRAINT "RE_G_RCDS_FRM_PGO_ID_RC_F_P_NN" NOT NULL ENABLE,
	"ID_RCDO" NUMBER CONSTRAINT "RE_G_RCDS_FRM_PGO_ID_RCDO_NN" NOT NULL ENABLE,
	"CDGO_FRMA_PGO" VARCHAR2(2) CONSTRAINT "RE_G_RCDS_FRM_PGO_CDGO_FR_P_NN" NOT NULL ENABLE,
	"VLOR_PGDO" NUMBER CONSTRAINT "RE_G_RCDS_FRM_PGO_VLOR_PGDO_NN" NOT NULL ENABLE,
	"RCDO_ORGN" VARCHAR2(20),
	 CONSTRAINT "RE_G_RCDS_FRM_PGO_ID_RC_F_P_PK" PRIMARY KEY ("ID_RCDO_FRMA_PGO")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_RCDS_FRM_PGO_CDGO_FR_P_CK" CHECK (cdgo_frma_pgo	in	('EF','CH','TR')) ENABLE,
	 CONSTRAINT "RE_G_RCDS_FRM_PGO_ID_RCDO_FK" FOREIGN KEY ("ID_RCDO")
	  REFERENCES "RE_G_RECAUDOS" ("ID_RCDO") ENABLE
   ) ;

