
  CREATE TABLE "RE_G_DCMNTO_LTE_BLOB"
   (	"ID_DCMNTO_LTE_BLOB" NUMBER CONSTRAINT "RE_G_DC_LT_BL_ID_DC_LTE_BLB_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER,
	"FCHA_LTE" DATE,
	"ID_FNCNRIO" NUMBER,
	"ID_DCMNTO_LTE" NUMBER,
	"NMRO_RGSTRO_PRCSAR" NUMBER,
	"CDGO_ESTDO_LTE" VARCHAR2(3),
	 CONSTRAINT "RE_G_DC_LT_BL_ID_DC_LTE_BLB_PK" PRIMARY KEY ("ID_DCMNTO_LTE_BLOB")
  USING INDEX  ENABLE
   ) ;

