
  CREATE TABLE "RE_G_RECAUDOS_ARCHVO_CNCLCN"
   (	"ID_RCDO_ARCHVO_CNCLCION" NUMBER CONSTRAINT "RE_G_RDOS_AR_CN_ID_RDO_A_C_NN" NOT NULL ENABLE,
	"NMBRE_ARCHVO" VARCHAR2(100) CONSTRAINT "RE_G_RDOS_AR_CN_NMBR_ARCHV_NN" NOT NULL ENABLE,
	"FCHA_CNCLCION" TIMESTAMP (6) CONSTRAINT "RE_G_RDOS_AR_CN_FCH_CNCLCN_NN" NOT NULL ENABLE,
	"ESTDO_ARCHVO" VARCHAR2(2) CONSTRAINT "RE_G_RDOS_AR_CN_ESTD_ARCHV_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_G_RDOS_AR_CN_ESTD_ARCHV_CK" CHECK (estdo_archvo in ('IN', 'FN')) ENABLE,
	 CONSTRAINT "RE_G_RDOS_AR_CN_ID_RDO_A_C_PK" PRIMARY KEY ("ID_RCDO_ARCHVO_CNCLCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_RDOS_AR_CN_NMBR_ARCHV_UK" UNIQUE ("NMBRE_ARCHVO")
  USING INDEX  ENABLE
   ) ;

