
  CREATE TABLE "RE_G_DOCUMENTOS_AD_PREDIO"
   (	"ID_DCMNTO_AD_PRDIO" NUMBER(15,0) CONSTRAINT "RE_G_DCMT_PRD_ID_DCM_AD_PRD_NN" NOT NULL ENABLE,
	"ID_DCMNTO" NUMBER(15,0) CONSTRAINT "RE_G_DCMT_PRD_ID_DCMNTO_NN" NOT NULL ENABLE,
	"CDGO_PRDIO_CLSFCCION" VARCHAR2(3),
	"ID_PRDIO_USO_SLO" NUMBER(15,0),
	"ID_PRDIO_DSTNO" NUMBER(15,0),
	"CDGO_ESTRTO" VARCHAR2(3),
	"AREA_TRRNO" NUMBER(16,2),
	"AREA_CNSTRDA" NUMBER(16,2),
	"AREA_GRVBLE" NUMBER(16,2),
	"MTRCLA_INMBLRIA" VARCHAR2(50),
	"DSCRPCION_PRDIO_CLSFCCION" VARCHAR2(50),
	"DSCRPCION_USO_SUELO" VARCHAR2(100),
	"DSCRPCION_PRDO_DSTNO" VARCHAR2(100),
	"DSCRPCION_ESTRTO" VARCHAR2(50),
	 CONSTRAINT "RE_G_DCMT_PRD_ID_DCM_AD_PRD_PK" PRIMARY KEY ("ID_DCMNTO_AD_PRDIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_DCMT_PRD_ID_PRD_DSTN_FK" FOREIGN KEY ("ID_PRDIO_DSTNO")
	  REFERENCES "DF_I_PREDIOS_DESTINO" ("ID_PRDIO_DSTNO") ENABLE,
	 CONSTRAINT "RE_G_DCMT_PRD_CDGO_ESTRTO_FK" FOREIGN KEY ("CDGO_ESTRTO")
	  REFERENCES "DF_S_ESTRATOS" ("CDGO_ESTRTO") ENABLE,
	 CONSTRAINT "RE_G_DCMT_PRD_CDG_PRD_CLS_FK" FOREIGN KEY ("CDGO_PRDIO_CLSFCCION")
	  REFERENCES "DF_S_PREDIOS_CLASIFICACION" ("CDGO_PRDIO_CLSFCCION") ENABLE,
	 CONSTRAINT "RE_G_DCMT_PRD_ID_DCMNTO_FK" FOREIGN KEY ("ID_DCMNTO")
	  REFERENCES "RE_G_DOCUMENTOS" ("ID_DCMNTO") ENABLE,
	 CONSTRAINT "RE_G_DCMT_PRD_ID_USO_SLO_FK" FOREIGN KEY ("ID_PRDIO_USO_SLO")
	  REFERENCES "DF_C_PREDIOS_USO_SUELO" ("ID_PRDIO_USO_SLO") ENABLE
   ) ;

