
  CREATE TABLE "RE_G_RECAUDOS_HSTRCO_RVRSN"
   (	"ID_RCDO_HTRCO_RVRSION" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_R_H_RV_NN" NOT NULL ENABLE,
	"FCHA_RVRSION" TIMESTAMP (6) CONSTRAINT "RE_G_RDO_HST_RVR_FCHA_RVRS_NN" NOT NULL ENABLE,
	"ID_LQDCION" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_LQDDCN_NN" NOT NULL ENABLE,
	"CDGO_RCDO_ORGEN_TPO" VARCHAR2(3) CONSTRAINT "RE_G_RDO_HST_RVR_CG_RC_O_T_NN" NOT NULL ENABLE,
	"CNSCTVO_RCDO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_CNSCVO_RD_NN" NOT NULL ENABLE,
	"ID_RCDO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_RCDO_NN" NOT NULL ENABLE,
	"ID_ORGEN" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_ORGEN_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_I_IMP_SBM_NN" NOT NULL ENABLE,
	"ID_IMPSTO_ACTO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_IM_ACT_NN" NOT NULL ENABLE,
	"VLOR_EFCTVO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_VLOR_EFCT_NN" NOT NULL ENABLE,
	"VLOR_CHQUE" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_VLOR_CHQ_NN" NOT NULL ENABLE,
	"VLOR_RCDO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_VLOR_RCDO_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(200) CONSTRAINT "RE_G_RDO_HST_RVR_OBSRVCION_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_USRIO_NN" NOT NULL ENABLE,
	"ID_USRIO_APLCO" NUMBER CONSTRAINT "RE_G_RDO_HST_RVR_ID_USR_AP_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_G_RDO_HST_RVR_ID_R_H_RV_PK" PRIMARY KEY ("ID_RCDO_HTRCO_RVRSION")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_RDO_HST_RVR_I_IMP_SBM_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "RE_G_RDO_HST_RVR_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE
   ) ;

