
  CREATE TABLE "RE_G_PAGADORES"
   (	"ID_PGDOR" NUMBER CONSTRAINT "RE_T_PGDRS_ID_PGDOR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "RE_T_PGDRS_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(1) CONSTRAINT "RE_T_PGDRS_CGO_IDNT_TP_NN" NOT NULL ENABLE,
	"IDNTFCCION" NUMBER CONSTRAINT "RE_T_PGDRS_IDNTFCCION_NN" NOT NULL ENABLE,
	"PRMER_NMBRE" VARCHAR2(200) CONSTRAINT "RE_T_PGDRS_PRMER_NMBRE_NN" NOT NULL ENABLE,
	"SGNDO_NMBRE" VARCHAR2(100),
	"PRMER_APLLDO" VARCHAR2(100) CONSTRAINT "RE_T_PGDRS_PRMER_APLLDO_NN" NOT NULL ENABLE,
	"SGNDO_APLLDO" VARCHAR2(100),
	"TLFNO_1" VARCHAR2(15) CONSTRAINT "RE_T_PGDRS_TLFNO_1_NN" NOT NULL ENABLE,
	"TLFNO_2" VARCHAR2(15),
	"TLFNO_3" VARCHAR2(15),
	"DRCCION_1" VARCHAR2(100) CONSTRAINT "RE_T_PGDRS_DRCCION_1_NN" NOT NULL ENABLE,
	"DRCCION_2" VARCHAR2(50),
	"DRCCION_3" VARCHAR2(50),
	"EMAIL" VARCHAR2(70) CONSTRAINT "RE_T_PGDRS_EMAIL_NN" NOT NULL ENABLE,
	"ID_TRCRO" NUMBER CONSTRAINT "RE_T_PGDRS_ID_TRCRO_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_T_PGDRS_ID_PGDOR_PK" PRIMARY KEY ("ID_PGDOR")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_T_PGDRS_IDNTFCCION_UN" UNIQUE ("IDNTFCCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_T_PGDRS_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "RE_T_PGDRS_ID_TRCRO_FK" FOREIGN KEY ("ID_TRCRO")
	  REFERENCES "SI_C_TERCEROS" ("ID_TRCRO") ENABLE,
	 CONSTRAINT "RE_T_PGDRS_CGO_IDNT_TP_FK" FOREIGN KEY ("CDGO_IDNTFCCION_TPO")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE
   ) ;

