
  CREATE TABLE "RE_G_RECAUDOS_ASOBANCARIA"
   (	"ID_RCDO_ASBNCRIA" NUMBER DEFAULT "GENESYS"."SQ_RE_G_RECAUDOS_ASOBANCARIA"."NEXTVAL" CONSTRAINT "RE_G_RCD_ASBN_ID_RCD_ASBNCR_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER CONSTRAINT "RE_G_RCD_ASBN_ID_PRCSO_CRGA_NN" NOT NULL ENABLE,
	"ID_PRCSO_INTRMDIA" NUMBER CONSTRAINT "RE_G_RCD_ASBN_ID_PRCS_ITRMD_NN" NOT NULL ENABLE,
	"NMERO_LNEA" NUMBER CONSTRAINT "RE_G_RCD_ASBN_NMERO_LNEA_NN" NOT NULL ENABLE,
	"TPO_RGSTRO" VARCHAR2(2) CONSTRAINT "RE_G_RCD_ASBN_TPO_RGSTRO_NN" NOT NULL ENABLE,
	"LNEA" VARCHAR2(4000) CONSTRAINT "RE_G_RCD_ASBN_LNEA_NN" NOT NULL ENABLE,
	"CDGO_TPO_ASBNCRIA" VARCHAR2(6),
	"ID_RCDO" NUMBER,
	"INDCDOR_RLZDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "RE_G_RCD_ASBN_INDCDOR_RLZDO_NN" NOT NULL ENABLE,
	"MNSJE_RSPSTA" VARCHAR2(4000),
	"ID_BNCO" NUMBER,
	"ID_BNCO_CNTA" NUMBER,
	 CONSTRAINT "RE_G_RCD_ASBN_TPO_RGSTRO_CK" CHECK ( tpo_rgstro in ( '01' ,'05' , '06' ,'08' , '09')) ENABLE,
	 CONSTRAINT "RE_G_RCD_ASBN_INDCDOR_RLZDO_CK" CHECK ( indcdor_rlzdo in ( 'S' , 'N' )) ENABLE,
	 CONSTRAINT "RE_G_RCD_ASBN_ID_RCD_ASBNCR_PK" PRIMARY KEY ("ID_RCDO_ASBNCRIA")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_RCD_ASBN_ID_PRCS_ITRMD_FK" FOREIGN KEY ("ID_PRCSO_INTRMDIA")
	  REFERENCES "ET_G_PROCESOS_INTERMEDIA" ("ID_PRCSO_INTRMDIA") ENABLE,
	 CONSTRAINT "RE_G_RCD_ASBN_ID_BNCO_FK" FOREIGN KEY ("ID_BNCO")
	  REFERENCES "DF_C_BANCOS" ("ID_BNCO") ENABLE,
	 CONSTRAINT "RE_G_RCD_ASBN_CDGO_TPO_ASB_FK" FOREIGN KEY ("CDGO_TPO_ASBNCRIA")
	  REFERENCES "RE_D_TIPOS_ASOBANCARIA" ("CDGO_TPO_ASBNCRIA") ENABLE,
	 CONSTRAINT "RE_G_RCD_ASBN_ID_RCDO_FK" FOREIGN KEY ("ID_RCDO")
	  REFERENCES "RE_G_RECAUDOS" ("ID_RCDO") ENABLE,
	 CONSTRAINT "RE_G_RCD_ASBN_ID_BNCO_CNTA_FK" FOREIGN KEY ("ID_BNCO_CNTA")
	  REFERENCES "DF_C_BANCOS_CUENTA" ("ID_BNCO_CNTA") ENABLE
   ) ;

