
  CREATE TABLE "RE_G_RECAUDOS_CAJA"
   (	"ID_RCDO_CJA" NUMBER CONSTRAINT "RE_G_RCDS_CJA_ID_RCDO_CJA_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "RE_G_RCDS_CJA_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_BNCO" NUMBER CONSTRAINT "RE_G_RCDS_CJA_ID_BNCO_NN" NOT NULL ENABLE,
	"FCHA_APRTRA" TIMESTAMP (6) CONSTRAINT "RE_G_RCDS_CJA_FCHA_APRTRA_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(1000) CONSTRAINT "RE_G_RCDS_CJA_OBSRVCION_NN" NOT NULL ENABLE,
	"CNTDAD_RCDOS" NUMBER CONSTRAINT "RE_G_RCDS_CJA_CNTDD_RCDOS_NN" NOT NULL ENABLE,
	"VLOR_RCDOS" NUMBER CONSTRAINT "RE_G_RCDS_CJA_VLOR_RCDOS_NN" NOT NULL ENABLE,
	"CDGO_RCDO_ORGEN" VARCHAR2(3) CONSTRAINT "RE_G_RCDS_CJA_CGO_RDO_ORGN_NN" NOT NULL ENABLE,
	"ESTDO_APRTRA" VARCHAR2(1) CONSTRAINT "RE_G_RCDS_CJA_ESTDO_APRTRA_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "RE_G_RCDS_CJA_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) CONSTRAINT "RE_G_RCDS_CJA_FCHA_RGSTRO_NN" NOT NULL ENABLE,
	"FCHA_CRRE" TIMESTAMP (6),
	"CNSCTVO_CNTROL" NUMBER CONSTRAINT "RE_G_RCDS_CJA_CNSCTVO_CTRL_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_G_RCDS_CJA_ID_RCDO_CJA_PK" PRIMARY KEY ("ID_RCDO_CJA")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_RCDS_CJA_ESTDO_APRTRA_CK" CHECK (estdo_aprtra	in	('A','B','C')) ENABLE,
	 CONSTRAINT "RE_G_RCDS_CJA_ID_BNCO_FK" FOREIGN KEY ("ID_BNCO")
	  REFERENCES "DF_C_BANCOS" ("ID_BNCO") ENABLE,
	 CONSTRAINT "RE_G_RCDS_CJA_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

