
  CREATE TABLE "RE_G_DESCUENTOS_CONDICION"
   (	"ID_DSCNTO_CNDCION" NUMBER DEFAULT "GENESYS"."SQ_RE_G_DESCUENTOS_CONDICION"."NEXTVAL" CONSTRAINT "RE_G_DSCNT_CNDC_ID_DSC_CNDC_NN" NOT NULL ENABLE,
	"ID_DSCNTO_RGLA" NUMBER CONSTRAINT "RE_G_DSCNT_CNDC_DSCNT_RGLA_NN" NOT NULL ENABLE,
	"CDGO_DSCNTO_CNDCION_TPO" VARCHAR2(3) CONSTRAINT "RE_G_DSCNT_CNDC_CD_DS_CN_TP_NN" NOT NULL ENABLE,
	"VGNCIA_DSDE_PGO" NUMBER,
	"ID_PRDO_DSDE_PGO" NUMBER,
	"VGNCIA_HSTA_PGO" NUMBER,
	"ID_PRDO_HSTA_PGO" NUMBER,
	"VGNCIA_DSDE_PAZ_SLVO" NUMBER,
	"ID_PRDO_DSDE_PAZ_SLVO" NUMBER,
	"VGNCIA_HSTA_PAZ_SLVO" NUMBER,
	"ID_PRDO_HSTA_PAZ_SLVO" NUMBER,
	"FCHA_LMTE_PAZ_SLVO" DATE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "RE_G_DSCNT_CNDC_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_ID_DSC_CNDC_PK" PRIMARY KEY ("ID_DSCNTO_CNDCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_CD_DS_CN_TP_CK" CHECK (cdgo_dscnto_cndcion_tpo in ('DCM', 'PYS', 'FNC')) ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_VGNC_DSD_PG_FK" FOREIGN KEY ("VGNCIA_DSDE_PGO")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_VGNC_DSD_PS_FK" FOREIGN KEY ("VGNCIA_DSDE_PAZ_SLVO")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_DSCNT_RGLA_FK" FOREIGN KEY ("ID_DSCNTO_RGLA")
	  REFERENCES "RE_G_DESCUENTOS_REGLA" ("ID_DSCNTO_RGLA") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_VGNC_HST_PG_FK" FOREIGN KEY ("VGNCIA_HSTA_PGO")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_PRD_HST_PS_FK" FOREIGN KEY ("ID_PRDO_HSTA_PAZ_SLVO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_PRD_DSD_PS_FK" FOREIGN KEY ("ID_PRDO_DSDE_PAZ_SLVO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_PRD_HST_PG_FK" FOREIGN KEY ("ID_PRDO_HSTA_PGO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_PRD_DSD_PG_FK" FOREIGN KEY ("ID_PRDO_DSDE_PGO")
	  REFERENCES "DF_I_PERIODOS" ("ID_PRDO") ENABLE,
	 CONSTRAINT "RE_G_DSCNT_CNDC_VGNC_HST_PS_FK" FOREIGN KEY ("VGNCIA_HSTA_PAZ_SLVO")
	  REFERENCES "DF_S_VIGENCIAS" ("VGNCIA") ENABLE
   ) ;

