
  CREATE TABLE "RE_G_PGADORES_DCMNTO_ARCHVO"
   (	"ID_PGDOR_DCMNTO_ARCHVO" NUMBER CONSTRAINT "RE_G_PGD_DCM_ARC_I_PG_DC_AR_NN" NOT NULL ENABLE,
	"ID_PGDOR_DCMNTO" NUMBER CONSTRAINT "RE_G_PGD_DCM_ARC_ID_PGD_DCM_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(300),
	"FILE_BLOB" BLOB,
	"FILE_MIME" VARCHAR2(300),
	"FCHA_RGSTRO" TIMESTAMP (6) CONSTRAINT "RE_G_PGD_DCM_ARC_FCHA_RGSTR_NN" NOT NULL ENABLE,
	 CONSTRAINT "RE_G_PGD_DCM_ARC_I_PG_DC_AR_PK" PRIMARY KEY ("ID_PGDOR_DCMNTO_ARCHVO")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_PGD_DCM_ARC_ID_PGD_DCM_FK" FOREIGN KEY ("ID_PGDOR_DCMNTO")
	  REFERENCES "RE_G_PAGADORES_DOCUMENTO" ("ID_PGDOR_DCMNTO") ENABLE
   ) ;

