
  CREATE TABLE "RE_G_DOCUMENTOS_CNVNIO_CTA"
   (	"ID_DCMNTO_CNVNIO_CTA" NUMBER CONSTRAINT "RE_G_DCT_CNV_CT_ID_DC_CN_CT_NN" NOT NULL ENABLE,
	"ID_DCMNTO" NUMBER CONSTRAINT "RE_G_DCT_CNV_CT_ID_DCMNTO_NN" NOT NULL ENABLE,
	"ID_CNVNIO" NUMBER CONSTRAINT "RE_G_DCT_CNV_CT_ID_CNVNIO_NN" NOT NULL ENABLE,
	"NMRO_CTA" NUMBER CONSTRAINT "RE_G_DCT_CNV_CT_NMRO_CTA_NN" NOT NULL ENABLE,
	"ID_MVMNTO_DTLLE" NUMBER CONSTRAINT "RE_G_DCT_CNV_CT_ID_MVT_DTLL_NN" NOT NULL ENABLE,
	"ID_CNCPTO" NUMBER CONSTRAINT "RE_G_DCT_CNV_CT_ID_CNPTO_NN" NOT NULL ENABLE,
	"VLOR_DBE" NUMBER DEFAULT 0 CONSTRAINT "RE_G_DCT_CNV_CT_VLOR_DBE_NN" NOT NULL ENABLE,
	"VLOR_HBER" NUMBER DEFAULT 0,
	 CONSTRAINT "RE_G_DCT_CNV_CT_VLOR_DBE_CK" CHECK ( vlor_dbe >= 0 ) ENABLE,
	 CONSTRAINT "RE_G_DCT_CNV_CT_ID_DC_CN_CT_PK" PRIMARY KEY ("ID_DCMNTO_CNVNIO_CTA")
  USING INDEX  ENABLE,
	 CONSTRAINT "RE_G_DCT_CNV_CT_ID_CNPTO_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "RE_G_DCT_CNV_CT_ID_CNVNIO_FK" FOREIGN KEY ("ID_CNVNIO")
	  REFERENCES "GF_G_CONVENIOS" ("ID_CNVNIO") ENABLE,
	 CONSTRAINT "RE_G_DCT_CNV_CT_ID_MVT_DTLL_FK" FOREIGN KEY ("ID_MVMNTO_DTLLE")
	  REFERENCES "GF_G_MOVIMIENTOS_DETALLE" ("ID_MVMNTO_DTLLE") DISABLE,
	 CONSTRAINT "RE_G_DCT_CNV_CT_ID_DCMNTO_FK" FOREIGN KEY ("ID_DCMNTO")
	  REFERENCES "RE_G_DOCUMENTOS" ("ID_DCMNTO") ENABLE
   ) ;

