
  CREATE TABLE "RE_T_PAGADORES_DOCUMENTO_BACKUP"
   (	"ID_PGDOR_DCMNTO" NUMBER NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER NOT NULL ENABLE,
	"ID_DCMNTO" NUMBER NOT NULL ENABLE,
	"ID_PGDOR" NUMBER NOT NULL ENABLE,
	"INDCDOR_ESTDO_TRNSCCION" VARCHAR2(3) NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) NOT NULL ENABLE,
	"FCHA_MDFCCION" TIMESTAMP (6),
	"INDCDOR_ESTDO_TRNSCCION2" VARCHAR2(2)
   ) ;

