
  CREATE TABLE "REPORTE_LIQUIDACION"
   (	"CODIGO" CLOB
   )
 LOB ("CODIGO") STORE AS SECUREFILE "SYS_LOB0000110226C00001$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

