
  CREATE TABLE "SG_D_DESTINOS_TIPO"
   (	"DSTNO_TPO" NUMBER(15,0) CONSTRAINT "SG_D_DSTNO_TPO_DSTNO_TPO_NN" NOT NULL ENABLE,
	"DSCRPCION_DSTNO_TPO" VARCHAR2(30) CONSTRAINT "SG_D_DSTNO_TPO_DSCRP_DS_TPO_NN" NOT NULL ENABLE,
	 CONSTRAINT "SG_D_DSTNO_TPO_DSTNO_TPO_PK" PRIMARY KEY ("DSTNO_TPO")
  USING INDEX  ENABLE
   ) ;

