
  CREATE TABLE "SG_D_CONFIGURACIONES_LOG"
   (	"ID_CNFGRCION_LOG" NUMBER CONSTRAINT "SG_D_CONG_LOG_ID_CNFGRC_LOG_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "SG_D_CONG_LOG_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER,
	"NMBRE_UP" VARCHAR2(70) CONSTRAINT "SG_D_CONF_LOG_NMBRE_LOG_NN" NOT NULL ENABLE,
	"TPO_UP" VARCHAR2(15) CONSTRAINT "SG_D_CONF_LOG_TPO_UP_NN" NOT NULL ENABLE,
	"NVEL_LOG" NUMBER DEFAULT 0 CONSTRAINT "SG_D_CONF_LOG_NVEL_LOG_NN" NOT NULL ENABLE,
	 CONSTRAINT "SG_D_CONF_LOG_TPO_UP_CK" CHECK (tpo_up in ('FUNCTION','PROCEDURE','PACKAGE')) ENABLE,
	 CONSTRAINT "SG_D_CONF_LOG_CLNT_IMPST_UP_UN" UNIQUE ("CDGO_CLNTE", "ID_IMPSTO", "NMBRE_UP")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_D_CONG_LOG_ID_CNFGRC_LOG_PK" PRIMARY KEY ("ID_CNFGRCION_LOG")
  USING INDEX  ENABLE
   ) ;

