
  CREATE TABLE "SG_G_PERFILES"
   (	"ID_PRFIL" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_ID_MNU_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"NMBRE_PRFIL" VARCHAR2(100) CONSTRAINT "SG_G_PRFIL_NMBRE_PRFIL_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "SG_G_PRFIL_ACTVO_NN" NOT NULL ENABLE,
	"USERNAME_DIGITA" VARCHAR2(100) DEFAULT user CONSTRAINT "SG_G_PRFIL_USER_DIGITA_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "SG_G_PRFIL_FECH_DIGITA_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	"INDCDOR_PRFIL_ADMNSTDOR" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "SG_G_PRFIL_IND_PRFL_ADMIN_NN" NOT NULL ENABLE,
	 CONSTRAINT "SG_G_PRFIL_IND_PRFL_ADMIN_CK" CHECK (indcdor_prfil_admnstdor in ('S','N')) ENABLE,
	 CONSTRAINT "SG_G_PRFIL_ID_MNU_PK" PRIMARY KEY ("ID_PRFIL")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_PRFIL_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "SG_G_PRFIL_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE
   ) ;

