
  CREATE TABLE "SG_G_PERFILES_BOTON"
   (	"ID_PRFIL_BTON" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_BTN_ID_PRFIL_BTN_NN" NOT NULL ENABLE,
	"ID_PRFIL" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_BTN_ID_PRFIL_NN" NOT NULL ENABLE,
	"ID_APLCCION" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_BTN_ID_APLCCION_NN" NOT NULL ENABLE,
	"NMRO_PGNA" NUMBER CONSTRAINT "SG_G_PRFIL_BTN_NMRO_PGNA_NN" NOT NULL ENABLE,
	"ID_BTON" NUMBER CONSTRAINT "SG_G_PRFIL_BTN_ID_BTON_NN" NOT NULL ENABLE,
	"NMBRE_BTON" VARCHAR2(100) CONSTRAINT "SG_G_PRFIL_BTN_NMBRE_BTON_NN" NOT NULL ENABLE,
	"USERNAME_DIGITA" VARCHAR2(100) DEFAULT user CONSTRAINT "SG_G_PRFIL_BTN_USER_DIGIT_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "SG_G_PRFIL_BTN_FECH_DIGIT_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	 CONSTRAINT "SG_G_PRFIL_BTN_ID_PRFIL_BTN_PK" PRIMARY KEY ("ID_PRFIL_BTON")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_PRFIL_BTN_ID_PRFIL_FK" FOREIGN KEY ("ID_PRFIL")
	  REFERENCES "SG_G_PERFILES" ("ID_PRFIL") ENABLE,
	 CONSTRAINT "SG_G_PRFIL_BTN_ID_APLCCION_FK" FOREIGN KEY ("ID_APLCCION")
	  REFERENCES "SG_G_APLICACIONES" ("ID_APLCCION") ENABLE
   ) ;

