
  CREATE TABLE "SG_G_PERFILES_REGION"
   (	"ID_PRFIL_RGION" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_RGN_ID_PRFIL_RGN_NN" NOT NULL ENABLE,
	"ID_PRFIL" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_RGN_ID_PRFIL_NN" NOT NULL ENABLE,
	"ID_APLCCION" NUMBER(15,0) CONSTRAINT "SG_G_PRFIL_RGN_ID_APLCCION_NN" NOT NULL ENABLE,
	"NMRO_PGNA" NUMBER CONSTRAINT "SG_G_PRFIL_RGN_NMRO_PGNA_NN" NOT NULL ENABLE,
	"ID_RGION" NUMBER CONSTRAINT "SG_G_PRFIL_RGN_ID_RGION_NN" NOT NULL ENABLE,
	"NMBRE_RGION" VARCHAR2(100) CONSTRAINT "SG_G_PRFIL_RGN_NMBRE_RGION_NN" NOT NULL ENABLE,
	"USERNAME_DIGITA" VARCHAR2(100) DEFAULT user CONSTRAINT "SG_G_PRFIL_RGN_USER_DIGIT_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "SG_G_PRFIL_RGN_FECH_DIGIT_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	 CONSTRAINT "SG_G_PRFIL_RGN_ID_PRFIL_RGN_PK" PRIMARY KEY ("ID_PRFIL_RGION")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_PRFIL_RGN_ID_PRFIL_FK" FOREIGN KEY ("ID_PRFIL")
	  REFERENCES "SG_G_PERFILES" ("ID_PRFIL") ENABLE,
	 CONSTRAINT "SG_G_PRFIL_RGN_ID_APLCCION_FK" FOREIGN KEY ("ID_APLCCION")
	  REFERENCES "SG_G_APLICACIONES" ("ID_APLCCION") ENABLE
   ) ;

