
  CREATE TABLE "SG_G_USUARIOS_SUCURSAL"
   (	"ID_USRIO_SCRSAL" NUMBER CONSTRAINT "SG_G_USR_SCRSAL_ID_USR_SCRS_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "SG_G_USR_SCRSAL_ID_USRIO_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "SG_G_USR_SCRSAL_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_SJTO_SCRSAL" NUMBER CONSTRAINT "SG_G_USR_SCRSAL_ID_SJT_SCRS_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S',
	 CONSTRAINT "SG_G_USR_SCRSAL_ID_USR_SCRS_PK" PRIMARY KEY ("ID_USRIO_SCRSAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_USR_SCRSL_ID_USR_SJT_SCRS" UNIQUE ("ID_USRIO", "ID_SJTO_SCRSAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_USR_SCRSAL_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "SG_G_USR_SCRSAL_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "SG_G_USR_SCRSAL_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

