
  CREATE TABLE "SG_G_PERFILES_MENU"
   (	"ID_PRFIL_MNU" NUMBER(15,0) CONSTRAINT "SG_G_PRFL_MNU_ID_PRFIL_MNU_NN" NOT NULL ENABLE,
	"ID_PRFIL" NUMBER(15,0) CONSTRAINT "SG_G_PRFL_MNU_ID_PRFL_NN" NOT NULL ENABLE,
	"ID_MNU" NUMBER(15,0) CONSTRAINT "SG_G_PRFL_MNU_ID_MNU_NN" NOT NULL ENABLE,
	"USERNAME_DIGITA" VARCHAR2(100) DEFAULT user CONSTRAINT "SG_G_PRFL_MNU_USER_DIGIT_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "SG_G_PRFL_MNU_FECH_DIGIT_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	 CONSTRAINT "SG_G_PRFL_MN_ID_PRFIL_ID_MN_UN" UNIQUE ("ID_PRFIL", "ID_MNU")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_PRFL_MNU_ID_PRFIL_MNU_PK" PRIMARY KEY ("ID_PRFIL_MNU")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_PRFL_MNU_ID_MNU_FK" FOREIGN KEY ("ID_MNU")
	  REFERENCES "SG_G_MENU" ("ID_MNU") ENABLE,
	 CONSTRAINT "SG_G_PRFL_MNU_ID_PRFL_FK" FOREIGN KEY ("ID_PRFIL")
	  REFERENCES "SG_G_PERFILES" ("ID_PRFIL") ENABLE
   ) ;

