
  CREATE TABLE "SG_G_APLICACIONES"
   (	"ID_APLCCION" NUMBER(15,0) CONSTRAINT "SG_G_APLCCN_ID_APLCCION_NN" NOT NULL ENABLE,
	"NMRO_APLCCION" NUMBER(15,0) CONSTRAINT "SG_G_APLCCN_NMRO_APLCCION_NN" NOT NULL ENABLE,
	"NMBRE_APLCCION" VARCHAR2(30) CONSTRAINT "SG_G_APLCCN_NMBRE_APLCCION_NN" NOT NULL ENABLE,
	"DSCRPCION_APLCCION" VARCHAR2(500),
	"ORDEN" NUMBER(3,0) DEFAULT 10 CONSTRAINT "SG_G_APLCCN_ORDEN_APLCCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "SG_G_APLCCN_ACTVO_NN" NOT NULL ENABLE,
	"USERNAME_DIGITA" VARCHAR2(100) DEFAULT user CONSTRAINT "SG_G_APLCCN_USER_DIGITA_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "SG_G_APLCCN_FECH_DIGITA_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	"PGNA_INCIO" VARCHAR2(50),
	 CONSTRAINT "SG_G_APLCCN_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "SG_G_APLCCN_NMRO_APLCCION_UN" UNIQUE ("NMRO_APLCCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_APLCCN_ID_APLCCION_PK" PRIMARY KEY ("ID_APLCCION")
  USING INDEX  ENABLE
   ) ;

