
  CREATE TABLE "SG_G_USUARIOS"
   (	"ID_USRIO" NUMBER(15,0) CONSTRAINT "SG_G_USRIO_ID_USRIO_NN" NOT NULL ENABLE,
	"USER_NAME" NUMBER(15,0),
	"FCHA_CRCION" TIMESTAMP (6) DEFAULT systimestamp,
	"ADMIN" NUMBER(1,0) DEFAULT 0 CONSTRAINT "SG_G_USRIO_ADMIN_NN" NOT NULL ENABLE,
	"ADMIN_RNION" NUMBER(1,0) DEFAULT 0 CONSTRAINT "SG_G_USRIO_ADMIN_RNION_NN" NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(500),
	"FCHA_EXPRCION" DATE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "SG_G_USRIO_ACTVO_NN" NOT NULL ENABLE,
	"USERNAME_DIGITA" VARCHAR2(100) DEFAULT user CONSTRAINT "SG_G_USRIO_USER_DIGITA_NN" NOT NULL ENABLE,
	"FECHA_DIGITA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "SG_G_USRIO_FECH_DIGITA_NN" NOT NULL ENABLE,
	"USERNAME_MODIFICA" VARCHAR2(100),
	"FECHA_MODIFICA" TIMESTAMP (6),
	"ID_TRCRO" NUMBER DEFAULT 1 CONSTRAINT "SG_G_USRIO_ID_TRCR_NN" NOT NULL ENABLE,
	 CONSTRAINT "SG_G_USRIO_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "SG_G_USRIO_USER_NAME_NN" CHECK (USER_NAME is NOT NULL) ENABLE,
	 CONSTRAINT "SG_G_USRIO_ID_USRIO_PK" PRIMARY KEY ("ID_USRIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_USRIO_ID_TRCR_FK" FOREIGN KEY ("ID_TRCRO")
	  REFERENCES "SI_C_TERCEROS" ("ID_TRCRO") ENABLE
   ) ;

