
  CREATE TABLE "SG_G_MANEJOS_ERROR"
   (	"ID_MNJO_ERROR" NUMBER CONSTRAINT "SG_G_MNJO_ERROR_ID_MNJO_ERR_NN" NOT NULL ENABLE,
	"ID_TPO_ERROR" NUMBER CONSTRAINT "SG_G_MNJO_ERROR_ID_TPO_ERRO_NN" NOT NULL ENABLE,
	"CNSTRNT_NME" VARCHAR2(35) CONSTRAINT "SG_G_MNJO_ERROR_CNSTRNT_NME_NN" NOT NULL ENABLE,
	"MNSJE_ES" VARCHAR2(1000) CONSTRAINT "SG_G_MNJO_ERROR_MNSJE_ES_NN" NOT NULL ENABLE,
	"MNSJE_US" VARCHAR2(1000),
	 CONSTRAINT "SG_G_MNJO_ERROR_CNSTRNT_NME_UN" UNIQUE ("CNSTRNT_NME")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_MNJO_ERROR_ID_MNJO_ERR_PK" PRIMARY KEY ("ID_MNJO_ERROR")
  USING INDEX  ENABLE,
	 CONSTRAINT "SG_G_MNJO_ERROR_ID_TPO_ERRO_FK" FOREIGN KEY ("ID_TPO_ERROR")
	  REFERENCES "SG_D_TIPOS_ERROR" ("ID_TPO_ERROR") ENABLE
   ) ;

