
  CREATE TABLE "SI_C_TERCEROS_PORTAL"
   (	"ID_TRCRO_PRTAL" NUMBER DEFAULT "GENESYS"."SQ_SI_C_TERCEROS_PORTAL"."NEXTVAL" CONSTRAINT "SI_C_TRCRO_PRTAL_ID_TRC_PRT_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "SI_C_TRCRO_PRTAL_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(3) CONSTRAINT "SI_C_TRCRO_PRTAL_CDG_IDN_TP_NN" NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(25) CONSTRAINT "SI_C_TRCRO_PRTAL_IDNTFCCION_NN" NOT NULL ENABLE,
	"PRMER_NMBRE" VARCHAR2(100) CONSTRAINT "SI_C_TRCRO_PRTAL_PRMER_NMBR_NN" NOT NULL ENABLE,
	"SGNDO_NMBRE" VARCHAR2(100),
	"PRMER_APLLDO" VARCHAR2(100) CONSTRAINT "SI_C_TRCRO_PRTAL_PRMR_APLLD_NN" NOT NULL ENABLE,
	"SGNDO_APLLDO" VARCHAR2(100),
	"DRCCION" VARCHAR2(100),
	"ID_PAIS" NUMBER CONSTRAINT "SI_C_TRCRO_PRTAL_ID_PAIS_NN" NOT NULL ENABLE,
	"ID_DPRTMNTO" NUMBER CONSTRAINT "SI_C_TRCRO_PRTAL_ID_DPRTMNT_NN" NOT NULL ENABLE,
	"ID_MNCPIO" NUMBER CONSTRAINT "SI_C_TRCRO_PRTAL_ID_MNCPIO_NN" NOT NULL ENABLE,
	"DRCCION_NTFCCION" VARCHAR2(100),
	"ID_PAIS_NTFCCION" NUMBER,
	"ID_DPRTMNTO_NTFCCION" NUMBER,
	"ID_MNCPIO_NTFCCION" NUMBER,
	"EMAIL" VARCHAR2(320) CONSTRAINT "SI_C_TRCRO_PRTAL_EMAIL_NN" NOT NULL ENABLE,
	"TLFNO" VARCHAR2(50),
	"GNRO" VARCHAR2(1) DEFAULT 'M' CONSTRAINT "SI_C_TRCRO_PRTAL_GNRO_NN" NOT NULL ENABLE,
	"NCNLDAD" VARCHAR2(50),
	"FCHA_NCMNTO" TIMESTAMP (6),
	"ID_PAIS_ORGN" NUMBER CONSTRAINT "SI_C_TRCRO_PRTAL_ID_PS_ORGN_NN" NOT NULL ENABLE,
	"CLLAR" VARCHAR2(50),
	"INDCDOR_PRCSDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "SI_C_TRCRO_PRTAL_IND_PRC_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_GNRO_CK" CHECK (gnro in ('M','F')) ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_CLNT_IDNT_UN" UNIQUE ("CDGO_CLNTE", "IDNTFCCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_IND_PRC_CK" CHECK (indcdor_prcsdo in ('S','N')) ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_TRC_PRT_PK" PRIMARY KEY ("ID_TRCRO_PRTAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_PAIS_FK" FOREIGN KEY ("ID_PAIS")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_MNCPIO_FK" FOREIGN KEY ("ID_MNCPIO")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_DPT_NTF_FK" FOREIGN KEY ("ID_DPRTMNTO_NTFCCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_MNC_NTF_FK" FOREIGN KEY ("ID_MNCPIO_NTFCCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_PS_NT_FK" FOREIGN KEY ("ID_PAIS_NTFCCION")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_CDG_IDN_TP_FK" FOREIGN KEY ("CDGO_IDNTFCCION_TPO")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_DPRTMNT_FK" FOREIGN KEY ("ID_DPRTMNTO")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "SI_C_TRCRO_PRTAL_ID_PS_ORGN_FK" FOREIGN KEY ("ID_PAIS_ORGN")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE
   ) ;

