
  CREATE TABLE "SI_C_TERCEROS_PORTAL_TRAZA"
   (	"ID_PRCSO_EL_TRZA" NUMBER(15,0) DEFAULT "GENESYS"."SQ_SI_C_TERCEROS_PORTAL_TRAZA"."NEXTVAL" NOT NULL ENABLE,
	"FCHA_EJCCION" TIMESTAMP (6) DEFAULT systimestamp,
	"CNTDAD_RGSTROS_ELMNDOS" NUMBER(10,0),
	"RGSTROS_ELMNDOS" CLOB,
	 CONSTRAINT "SI_C_TERCEROS_PORTAL_TRAZA_ID_PRCSO_EL_TRZA_PK" PRIMARY KEY ("ID_PRCSO_EL_TRZA")
  USING INDEX  ENABLE
   ) ;

