
  CREATE TABLE "SI_D_NOVEDADES_MOTIVO_VHCLO"
   (	"CDGO_MOTIVO" VARCHAR2(3) NOT NULL ENABLE,
	"DESCRIPCION" VARCHAR2(150) NOT NULL ENABLE,
	"CDGO_NVDAD_TPO" VARCHAR2(3) NOT NULL ENABLE,
	"TRAMITE" VARCHAR2(1) NOT NULL ENABLE,
	"TIPO_AFECTADO" VARCHAR2(1) NOT NULL ENABLE,
	"DSCRPCION_ACCION" VARCHAR2(255),
	"INDCDOR_ACRDTCION" VARCHAR2(1),
	"INDCDOR_CMBIA_ESTDO" VARCHAR2(1),
	"ESTADO" VARCHAR2(1) DEFAULT 'A' NOT NULL ENABLE,
	"ADJNTO_OBLGTRIO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"DSCRPCION_ADJNTO" VARCHAR2(1000),
	 CONSTRAINT "SI_D_NVDDS_MTV_VHCL_CDG_MT_PK" PRIMARY KEY ("CDGO_MOTIVO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_D_NVDDS_MTV_VHCL_CDG_TP_FK" FOREIGN KEY ("CDGO_NVDAD_TPO")
	  REFERENCES "SI_D_NOVEDADES_TIPO" ("CDGO_NVDAD_TPO") ENABLE
   ) ;

