
  CREATE TABLE "SI_G_SLCTDS_PERMISOS_ASOCIADO"
   (	"ID_SLCTUD_PRMSOS" NUMBER,
	"CDGO_SLCTUD" VARCHAR2(50) CONSTRAINT "SI_G_SLC_PRM_CDG_SLCTD_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "SI_G_SLC_PRM_CDG_CLNT_NN" NOT NULL ENABLE,
	"NMRO_CNSCTVO" NUMBER,
	"CDNA_SJTO_IMPSTO" VARCHAR2(1000),
	"ID_SJTO" NUMBER CONSTRAINT "SI_G_SLC_PRM_ID_SJT_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "SI_G_SLC_PRM_ID_USR_NN" NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100),
	"CDGO_GSTION" VARCHAR2(1),
	"ESTDO" VARCHAR2(3) CONSTRAINT "SI_G_SLC_PRM_STD_NN" NOT NULL ENABLE,
	"FCHA_SLCTUD" TIMESTAMP (6) CONSTRAINT "SI_G_SLC_PRM_FCH_SLCTD_NN" NOT NULL ENABLE,
	"FCHA_GSTION" TIMESTAMP (6),
	 CONSTRAINT "SI_G_SLC_PRM_ID_SLC_PRM_PK" PRIMARY KEY ("ID_SLCTUD_PRMSOS")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_SLC_PRM_CDG_CLNT_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "SI_G_SLC_PRM_ID_SJT_FK" FOREIGN KEY ("ID_SJTO")
	  REFERENCES "SI_C_SUJETOS" ("ID_SJTO") ENABLE,
	 CONSTRAINT "SI_G_SLC_PRM_ID_USR_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "SI_G_SLC_PRM_STD_FK" FOREIGN KEY ("ESTDO")
	  REFERENCES "SI_D_ESTDO_SLCTUD" ("ESTDO") ENABLE
   ) ;

