
  CREATE TABLE "SI_G_NOVEDADES_PRDIO_CRGUE"
   (	"ID_NVDAD_PRDIO_CRGUE" NUMBER,
	"ID_PRCSO_CRGA" NUMBER,
	"ID_PRCSO_INTRMDIA" NUMBER,
	"NMERO_LNEA" NUMBER,
	"IDNTFCCION_SJTO" VARCHAR2(25),
	"CDGO_ESTRTO_CRGUE" VARCHAR2(3),
	"NMRO_RSLCION" VARCHAR2(50),
	"FCHA_RSLCION" TIMESTAMP (6),
	"INDCDOR_RLZDO" VARCHAR2(1) DEFAULT 'N',
	"MNSJE_RSPSTA" VARCHAR2(2000),
	"ID_SJTO_IMPSTO" NUMBER,
	"CDGO_ESTRTO" VARCHAR2(3),
	"ID_NVDAD_PRDIO_RSMEN" NUMBER,
	"INDCDOR_ERROR" VARCHAR2(1) DEFAULT 'N',
	"FCHA_APLCCION" TIMESTAMP (6),
	 CONSTRAINT "SI_G_NVD_PRD_CRG_ID_NVD_P_C_NN" CHECK ("ID_NVDAD_PRDIO_CRGUE" IS NOT NULL) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_IND_RLZDO_CK" CHECK (indcdor_rlzdo in ('S','N')) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_IDNTFCCION_NN" CHECK ("IDNTFCCION_SJTO" IS NOT NULL) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_ID_NVD_P_C_PK" PRIMARY KEY ("ID_NVDAD_PRDIO_CRGUE")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_FCHA_RSLCI_NN" CHECK ("FCHA_RSLCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_NMRO_RSLCI_NN" CHECK ("NMRO_RSLCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_NMERO_LNEA_NN" CHECK ("NMERO_LNEA" IS NOT NULL) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_IND_ERROR_CK" CHECK (indcdor_error in ('S','N')) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_ID_PRC_CRG_NN" CHECK ("ID_PRCSO_CRGA" IS NOT NULL) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_ID_PRC_ITR_NN" CHECK ("ID_PRCSO_INTRMDIA" IS NOT NULL) ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_CDGO_ESTRT_FK" FOREIGN KEY ("CDGO_ESTRTO")
	  REFERENCES "DF_S_ESTRATOS" ("CDGO_ESTRTO") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_ID_NVPRRS_FK" FOREIGN KEY ("ID_NVDAD_PRDIO_RSMEN")
	  REFERENCES "SI_G_NOVEDADES_PRDIO_RSUMEN" ("ID_NVDAD_PRDIO_RSMEN") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_CRG_ID_PRC_ITR_FK" FOREIGN KEY ("ID_PRCSO_INTRMDIA")
	  REFERENCES "ET_G_PROCESOS_INTERMEDIA" ("ID_PRCSO_INTRMDIA") ENABLE
   ) ;

