
  CREATE TABLE "SI_G_RESOLUCION_IGAC_T1"
   (	"ID_RSLCION_IGAC_T1" NUMBER DEFAULT "GENESYS"."SQ_SI_G_RESOLUCION_IGAC_T1"."NEXTVAL" CONSTRAINT "SI_G_RSL_IG_T1_ID_RSLCN_IGC_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER CONSTRAINT "SI_G_RSL_IG_T1_ID_PRCSO_CRG_NN" NOT NULL ENABLE,
	"ID_PRCSO_INTRMDIA" NUMBER CONSTRAINT "SI_G_RSL_IG_T1_ID_PRCSO_INT_NN" NOT NULL ENABLE,
	"NMERO_LNEA" NUMBER CONSTRAINT "SI_G_RSL_IG_T1_NMERO_LNEA_NN" NOT NULL ENABLE,
	"CDGO_DPRTMNTO" VARCHAR2(2) CONSTRAINT "SI_G_RSL_IG_T1_CDGO_DPRTMNT_NN" NOT NULL ENABLE,
	"CDGO_MNCPIO" VARCHAR2(3) CONSTRAINT "SI_G_RSL_IG_T1_CDGO_MNCPIO_NN" NOT NULL ENABLE,
	"RSLCION" VARCHAR2(13) CONSTRAINT "SI_G_RSL_IG_T1_RSLCION_NN" NOT NULL ENABLE,
	"RDCCION" VARCHAR2(15) CONSTRAINT "SI_G_RSL_IG_T1_RDCCION_NN" NOT NULL ENABLE,
	"TPO_TRMTE" VARCHAR2(2),
	"CLSE_MTCION" VARCHAR2(1) CONSTRAINT "SI_G_RSL_IG_T1_CLSE_MTCION_NN" NOT NULL ENABLE,
	"RFRNCIA_IGAC" VARCHAR2(25) CONSTRAINT "SI_G_RSL_IG_T1_RFRNCIA_IGAC_NN" NOT NULL ENABLE,
	"CNCLA_INSCRBE" VARCHAR2(1) CONSTRAINT "SI_G_RSL_IG_T1_CNCLA_INSCRB_NN" NOT NULL ENABLE,
	"TPO_RGSTRO" NUMBER(1,0) CONSTRAINT "SI_G_RSL_IG_T1_TPO_RGSTRO_NN" NOT NULL ENABLE,
	"NMRO_ORDEN" VARCHAR2(3),
	"TTAL_RGSTRO" VARCHAR2(3),
	"NMBRE_PRPTRIO" VARCHAR2(100),
	"ESTDO_CVIL" VARCHAR2(1),
	"TPO_DCMNTO" VARCHAR2(1),
	"NMRO_DCMNTO" VARCHAR2(12),
	"DRCCION" VARCHAR2(100),
	"CMNA" VARCHAR2(1),
	"DSTNO_ECNMCO" VARCHAR2(2),
	"AREA_TRRNO" NUMBER(15,0),
	"AREA_CNSTRDA" NUMBER(6,0),
	"AVLUO_CTSTRAL" NUMBER(16,0),
	"VGNCIA_IGAC" VARCHAR2(8),
	"NMRO_PRDIAL_ANTRIOR" VARCHAR2(15),
	"APLCDA" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "SI_G_RSL_IG_T1_APLCDA_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA_PDRE" NUMBER,
	"ID_RSLCION_APLCDA" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER,
	"ID_USRIO_RLQDA" NUMBER,
	"LTTUD" VARCHAR2(500),
	"LNGTUD" VARCHAR2(500),
	"PRCNTJE_PRTCPCION" NUMBER(5,2),
	"FCHA_FRMZA" DATE,
	 CONSTRAINT "SI_G_RSL_IG_T1_TPO_RGSTRO_CK" CHECK ( tpo_rgstro = 1 ) ENABLE,
	 CONSTRAINT "SI_G_RSL_IG_T1_APLCDA_CK" CHECK (aplcda in ( 'S' , 'N' , 'R' )) ENABLE,
	 CONSTRAINT "SI_G_RSL_IG_T1_ID_RSLCN_IGC_PK" PRIMARY KEY ("ID_RSLCION_IGAC_T1")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_RSL_IG_T1_ID_PRCSO_INT_FK" FOREIGN KEY ("ID_PRCSO_INTRMDIA")
	  REFERENCES "ET_G_PROCESOS_INTERMEDIA" ("ID_PRCSO_INTRMDIA") ENABLE,
	 CONSTRAINT "SI_G_RSL_IG_T1_ID_SJT_IMPST_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "SI_G_RSL_IG_T1_ID_RSLCN_APL_FK" FOREIGN KEY ("ID_RSLCION_APLCDA")
	  REFERENCES "SI_G_RESOLUCION_APLICADA" ("ID_RSLCION_APLCDA") ENABLE,
	 CONSTRAINT "SI_G_RSL_IG_T1_ID_USR_RLQ_FK" FOREIGN KEY ("ID_USRIO_RLQDA")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

