
  CREATE TABLE "SI_G_NOVEDADES_PRDIO_RSUMEN"
   (	"ID_NVDAD_PRDIO_RSMEN" NUMBER CONSTRAINT "SI_G_NVD_PRD_RSM_ID_NVD_P_R_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER CONSTRAINT "SI_G_NVD_PRD_RSM_ID_PRC_CRG_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "SI_G_NVD_PRD_RSM_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "SI_G_NVD_PRD_RSM_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "SI_G_NVD_PRD_RSM_ID_IMP_SMP_NN" NOT NULL ENABLE,
	"FCHA_INCIO" TIMESTAMP (6),
	"FCHA_FIN" TIMESTAMP (6),
	"ID_USRIO" NUMBER CONSTRAINT "SI_G_NVD_PRD_RSM_ID_USRIO_NN" NOT NULL ENABLE,
	"NMRO_RGSTRO" NUMBER,
	"NMRO_CMBIO_ESTRTOS" NUMBER,
	 CONSTRAINT "SI_G_NVD_PRD_RSM_ID_NVD_P_R_PK" PRIMARY KEY ("ID_NVDAD_PRDIO_RSMEN")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_RSM_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_RSM_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_RSM_ID_IMP_SMP_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_RSM_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

