
  CREATE TABLE "SI_G_NOVEDADES_PERSONA"
   (	"ID_NVDAD_PRSNA" NUMBER DEFAULT "GENESYS"."SQ_SI_G_NOVEDADES_PERSONA"."NEXTVAL" CONSTRAINT "SI_G_NVDDS_PRSN_ID_NVD_PRSN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "SI_G_NVDDS_PRSN_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "SI_G_NVDDS_PRSN_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER,
	"OBSRVCION" VARCHAR2(4000) CONSTRAINT "SI_G_NVDDS_PRSN_OBSRVCION_NN" NOT NULL ENABLE,
	"CDGO_NVDAD_TPO" VARCHAR2(3) CONSTRAINT "SI_G_NVDDS_PRSN_CDGO_NVD_TP_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER,
	"ID_INSTNCIA_FLJO_PDRE" NUMBER,
	"ID_SLCTUD" NUMBER,
	"CDGO_NVDAD_PRSNA_ESTDO" VARCHAR2(3) CONSTRAINT "SI_G_NVDDS_PRSN_CD_NV_PS_ES_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "SI_G_NVDDS_PRSN_FCHA_RGSTRO_NN" NOT NULL ENABLE,
	"ID_USRIO_RGSTRO" NUMBER CONSTRAINT "SI_G_NVDDS_PRSN_ID_USRIO_NN" NOT NULL ENABLE,
	"FCHA_APLCO" TIMESTAMP (6) DEFAULT NULL,
	"ID_USRIO_APLCO" NUMBER,
	"FCHA_RCHZO" TIMESTAMP (6) DEFAULT NULL,
	"ID_USRIO_RCHZO" NUMBER,
	"ID_FLJO_TREA" NUMBER,
	"OBSRVCION_RCHZO" VARCHAR2(1000),
	"ID_ACTO" NUMBER,
	"DCMNTO_HTML" CLOB,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_NVD_PRSN_PK" PRIMARY KEY ("ID_NVDAD_PRSNA")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO_RGSTRO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_IMP_SBMPT_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_CD_NV_PS_ES_FK" FOREIGN KEY ("CDGO_NVDAD_PRSNA_ESTDO")
	  REFERENCES "SI_D_NOVEDADES_PRSNA_ESTDO" ("CDGO_NVDAD_PRSNA_ESTDO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_FLJO_TREA_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_ACTO_FK" FOREIGN KEY ("ID_ACTO")
	  REFERENCES "GN_G_ACTOS" ("ID_ACTO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_CDGO_NVD_TP_FK" FOREIGN KEY ("CDGO_NVDAD_TPO")
	  REFERENCES "SI_D_NOVEDADES_TIPO" ("CDGO_NVDAD_TPO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_SJTO_IMP_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_USRI_RCH_FK" FOREIGN KEY ("ID_USRIO_RCHZO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_INS_FJ_PD_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO_PDRE")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_USRI_APLC_FK" FOREIGN KEY ("ID_USRIO_APLCO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_INST_FLJO_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "SI_G_NVDDS_PRSN_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE
   ) ;

