
  CREATE TABLE "SI_G_RSLCION_IGAC_MNUAL_DCRTS"
   (	"ID_RSLCION_IGAC_MNUAL_DCRTS" NUMBER NOT NULL ENABLE,
	"AVLUO_CTSTRAL" NUMBER(16,2) NOT NULL ENABLE,
	"FECHA_VGNCIA_FSCAL" DATE NOT NULL ENABLE,
	"ID_RSLCION_IGAC_MNUAL_DTLLE" NUMBER NOT NULL ENABLE,
	"DCRTO" VARCHAR2(20) NOT NULL ENABLE,
	 PRIMARY KEY ("ID_RSLCION_IGAC_MNUAL_DCRTS")
  USING INDEX  ENABLE
   ) ;

