
  CREATE TABLE "SI_G_NOVEDADES_PREDIAL_T5"
   (	"ID_NVDAD_PRDIAL_T5" NUMBER CONSTRAINT "SI_G_NVD_PRD_T5_ID_NVD_PRD_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER CONSTRAINT "SI_G_NVD_PRD_T5_ID_PRCSO_CRG_NN" NOT NULL ENABLE,
	"ID_PRCSO_INTRMDIA" NUMBER CONSTRAINT "SI_G_NVD_PRD_T5_ID_PRCSO_INT_NN" NOT NULL ENABLE,
	"NMERO_LNEA" NUMBER CONSTRAINT "SI_G_NVD_PRD_T5_NMRO_LNEA_NN" NOT NULL ENABLE,
	"CDGO_DPRTMNTO" VARCHAR2(2) CONSTRAINT "SI_G_NVD_PRD_T5_CDGO_DPRTMNT_NN" NOT NULL ENABLE,
	"CDGO_MNCPIO" VARCHAR2(3) CONSTRAINT "SI_G_NVD_PRD_T5_CDGO_MNCPIO_NN" NOT NULL ENABLE,
	"RFRNCIA_IGAC_NVA" VARCHAR2(25) CONSTRAINT "SI_G_NVD_PRD_T5_RFRNCIA_IGAC_NN" NOT NULL ENABLE,
	"TPO_RGSTRO" NUMBER(1,0) CONSTRAINT "SI_G_NVD_PRD_T5_TPO_RGSTRO_NN" NOT NULL ENABLE,
	"NMRO_ORDEN" VARCHAR2(3),
	"TTAL_RGSTRO" VARCHAR2(3),
	"CDGO_NVDAD" NUMBER,
	"RFRNCIA_IGAC_ACTUAL" VARCHAR2(25),
	"APLCDA" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "SI_G_NVD_PRD_T5_APLCDA_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER,
	"ID_USRIO" NUMBER,
	"FCHA_PRCSO" TIMESTAMP (6),
	 CONSTRAINT "SI_G_NVD_PRD_T5_ID_NVD_PRD_PK" PRIMARY KEY ("ID_NVDAD_PRDIAL_T5")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_T5_ID_PRCSO_INT_FK" FOREIGN KEY ("ID_PRCSO_INTRMDIA")
	  REFERENCES "ET_G_PROCESOS_INTERMEDIA" ("ID_PRCSO_INTRMDIA") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_T5_CDGO_NVDAD_FK" FOREIGN KEY ("CDGO_NVDAD")
	  REFERENCES "DF_C_NOVEDADES_PREDIO_CODGO" ("CDGO_NVDAD") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_T5_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

