
  CREATE TABLE "SI_G_SOLICITUDES_ASOCIADOS"
   (	"ID_SLCTUD_ASCDO" NUMBER,
	"CDGO_SLCTUD" VARCHAR2(50) CONSTRAINT "SI_G_SLCTD_ASCD_CDGO_SLCTD_NN" NOT NULL ENABLE,
	"NMRO_CNSCTVO" NUMBER,
	"CDGO_CLNTE" NUMBER CONSTRAINT "SI_G_SLCTD_ASCD_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_SJTO" NUMBER CONSTRAINT "SI_G_SLCTD_ASCD_ID_SJT_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "SI_G_SLCTD_ASCD_ID_USRIO_NN" NOT NULL ENABLE,
	"EMAIL" VARCHAR2(100),
	"ESTDO" VARCHAR2(3) CONSTRAINT "SI_G_SLCTD_ASCD_ESTDO_NN" NOT NULL ENABLE,
	"FCHA_SLCTUD" TIMESTAMP (6) CONSTRAINT "SI_G_SLCTD_ASCD_FCHA_SLCTD_NN" NOT NULL ENABLE,
	"FCHA_GSTION" TIMESTAMP (6),
	 CONSTRAINT "SI_G_SLCTD_ASCD_ID_SLC_ASCD_PK" PRIMARY KEY ("ID_SLCTUD_ASCDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_SLCTD_ASCD_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "SI_G_SLCTD_ASCD_ID_SJT_FK" FOREIGN KEY ("ID_SJTO")
	  REFERENCES "SI_C_SUJETOS" ("ID_SJTO") ENABLE,
	 CONSTRAINT "SI_G_SLCTD_ASCD_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "SI_G_SLCTD_ASCD_ESTDO_FK" FOREIGN KEY ("ESTDO")
	  REFERENCES "SI_D_ESTDO_SLCTUD" ("ESTDO") ENABLE
   ) ;

