
  CREATE TABLE "SI_G_RSLCION_IGAC_MNUAL"
   (	"ID_RSLCION_IGAC_MNUAL" NUMBER NOT NULL ENABLE,
	"RSLCION_IGAC" VARCHAR2(50) NOT NULL ENABLE,
	"RDCCION_IGAC" VARCHAR2(50) NOT NULL ENABLE,
	"FCHA_RSLCION_IGAC" DATE NOT NULL ENABLE,
	"TPO_TRMTE" NUMBER(5,0) NOT NULL ENABLE,
	"CLSE_MTCION" NUMBER(5,0) NOT NULL ENABLE,
	"ID_USRIO_DGTA" NUMBER(10,0),
	"FCHA_INGRSA_RSLCION" TIMESTAMP (6) DEFAULT systimestamp,
	 PRIMARY KEY ("ID_RSLCION_IGAC_MNUAL")
  USING INDEX  ENABLE
   ) ;

