
  CREATE TABLE "SI_G_NOVEDADES_PREDIAL_T6"
   (	"ID_NVDAD_PRDIAL_T6" NUMBER CONSTRAINT "SI_G_NVD_PRD_T6_ID_NVD_PRD_NN" NOT NULL ENABLE,
	"ID_PRCSO_CRGA" NUMBER CONSTRAINT "SI_G_NVD_PRD_T6_ID_PRCSO_CRG_NN" NOT NULL ENABLE,
	"ID_PRCSO_INTRMDIA" NUMBER CONSTRAINT "SI_G_NVD_PRD_T6_ID_PRCSO_INT_NN" NOT NULL ENABLE,
	"NMERO_LNEA" NUMBER CONSTRAINT "SI_G_NVD_PRD_T6_NMRO_LNEA_NN" NOT NULL ENABLE,
	"CDGO_DPRTMNTO" VARCHAR2(2) CONSTRAINT "SI_G_NVD_PRD_T6_CDGO_DPRTMNT_NN" NOT NULL ENABLE,
	"CDGO_MNCPIO" VARCHAR2(3) CONSTRAINT "SI_G_NVD_PRD_T6_CDGO_MNCPIO_NN" NOT NULL ENABLE,
	"RFRNCIA_IGAC" VARCHAR2(25) CONSTRAINT "SI_G_NVD_PRD_T6_RFRNCIA_IGAC_NN" NOT NULL ENABLE,
	"TPO_RGSTRO" NUMBER(1,0) CONSTRAINT "SI_G_NVD_PRD_T6_TPO_RGSTRO_NN" NOT NULL ENABLE,
	"CDGO_NVDAD" NUMBER,
	 CONSTRAINT "SI_G_NVD_PRD_T6_ID_NVD_PRD_PK" PRIMARY KEY ("ID_NVDAD_PRDIAL_T6")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_NVD_PRD_T6_ID_PRCSO_INT_FK" FOREIGN KEY ("ID_PRCSO_INTRMDIA")
	  REFERENCES "ET_G_PROCESOS_INTERMEDIA" ("ID_PRCSO_INTRMDIA") ENABLE
   ) ;

