
  CREATE TABLE "SI_G_NOVEDADES_PRSNA_ADJNTO"
   (	"ID_NVDAD_PRSNA_ADJNTO" NUMBER DEFAULT "GENESYS"."SQ_SI_G_NOVEDADES_PRSNA_ADJNTO"."NEXTVAL" CONSTRAINT "SI_G_NVD_PRS_AD_ID_NV_PS_AD_NN" NOT NULL ENABLE,
	"ID_NVDAD_PRSNA" NUMBER CONSTRAINT "SI_G_NVD_PRS_AD_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"FILE_BLOB" BLOB CONSTRAINT "SI_G_NVD_PRS_AD_FILE_BLOB_NN" NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(255),
	"FILE_MIMETYPE" VARCHAR2(100),
	"USER_DGTA" VARCHAR2(100) CONSTRAINT "SI_G_NVD_PRS_AD_USER_DGT_NN" NOT NULL ENABLE,
	"FCHA_DGTA" TIMESTAMP (6) CONSTRAINT "SI_G_NVD_PRS_AD_FCHA_DGT_NN" NOT NULL ENABLE,
	"USER_MDFCA" VARCHAR2(100),
	"FCHA_MDFCA" TIMESTAMP (6),
	"ID_NVDAD_PRSNA_ADJNTO_TPO" NUMBER,
	 CONSTRAINT "SI_G_NVD_PRS_AD_ID_NV_PS_AD_PK" PRIMARY KEY ("ID_NVDAD_PRSNA_ADJNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_G_NVD_PRS_AD_ID_NVDAD_PR_FK" FOREIGN KEY ("ID_NVDAD_PRSNA_ADJNTO_TPO")
	  REFERENCES "SI_D_NVDDES_PRSNA_ADJNTO_TP" ("ID_NVDAD_PRSNA_ADJNTO_TPO") ENABLE,
	 CONSTRAINT "SI_G_NVD_PRS_AD_CDGO_CLNTE_FK" FOREIGN KEY ("ID_NVDAD_PRSNA")
	  REFERENCES "SI_G_NOVEDADES_PERSONA" ("ID_NVDAD_PRSNA") ENABLE
   )
 LOB ("FILE_BLOB") STORE AS SECUREFILE "SYS_LOB0000135085C00003$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

