
  CREATE TABLE "SI_H_SUJETOS_IMPUESTO"
   (	"ID_SJTO_IMPSTO_HSTRCO" NUMBER DEFAULT "GENESYS"."SQ_SI_H_SUJETOS_IMPUESTO"."NEXTVAL" CONSTRAINT "SI_H_SJTO_ID_SJTO_IMPSTO_HS_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "SI_H_SJTO_IMPST_ID_SJTO_IMP_NN" NOT NULL ENABLE,
	"ID_SJTO" NUMBER CONSTRAINT "SI_H_SJTO_IMPST_ID_SJTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "SI_H_SJTO_IMPST_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_SJTO_ESTDO" NUMBER CONSTRAINT "SI_H_SJTO_IMPST_ID_SJT_EST_NN" NOT NULL ENABLE,
	"ESTDO_BLQDO" VARCHAR2(1) CONSTRAINT "SI_H_SJTO_IMPST_ESTDO_BLQDO_NN" NOT NULL ENABLE,
	"ID_PAIS_NTFCCION" NUMBER,
	"ID_DPRTMNTO_NTFCCION" NUMBER,
	"ID_MNCPIO_NTFCCION" NUMBER,
	"DRCCION_NTFCCION" VARCHAR2(100),
	"EMAIL" VARCHAR2(320),
	"TLFNO" VARCHAR2(50),
	"FCHA_RGSTRO" TIMESTAMP (6) CONSTRAINT "SI_H_SJTO_IMPST_FCHA_RGSTRA_NN" NOT NULL ENABLE,
	"USRIO_RGSTRO" VARCHAR2(100) CONSTRAINT "SI_H_SJTO_IMPST_USRIO_RGSTR_NN" NOT NULL ENABLE,
	"ID_NVDAD" NUMBER,
	 CONSTRAINT "SI_H_SJTO_IMPST_ESTDO_BLQDO_CK" CHECK (estdo_blqdo in ('N','S')) ENABLE,
	 CONSTRAINT "SI_H_SJTO_ID_SJTO_IMPSTO_HS_PK" PRIMARY KEY ("ID_SJTO_IMPSTO_HSTRCO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_H_SJTO_IMPST_ID_SJTO_IMP_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") DISABLE,
	 CONSTRAINT "SI_H_SJTO_IMPST_ID_SJT_EST_FK" FOREIGN KEY ("ID_SJTO_ESTDO")
	  REFERENCES "DF_S_SUJETOS_ESTADO" ("ID_SJTO_ESTDO") ENABLE,
	 CONSTRAINT "SI_H_SJTO_IMPST_ID_DPRT_NTF_FK" FOREIGN KEY ("ID_DPRTMNTO_NTFCCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "SI_H_SJTO_IMPST_ID_PAIS_NTF_FK" FOREIGN KEY ("ID_PAIS_NTFCCION")
	  REFERENCES "DF_S_PAISES" ("ID_PAIS") ENABLE,
	 CONSTRAINT "SI_H_SJTO_IMPST_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "SI_H_SJTO_IMPST_ID_MNC_NTFC_FK" FOREIGN KEY ("ID_MNCPIO_NTFCCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE,
	 CONSTRAINT "SI_H_SJTO_IMPST_ID_SJTO_FK" FOREIGN KEY ("ID_SJTO")
	  REFERENCES "SI_C_SUJETOS" ("ID_SJTO") DISABLE
   ) ;

