
  CREATE TABLE "SI_I_AUDT_ESTADO_ASOCIADO"
   (	"ID_AUDT_ESTDO" NUMBER,
	"ID_SLCTUD_PRMSOS" NUMBER CONSTRAINT "SI_I_AUDT_STD_ID_SLC_PRMS_NN" NOT NULL ENABLE,
	"ID_SJTO_ASCDO" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "SI_I_AUDT_STD_ID_SJT_IMPS_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "SI_I_AUDT_STD_ID_USRIO_NN" NOT NULL ENABLE,
	"CDGO_GSTION" VARCHAR2(1),
	"FCHA" TIMESTAMP (6) CONSTRAINT "SI_I_AUDT_STD_FCHA_SLCTD_NN" NOT NULL ENABLE,
	 CONSTRAINT "SI_I_AUD_STD_ID_AUD_STDO_PK" PRIMARY KEY ("ID_AUDT_ESTDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_I_AUDT_STD_ID_LCT_PRMS_FK" FOREIGN KEY ("ID_SLCTUD_PRMSOS")
	  REFERENCES "SI_G_SLCTDS_PERMISOS_ASOCIADO" ("ID_SLCTUD_PRMSOS") ENABLE,
	 CONSTRAINT "SI_I_AUDT_STD_ID_SJT_IMPS_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "SI_I_AUDT_STD_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

