
  CREATE TABLE "SI_I_SUJETOS_SUCURSAL"
   (	"ID_SJTO_SCRSAL" NUMBER CONSTRAINT "SI_I_SJT_SCRSL_ID_SJT_SCRSL_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "SI_I_SJT_SCRSL_ID_SJTO_IMPS_NN" NOT NULL ENABLE,
	"ID_SJTO" NUMBER CONSTRAINT "SI_I_SJT_SCRSL_ID_SJTO_NN" NOT NULL ENABLE,
	"CDGO_SCRSAL" VARCHAR2(10) CONSTRAINT "SI_I_SJT_SCRSL_CDGO_SCRSAL_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(100) CONSTRAINT "SI_I_SJT_SCRSL_NMBRE_NN" NOT NULL ENABLE,
	"DRCCION" VARCHAR2(100),
	"ID_DPRTMNTO_NTFCCION" NUMBER,
	"ID_MNCPIO_NTFCCION" NUMBER,
	"TLFNO" NUMBER,
	"CLLAR" NUMBER,
	"EMAIL" VARCHAR2(100),
	"ACTVO" VARCHAR2(1) DEFAULT 'S',
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT sysdate NOT NULL ENABLE,
	"MTRCLA" VARCHAR2(10),
	 CONSTRAINT "SI_I_SJT_SCRSL_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "SI_I_SJT_SCRSL_ID_SJT_SCRSL_PK" PRIMARY KEY ("ID_SJTO_SCRSAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_I_SJTO_SCRSL_SJTO_IMPS_SCRS" UNIQUE ("ID_SJTO_IMPSTO", "CDGO_SCRSAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_I_SJT_SCRSL_ID_DPRTM_FK" FOREIGN KEY ("ID_DPRTMNTO_NTFCCION")
	  REFERENCES "DF_S_DEPARTAMENTOS" ("ID_DPRTMNTO") ENABLE,
	 CONSTRAINT "SI_I_SJT_SCRSL_ID_SJTO_IMPS_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "SI_I_SJT_SCRSL_ID_SJTO_FK" FOREIGN KEY ("ID_SJTO")
	  REFERENCES "SI_C_SUJETOS" ("ID_SJTO") ENABLE,
	 CONSTRAINT "SI_I_SJT_SCRSL_ID_MNCPIO_FK" FOREIGN KEY ("ID_MNCPIO_NTFCCION")
	  REFERENCES "DF_S_MUNICIPIOS" ("ID_MNCPIO") ENABLE
   ) ;

