
  CREATE TABLE "SI_I_SUJETOS_ASOCIADOS"
   (	"ID_SJTO_ASCDO" NUMBER,
	"CDGO_CLNTE" NUMBER CONSTRAINT "SI_I_SJT_ASCD_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "SI_I_SJT_ASCD_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER CONSTRAINT "SI_I_SJT_ASCD_ID_SJT_IMPS_NN" NOT NULL ENABLE,
	"ID_USRIO" NUMBER CONSTRAINT "SI_I_SJT_ASCD_ID_USRIO_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "SI_I_SJT_ASCD_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "SI_I_SJT_ASCD_ID_SJT_ASCD_PK" PRIMARY KEY ("ID_SJTO_ASCDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SI_I_SJT_ASCD_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "SI_I_SJT_ASCD_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "SI_I_SJT_ASCD_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "SI_I_SJT_ASCD_ID_SJT_IMPS_FK" FOREIGN KEY ("ID_SJTO_IMPSTO")
	  REFERENCES "SI_I_SUJETOS_IMPUESTO" ("ID_SJTO_IMPSTO") ENABLE,
	 CONSTRAINT "SI_I_SJT_ASCD_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

