
  CREATE GLOBAL TEMPORARY TABLE "SI_T_PREDIOS_SECTOR"
   (	"CDGO_ESTRTO" VARCHAR2(5),
	"SCTOR" VARCHAR2(4),
	"ID_PRDIO_DSTNO" NUMBER,
	 CONSTRAINT "SI_C_PRDIO_SCTOR_ID_DSTNO_UN" UNIQUE ("SCTOR", "ID_PRDIO_DSTNO") ENABLE
   ) ON COMMIT PRESERVE ROWS ;

