
  CREATE GLOBAL TEMPORARY TABLE "SI_T_PREDIOS_MANZANA"
   (	"CDGO_ESTRTO" VARCHAR2(5),
	"MNZANA" VARCHAR2(8),
	"ID_PRDIO_DSTNO" NUMBER,
	 CONSTRAINT "SI_C_PRDIO_MNZN_ID_DSTNO_UN" UNIQUE ("MNZANA", "ID_PRDIO_DSTNO") ENABLE
   ) ON COMMIT PRESERVE ROWS ;

