
  CREATE TABLE "TEMP_AJUSTES_MASIVOS"
   (	"ID_SJTO_IMPSTO" NUMBER,
	"IDNTFCCION" VARCHAR2(25),
	"VGNCIA" NUMBER,
	"PRDO" NUMBER,
	"DSCNTO" NUMBER,
	"PRCSDO" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE
   ) ;

