
  CREATE TABLE "TEMP_DOC"
   (	"NMERO_LNEA" NUMBER,
	"CDGO_CLNTE" NUMBER(15,0),
	"ID_IMPSTO" NUMBER(15,0),
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0),
	"ID_SJTO_IMPSTO" NUMBER(15,0),
	"CDGO_EAN" VARCHAR2(30),
	"FCHA_RCDO" TIMESTAMP (6),
	"NMRO_DCMNTO" NUMBER,
	"VLOR_RCDO" NUMBER,
	"CDGO_RCDO_ORGN_TPO" VARCHAR2(3),
	"ID_ORGEN" NUMBER,
	"ID_RCDO" NUMBER,
	"INDCDOR_RLZDO" VARCHAR2(1),
	"CDGO_TPO_ASBNCRIA" VARCHAR2(6),
	"MNSJE_RSPSTA" VARCHAR2(4000),
	"ID_PRCSO_CRGA" NUMBER
   ) ;

