
  CREATE TABLE "TEMP_PAGOS_CA_SA_IM"
   (	"IMPUESTO" VARCHAR2(20),
	"FCHA_RCDO" DATE,
	"NMRO_DCMNTO" NUMBER NOT NULL ENABLE,
	"IDNTFCCION" VARCHAR2(25),
	"NMBRE_RZON_SCIAL" VARCHAR2(200),
	"IDNTFCCION_SJTO" VARCHAR2(25) NOT NULL ENABLE,
	"PAGO_IMPSTO" NUMBER,
	"PAGO_SANCION" NUMBER,
	"PAGO_INTERES" NUMBER,
	"ID_SJTO_IMPSTO" NUMBER(15,0) NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0),
	"ID_DCMNTO" NUMBER NOT NULL ENABLE,
	"CDGO_RCDO_ORGN_TPO" VARCHAR2(3) NOT NULL ENABLE,
	 CONSTRAINT "TEMP_PAG_CA_SA_IM_PK" PRIMARY KEY ("ID_DCMNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "TEMP_PAG_CA_SA_IM_UK" UNIQUE ("ID_DCMNTO", "ID_IMPSTO", "ID_SJTO_IMPSTO")
  USING INDEX  ENABLE
   ) ;

