
  CREATE TABLE "TEMP_CARTERA"
   (	"ID_MVMNTO_FNCRO" NUMBER(*,0) NOT NULL ENABLE,
	"ID_SJTO_IMPSTO" NUMBER(15,0) NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER(15,0) NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER(15,0) NOT NULL ENABLE,
	"VGNCIA" NUMBER(4,0) NOT NULL ENABLE,
	"PRDO" NUMBER(2,0) NOT NULL ENABLE,
	"ID_PRDO" NUMBER(15,0) NOT NULL ENABLE,
	"VLOR_SLDO_CPTAL" NUMBER,
	"CDGO_MVMNTO_ORGN" VARCHAR2(3) NOT NULL ENABLE,
	"ID_ORGEN" NUMBER NOT NULL ENABLE,
	"NMBRE_IMPSTO" VARCHAR2(200),
	"NMBRE_IMPSTO_SBMPSTO" VARCHAR2(50) NOT NULL ENABLE,
	"DSCRPCION_MVNT_FNCRO_ESTDO" VARCHAR2(50) NOT NULL ENABLE,
	"ID_CNCPTO" NUMBER(15,0) NOT NULL ENABLE,
	"CDGO_CNCPTO" VARCHAR2(3) NOT NULL ENABLE,
	"DSCRPCION_CNCPTO" VARCHAR2(100) NOT NULL ENABLE,
	"INTERES" NUMBER
   ) ;

