
  CREATE TABLE "TEMP_FECHAS_MATRICULA_SGI"
   (	"PLACA" VARCHAR2(10),
	"FCHA_MTRCLA" DATE,
	"TPO_FRMLRIO" VARCHAR2(2),
	 CONSTRAINT "TEMP_FE_MA_SGI_PK" PRIMARY KEY ("PLACA")
  USING INDEX  ENABLE
   ) ;

