
  CREATE TABLE "TEMP_RECAUDOS_DESCONOCIDOS"
   (	"ID" NUMBER,
	"BANCO" VARCHAR2(50),
	"CUENTA" VARCHAR2(20),
	"VALOR" NUMBER,
	"FECHA" DATE,
	"REFERENCIA" VARCHAR2(50),
	"OBSERVACION" VARCHAR2(150)
   ) ;

