
  CREATE TABLE "TEMP_REQ_INFORMCION_2022"
   (	"ID_SJTO_IMPSTO" NUMBER,
	"IDNTFCCION" VARCHAR2(50),
	"RZON_SCIAL" VARCHAR2(100),
	"DRRCION" VARCHAR2(100),
	"EMAIL" VARCHAR2(100),
	"VGNCIAS" VARCHAR2(100),
	"TIPO" VARCHAR2(100),
	"DCMNTO" CLOB,
	"BLOB" BLOB,
	"ENVIO_EMAIL" VARCHAR2(1),
	"FCHA_ENVIO" DATE,
	"NMRO_ACTO" NUMBER,
	"FCHA_ACTO" DATE,
	"PRGRMA" VARCHAR2(100)
   ) ;

