
  CREATE TABLE "TEMP_INFO_DIAN_ICA"
   (	"TPO_DCMNTO" VARCHAR2(2),
	"IDNTFCCION" VARCHAR2(50),
	"PRMER_APLLDO" VARCHAR2(50),
	"SGNDO_APLLDO" VARCHAR2(50),
	"PRMER_NMBRE" VARCHAR2(50),
	"OTROS_NMBRES" VARCHAR2(50),
	"RZON_SCIAL" VARCHAR2(100),
	"DRCCION" VARCHAR2(100),
	"CDGO_DPRTMNTO" NUMBER,
	"CDGO_MNCPIO" NUMBER,
	"TLFNO" VARCHAR2(100),
	"EMAIL" VARCHAR2(100),
	"ACTVDAD_PRNCPAL" VARCHAR2(300),
	"ACTVDAD_SCNDRIA" VARCHAR2(100),
	"NMRO_ESTBLCMNTOS" NUMBER,
	"INGRSOS_BRTOS_MNCPIO" NUMBER,
	"INGRSOS_BRTOS_FRA" NUMBER,
	"INGRSOS_GRVBLES_MNCPIO" NUMBER,
	"ICA" NUMBER,
	"ICA_PGDO" NUMBER,
	"AYT" NUMBER,
	"AYT_PGDO" NUMBER,
	"BOM" NUMBER,
	"BOM_PGDO" NUMBER,
	"TPO_ACTVDAD" VARCHAR2(100)
   ) ;

