
  CREATE TABLE "TEMP_UNIFICACION_PLACAS"
   (	"NIT" VARCHAR2(20),
	"RZON_SCIAL" VARCHAR2(100),
	"NMRO_PLCAS" NUMBER,
	"PLCAS" VARCHAR2(250),
	"DCLRCNES" VARCHAR2(400),
	"NMRO_PLCAS_DLCRCNES" NUMBER,
	"PLCA_UNFCDA" VARCHAR2(20),
	"ESTDO" VARCHAR2(1) DEFAULT 'N',
	"DSCRPCION_APLCCION" VARCHAR2(100),
	 CONSTRAINT "TMP_UNI_PLA_PK" PRIMARY KEY ("NIT")
  USING INDEX  ENABLE
   ) ;

