
  CREATE TABLE "TI_D_PRUEBA_TIPO"
   (	"ID_PRBA_TPO" NUMBER DEFAULT "GENESYS"."SQ_TI_D_PRUEBA_TIPO"."NEXTVAL" CONSTRAINT "TI_D_PRUEBA_TPO_ID_PRBA_TPO_NN" NOT NULL ENABLE,
	"CDGO_PRBA_TPO" VARCHAR2(3) CONSTRAINT "TI_D_PRUEBA_TPO_CD_PRBA_TPO_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "TI_D_PRUEBA_TPO_DS_PRBA_TPO_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "TI_D_PRUEBA_TPO_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "TI_D_PRUEBA_TPO_ID_PRBA_TPO_PK" PRIMARY KEY ("ID_PRBA_TPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_D_PRUEBA_TPO_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE
   ) ;

