
  CREATE TABLE "TI_D_CATEGORIA_DESPLIEGUE"
   (	"ID_CTGRIA_DSPLGUE" NUMBER CONSTRAINT "TI_D_CTGR_DSPL_ID_CTGR_DSPL_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(1000) CONSTRAINT "TI_D_CTGR_DSPL_NMBRE_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(2000),
	 CONSTRAINT "TI_D_CTGR_DSPL_ID_CTGR_DSPL_PK" PRIMARY KEY ("ID_CTGRIA_DSPLGUE")
  USING INDEX  ENABLE
   ) ;

