
  CREATE TABLE "TI_D_RESPUESTA_QA_ESTADO"
   (	"CDGO_RSPSTA_QA_ESTDO" VARCHAR2(3) CONSTRAINT "TI_D_RS_QA_EST_CDGO_ERR_EST_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(500) CONSTRAINT "TI_D_RS_QA_EST_DSCRPCION_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "TI_D_RS_QA_EST_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "TI_D_RS_QA_EST_CDGO_ERR_EST_PK" PRIMARY KEY ("CDGO_RSPSTA_QA_ESTDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_D_RS_QA_EST_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE
   ) ;

