
  CREATE TABLE "TI_D_SOFTWARE_FASE"
   (	"ID_SFTWRE_FSE" NUMBER CONSTRAINT "TI_D_SFTWRE_FSE_ID_SFTWR_FS_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(1000) CONSTRAINT "TI_D_SFTWRE_FSE_NMBRE_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(2000),
	 CONSTRAINT "TI_D_SFTWRE_FSE_ID_SFTWR_FS_PK" PRIMARY KEY ("ID_SFTWRE_FSE")
  USING INDEX  ENABLE
   ) ;

