
  CREATE TABLE "TI_D_REQUERIMIENTO_ITEM"
   (	"ID_RQRMNTO_ITEM" NUMBER DEFAULT "GENESYS"."SQ_TI_D_REQUERIMIENTO_ITEM"."NEXTVAL" CONSTRAINT "TI_D_RQRMNTO_ITM_ID_RQR_ITM_NN" NOT NULL ENABLE,
	"CDGO_RQRMNTO_ITEM" VARCHAR2(3) CONSTRAINT "TI_D_RQRMNTO_ITM_CD_RQR_ITM_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(100) CONSTRAINT "TI_D_RQRMNTO_ITM_DS_RQR_ITM_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) CONSTRAINT "TI_D_RQRMNTO_ITM_ACTVO_NN" NOT NULL ENABLE,
	"ID_RQRMNTO_TPO" NUMBER CONSTRAINT "TI_D_RQRMNTO_ITM_ID_RQRMNTO_NN" NOT NULL ENABLE,
	 CONSTRAINT "TI_D_RQRMNTO_ITM_ACTVO_CK" CHECK (actvo in ('S', 'N')) ENABLE,
	 CONSTRAINT "TI_D_RQRMNTO_ITM_ID_RQR_ITM_PK" PRIMARY KEY ("ID_RQRMNTO_ITEM")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_D_RQRMNTO_ITM_ID_RQRMNTO_FK" FOREIGN KEY ("ID_RQRMNTO_TPO")
	  REFERENCES "TI_D_REQUERIMIENTO_TIPO" ("ID_RQRMNTO_TPO") ENABLE
   ) ;

