
  CREATE TABLE "TI_D_PAQUETES_ESTADO"
   (	"NMBRE" VARCHAR2(1000) CONSTRAINT "TI_PQTE_ESTD_NMBRE_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(2000),
	"ACTVO" VARCHAR2(1) DEFAULT 'S',
	"CDGO_ESTDO" VARCHAR2(2) NOT NULL ENABLE,
	 CONSTRAINT "TI_PQTE_CDGO_ESTD_PQT_ESTD_PK" PRIMARY KEY ("CDGO_ESTDO")
  USING INDEX (CREATE UNIQUE INDEX "TI_PQTE_ESTD_ID_PQT_ESTD_PK" ON "TI_D_PAQUETES_ESTADO" ("CDGO_ESTDO")
  )  ENABLE,
	 CONSTRAINT "TI_PQTE_ESTD_ACTVO_NN" CHECK ( actvo in ('N','S') ) ENABLE
   ) ;

