
  CREATE TABLE "TI_D_REQUISITOS_ESTADO"
   (	"ID_RQSTO_ESTDO" NUMBER CONSTRAINT "TI_RQSTO_ESTD_ID_RQST_ESTD_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(1000) CONSTRAINT "TI_RQSTO_ESTD_NMBRE_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(2000),
	"ACTVO" VARCHAR2(1) DEFAULT 'S',
	 CONSTRAINT "TI_RQSTO_ESTD_ACTVO_NN" CHECK ( actvo in ('N','S') ) ENABLE,
	 CONSTRAINT "TI_RQSTO_ESTD_ID_RQST_ESTD_PK" PRIMARY KEY ("ID_RQSTO_ESTDO")
  USING INDEX  ENABLE
   ) ;

