
  CREATE TABLE "TI_G_PAQUETES_FNCNAL_TREA"
   (	"ID_PQTE_FNCNAL_TREA" NUMBER CONSTRAINT "TI_G_PQT_FN_TR_ID_PQT_FN_TR_NN" NOT NULL ENABLE,
	"ID_PQTE_FNCNAL" NUMBER CONSTRAINT "TI_G_PQT_FN_TR_ID_PQT_FNCNL_NN" NOT NULL ENABLE,
	"ID_TREA" NUMBER CONSTRAINT "TI_G_PQT_FN_TR_ID_TREA_NN" NOT NULL ENABLE,
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "TI_G_PQT_FN_TR_FCHA_NN" NOT NULL ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_TR_ID_PQT_FN_TR_PK" PRIMARY KEY ("ID_PQTE_FNCNAL_TREA")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_TR_ID_TREA_FK" FOREIGN KEY ("ID_TREA")
	  REFERENCES "TI_G_TAREAS" ("ID_TREA") ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_TR_ID_PQT_FNCNL_FK" FOREIGN KEY ("ID_PQTE_FNCNAL")
	  REFERENCES "TI_G_PAQUETES_FUNCIONAL" ("ID_PQTE_FNCNAL") ENABLE
   ) ;

