
  CREATE TABLE "TI_G_PQTE_FNCNAL_ITRCION"
   (	"ID_PQTE_FNCNAL_ITRCION" NUMBER CONSTRAINT "TI_G_PQT_FN_IT_ID_PQ_FN_IT_NN" NOT NULL ENABLE,
	"PQTE_FNCNAL_ITRCION" NUMBER DEFAULT 0 CONSTRAINT "TI_G_PQT_FN_IT_PQ_FN_IT_NN" NOT NULL ENABLE,
	"ID_PQTE_FNCNAL" NUMBER CONSTRAINT "TI_G_PQT_FN_IT_ID_PQ_FN_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER CONSTRAINT "TI_G_PQT_FN_IT_ID_INS_FLJ_NN" NOT NULL ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_IT_ID_PQ_FN_IT_PK" PRIMARY KEY ("ID_PQTE_FNCNAL_ITRCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_G_PQ_FN_IT_PQ_FN_IT_ID_PQ_FN_UN" UNIQUE ("PQTE_FNCNAL_ITRCION", "ID_PQTE_FNCNAL")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_IT_ID_INS_FLJ_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_IT_ID_PQ_FN_FK" FOREIGN KEY ("ID_PQTE_FNCNAL")
	  REFERENCES "TI_G_PAQUETES_FUNCIONAL" ("ID_PQTE_FNCNAL") ENABLE
   ) ;

