
  CREATE TABLE "TI_G_PLAN_PRUEBA"
   (	"ID_PLAN_PRBA" NUMBER DEFAULT "GENESYS"."SQ_TI_D_REQUERIMIENTO_ITEM"."NEXTVAL" CONSTRAINT "TI_G_PLAN_PRBA_ID_PLAN_PRBA_NN" NOT NULL ENABLE,
	"CDGO_PLAN_PRBA" VARCHAR2(20) CONSTRAINT "TI_G_PLAN_PRBA_CDG_PLAN_PRB_NN" NOT NULL ENABLE,
	"ID_PQTE_FNCNAL" NUMBER CONSTRAINT "TI_G_PLAN_PRBA_ID_PQ_FN_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER,
	"ID_EDSION" NUMBER CONSTRAINT "TI_G_PLAN_PRBA_ID_EDCION_NN" NOT NULL ENABLE,
	"ID_VRSION" NUMBER CONSTRAINT "TI_G_PLAN_PRBA_ID_VRSION_NN" NOT NULL ENABLE,
	"ID_IMPLMNTCION_TPO" NUMBER CONSTRAINT "TI_G_PLAN_PRBA_ID_IMPLM_TPO_NN" NOT NULL ENABLE,
	"UNDAD_DRCION" VARCHAR2(3),
	"DRCION" NUMBER CONSTRAINT "TI_G_PLAN_PRBA_DRCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "TI_G_PLAN_PRBA_UNDAD_DRCION_CK" CHECK (undad_drcion in ('MN','HR','DI','SM','MS')) ENABLE,
	 CONSTRAINT "TI_G_PLAN_PRBA_ID_PLAN_PRBA_PK" PRIMARY KEY ("ID_PLAN_PRBA")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_G_PLAN_PRBA_ID_PQ_FN_FK" FOREIGN KEY ("ID_PQTE_FNCNAL")
	  REFERENCES "TI_G_PAQUETES_FUNCIONAL" ("ID_PQTE_FNCNAL") ENABLE,
	 CONSTRAINT "TI_G_PLAN_PRBA_ID_IMPLM_TPO_FK" FOREIGN KEY ("ID_IMPLMNTCION_TPO")
	  REFERENCES "TI_D_IMPLEMENTACION_TIPO" ("ID_IMPLMNTCION_TPO") ENABLE,
	 CONSTRAINT "TI_G_PLAN_PRBA_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "TI_G_PLAN_PRBA_ID_VRSION_FK" FOREIGN KEY ("ID_VRSION")
	  REFERENCES "DF_S_VERSIONES" ("ID_VRSION") ENABLE,
	 CONSTRAINT "TI_G_PLAN_PRBA_ID_EDCION_FK" FOREIGN KEY ("ID_EDSION")
	  REFERENCES "DF_S_EDICIONES" ("ID_EDCION") ENABLE
   ) ;

