
  CREATE TABLE "TI_G_PLAN_PRUEBA_ALCANCE"
   (	"ID_PLAN_PRBA_ALCNCE" NUMBER DEFAULT "GENESYS"."SQ_TI_G_PLAN_PRUEBA_ALCANCE"."NEXTVAL" CONSTRAINT "TI_G_PLN_PRB_ALC_I_PL_PR_AL_NN" NOT NULL ENABLE,
	"ID_PLAN_PRBA" NUMBER CONSTRAINT "TI_G_PLN_PRB_ALC_ID_PLN_PRB_NN" NOT NULL ENABLE,
	"ID_PRBA_TPO" NUMBER CONSTRAINT "TI_G_PLN_PRB_ALC_ID_PRB_TPO_NN" NOT NULL ENABLE,
	 CONSTRAINT "TI_G_PLN_PRB_ALC_I_PL_PR_AL_PK" PRIMARY KEY ("ID_PLAN_PRBA_ALCNCE")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_G_PLN_PRB_ALC_ID_PRB_TPO_FK" FOREIGN KEY ("ID_PRBA_TPO")
	  REFERENCES "TI_D_PRUEBA_TIPO" ("ID_PRBA_TPO") ENABLE,
	 CONSTRAINT "TI_G_PLN_PRB_ALC_ID_PLN_PRB_FK" FOREIGN KEY ("ID_PLAN_PRBA")
	  REFERENCES "TI_G_PLAN_PRUEBA" ("ID_PLAN_PRBA") ENABLE
   ) ;

