
  CREATE TABLE "TI_G_PAQUETES_FNCNAL_ADJNTO"
   (	"ID_PQTE_FNCNAL_ADJNTO" NUMBER CONSTRAINT "TI_G_PQT_FN_ADJ_ID_PQ_FN_AD_NN" NOT NULL ENABLE,
	"ID_PQTE_FNCNAL" NUMBER CONSTRAINT "TI_G_PQT_FN_ADJ_ID_PQ_FNCNL_NN" NOT NULL ENABLE,
	"CDGO_ADJNTO_TPO" VARCHAR2(3) CONSTRAINT "TI_G_PQT_FN_ADJ_ID_ADJ_TPO_NN" NOT NULL ENABLE,
	"FCHA" TIMESTAMP (6) DEFAULT systimestamp CONSTRAINT "TI_G_PQT_FN_ADJ_FCHA_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(4000) CONSTRAINT "TI_G_PQT_FN_ADJ_OBSRVCION_NN" NOT NULL ENABLE,
	"NMRO_APLCCION" NUMBER,
	"NMRO_PGNA" NUMBER,
	"FILE_BLOB" BLOB,
	"FILE_NAME" VARCHAR2(250),
	"FILE_MIMETYPE" VARCHAR2(100),
	"NMRO_VRSION" NUMBER,
	"ID_USRIO_ADJNTO" NUMBER NOT NULL ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_ADJ_ID_PQ_FN_AD_PK" PRIMARY KEY ("ID_PQTE_FNCNAL_ADJNTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_ADJ_ID_PQ_FNCNL_FK" FOREIGN KEY ("ID_PQTE_FNCNAL")
	  REFERENCES "TI_G_PAQUETES_FUNCIONAL" ("ID_PQTE_FNCNAL") ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_ADJ_ID_ADJ_TPO_FK" FOREIGN KEY ("CDGO_ADJNTO_TPO")
	  REFERENCES "TI_D_ADJUNTOS_TIPO" ("CDGO_ADJNTO_TPO") ENABLE,
	 CONSTRAINT "TI_G_PQT_FN_ADJ_ID_USR_ADJ_FK" FOREIGN KEY ("ID_USRIO_ADJNTO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   )
 LOB ("FILE_BLOB") STORE AS SECUREFILE "SYS_LOB0000075067C00008$$"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;

