
  CREATE TABLE "TI_G_TAREAS"
   (	"ID_TREA" NUMBER CONSTRAINT "TI_G_TREA_ID_TREA_NN" NOT NULL ENABLE,
	"ID_RQSTO" NUMBER CONSTRAINT "TI_G_TREA_ID_RQSTO_NN" NOT NULL ENABLE,
	"NMTCNCO" VARCHAR2(10) CONSTRAINT "TI_G_TREA_NMTCNCO_NN" NOT NULL ENABLE,
	"NMBRE" VARCHAR2(1000) CONSTRAINT "TI_G_TREA_NMBRE_NN" NOT NULL ENABLE,
	"DSCRPCION" VARCHAR2(1000),
	"CDGO_TREA_TPO" VARCHAR2(3) CONSTRAINT "TI_G_TREA_CDGO_TREA_TPO_NN" NOT NULL ENABLE,
	"FCHA_INCIO_PLNDA" TIMESTAMP (6) CONSTRAINT "TI_G_TREA_FCHA_INCIO_PLNDA_NN" NOT NULL ENABLE,
	"FCHA_FIN_PLNDA" TIMESTAMP (6) CONSTRAINT "TI_G_TREA_FCHA_FIN_PLNDA_NN" NOT NULL ENABLE,
	"FCHA_INCIO_REAL" TIMESTAMP (6),
	"FCHA_FIN_REAL" TIMESTAMP (6),
	"UNDAD_DRCION" VARCHAR2(3),
	"DRCION" NUMBER,
	"PRCNTJE_AVNCE" NUMBER DEFAULT 0,
	"ID_TREAS_ESTDO" NUMBER CONSTRAINT "TI_G_TREA_ID_TREA_ESTDO_NN" NOT NULL ENABLE,
	"ID_TREA_PDRE" NUMBER,
	"ID_RSPSBLE" NUMBER CONSTRAINT "TI_G_TREA_ID_RSPNSBLE_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER,
	 CONSTRAINT "TI_G_TREA_UNDAD_DRCION_CK" CHECK (undad_drcion in ('MN','HR','DI','SM','MS')) ENABLE,
	 CONSTRAINT "TI_G_TREA_PRCNTJE_AVNCE_CK" CHECK (prcntje_avnce between 0 and 100) ENABLE,
	 CONSTRAINT "TI_G_TREA_ID_TREA_PK" PRIMARY KEY ("ID_TREA")
  USING INDEX  ENABLE,
	 CONSTRAINT "TI_G_TREA_ID_TREA_PDRE_FK" FOREIGN KEY ("ID_TREA_PDRE")
	  REFERENCES "TI_G_TAREAS" ("ID_TREA") ENABLE,
	 CONSTRAINT "TI_G_TREA_ID_RSPNSBLE_FK" FOREIGN KEY ("ID_RSPSBLE")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE,
	 CONSTRAINT "TI_G_TREA_ID_TREA_ESTDO_FK" FOREIGN KEY ("ID_TREAS_ESTDO")
	  REFERENCES "TI_D_TAREAS_ESTADO" ("ID_TREAS_ESTDO") ENABLE,
	 CONSTRAINT "TI_G_TREA_ID_RQSTO_FK" FOREIGN KEY ("ID_RQSTO")
	  REFERENCES "TI_G_REQUISITOS" ("ID_RQSTO") ENABLE,
	 CONSTRAINT "TI_G_TREA_CDGO_TREA_TPO_FK" FOREIGN KEY ("CDGO_TREA_TPO")
	  REFERENCES "TI_D_TAREAS_TIPO" ("CDGO_TREA_TPO") ENABLE
   ) ;

