
  CREATE TABLE "TIPOS_ACTIVIDAD_TARIFARIA"
   (	"TPO_ACTVDAD" VARCHAR2(3) NOT NULL ENABLE,
	"CDGO_CLSE_ACTVDAD" NUMBER(6,0) DEFAULT 0 NOT NULL ENABLE,
	"DSCRPCION_CLSE_ACTVDAD" VARCHAR2(150) NOT NULL ENABLE,
	"FCHA_MDFCCION" DATE DEFAULT SYSDATE NOT NULL ENABLE,
	"USRIO" VARCHAR2(30) DEFAULT USER NOT NULL ENABLE,
	"VGNCIA_INICIAL" NUMBER(6,0) NOT NULL ENABLE,
	"VGNCIA_FNAL" NUMBER(6,0) NOT NULL ENABLE,
	"TRFA" NUMBER(5,2)
   ) ;

