
  CREATE TABLE "WF_D_FLUJOS_TRANSICION"
   (	"ID_FLJO_TRNSCION" NUMBER(15,0) CONSTRAINT "WF_D_FLJO_TRNSCN_ID_FLJ_SCN_NN" NOT NULL ENABLE,
	"ID_FLJO" NUMBER(15,0) CONSTRAINT "WF_D_FLJO_TRNSCN_ID_FLJO_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER(15,0) CONSTRAINT "WF_D_FLJO_TRNSCN_ID_FLJ_TRA_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA_DSTNO" NUMBER(15,0) CONSTRAINT "WF_D_FLJO_TRNSCN_FLJ_TRA_DS_NN" NOT NULL ENABLE,
	"ORDEN" NUMBER(10,0) CONSTRAINT "WF_D_FLJO_TRNSCN_ORDEN_NN" NOT NULL ENABLE,
	"NMBRE_TRNSCION" VARCHAR2(30) CONSTRAINT "WF_D_FLJO_TRNSCN_NMBRE_TRNS_NN" NOT NULL ENABLE,
	"CDGO_MTDO_ASGNCION" VARCHAR2(3) CONSTRAINT "WF_D_FLJO_TRNSCN_ID_MTD_ASG_NN" NOT NULL ENABLE,
	"INDCDOR_APRBAR_TDO_PRTCPNTES" VARCHAR2(1),
	"INDCDOR_ACTLZAR" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "WF_D_FLJO_TRNSCN_INDC_ACTLZ_NN" NOT NULL ENABLE,
	 CONSTRAINT "WF_D_FLJO_TRNSCN_ID_FLJ_SCN_PK" PRIMARY KEY ("ID_FLJO_TRNSCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJO_TRNSCN_INDC_ACTLZ_CK" CHECK (indcdor_actlzar in ('S','N')) ENABLE,
	 CONSTRAINT "WF_D_FLJO_TREA_I_APR_TD_PRT_CK" CHECK (indcdor_aprbar_tdo_prtcpntes in ('S','N')) ENABLE,
	 CONSTRAINT "WF_D_FLJO_TRNSCN_F_F_T_F_TD_UN" UNIQUE ("ID_FLJO", "ID_FLJO_TREA", "ID_FLJO_TREA_DSTNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJO_TRNSCN_ID_FLJO_FK" FOREIGN KEY ("ID_FLJO")
	  REFERENCES "WF_D_FLUJOS" ("ID_FLJO") ENABLE,
	 CONSTRAINT "WF_D_FLJO_TRNSCN_ID_FLJ_TRA_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE,
	 CONSTRAINT "WF_D_FLJO_TRNSCN_FLJ_TRA_DS_FK" FOREIGN KEY ("ID_FLJO_TREA_DSTNO")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE,
	 CONSTRAINT "WF_D_FLJO_TRNSCN_ID_MTD_ASG_FK" FOREIGN KEY ("CDGO_MTDO_ASGNCION")
	  REFERENCES "DF_S_METODOS_ASIGNACION" ("CDGO_MTDO_ASGNCION") ENABLE
   ) ;

