
  CREATE TABLE "WF_D_FLUJOS_TRNSCION_PRMTRO"
   (	"ID_FLJO_TRNSCION_PRMTRO" NUMBER(15,0) CONSTRAINT "WF_D_FLJ_TRN_PRM_ID_F_TR_P_NN" NOT NULL ENABLE,
	"ID_FLJO_TRNSCION" NUMBER CONSTRAINT "WF_D_FLJ_TRN_PRM_ID_F_TRNS_NN" NOT NULL ENABLE,
	"PRMTRO_ORGEN" VARCHAR2(30) CONSTRAINT "WF_D_FLJ_TRN_PRM_PRMTR_ORGN_NN" NOT NULL ENABLE,
	"PRMTRO_DSTNO" VARCHAR2(30) NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1),
	 CONSTRAINT "WF_D_FLJ_TRN_PRM_F_T_P_O_PD_UN" UNIQUE ("ID_FLJO_TRNSCION", "PRMTRO_ORGEN", "PRMTRO_DSTNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJ_TRN_PRM_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "WF_D_FLJ_TRN_PRM_ID_F_TR_P_PK" PRIMARY KEY ("ID_FLJO_TRNSCION_PRMTRO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJ_TRN_PRM_ID_F_TRNS_FK" FOREIGN KEY ("ID_FLJO_TRNSCION")
	  REFERENCES "WF_D_FLUJOS_TRANSICION" ("ID_FLJO_TRNSCION") ENABLE
   ) ;

