
  CREATE TABLE "WF_D_PROCESOS"
   (	"ID_PRCSO" NUMBER(15,0) CONSTRAINT "WF_D_PRCSO_ID_PRCSO_NN" NOT NULL ENABLE,
	"NMBRE_PRCSO" VARCHAR2(4000) CONSTRAINT "WF_D_PRCSO_NMBRE_PRCSO_NN" NOT NULL ENABLE,
	"NMBRE_UNDAD_PRGRMA" VARCHAR2(100) CONSTRAINT "WF_D_PRCSO_NMBRE_UNDD_PRGRM_NN" NOT NULL ENABLE,
	 CONSTRAINT "WF_D_PRCSO_ID_PRCSO_PK" PRIMARY KEY ("ID_PRCSO")
  USING INDEX  ENABLE
   ) ;

