
  CREATE TABLE "WF_D_FLUJOS_EVENTO_MANEJDOR"
   (	"ID_FLJO_EVNTO_MNJDOR" NUMBER CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FL_EV_M_NN" NOT NULL ENABLE,
	"ID_FLJO" NUMBER CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FLJO_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FLJ_TRA_NN" NOT NULL ENABLE,
	"ID_FLJO_EVNTO" NUMBER CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FLJ_EVN_NN" NOT NULL ENABLE,
	"FNCION" VARCHAR2(1000) CONSTRAINT "WF_D_FLJ_EVN_MNJ_FNCION_NN" NOT NULL ENABLE,
	 CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FL_EV_M_PK" PRIMARY KEY ("ID_FLJO_EVNTO_MNJDOR")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FLJ_EVN_FK" FOREIGN KEY ("ID_FLJO_EVNTO")
	  REFERENCES "WF_D_FLUJOS_EVENTO" ("ID_FLJO_EVNTO") ENABLE,
	 CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FLJO_FK" FOREIGN KEY ("ID_FLJO")
	  REFERENCES "WF_D_FLUJOS" ("ID_FLJO") ENABLE,
	 CONSTRAINT "WF_D_FLJ_EVN_MNJ_ID_FLJ_TRA_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE
   ) ;

