
  CREATE TABLE "WF_D_FLJ_TREA_ESTD_PRTCPNTE"
   (	"ID_ESTDO_PRTCPNTE" NUMBER(15,0),
	"ID_FLJO_TREA_ESTDO" NUMBER(15,0) CONSTRAINT "WF_D_FLJ_TR_ST_PT_FLJ_TR_ST_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA_PRTCPNTE" NUMBER(15,0) CONSTRAINT "WF_D_FLJ_TR_ST_PT_FLJ_TR_PT_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "WF_D_FLJ_TR_ST_PT_ACTVO_NN" NOT NULL ENABLE,
	 CONSTRAINT "WF_D_FLJ_TR_ST_PT_F_T_E_F_T_UN" UNIQUE ("ID_FLJO_TREA_ESTDO", "ID_FLJO_TREA_PRTCPNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJ_TR_ST_PT_ID_ST_PT_PK" PRIMARY KEY ("ID_ESTDO_PRTCPNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJ_TR_ST_PT_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "WF_D_FLJ_TR_ST_PT_FLJ_TR_PT_FK" FOREIGN KEY ("ID_FLJO_TREA_PRTCPNTE")
	  REFERENCES "WF_D_FLUJOS_TAREA_PRTCPNTE" ("ID_FLJO_TREA_PRTCPNTE") ENABLE,
	 CONSTRAINT "WF_D_FLJ_TR_ST_PT_FLJ_TR_ST_FK" FOREIGN KEY ("ID_FLJO_TREA_ESTDO")
	  REFERENCES "WF_D_FLUJOS_TAREA_ESTADO" ("ID_FLJO_TREA_ESTDO") ENABLE
   ) ;

