
  CREATE TABLE "WF_D_ATRIBUTOS"
   (	"ID_ATRBTO" NUMBER(15,0) CONSTRAINT "WF_D_ATRBTO_ID_ATRBTO_NN" NOT NULL ENABLE,
	"CDGO_CTGRIA_TPO" VARCHAR2(3) CONSTRAINT "WF_D_ATRBTO_CDG_CTG_TPO_NN" NOT NULL ENABLE,
	"NMBRE_ATRBTO" VARCHAR2(100) CONSTRAINT "WF_D_ATRBTO_NMBRE_ATRBTO_NN" NOT NULL ENABLE,
	"TOOLTIP" VARCHAR2(100),
	"TPO_DTO" VARCHAR2(10) CONSTRAINT "WF_D_ATRBTO_TPO_DTO_NN" NOT NULL ENABLE,
	"TMÑO" NUMBER(10,0),
	"TPO_OBJTO" VARCHAR2(30) CONSTRAINT "WF_D_ATRBTO_TPO_OBJTO_NN" NOT NULL ENABLE,
	 CONSTRAINT "WF_D_ATRBTO_NMBRE_ATRBTO_UN" UNIQUE ("NMBRE_ATRBTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_ATRBTO_TPO_OBJTO_CK" CHECK (tpo_objto in('TEXT', 'TEXT_AREA', 'FECHA', 'SELECT_LIST', 'CHECK_BOX')) ENABLE,
	 CONSTRAINT "WF_D_ATRBTO_ID_ATRBTO_PK" PRIMARY KEY ("ID_ATRBTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_ATRBTO_TPO_DTO_CK" CHECK (tpo_dto in('CARACTER', 'NUMERO', 'FECHA')) ENABLE,
	 CONSTRAINT "WF_D_ATRBTO_CDG_CTG_TPO_PK" FOREIGN KEY ("CDGO_CTGRIA_TPO")
	  REFERENCES "WF_D_CATEGORIAS_TIPO" ("CDGO_CTGRIA_TPO") ENABLE
   ) ;

