
  CREATE TABLE "WF_D_FLUJOS_TAREA_PRTCPNTE"
   (	"ID_FLJO_TREA_PRTCPNTE" NUMBER(15,0) CONSTRAINT "WF_D_FLJO_PRT_TR_ID_FLJ_P_T_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER(15,0) CONSTRAINT "WF_D_FLJO_PRT_TR_ID_FLJ_TR_NN" NOT NULL ENABLE,
	"TPO_PRTCPNTE" VARCHAR2(15) CONSTRAINT "WF_D_FLJO_PRT_TR_TPO_PRTCNT_NN" NOT NULL ENABLE,
	"ID_PRTCPTE" NUMBER(15,0) CONSTRAINT "WF_D_FLJO_PRT_TR_ID_PRTCPNT_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1),
	 CONSTRAINT "WF_D_FLJO_PRT_TR_FT_TP_IP_UN" UNIQUE ("ID_FLJO_TREA", "TPO_PRTCPNTE", "ID_PRTCPTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJO_PRT_TR_TPO_PRTCNT_CK" CHECK (tpo_prtcpnte in ('USUARIO','PERFIL')) ENABLE,
	 CONSTRAINT "WF_D_FLJO_PRT_TR_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "WF_D_FLJO_PRT_TR_ID_FLJ_P_T_PK" PRIMARY KEY ("ID_FLJO_TREA_PRTCPNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJO_PRT_TR_ID_FLJ_TR_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE
   ) ;

