
  CREATE TABLE "WF_D_FLUJOS_GRUPO"
   (	"ID_FLJO_GRPO" NUMBER CONSTRAINT "WF_D_FLJ_GRPO_ID_FLJO_GRPO_NN" NOT NULL ENABLE,
	"ID_FLJO" NUMBER CONSTRAINT "WF_D_FLJ_GRPO_ID_FLJO_NN" NOT NULL ENABLE,
	"NMBRE_GRPO" VARCHAR2(50) CONSTRAINT "WF_D_FLJ_GRPO_NMBRE_GRPO_NN" NOT NULL ENABLE,
	"DSCRPCION_GRPO" VARCHAR2(200) CONSTRAINT "WF_D_FLJ_GRPO_DSCRPCION_GRP_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) DEFAULT 'S' CONSTRAINT "WF_D_FLJ_GRPO_ACTVO_NN" NOT NULL ENABLE,
	"CDGO_GRPO" VARCHAR2(3) DEFAULT NULL CONSTRAINT "WF_D_FLJ_GRPO_CDGO_GRPO_NN" NOT NULL ENABLE,
	 CONSTRAINT "WF_D_FLJ_GRPO_ID_FLJO_GRPO_PK" PRIMARY KEY ("ID_FLJO_GRPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJ_GRP_ID_FLJO_CGO_GRPO" UNIQUE ("ID_FLJO", "CDGO_GRPO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_D_FLJ_GRPO_ACTVO_CK" CHECK (actvo in ('S','N')) ENABLE,
	 CONSTRAINT "WF_D_FLJ_GRPO_ID_FLJO_FK" FOREIGN KEY ("ID_FLJO")
	  REFERENCES "WF_D_FLUJOS" ("ID_FLJO") ENABLE
   ) ;

