
  CREATE TABLE "WF_G_INSTANCIAS_FLUJO_GNRDO"
   (	"ID_INSTNCIA_FLJO_GNRDO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_WF_G_INSTANCIAS_FLUJO_GNRDO"."NEXTVAL" CONSTRAINT "WF_G_INS_FLJ_GNR_I_I_F_G_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO" NUMBER CONSTRAINT "WF_G_INS_FLJ_GNR_ID_INS_FLJ_NN" NOT NULL ENABLE,
	"ID_INSTNCIA_FLJO_GNRDO_HJO" NUMBER CONSTRAINT "WF_G_INS_FLJ_GNR_ID_I_F_G_H_NN" NOT NULL ENABLE,
	"ID_FLJO_TREA" NUMBER DEFAULT 1 CONSTRAINT "WF_G_INS_FLJ_GNR_ID_FLJO_TR_NN" NOT NULL ENABLE,
	"INDCDOR_MNJDO" VARCHAR2(1) DEFAULT 'N' CONSTRAINT "WF_G_INS_FLJ_GNR_INDC_MNJ_NN" NOT NULL ENABLE,
	"INDCDOR_MGRDO" VARCHAR2(1),
	 CONSTRAINT "WF_G_INS_FLJ_GNR_INDC_MNJ_CK" CHECK (indcdor_mnjdo in ('S','N','E')) ENABLE,
	 CONSTRAINT "WF_G_INS_FLJ_GNR_I_I_F_G_PK" PRIMARY KEY ("ID_INSTNCIA_FLJO_GNRDO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_G_INS_FLJ_GNR_ID_FLJO_TR_FK" FOREIGN KEY ("ID_FLJO_TREA")
	  REFERENCES "WF_D_FLUJOS_TAREA" ("ID_FLJO_TREA") ENABLE,
	 CONSTRAINT "WF_G_INS_FLJ_GNR_ID_INS_FLJ_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE,
	 CONSTRAINT "WF_G_INS_FLJ_GNR_ID_I_F_G_H_FK" FOREIGN KEY ("ID_INSTNCIA_FLJO_GNRDO_HJO")
	  REFERENCES "WF_G_INSTANCIAS_FLUJO" ("ID_INSTNCIA_FLJO") ENABLE
   ) ;

