
  CREATE TABLE "WF_G_INSTANCIAS_FLUJO"
   (	"ID_INSTNCIA_FLJO" NUMBER(15,0) DEFAULT "GENESYS"."SQ_WF_G_INSTANCIAS_FLUJO"."NEXTVAL" CONSTRAINT "WF_G_INS_FLJ_ID_INSTN_FLJO_NN" NOT NULL ENABLE,
	"ID_FLJO" NUMBER(15,0) CONSTRAINT "WF_G_INS_FLJ_ID_FLJO_NN" NOT NULL ENABLE,
	"FCHA_INCIO" TIMESTAMP (6) CONSTRAINT "WF_G_INS_FLJ_FCHA_INCIO_NN" NOT NULL ENABLE,
	"FCHA_FIN_PLNDA" TIMESTAMP (6),
	"FCHA_FIN_OPTMA" TIMESTAMP (6),
	"FCHA_FIN_REAL" TIMESTAMP (6),
	"ID_USRIO" NUMBER(15,0) CONSTRAINT "WF_G_INS_ID_USRIO_NN" NOT NULL ENABLE,
	"ESTDO_INSTNCIA" VARCHAR2(30) CONSTRAINT "WF_G_INS_ESTDO_INSTNCIA_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(4000),
	"INDCDOR_MGRDO" VARCHAR2(1),
	 CONSTRAINT "WF_G_INS_ESTDO_INSTNCIA_CK" CHECK (estdo_instncia in ('INICIADA','EJECUTANDO','FINALIZADA')) ENABLE,
	 CONSTRAINT "WF_G_INS_FLJ_ID_INSTN_FLJO_PK" PRIMARY KEY ("ID_INSTNCIA_FLJO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WF_G_INS_FLJ_ID_FLJO_FK" FOREIGN KEY ("ID_FLJO")
	  REFERENCES "WF_D_FLUJOS" ("ID_FLJO") ENABLE,
	 CONSTRAINT "WF_G_INS_ID_USRIO_FK" FOREIGN KEY ("ID_USRIO")
	  REFERENCES "SG_G_USUARIOS" ("ID_USRIO") ENABLE
   ) ;

