
  CREATE TABLE "WS_D_PROVEDORES_BANCO"
   (	"ID_PRVDOR_BNCO" NUMBER CONSTRAINT "WS_D_PRVDRES_BNCO_I_PRV_BCO_NN" NOT NULL ENABLE,
	"ID_PRVDOR" NUMBER CONSTRAINT "WS_D_PRVDRES_BNCO_ID_PRVDOR_NN" NOT NULL ENABLE,
	"CDGO_BNCO" VARCHAR2(5) CONSTRAINT "WS_D_PRVDRES_BNCO_CDGO_BNCO_NN" NOT NULL ENABLE,
	"NMBRE_BNCO" VARCHAR2(100) CONSTRAINT "WS_D_PRVDRES_BNCO_NMBRE_BCO_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) CONSTRAINT "WS_D_PRVDRES_BNCO_FCH_RGSTR_NN" NOT NULL ENABLE,
	 CONSTRAINT "WS_D_PRVDRES_BNCO_I_PRV_BCO_PK" PRIMARY KEY ("ID_PRVDOR_BNCO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PRVDRES_BNCO_ID_PRVDOR_FK" FOREIGN KEY ("ID_PRVDOR")
	  REFERENCES "WS_D_PROVEDORES" ("ID_PRVDOR") ENABLE
   ) ;

