
  CREATE TABLE "WS_D_CODIGOS_RESPUESTA"
   (	"ID_CDGO_RSPSTA" NUMBER CONSTRAINT "WS_D_CDGOS_RSPSTA_ID_CDG_RS_NN" NOT NULL ENABLE,
	"ID_PRVDOR" NUMBER CONSTRAINT "WS_D_CDGOS_RSPSTA_ID_PRVDOR_NN" NOT NULL ENABLE,
	"CDGO_RSPSTA_PRVDOR" VARCHAR2(3),
	"DSCRPCION_ERROR" VARCHAR2(100),
	"RSPSTA_EXTSA" VARCHAR2(3) CONSTRAINT "WS_D_CDGOS_RSPSTA_RSPST_EXT_NN" NOT NULL ENABLE,
	 CONSTRAINT "WS_D_CDGOS_RSPSTA_RSPST_EXT_CK" CHECK (rspsta_extsa in ('S','N')) ENABLE,
	 CONSTRAINT "WS_D_CDGOS_RSPSTA_ID_CDG_RS_PK" PRIMARY KEY ("ID_CDGO_RSPSTA")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_CDGOS_RSPSTA_ID_PRVDOR_FK" FOREIGN KEY ("ID_PRVDOR")
	  REFERENCES "WS_D_PROVEDORES" ("ID_PRVDOR") ENABLE
   ) ;

