
  CREATE TABLE "WS_D_CODIGOS_SERVICIO"
   (	"ID_CDGO_SRVCIO" NUMBER CONSTRAINT "WS_D_CGS_SRVC_ID_CG_SRV_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "WS_D_CGS_SRVC_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_PRVDOR" NUMBER CONSTRAINT "WS_D_CGS_SRVC_ID_PRVDOR_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "WS_D_CGS_SRVC_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ID_IMPSTO_SBMPSTO" NUMBER CONSTRAINT "WS_D_CGS_SRVC_ID_IMP_SBM_NN" NOT NULL ENABLE,
	"CDGO_SRVCIO" VARCHAR2(100) CONSTRAINT "WS_D_CGS_SRVC_CG_SRVCIO_NN" NOT NULL ENABLE,
	"ID_CNCPTO" NUMBER,
	"INDCDOR_CDGO_PRNCPAL" VARCHAR2(1) CONSTRAINT "WS_D_CGS_SRVC_IND_CD_PR_NN" NOT NULL ENABLE,
	"IDNTFCCION_ASCDA" VARCHAR2(40),
	"CNCPTO_INTRES_MRA" VARCHAR2(1),
	 CONSTRAINT "WS_D_CGS_SRVC_ID_CG_SRV_PK" PRIMARY KEY ("ID_CDGO_SRVCIO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_CGS_SRVC_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "WS_D_CGS_SRVC_ID_PRVDOR_FK" FOREIGN KEY ("ID_PRVDOR")
	  REFERENCES "WS_D_PROVEDORES" ("ID_PRVDOR") ENABLE,
	 CONSTRAINT "WS_D_CGS_SRVC_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "WS_D_CGS_SRVC_ID_CNCPTO_FK" FOREIGN KEY ("ID_CNCPTO")
	  REFERENCES "DF_I_CONCEPTOS" ("ID_CNCPTO") ENABLE,
	 CONSTRAINT "WS_D_CGS_SRVC_ID_IMP_SBM_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE
   ) ;

