
  CREATE TABLE "WS_D_PROVEDORES"
   (	"ID_PRVDOR" NUMBER CONSTRAINT "WS_D_PRVDOR_ID_PRVDOR_NN" NOT NULL ENABLE,
	"CDGO_PRVDOR" VARCHAR2(3) CONSTRAINT "WS_D_PRVDOR_CDGO_PRVDOR_NN" NOT NULL ENABLE,
	"NMBRE_PRVDOR" VARCHAR2(100) CONSTRAINT "WS_D_PRVDOR_NMBRE_PRVDOR_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(3) CONSTRAINT "WS_D_PRVDOR_ACTVO_NN" NOT NULL ENABLE,
	"USERNAME" VARCHAR2(100),
	"PASSWORD" VARCHAR2(100),
	 CONSTRAINT "WS_D_PRVDOR_ID_PRVDOR_PK" PRIMARY KEY ("ID_PRVDOR")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PROVEDORES_CDGO_PRVDOR_UN" UNIQUE ("CDGO_PRVDOR")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PRVDOR_ACTVO_CK" CHECK (actvo in ( 'S','N')) ENABLE
   ) ;

