
  CREATE TABLE "WS_D_PROVEDORES_CLIENTE"
   (	"ID_PRVDOR_CLNTE" NUMBER CONSTRAINT "WS_D_PRVD_CLNT_ID_PRVD_CLNT_NN" NOT NULL ENABLE,
	"ID_PRVDOR" NUMBER CONSTRAINT "WS_D_PRVD_CLNT_ID_PRVDOR_NN" NOT NULL ENABLE,
	"CDGO_CLNTE" NUMBER CONSTRAINT "WS_D_PRVD_CLNT_CDGO_CLNTE_NN" NOT NULL ENABLE,
	"ID_IMPSTO" NUMBER CONSTRAINT "WS_D_PRVD_CLNT_ID_IMPSTO_NN" NOT NULL ENABLE,
	"ACTVO" VARCHAR2(1) NOT NULL ENABLE,
	"ID_BNCO" NUMBER,
	"ID_BNCO_CNTA" NUMBER,
	"ID_IMPSTO_SBMPSTO" NUMBER,
	"ID_USRIO_APLCA_RCDOS" NUMBER,
	"INDCDOR_TRNSFRNCIA_BNCRIA" VARCHAR2(2) DEFAULT 'N',
	"CDGO_TPO_OPRCION" VARCHAR2(10) DEFAULT 'MNCDT',
	 CONSTRAINT "WS_D_PRVD_CLNT_CDG_TP_OPRCN_NN" CHECK ("CDGO_TPO_OPRCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ID_PRV_CLNTE_UN" UNIQUE ("CDGO_CLNTE", "ID_IMPSTO", "ID_IMPSTO_SBMPSTO")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ID_PRVD_CLNT_PK" PRIMARY KEY ("ID_PRVDOR_CLNTE")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_CDG_TP_OPRCN_CK" CHECK (cdgo_tpo_oprcion in ('MNCDT','MLTCDT')) ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ACTVO_CK" CHECK (actvo in ( 'S','N')) ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_CDGO_CLNTE_FK" FOREIGN KEY ("CDGO_CLNTE")
	  REFERENCES "DF_S_CLIENTES" ("CDGO_CLNTE") ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ID_IMPSTO_SB_FK" FOREIGN KEY ("ID_IMPSTO_SBMPSTO")
	  REFERENCES "DF_I_IMPUESTOS_SUBIMPUESTO" ("ID_IMPSTO_SBMPSTO") ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ID_BNCO_CNTA_FK" FOREIGN KEY ("ID_BNCO_CNTA")
	  REFERENCES "DF_C_BANCOS_CUENTA" ("ID_BNCO_CNTA") ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ID_BNCO_FK" FOREIGN KEY ("ID_BNCO")
	  REFERENCES "DF_C_BANCOS" ("ID_BNCO") ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ID_IMPSTO_FK" FOREIGN KEY ("ID_IMPSTO")
	  REFERENCES "DF_C_IMPUESTOS" ("ID_IMPSTO") ENABLE,
	 CONSTRAINT "WS_D_PRVD_CLNT_ID_PRVDOR_FK" FOREIGN KEY ("ID_PRVDOR")
	  REFERENCES "WS_D_PROVEDORES" ("ID_PRVDOR") ENABLE
   ) ;

