
  CREATE TABLE "WS_D_PROVEDORES_CNFGRCION"
   (	"ID_PRVDOR_CNFGRCION" NUMBER,
	"ID_PRVDOR" NUMBER,
	"CDGO_CNFGRCION" VARCHAR2(3),
	"VLOR" VARCHAR2(4000),
	 CONSTRAINT "WS_D_PRV_CNFG_CDG_CNFGRCN_NN" CHECK ("CDGO_CNFGRCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "WS_D_PRV_CNFG_ID_PRVDOR_NN" CHECK ("ID_PRVDOR" IS NOT NULL) ENABLE,
	 CONSTRAINT "WS_D_PRV_CNFG_ID_PRV_CNFG_PK" PRIMARY KEY ("ID_PRVDOR_CNFGRCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PRV_CNFG_ID_PRV_CNFG_NN" CHECK ("ID_PRVDOR_CNFGRCION" IS NOT NULL) ENABLE,
	 CONSTRAINT "WS_D_PRV_CNFG_ID_PRVDOR_FK" FOREIGN KEY ("ID_PRVDOR")
	  REFERENCES "WS_D_PROVEDORES" ("ID_PRVDOR") ENABLE,
	 CONSTRAINT "WS_D_PRV_CNFG_CDG_CNFGRCN_FK" FOREIGN KEY ("CDGO_CNFGRCION")
	  REFERENCES "WS_D_CONFIGURACIONES" ("CDGO_CNFGRCION") ENABLE
   ) ;

