
  CREATE TABLE "WS_D_PRVDRES_TPO_IDNTFCCION"
   (	"ID_PRVDOR_TPO_IDNTFCCION" NUMBER CONSTRAINT "WS_D_PRV_TP_IDNT_I_PR_TP_ID_NN" NOT NULL ENABLE,
	"ID_PRVDOR" NUMBER CONSTRAINT "WS_D_PRV_TP_IDNT_ID_PRVDOR_NN" NOT NULL ENABLE,
	"CDGO_TPO_IDNTFCCION_PRVDOR" VARCHAR2(3) CONSTRAINT "WS_D_PRV_TP_IDNT_C_TP_ID_PR_NN" NOT NULL ENABLE,
	"CDGO_IDNTFCCION_TPO" VARCHAR2(3) CONSTRAINT "WS_D_PRV_TP_IDNT_CDG_ID_TPO_NN" NOT NULL ENABLE,
	 CONSTRAINT "WS_D_PRV_TP_IDNT_I_PR_TP_ID_PK" PRIMARY KEY ("ID_PRVDOR_TPO_IDNTFCCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PRV_TP_IDNT_CDG_ID_TPO_FK" FOREIGN KEY ("CDGO_IDNTFCCION_TPO")
	  REFERENCES "DF_S_IDENTIFICACIONES_TIPO" ("CDGO_IDNTFCCION_TPO") ENABLE,
	 CONSTRAINT "WS_D_PRV_TP_IDNT_ID_PRVDOR_FK" FOREIGN KEY ("ID_PRVDOR")
	  REFERENCES "WS_D_PROVEDORES" ("ID_PRVDOR") ENABLE
   ) ;

