
  CREATE TABLE "WS_D_PROVEDORES_HEADER_API"
   (	"ID_PRVDOR_HEADER_API" NUMBER CONSTRAINT "WS_D_PR_HD_API_ID_PR_HD_API_NN" NOT NULL ENABLE,
	"ID_PRVDOR_API" NUMBER CONSTRAINT "WS_D_PR_HD_API_ID_PRVDR_API_NN" NOT NULL ENABLE,
	"ID_PRVDOR_HEADER" NUMBER CONSTRAINT "WS_D_PR_HD_API_ID_PRVDR_HDR_NN" NOT NULL ENABLE,
	 CONSTRAINT "WS_D_PR_HD_API_ID_PR_HD_API_PK" PRIMARY KEY ("ID_PRVDOR_HEADER_API")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PR_HD_API_ID_PA_ID_PHD_UN" UNIQUE ("ID_PRVDOR_API", "ID_PRVDOR_HEADER")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_PR_HD_API_ID_PRVDR_HDR_FK" FOREIGN KEY ("ID_PRVDOR_HEADER")
	  REFERENCES "WS_D_PROVEDORES_HEADER" ("ID_PRVDOR_HEADER") ENABLE,
	 CONSTRAINT "WS_D_PR_HD_API_ID_PRVDR_API_FK" FOREIGN KEY ("ID_PRVDOR_API")
	  REFERENCES "WS_D_PROVEDORES_API" ("ID_PRVDOR_API") ENABLE
   ) ;

