
  CREATE TABLE "WS_D_ESTADOS_TRANSACCION"
   (	"CDGO_ESTDO_TRNSCCION" VARCHAR2(3) CONSTRAINT "WS_D_ESTDOS_TRNSCCN_C_ES_TR_NN" NOT NULL ENABLE,
	"DSCRPCION_ESTDO" VARCHAR2(40) CONSTRAINT "WS_D_ESTDOS_TRNSCCN_DSC_EST_NN" NOT NULL ENABLE,
	"ESTDO_FNAL" VARCHAR2(3) CONSTRAINT "WS_D_ESTDOS_TRNSCCN_ESTD_FN_NN" NOT NULL ENABLE,
	"APRBCCION" VARCHAR2(3) CONSTRAINT "WS_D_ESTDOS_TRNSCCN_APRBCCN_NN" NOT NULL ENABLE,
	 CONSTRAINT "WS_D_ESTDOS_TRNSCCN_APRBCCN_CK" CHECK (aprbccion in ('S','N')) ENABLE,
	 CONSTRAINT "WS_D_ESTDOS_TRNSCCN_C_ES_TR_PK" PRIMARY KEY ("CDGO_ESTDO_TRNSCCION")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_D_ESTDOS_TRNSCCN_ESTD_FN_CK" CHECK (estdo_fnal in ('S','N')) ENABLE
   ) ;

