
  CREATE TABLE "WS_G_RECAUDOS_WEBSERVICE_LOG"
   (	"ID_RCDO_WBSRVCE_LOG" NUMBER CONSTRAINT "WS_RCDO_LOG_ID_RCDO_WB_LG_NN" NOT NULL ENABLE,
	"ID_RCDO_WBSRVCE" NUMBER CONSTRAINT "WS_RCDO_LOG_ID_RCDO_WB_NN" NOT NULL ENABLE,
	"OBSRVCION" VARCHAR2(100) CONSTRAINT "WS_RCDO_LOG_OBSRVCION_NN" NOT NULL ENABLE,
	"FCHA_RGSTRO" TIMESTAMP (6) DEFAULT systimestamp,
	 CONSTRAINT "WS_RCDO_LOG_ID_RCDO_WB_LG_PK" PRIMARY KEY ("ID_RCDO_WBSRVCE_LOG")
  USING INDEX  ENABLE,
	 CONSTRAINT "WS_RCDO_LOG_ID_RCDO_WB_FK" FOREIGN KEY ("ID_RCDO_WBSRVCE")
	  REFERENCES "WS_G_RECAUDOS_WEBSERVICE" ("ID_RCDO_WBSRVCE") ENABLE
   ) ;

