prompt --install
@application/set_environment.sql
@application/delete_application.sql
@application/create_application.sql
@application/shared_components/navigation/lists/wizard_de_liquidación_de_rentas.sql
@application/shared_components/navigation/lists/wizard_solicitud_de_acuerdo_de_pago_portal.sql
@application/shared_components/navigation/lists/wizard_proyección_de_acuerdo_de_pago.sql
@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@application/shared_components/navigation/lists/opciones_de_proceso_de_carga.sql
@application/shared_components/navigation/lists/opciones_de_proceso_de_carga_principal.sql
@application/shared_components/navigation/lists/escritorio_menú_de_navegación.sql
@application/shared_components/navigation/lists/escritorio_barra_de_navegación.sql
@application/shared_components/navigation/lists/desktop_navegation_menu_dynamic.sql
@application/shared_components/navigation/lists/lista_perfil.sql
@application/shared_components/navigation/lists/regresar.sql
@application/shared_components/files/acceso_notarios_png.sql
@application/shared_components/files/alumbrado_png.sql
@application/shared_components/files/archivo_1_informacion_exogena_xlsx.sql
@application/shared_components/files/circulacion_png.sql
@application/shared_components/files/durbana_png.sql
@application/shared_components/files/emision_recb_pag_pse_png.sql
@application/shared_components/files/emision_recb_pag_pse_ica_png.sql
@application/shared_components/files/emision_recb_pag_pse_reteica_png.sql
@application/shared_components/files/esl_monteria_png.sql
@application/shared_components/files/estado_de_cuenta_png.sql
@application/shared_components/files/exogena_png.sql
@application/shared_components/files/fondo_rectangular_monteria_png.sql
@application/shared_components/files/formato_solicitud_de_pago_por_cuotas_ica_pdf.sql
@application/shared_components/files/formulario_cancelacion_rit_pdf.sql
@application/shared_components/files/gestion_de_decla_png.sql
@application/shared_components/files/imprimir_cuotas_de_acu_de_pago_png.sql
@application/shared_components/files/it_ac_m_01_plantilla_manual_de_usuario_registro_de_información_exógena_pdf.sql
@application/shared_components/files/logo_x_png.sql
@application/shared_components/files/m001_industria_png.sql
@application/shared_components/files/m002_predial_png.sql
@application/shared_components/files/m007_rentas_png.sql
@application/shared_components/files/m009_pqrs_png.sql
@application/shared_components/files/m010_normatividad_png.sql
@application/shared_components/files/notificaciones_png.sql
@application/shared_components/files/pagos_actos_fisca_png.sql
@application/shared_components/files/plusvalia_png.sql
@application/shared_components/files/proyeccion_de_acu_de_pago_png.sql
@application/shared_components/files/regis_e_impr_ica_png.sql
@application/shared_components/files/registro_de_información_tributaria_rit_pdf.sql
@application/shared_components/files/registro_e_impr_png.sql
@application/shared_components/files/registro_e_impr_retenciones_png.sql
@application/shared_components/files/registro_infrm_trb_rit_png.sql
@application/shared_components/files/resolucion_0279_dic_22_2023_exogena_perido_gravable_20230957_pdf.sql
@application/shared_components/files/shf_r002_19_solicitud_de_tramites_xlsx.sql
@application/shared_components/files/sobretasa_png.sql
@application/shared_components/files/validar_paz_salvo_png.sql
@application/shared_components/files/ventanilla_png.sql
@application/shared_components/files/ventanilla_v2_png.sql
@application/shared_components/files/res_004_2025_exogena_2024_pdf.sql
@application/shared_components/files/instructivo_pago_pliego_cargos_mp4.sql
@application/shared_components/files/archivo_1_informacion_exogena_2023_xlsx.sql
@application/shared_components/files/acceso_usuarios_png.sql
@application/shared_components/files/logo_transparente_tax_png.sql
@application/shared_components/files/exogena_alumbrado_xlsx.sql
@application/shared_components/files/exogena_gasolina_xlsx.sql
@application/shared_components/files/instructivo_rit_pdf.sql
@application/shared_components/files/factura_titulo_png.sql
@application/shared_components/files/gestion_autorizacion_png.sql
@application/shared_components/files/consul_autorizacion_png.sql
@application/shared_components/files/soli_autorizacion_png.sql
@application/plugin_settings.sql
@application/shared_components/security/authorizations/esquema_autorizacion_pagina.sql
@application/shared_components/security/authorizations/esquema_autorizacion_boton.sql
@application/shared_components/security/authorizations/esquema_autorizacion_region.sql
@application/shared_components/navigation/navigation_bar.sql
@application/shared_components/logic/application_processes.sql
@application/shared_components/logic/application_processes.sql
@application/shared_components/logic/application_items.sql
@application/shared_components/logic/application_computations.sql
@application/shared_components/logic/application_settings.sql
@application/shared_components/navigation/tabs/standard.sql
@application/shared_components/navigation/tabs/parent.sql
@application/shared_components/user_interface/lovs/lv_archivos_tipo.sql
@application/shared_components/user_interface/lovs/lv_carga.sql
@application/shared_components/user_interface/lovs/lv_cargos.sql
@application/shared_components/user_interface/lovs/lv_carroceria.sql
@application/shared_components/user_interface/lovs/lv_categoria_vehiculo.sql
@application/shared_components/user_interface/lovs/lv_clases_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_clasificacion_predio.sql
@application/shared_components/user_interface/lovs/lv_columnas.sql
@application/shared_components/user_interface/lovs/lv_convenio_estado.sql
@application/shared_components/user_interface/lovs/lv_convenio_tipo.sql
@application/shared_components/user_interface/lovs/lv_datos_tipo.sql
@application/shared_components/user_interface/lovs/lv_departamentos.sql
@application/shared_components/user_interface/lovs/lv_estado_convenio.sql
@application/shared_components/user_interface/lovs/lv_estado_proceso_carga.sql
@application/shared_components/user_interface/lovs/lv_funcionario.sql
@application/shared_components/user_interface/lovs/lv_grupo_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_identificaciones_tipo.sql
@application/shared_components/user_interface/lovs/lv_impuestos.sql
@application/shared_components/user_interface/lovs/lv_impuesto_subimpuesto.sql
@application/shared_components/user_interface/lovs/lv_impuesto_x_usuario.sql
@application/shared_components/user_interface/lovs/lv_indicadores_economicos.sql
@application/shared_components/user_interface/lovs/lv_linea_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_marcas_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_metodos_asignacion.sql
@application/shared_components/user_interface/lovs/lv_oficina.sql
@application/shared_components/user_interface/lovs/lv_oficina_padre.sql
@application/shared_components/user_interface/lovs/lv_operacion_mat_o.sql
@application/shared_components/user_interface/lovs/lv_operacion_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_operadores_tipo.sql
@application/shared_components/user_interface/lovs/lv_pais.sql
@application/shared_components/user_interface/lovs/lv_periodicidad.sql
@application/shared_components/user_interface/lovs/lv_profesiones.sql
@application/shared_components/user_interface/lovs/lv_recurso_a_i_r.sql
@application/shared_components/user_interface/lovs/lv_servicio_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_si_no.sql
@application/shared_components/user_interface/lovs/lv_si_no_s_n.sql
@application/shared_components/user_interface/lovs/lv_sujeto_estado.sql
@application/shared_components/user_interface/lovs/lv_tabla_destino.sql
@application/shared_components/user_interface/lovs/lv_tipo_dia.sql
@application/shared_components/user_interface/lovs/lv_tipo_instancia.sql
@application/shared_components/user_interface/lovs/lv_tipo_recurso.sql
@application/shared_components/user_interface/lovs/lv_tipo_regimen.sql
@application/shared_components/user_interface/lovs/lv_tipo_responsable.sql
@application/shared_components/user_interface/lovs/lv_tpo_sjto.sql
@application/shared_components/user_interface/lovs/lv_vigencias.sql
@application/pages/page_groups.sql
@application/shared_components/navigation/breadcrumbs/ruta_de_navegación.sql
@application/shared_components/user_interface/templates/page/left_side_column.sql
@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@application/shared_components/user_interface/templates/page/login.sql
@application/shared_components/user_interface/templates/page/master_detail.sql
@application/shared_components/user_interface/templates/page/modal_dialog.sql
@application/shared_components/user_interface/templates/page/right_side_column.sql
@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@application/shared_components/user_interface/templates/page/standard.sql
@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@application/shared_components/user_interface/templates/button/icon.sql
@application/shared_components/user_interface/templates/button/text.sql
@application/shared_components/user_interface/templates/button/text_with_icon.sql
@application/shared_components/user_interface/templates/region/alert.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@application/shared_components/user_interface/templates/region/hero.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@application/shared_components/user_interface/templates/region/carousel_container.sql
@application/shared_components/user_interface/templates/region/buttons_container.sql
@application/shared_components/user_interface/templates/region/collapsible.sql
@application/shared_components/user_interface/templates/region/content_block.sql
@application/shared_components/user_interface/templates/region/inline_dialog.sql
@application/shared_components/user_interface/templates/region/interactive_report.sql
@application/shared_components/user_interface/templates/region/login.sql
@application/shared_components/user_interface/templates/region/standard.sql
@application/shared_components/user_interface/templates/region/tabs_container.sql
@application/shared_components/user_interface/templates/region/title_bar.sql
@application/shared_components/user_interface/templates/region/wizard_container.sql
@application/shared_components/user_interface/templates/region/breadcrumb_prueba.sql
@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@application/shared_components/user_interface/templates/list/badge_list.sql
@application/shared_components/user_interface/templates/list/cards.sql
@application/shared_components/user_interface/templates/list/menu_bar.sql
@application/shared_components/user_interface/templates/list/navigation_bar.sql
@application/shared_components/user_interface/templates/list/wizard_progress.sql
@application/shared_components/user_interface/templates/list/links_list.sql
@application/shared_components/user_interface/templates/list/media_list.sql
@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@application/shared_components/user_interface/templates/list/menu_popup.sql
@application/shared_components/user_interface/templates/list/tabs.sql
@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@application/shared_components/user_interface/templates/report/media_list.sql
@application/shared_components/user_interface/templates/report/alerts.sql
@application/shared_components/user_interface/templates/report/badge_list.sql
@application/shared_components/user_interface/templates/report/cards.sql
@application/shared_components/user_interface/templates/report/comments.sql
@application/shared_components/user_interface/templates/report/search_results.sql
@application/shared_components/user_interface/templates/report/standard.sql
@application/shared_components/user_interface/templates/report/timeline.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@application/shared_components/user_interface/templates/label/optional_floating.sql
@application/shared_components/user_interface/templates/label/required_floating.sql
@application/shared_components/user_interface/templates/label/hidden.sql
@application/shared_components/user_interface/templates/label/optional.sql
@application/shared_components/user_interface/templates/label/optional_above.sql
@application/shared_components/user_interface/templates/label/required.sql
@application/shared_components/user_interface/templates/label/required_above.sql
@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@application/shared_components/user_interface/templates/popuplov.sql
@application/shared_components/user_interface/templates/calendar/calendar.sql
@application/shared_components/user_interface/themes.sql
@application/shared_components/user_interface/theme_style.sql
@application/shared_components/user_interface/theme_files.sql
@application/shared_components/user_interface/theme_display_points.sql
@application/shared_components/user_interface/template_opt_groups.sql
@application/shared_components/user_interface/template_options.sql
@application/shared_components/logic/build_options.sql
@application/shared_components/globalization/language.sql
@application/shared_components/globalization/messages.sql
@application/shared_components/globalization/dyntranslations.sql
@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@application/shared_components/reports/report_queries/re_c_recibo_pago_rentas.sql
@application/shared_components/reports/report_queries/re_c_recibo_cuota_acuerdo.sql
@application/shared_components/reports/report_layouts/re_c_recibo_pago_rentas.sql
@application/shared_components/reports/report_layouts/re_c_recibo_cuota_acuerdo.sql
@application/shared_components/reports/report_layouts/gf_g_prescriones_respuesta.sql
@application/shared_components/security/authentications/custom_portal.sql
@application/shared_components/security/authentications/sin_autenticación.sql
@application/shared_components/security/authentications/custom.sql
@application/shared_components/plugins/region_type/com_infortributos_sujeto_tributo.sql
@application/shared_components/plugins/region_type/com_infortributos_workflow.sql
@application/shared_components/plugins/region_type/com_infortributos_formulario_declaracion.sql
@application/shared_components/plugins/dynamic_action/com_infortributos_notificationmenu.sql
@application/shared_components/plugins/item_type/ca_trevis_apex_ig_simple_checkbox.sql
@application/shared_components/plugins/item_type/be_ctb_select2.sql
@application/shared_components/plugins/item_type/autonumeric.sql
@application/shared_components/plugins/region_type/apex_material_cards.sql
@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@application/shared_components/plugins/process_type/nl_amis_scheffer_process_excel2collection.sql
@application/shared_components/plugins/item_type/unitedcodes_autonumeric.sql
@application/user_interfaces.sql
@application/user_interfaces/combined_files.sql
@application/pages/page_00000.sql
@application/pages/page_00001.sql
@application/pages/page_00002.sql
@application/pages/page_00003.sql
@application/pages/page_00004.sql
@application/pages/page_00005.sql
@application/pages/page_00006.sql
@application/pages/page_00007.sql
@application/pages/page_00008.sql
@application/pages/page_00009.sql
@application/pages/page_00010.sql
@application/pages/page_00011.sql
@application/pages/page_00012.sql
@application/pages/page_00013.sql
@application/pages/page_00014.sql
@application/pages/page_00015.sql
@application/pages/page_00016.sql
@application/pages/page_00017.sql
@application/pages/page_00018.sql
@application/pages/page_00019.sql
@application/pages/page_00020.sql
@application/pages/page_00021.sql
@application/pages/page_00022.sql
@application/pages/page_00023.sql
@application/pages/page_00024.sql
@application/pages/page_00025.sql
@application/pages/page_00026.sql
@application/pages/page_00027.sql
@application/pages/page_00028.sql
@application/pages/page_00029.sql
@application/pages/page_00030.sql
@application/pages/page_00031.sql
@application/pages/page_00032.sql
@application/pages/page_00033.sql
@application/pages/page_00034.sql
@application/pages/page_00040.sql
@application/pages/page_00042.sql
@application/pages/page_00044.sql
@application/pages/page_00056.sql
@application/pages/page_00100.sql
@application/pages/page_00101.sql
@application/pages/page_00102.sql
@application/pages/page_00103.sql
@application/pages/page_00104.sql
@application/pages/page_00105.sql
@application/pages/page_00106.sql
@application/pages/page_00107.sql
@application/pages/page_00108.sql
@application/pages/page_00109.sql
@application/pages/page_00110.sql
@application/pages/page_00111.sql
@application/pages/page_00112.sql
@application/pages/page_00113.sql
@application/pages/page_00114.sql
@application/pages/page_00115.sql
@application/pages/page_00116.sql
@application/pages/page_00117.sql
@application/pages/page_00118.sql
@application/pages/page_00119.sql
@application/pages/page_00120.sql
@application/pages/page_00121.sql
@application/pages/page_00122.sql
@application/pages/page_00200.sql
@application/pages/page_00201.sql
@application/pages/page_00202.sql
@application/pages/page_00203.sql
@application/pages/page_00204.sql
@application/pages/page_00205.sql
@application/pages/page_00206.sql
@application/pages/page_00207.sql
@application/pages/page_00208.sql
@application/pages/page_00280.sql
@application/pages/page_00300.sql
@application/pages/page_00301.sql
@application/pages/page_00302.sql
@application/pages/page_00303.sql
@application/pages/page_00304.sql
@application/pages/page_00305.sql
@application/pages/page_00306.sql
@application/pages/page_00307.sql
@application/pages/page_00308.sql
@application/pages/page_00309.sql
@application/pages/page_00310.sql
@application/pages/page_00311.sql
@application/pages/page_00312.sql
@application/pages/page_00550.sql
@application/pages/page_09999.sql
@application/pages/page_20240.sql
@application/pages/page_20240_002.sql
@application/pages/page_20240_003.sql
@application/pages/page_20240_004.sql
@application/pages/page_20240_005.sql
@application/pages/page_20250.sql
@application/pages/page_20250_002.sql
@application/pages/page_20250_003.sql
@application/pages/page_20250_004.sql
@application/pages/page_20250_005.sql
@application/pages/page_20250_006.sql
@application/deployment/definition.sql
@application/deployment/checks.sql
@application/deployment/buildoptions.sql
@application/end_environment.sql
