prompt --application/shared_components/reports/report_queries/pq_g_slctdes_x_tpo_mtvo_x_fncnrio
begin
wwv_flow_api.create_shared_query(
 p_id=>wwv_flow_api.id(45948078402528066)
,p_name=>'pq_g_slctdes_x_tpo_mtvo_x_fncnrio'
,p_query_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT a.nmro_rdcdo_dsplay,',
'       a.fcha_rdcdo,',
'       a.prmer_nmbre ||'' ''|| a.prmer_aplldo ||'' ''||a.sgndo_aplldo SOLICITANTE,',
'       a.idntfccion_slctnte,',
'       a.impsto,',
'       concat(a.idntfccion, ''_'') idntfccion,',
'       a.id_instncia_fljo,',
'       a.motivo,',
'       a.motivo_pqr,',
'       a.estado_pqr,',
'       a.funcionario,',
'       a.fcha_pryctda,',
'       a.dias_vncer,',
'       a.trea_actual,',
'       a.estdo_trea',
'  FROM (select A.nmro_rdcdo_dsplay,',
'               TRUNC(A.FCHA_RDCDO) FCHA_RDCDO,',
'               k.prmer_nmbre,',
'               k.prmer_aplldo,',
'               k.sgndo_aplldo,',
'               k.idntfccion idntfccion_slctnte,',
'               (select p.nmbre_impsto',
'                  from df_c_impuestos p',
'                 where p.id_impsto = o.id_impsto) impsto,',
'               o.idntfccion,',
'               C.ID_INSTNCIA_FLJO,',
'               d.dscrpcion_fljo as motivo,',
'               (SELECT R.DSCRPCION',
'                  FROM PQ_D_MOTIVOS R',
'                 WHERE R.ID_MTVO = Q.ID_MTVO) MOTIVO_PQR,',
'               l.dscrpcion estado_pqr,',
'               i.prmer_nmbre || '' '' || i.prmer_aplldo as funcionario,',
'               TO_CHAR(A.FCHA_PRYCTDA, ''DD/MM/YYYY'') FCHA_PRYCTDA,',
'               (TRUNC(A.FCHA_PRYCTDA) - TRUNC(SYSDATE)) DIAS_VNCER,',
'               g.nmbre_trea TREA_ACTUAL,',
'               j.estdo_trnscion ESTDO_TREA',
'          from pq_g_solicitudes a',
'          join wf_g_instancias_flujo_gnrdo b',
'            on a.id_instncia_fljo = b.id_instncia_fljo',
'          join wf_g_instancias_flujo c',
'            on b.id_instncia_fljo_gnrdo_hjo = c.id_instncia_fljo',
'          join wf_d_flujos d',
'            on c.id_fljo = d.id_fljo',
'          join wf_g_instancias_transicion e',
'            on c.id_instncia_fljo = e.id_instncia_fljo',
'          join wf_d_flujos_tarea f',
'            on e.id_fljo_trea_orgen = f.id_fljo_trea',
'          join wf_d_tareas g',
'            on f.id_trea = g.id_trea',
'          join sg_g_usuarios h',
'            on e.id_usrio = h.id_usrio',
'          join si_c_terceros i',
'            on h.id_trcro = i.id_trcro',
'          join wf_d_estado_transicion j',
'            on e.id_estdo_trnscion = j.id_estdo_trnscion',
'          join pq_g_solicitantes k',
'            on a.id_slctud = k.id_slctud',
'          join PQ_D_ESTADOS l',
'            on l.id_estdo = a.id_estdo',
'          JOIN PQ_G_SOLICITUDES_MOTIVO N',
'            on n.id_slctud = a.id_slctud',
'          join PQ_G_SLCTDES_MTVO_SJT_IMPST o',
'            on o.id_slctud_mtvo = n.id_slctud_mtvo',
'          join PQ_G_SOLICITUDES_MOTIVO Q',
'            ON A.ID_SLCTUD = Q.ID_SLCTUD',
'         where trunc(a.fcha_rdcdo)         between json_value(:P37_JSON, ''$.fcha_incial'') and json_value(:P37_JSON, ''$.fcha_fnal'')',
'            and h.id_usrio                  = nvl(json_value(:P37_JSON, ''$.id_usrio''), h.id_usrio)',
'           and e.id_instncia_trnscion in',
'               (select max(m.id_instncia_trnscion)',
'                  from wf_g_instancias_transicion m',
'                 where m.id_instncia_fljo = e.id_instncia_fljo)) a',
' WHERE a.ESTDO_TREA NOT IN (''FINALIZADA'')',
'   and a.estado_pqr not in (''RESUELTO'')',
'   AND a.DIAS_VNCER < 0',
' order by a.funcionario, a.FCHA_RDCDO, a.nmro_rdcdo_dsplay'))
,p_format=>'XLS'
,p_output_file_name=>'pq_g_slctdes_x_tpo_mtvo_x_fncnrio'
,p_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(75111966151647088)
,p_shared_query_id=>wwv_flow_api.id(45948078402528066)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'SELECT aa.nmro_rdcdo_dsplay,',
'       aa.fcha_rdcdo,',
'       aa.fcha_pryctda,',
'       aa.solicitante,',
'       aa.idntfccion_slctnte,',
'       aa.motivo_pqr,      ',
'       CASE aa.id_estdo_trnscion',
'                 WHEN 1 THEN',
'                  ''INICIADA''',
'                  WHEN 2 THEN',
'                  ''EJECUTANDO''',
'                 ELSE',
'                  ''FINALIZADA''',
'               END AS id_estdo_trnscion,',
'       aa.funcionario            ',
'  FROM (SELECT a.nmro_rdcdo_dsplay,',
'               TRUNC(a.fcha_rdcdo) as fcha_rdcdo,',
'               TRUNC (a.fcha_pryctda) as fcha_pryctda,',
'               r.nmbre_slctnte SOLICITANTE,',
'               r.idntfccion as IDNTFCCION_SLCTNTE,',
'               a.dscrpcion_mtvo motivo_pqr,',
'               a.estdo_instncia_gnrdo as estdo_trnscion,',
'               h.nmbre_trcro as funcionario, ',
'               g.id_estdo_trnscion                 ',
'          FROM v_pq_g_solicitudes a',
'          LEFT JOIN wf_g_instancias_flujo_gnrdo b',
'            ON a.id_instncia_fljo = b.id_instncia_fljo',
'          JOIN wf_g_instancias_flujo c',
'            ON b.id_instncia_fljo_gnrdo_hjo = c.id_instncia_fljo',
'          JOIN wf_g_instancias_transicion G  ',
'          ON G.ID_INSTNCIA_FLJO=a.id_instncia_fljo_gnrdo ',
'          JOIN V_SG_G_USUARIOS H',
'          ON H.ID_USRIO=G.ID_USRIO      ',
'          JOIN v_PQ_G_SOLICITANTES r',
'            on a.id_slctud = r.id_slctud',
'         WHERE    TRUNC(a.fcha_rdcdo) BETWEEN JSON_VALUE(:P37_JSON, ''$.fcha_incial'') AND JSON_VALUE(:P37_JSON, ''$.fcha_fnal'')',
'                   AND (JSON_VALUE(:P37_JSON, ''$.id_usrio'') IS NULL OR h.id_usrio = JSON_VALUE(:P37_JSON, ''$.id_usrio''))',
'                   -- a.fcha_rdcdo between to_date(''01,01,2023'',''dd,mm,yyyy'')and to_date(''17,01,2024'',''dd,mm,yyyy'')',
'                    AND g.id_instncia_trnscion = (SELECT MAX(id_instncia_trnscion) FROM wf_g_instancias_transicion WHERE ID_INSTNCIA_FLJO = a.id_instncia_fljo_gnrdo)',
'                    and h.id_usrio not in (230017)',
'               --a.fcha_rdcdo between to_date(''01,01,2023'',''dd,mm,yyyy'')and to_date(''15,01,2024'',''dd,mm,yyyy'')',
'  ) aa',
' group by aa.nmro_rdcdo_dsplay,',
'       aa.fcha_rdcdo,',
'       aa.fcha_pryctda,',
'       aa.solicitante,',
'       aa.idntfccion_slctnte,',
'       aa.motivo_pqr,',
'       aa.estdo_trnscion,',
'       aa.funcionario,',
'       aa.id_estdo_trnscion',
'      ORDER BY aa.fcha_rdcdo'))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(75112163932647089)
,p_shared_query_id=>wwv_flow_api.id(45948078402528066)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select upper(b.nmbre_clnte)nmbre_clnte',
'       ,upper(b.slgan)slgan',
'       ,pkg_gn_generalidades.fnc_cl_convertir_blob_a_base64( p_blob => a.file_blob ) as lgo_slgan',
'       ,to_char(systimestamp, ''DD/MM/YYYY HH:MM:SS AM'') HOY',
'       ,:F_IP as ipaddr',
'       ,:F_NMBRE_USRIO as Usuario     ',
'       ,a.file_mimetype',
'      ,json_value(:P37_JSON ,''$.fcha_incial'' )          as fcha_incial',
'      ,json_value(:P37_JSON ,''$.fcha_fnal'' )            as fcha_fnal',
'      ,upper(json_value(:P37_JSON ,''$.nmbre_rprte'' ))  as nmbre_rprte',
'from df_c_imagenes_cliente a',
'join df_s_clientes b on a.cdgo_clnte = b.cdgo_clnte ',
'where a.cdgo_clnte = :F_CDGO_CLNTE',
'and a.cdgo_imgen_clnte = ''L_E'''))
);
end;
/
