prompt --application/shared_components/reports/report_queries/re_c_recibo_cuota_acuerdo
begin
wwv_flow_api.create_shared_query(
 p_id=>wwv_flow_api.id(96774924728424725)
,p_name=>'re_c_recibo_cuota_acuerdo'
,p_query_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'-- Informacion del cliente',
' select upper(b.nmbre_clnte)nmbre_clnte,',
'        upper(b.slgan)slgan,',
'        pkg_gn_generalidades.fnc_cl_convertir_blob_a_base64( p_blob => a.file_blob ) as lgo_slgan,',
'        to_char(systimestamp, ''DD/MON/YYYY'') HOY,',
'        :F_IP as ipaddr,',
'        :F_NMBRE_USRIO as Usuario,       ',
'        a.file_mimetype,',
'        (select upper(nmbre_impsto) from df_c_impuestos m where m.id_impsto = pkg_gn_generalidades.fnc_ca_extract_value( p_xml => :P2_XML , p_nodo => ''P_ID_IMPSTO'' ) )nmbre_impsto,',
'        (select upper(nmbre_rprte) from gn_d_reportes m where m.id_rprte = pkg_gn_generalidades.fnc_ca_extract_value( p_xml => :P2_XML , p_nodo => ''P_ID_RPRTE'' ) )nmbre_rpte',
'   from df_c_imagenes_cliente a',
'   join df_s_clientes b on a.cdgo_clnte = b.cdgo_clnte   ',
'  where a.cdgo_clnte = :F_CDGO_CLNTE',
'    and a.cdgo_imgen_clnte = ''L_E'';'))
,p_format=>'PDF'
,p_output_file_name=>'re_c_recibo_cuota_acuerdo'
,p_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(97576187547006000)
,p_shared_query_id=>wwv_flow_api.id(96774924728424725)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/*select a.cdgo_clnte,',
'        b.id_dcmnto,',
'        b.id_sjto_impsto,',
'        ''*'' || b.idntfccion_sjto || ''*'' cdgo_brra_sjto,',
'        b.nmro_dcmnto,',
'        trunc (b.fcha_vncmnto) fcha_vncmnto,',
'        upper(a.nmbre_clnte)nmbre_clnte,',
'        upper(a.slgan)slgan,',
'        a.nmbre_ofcna,',
'        upper (b.nmbre_impsto) nmbre_impsto,',
'        (:F_NMBRE_USRIO)nmbre_usrio,',
'        to_char (b.fcha_dcmnto, ''YYYYMMDD-HH24:MI:SS'')  fcha_dcmnto,',
'        b.idntfccion_sjto_frmtda                        idntfccion,',
'        b.idntfccion_antrior_frmtda                     idntfccion_antrior,',
'        e.drccion,',
'        d.mtrcla_inmblria,',
'        e.drccion_ntfccion,',
'        e.cdgo_pstal,',
'        d.area_trrno,',
'        d.area_cnstrda,',
'        d.area_grvble,',
'        d.dscrpcion_prdo_dstno,',
'        d.dscrpcion_estrto,',
'        f.nmbre_rzon_scial,',
'        f.cdgo_idntfccion_tpo,',
'        f.idntfccion_rspnsble,',
'        trim(to_char(b.vlor_ttal_dbe ,:F_FRMTO_MNDA))vlor_ttal,',
'        trim(to_char(b.vlor_ttal_dcmnto,:F_FRMTO_MNDA)) vlor_ttal_pgar,',
'        h.cdgo_ean,',
'        pkgbarcode.funcadfac(null,null, null, b.nmro_dcmnto, b.vlor_ttal, b.fcha_vncmnto, h.cdgo_ean, ''S'') txto_cdgo_brra,',
'        pkgbarcode.fungencod(''EANUCC128'',pkgbarcode.funcadfac(null,null, null, b.nmro_dcmnto, b.vlor_ttal, b.fcha_vncmnto  , h.cdgo_ean, ''N'' ) )cdgo_brra,',
'        trim(to_char(i.tsa_dria,''0D9999''))tsa_dria,',
'        to_char(i.fcha_dsde,''DD/MM/YYYY'') || '' Hasta '' || to_char(i.fcha_hsta,''DD/MM/YYYY'') fchas_tsa_mra,',
'        m.vgncia_sldo,',
'        trim(to_char(m.vlor_ttal,:F_FRMTO_MNDA)) vgncia_sldo_ttal,',
'        pkg_gn_generalidades.fnc_co_bancos_recaudadores (p_cdgo_clnte => a.cdgo_clnte, p_id_impsto => b.id_impsto, p_id_impsto_sbmpsto => b.id_impsto_sbmpsto) bncos_rcddres,',
'        pkg_gn_generalidades.fnc_cl_convertir_blob_a_base64( p_blob => l.file_blob ) as lgo_slgan,',
'        -- Detalle del documento',
'        j.nmro_cnvnio,',
'        j.nmro_ctas,',
'        trim(to_char(j.sldo_ctas,:F_FRMTO_MNDA))sldo_ctas,',
'        --trim(to_char(m.vlor_ttal - b.vlor_ttal ,''999,999,999,999,999'')) sldo_ctas,',
'        --(select listagg(vgncia, '', '') within group (order by vgncia) from gf_g_convenios_cartera m where m.id_cnvnio = b.id_cnvnio) cnvnio_vgncia,',
'       (select listagg(a.vgncia, '', '') within group (order by a.vgncia)  as vgncia',
'            from (',
'                      select m.vgncia',
'                        from gf_g_convenios_cartera m ',
'                       where m.id_cnvnio = b.id_cnvnio',
'                       group by m.vgncia',
'                  ) a) as cnvnio_vgncia,',
'        null as cncpto,',
'        null ttal, --trim(to_char(n.ttal ,:F_FRMTO_MNDA))ttal,',
'        null bse_grvble, -- trim(to_char(n.bse_grvble ,:F_FRMTO_MNDA))bse_grvble,',
'        null txto_trfa',
'   from v_df_s_clientes             a',
'   join v_re_g_documentos           b on a.cdgo_clnte           = b.cdgo_clnte      ',
'   left join v_si_i_predios         d on b.id_sjto_impsto       = d.id_sjto_impsto',
'   join v_si_i_sujetos_impuesto     e on b.id_sjto_impsto       = e.id_sjto_impsto',
'   join (',
'                                                         select case when f.cdgo_idntfccion_tpo = ''N'' then',
'                                                                      upper(f.prmer_nmbre)',
'                                                                else',
'                                                                      upper( nvl2( f.sgndo_nmbre, f.prmer_nmbre || '' '' || f.sgndo_nmbre, f.prmer_nmbre )',
'                                                                                 || '' ''',
'                                                                                 || nvl2(f.sgndo_aplldo, f.prmer_aplldo',
'                                                                                 || '' ''',
'                                                                                 || f.sgndo_aplldo, f.prmer_aplldo))',
'                                                                end as nmbre_rzon_scial',
'                                                              , f.cdgo_idntfccion_tpo',
'                                                              , f.idntfccion  as idntfccion_rspnsble',
'                                                              , f.id_sjto_impsto',
'                                                           from si_i_sujetos_responsable f',
'                                                          where f.prncpal_s_n = ''S''',
'                                                   ) f on b.id_sjto_impsto       = f.id_sjto_impsto       ',
'  -- join v_si_i_sujetos_responsable  f on b.id_sjto_impsto       = f.id_sjto_impsto         and f.prncpal_s_n = ''S''',
'  -- join v_re_g_documentos_resumen   g on b.id_dcmnto            = g.id_dcmnto',
'   join df_i_impuestos_subimpuesto  h on b.id_impsto_sbmpsto    = h.id_impsto_sbmpsto',
'   join df_i_tasas_mora             i on a.cdgo_clnte           = i.cdgo_clnte      and b.id_impsto = i.id_impsto and trunc(sysdate) between i.fcha_dsde and i.fcha_hsta                                                            ',
'   join df_c_imagenes_cliente       l on a.cdgo_clnte           = l.cdgo_clnte      and l.cdgo_imgen_clnte = ''L_E''',
'   join table ( pkg_gf_convenios.fnc_co_datos_documento_cnvnio (b.id_dcmnto)) j on j.nmro_cnvnio = j.nmro_cnvnio',
'   join table ( pkg_gn_generalidades.fnc_co_vigencias_con_saldo (:F_CDGO_CLNTE, b.id_sjto_impsto)) m on m.vgncia_sldo = m.vgncia_sldo',
'   --join table ( pkg_re_documentos.fnc_co_dtos_dcmnto_cnvnio_dtll (b.id_dcmnto)) n on n.cncpto  = n.cncpto',
'  where b.id_dcmnto = :F_ID_DCMNTO',
'  order by b.nmro_dcmnto*/',
'',
'select a.cdgo_clnte,',
'        b.id_dcmnto,',
'        e.cdgo_sjto_tpo,',
'        b.id_sjto_impsto,',
'        ''*'' || b.idntfccion_sjto || ''*'' cdgo_brra_sjto,',
'        b.nmro_dcmnto,',
'        trunc (b.fcha_vncmnto) fcha_vncmnto,',
'        upper(a.nmbre_clnte)nmbre_clnte,',
'        upper(a.slgan)slgan,',
'        a.nmbre_ofcna,',
'        upper (b.nmbre_impsto) nmbre_impsto,',
'        (:F_NMBRE_USRIO)nmbre_usrio,',
'        to_char (b.fcha_dcmnto, ''YYYYMMDD-HH24:MI:SS'')  fcha_dcmnto,',
'        b.idntfccion_sjto_frmtda                        idntfccion,',
'        b.idntfccion_antrior_frmtda                     idntfccion_antrior,',
'        e.drccion,',
'        d.mtrcla_inmblria,',
'        e.drccion_ntfccion,',
'        e.cdgo_pstal,',
'        d.area_trrno,',
'        d.area_cnstrda,',
'        d.area_grvble,',
'        d.dscrpcion_prdo_dstno,',
'        d.dscrpcion_estrto,',
'        k.cdgo_idntfccion_tpo as cdgo_idntfccion_tpo_sjto,',
'        k.nmbre_rzon_scial as rzon_scial,',
'        e.idntfccion_sjto as idntfccion_rzon,',
'        z.dscrpcion_vhclo_mrca,',
'        z.dscrpcion_vhclo_lnea,',
'        z.mdlo,',
'        z.dscrpcion_vhclo_clse,',
'        z.dscrpcion_vhclo_crrocria,',
'        z.dscrpcion_vhclo_blndje,',
'        z.clndrje,',
'        e.nmbre_mncpio   as mncpio_rdmnto,',
'        e.nmbre_dprtmnto as dprtmnto_rdmnto,',
'        (',
'             -- Avaluo Ultima liquidacion   ',
'             select to_char(u.bse_grvble,''FM$999G999G999G999G999G999G990'') || '' - ''|| vgncia',
'               from gi_g_liquidaciones u',
'              where u.id_impsto          = b.id_impsto',
'                and u.id_impsto_sbmpsto  = b.id_impsto_sbmpsto',
'                and u.id_sjto_impsto     = b.id_sjto_impsto',
'                and u.cdgo_lqdcion_estdo = ''L''',
'              order by u.vgncia desc',
'              fetch first 1 rows only                                             ',
'         ) as avluo_ultma_lqdcion,',
'        nvl(z.cpcdad_crga, z.cpcdad_psjro) as cpcdad_psjro,        ',
'        case when f.cdgo_idntfccion_tpo = ''N'' then',
'                  upper(f.prmer_nmbre)',
'            else',
'                  upper( nvl2( f.sgndo_nmbre, f.prmer_nmbre || '' '' || f.sgndo_nmbre, f.prmer_nmbre )',
'                             || '' ''',
'                             || nvl2(f.sgndo_aplldo, f.prmer_aplldo',
'                             || '' ''',
'                             || f.sgndo_aplldo, f.prmer_aplldo))',
'        end nmbre_rzon_scial,',
'        f.cdgo_idntfccion_tpo,',
'        f.idntfccion_rspnsble,',
'        trim(to_char(b.vlor_ttal_dbe ,:F_FRMTO_MNDA))vlor_ttal,',
'        trim(to_char(b.vlor_ttal_dcmnto,:F_FRMTO_MNDA)) vlor_ttal_pgar,',
'        h.cdgo_ean,',
'        pkgbarcode.funcadfac(null,null, null, b.nmro_dcmnto, b.vlor_ttal, b.fcha_vncmnto, h.cdgo_ean, ''S'') txto_cdgo_brra,',
'        pkgbarcode.fungencod(''EANUCC128'',pkgbarcode.funcadfac(null,null, null, b.nmro_dcmnto, b.vlor_ttal, b.fcha_vncmnto  , h.cdgo_ean, ''N'' ) )cdgo_brra,',
'        trim(to_char(i.tsa_dria,''0D9999''))tsa_dria,',
'        to_char(i.fcha_dsde,''DD/MM/YYYY'') || '' Hasta '' || to_char(i.fcha_hsta,''DD/MM/YYYY'') fchas_tsa_mra,',
'        m.vgncia_sldo,',
'        trim(to_char(m.vlor_ttal,:F_FRMTO_MNDA)) vgncia_sldo_ttal,',
'        pkg_gn_generalidades.fnc_co_bancos_recaudadores (p_cdgo_clnte => a.cdgo_clnte, p_id_impsto => b.id_impsto, p_id_impsto_sbmpsto => b.id_impsto_sbmpsto) bncos_rcddres,',
'        pkg_gn_generalidades.fnc_cl_convertir_blob_a_base64( p_blob => l.file_blob ) as lgo_slgan,',
'        -- Detalle del documento',
'        j.nmro_cnvnio,',
'        j.nmro_ctas,',
'        trim(to_char(j.sldo_ctas,:F_FRMTO_MNDA))sldo_ctas,',
'       (select listagg(a.vgncia, '', '') within group (order by a.vgncia)  as vgncia',
'            from (',
'                      select m.vgncia',
'                        from gf_g_convenios_cartera m ',
'                       where m.id_cnvnio = b.id_cnvnio',
'                       group by m.vgncia',
'                  ) a) as cnvnio_vgncia,',
'        null as cncpto,',
'        null ttal, --trim(to_char(n.ttal ,:F_FRMTO_MNDA))ttal,',
'        null bse_grvble, -- trim(to_char(n.bse_grvble ,:F_FRMTO_MNDA))bse_grvble,',
'        null txto_trfa',
'   from v_df_s_clientes             a',
'   join v_re_g_documentos           b on a.cdgo_clnte           = b.cdgo_clnte      ',
'   left join v_si_i_predios         d on b.id_sjto_impsto       = d.id_sjto_impsto',
'   left join si_i_personas          k on b.id_sjto_impsto       = k.id_sjto_impsto',
'   left join v_si_i_vehiculos       z on b.id_sjto_impsto       = z.id_sjto_impsto',
'   join v_si_i_sujetos_impuesto     e on b.id_sjto_impsto       = e.id_sjto_impsto',
'   join v_si_i_sujetos_responsable  f on b.id_sjto_impsto       = f.id_sjto_impsto         and f.prncpal_s_n = ''S''',
'   join df_i_impuestos_subimpuesto  h on b.id_impsto_sbmpsto    = h.id_impsto_sbmpsto',
'   join df_i_tasas_mora             i on a.cdgo_clnte           = i.cdgo_clnte      and b.id_impsto = i.id_impsto and trunc(sysdate) between i.fcha_dsde and i.fcha_hsta                                                            ',
'   join df_c_imagenes_cliente       l on a.cdgo_clnte           = l.cdgo_clnte      and l.cdgo_imgen_clnte = ''L_E''',
'   join table ( pkg_gf_convenios.fnc_co_datos_documento_cnvnio (b.id_dcmnto)) j on j.nmro_cnvnio = j.nmro_cnvnio',
'   join table ( pkg_gn_generalidades.fnc_co_vigencias_con_saldo (:F_CDGO_CLNTE, b.id_sjto_impsto)) m on m.vgncia_sldo = m.vgncia_sldo',
'  where b.id_dcmnto = :F_ID_DCMNTO',
'  order by b.nmro_dcmnto'))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(97576338470006001)
,p_shared_query_id=>wwv_flow_api.id(96774924728424725)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select ''Valor Cuota''              concepto,',
'        to_char(sum(vlor_dbe - vlor_hber),:F_FRMTO_MNDA) a ',
'   from re_g_documentos_detalle',
'  where id_dcmnto   = :F_ID_DCMNTO;',
''))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(97576584324006001)
,p_shared_query_id=>wwv_flow_api.id(96774924728424725)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
' ',
'  select  nmro_cta',
'        , to_char(nvl(a.vlor_cptal,0),:F_FRMTO_MNDA)            vlor_cptal',
'         ,to_char(nvl(a.vlor_intres,0),:F_FRMTO_MNDA)           vlor_intres',
'        , to_char(nvl(a.vlor_intres_fnnccion,0),:F_FRMTO_MNDA)  vlor_intres_fnnccion',
'        , to_char(nvl(a.vlor_intres_vncdo,0),:F_FRMTO_MNDA)     vlor_intres_vncdo',
'        , to_char(nvl(a.vlor_dscnto,0),:F_FRMTO_MNDA)           vlor_dscnto',
'        , to_char((nvl(a.vlor_cptal,0) + nvl(a.vlor_intres,0) + nvl(a.vlor_intres_fnnccion,0) + nvl(a.vlor_intres_vncdo,0) - nvl(a.vlor_dscnto,0)),:F_FRMTO_MNDA) total',
' from (',
' select *  ',
'  from (select cdgo_cncpto_tpo_cnvnio, nmro_cta,',
'			   case',
'				 when a.cdgo_cncpto_tpo_cnvnio = ''D'' then',
'                       sum(a.vlor_hber)  ',
'                 when a.cdgo_cncpto_tpo_cnvnio is null then',
'                      sum(a.vlor_dbe)  ',
'				 else',
'                    sum(a.vlor_dbe - a.vlor_hber)  ',
'			   end as vlor   ',
'		  from re_g_documentos_detalle a',
'		 where a.id_dcmnto = :F_ID_DCMNTO',
'		  group by cdgo_cncpto_tpo_cnvnio,  nmro_cta    ',
'        )  ',
'pivot(sum(vlor)',
'   for cdgo_cncpto_tpo_cnvnio in(''C'' 	vlor_cptal,',
'                                 ''I'' 	vlor_intres, ',
'                                 ''IF'' 	vlor_intres_fnnccion,',
'                                 ''IV'' 	vlor_intres_vncdo,',
'                                 ''D'' 	vlor_dscnto))',
'        order by nmro_cta) a;'))
);
end;
/
