prompt --application/shared_components/reports/report_queries/re_g_lstdo_prcmnto_rcdo_dtllds
begin
wwv_flow_api.create_shared_query(
 p_id=>wwv_flow_api.id(22200557713610369)
,p_name=>'re_g_lstdo_prcmnto_rcdo_dtllds'
,p_query_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select c.dscrpcion_bnco',
'                                                     , a.fcha_rcdo',
'                                                     , b.*',
'                                                  from re_g_recaudos a',
'                                                  join (',
'                                                           select a.id_orgen as id_rcdo',
'                                                                , a.vgncia',
'                                                                , c.prdo',
'                                                                , a.id_prdo',
'                                                                , a.id_cncpto',
'                                                                , b.cdgo_cncpto',
'                                                                , b.dscrpcion',
'                                                                , a.cdgo_mvmnto_tpo',
'                                                                , d.dscrpcion as dscrpcion_mvmnto_tpo',
'                                                                , a.vlor_hber as vlor',
'                                                             from gf_g_movimientos_detalle a',
'                                                             join df_i_conceptos b',
'                                                               on a.id_cncpto = b.id_cncpto',
'                                                             join df_i_periodos c',
'                                                               on a.id_prdo   = c.id_prdo',
'                                                             join gf_d_movimiento_tipo d',
'                                                               on a.cdgo_mvmnto_tpo = d.cdgo_mvmnto_tpo',
'                                                            where a.cdgo_mvmnto_orgn = ''RE''',
'                                                              and a.cdgo_mvmnto_tpo in ( ''PC'' , ''PI'' )',
'                                                       ) b',
'                                                      on a.id_rcdo         = b.id_rcdo',
'                                                    join v_re_g_recaudos_control c',
'                                                      on a.id_rcdo_cntrol  = c.id_rcdo_cntrol        ',
'                                                   where a.cdgo_rcdo_estdo = ''AP''',
'                                                     and c.cdgo_clnte        = :F_CDGO_CLNTE',
'                                                     and c.id_impsto         = nvl( pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                                             , p_nodo => ''id_impsto'' ) , c.id_impsto )',
'                                                     and c.id_impsto_sbmpsto = nvl( pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                                             , p_nodo => ''id_impsto_sbmpsto'' ) , c.id_impsto_sbmpsto )',
'                                                     and a.fcha_rcdo between pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                                      , p_nodo => ''fcha_incial'' )',
'                                                     and pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                  , p_nodo => ''fcha_fnal'' )',
'                                                     and c.id_bnco = nvl( pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                                 , p_nodo => ''id_bnco'' ) , c.id_bnco )',
'                                                order by c.nmbre_bnco',
'                                                       , a.fcha_rcdo',
'                                                       , b.vgncia',
'                                                       , b.prdo',
'                                                       , b.cdgo_cncpto',
'                                                       , b.dscrpcion_mvmnto_tpo'))
,p_format=>'PDF'
,p_output_file_name=>'re_g_lstdo_prcmnto_rcdo_dtllds'
,p_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(21589631979253743)
,p_shared_query_id=>wwv_flow_api.id(22200557713610369)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'                                             ',
'     select a.*',
'          , json_value(:P37_JSON ,''$.fcha_incial'' ) as fcha_incial',
'          , json_value(:P37_JSON ,''$.fcha_fnal'' ) as fcha_fnal',
'          , upper(json_value(:P37_JSON ,''$.nmbre_rprte'' )) as nmbre_rprte                                              ',
'       from (',
'                       select c.nmbre_bnco',
'                            , c.dscrpcion_bnco',
'                            , trunc(a.fcha_rcdo) as fcha_rcdo',
'                            , c.dscrpcion_bnco || trunc(a.fcha_rcdo) as grpo',
'                            , b.vgncia',
'                            , b.prdo',
'                            , b.id_prdo',
'                            , b.id_cncpto',
'                            , b.cdgo_cncpto',
'                            , b.dscrpcion',
'                            , b.cdgo_mvmnto_tpo',
'                            , b.dscrpcion_mvmnto_tpo',
'                            , sum(b.vlor) as vlor',
'                         from re_g_recaudos a',
'                         join (',
'                                  select a.id_orgen as id_rcdo',
'                                       , a.vgncia',
'                                       , c.prdo',
'                                       , a.id_prdo',
'                                       , a.id_cncpto',
'                                       , b.cdgo_cncpto',
'                                       , b.dscrpcion',
'                                       , a.cdgo_mvmnto_tpo',
'                                       , d.dscrpcion as dscrpcion_mvmnto_tpo',
'                                       , a.vlor_hber as vlor',
'                                    from gf_g_movimientos_detalle a',
'                                    join df_i_conceptos b',
'                                      on a.id_cncpto = b.id_cncpto',
'                                    join df_i_periodos c',
'                                      on a.id_prdo   = c.id_prdo',
'                                    join gf_d_movimiento_tipo d',
'                                      on a.cdgo_mvmnto_tpo = d.cdgo_mvmnto_tpo',
'                                   where a.cdgo_mvmnto_orgn = ''RE''',
'                                     and a.cdgo_mvmnto_tpo in ( ''PC'' , ''PI'' )',
'                              ) b',
'                             on a.id_rcdo         = b.id_rcdo',
'                           join v_re_g_recaudos_control c',
'                             on a.id_rcdo_cntrol  = c.id_rcdo_cntrol        ',
'                          where a.cdgo_rcdo_estdo = ''AP''',
'                            and c.cdgo_clnte        = :F_CDGO_CLNTE',
'                            and c.id_impsto         = nvl( json_value(:P37_JSON ,''$.id_impsto'' ) , c.id_impsto )',
'                            and c.id_impsto_sbmpsto = nvl( json_value(:P37_JSON ,''$.id_impsto_sbmpsto'' ) , c.id_impsto_sbmpsto )',
'                            and a.fcha_rcdo between json_value(:P37_JSON ,''$.fcha_incial'' )',
'                                                and json_value(:P37_JSON ,''$.fcha_fnal'' )',
'                            and c.id_bnco = nvl( json_value(:P37_JSON ,''$.id_bnco'' ) , c.id_bnco )',
'                       group by c.nmbre_bnco',
'                              , c.dscrpcion_bnco',
'                              , trunc(a.fcha_rcdo)',
'                              , b.vgncia',
'                              , b.prdo',
'                              , b.id_prdo',
'                              , b.id_cncpto',
'                              , b.cdgo_cncpto',
'                              , b.dscrpcion',
'                              , b.cdgo_mvmnto_tpo',
'                              , b.dscrpcion_mvmnto_tpo',
'            ) a          ',
'     order by a.nmbre_bnco',
'            , a.fcha_rcdo',
'            , a.vgncia',
'            , a.prdo',
'            , a.cdgo_cncpto',
'            , a.dscrpcion_mvmnto_tpo'))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(21589835239253743)
,p_shared_query_id=>wwv_flow_api.id(22200557713610369)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select upper(b.nmbre_clnte)nmbre_clnte,',
'        upper(b.slgan)slgan,',
'         pkg_gn_generalidades.fnc_cl_convertir_blob_a_base64( p_blob => a.file_blob ) as lgo_slgan,',
'          to_char(systimestamp, ''DD/MM/YYYY'') HOY,',
'         :F_IP as ipaddr,',
'         :F_NMBRE_USRIO as Usuario,       ',
'        a.file_mimetype,',
'        (select upper(nmbre_impsto) from df_c_impuestos m where m.id_impsto = :P_ID_IMPSTO)nmbre_impsto,',
'        (select upper(nmbre_rprte) from gn_d_reportes m where m.id_rprte = :P_ID_RPRTE)nmbre_rpte',
'   from df_c_imagenes_cliente a',
'   join df_s_clientes b on a.cdgo_clnte = b.cdgo_clnte ',
'  where a.cdgo_clnte = :F_CDGO_CLNTE',
'    and a.cdgo_imgen_clnte = ''L_E''',
'    '))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(21590094022253743)
,p_shared_query_id=>wwv_flow_api.id(22200557713610369)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  select sum( b.vlor_sldo_fvor ) as vlor_sldo_fvor',
'    from v_re_g_recaudos_control a',
'    join v_re_g_recaudos_detalle b',
'      on a.id_rcdo_cntrol = b.id_rcdo_cntrol',
'   where a.cdgo_clnte        = :F_CDGO_CLNTE',
'     and a.id_impsto         = nvl( json_value(:P37_JSON ,''$.id_impsto'' ) , a.id_impsto )',
'     and a.id_impsto_sbmpsto = nvl( json_value(:P37_JSON ,''$.id_impsto_sbmpsto'' ) , a.id_impsto_sbmpsto )',
'     and b.fcha_rcdo between json_value(:P37_JSON ,''$.fcha_incial'' )',
'                         and json_value(:P37_JSON ,''$.fcha_fnal'' )',
'     and a.id_bnco = nvl( json_value(:P37_JSON ,''$.id_bnco'' ) , a.id_bnco )'))
);
end;
/
