prompt --application/shared_components/reports/report_queries/re_g_lstdo_rcdo_vgncia_x_mes
begin
wwv_flow_api.create_shared_query(
 p_id=>wwv_flow_api.id(23106720395332716)
,p_name=>'re_g_lstdo_rcdo_vgncia_x_mes'
,p_query_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
' select  nvl(enero,0) as enero',
'                , nvl(febrero,0) as febrero',
'                , nvl(marzo,0) as marzo',
'                , nvl(abril,0) as abril',
'                , nvl(mayo,0) as mayo',
'                , nvl(junio,0) as junio',
'                , nvl(julio,0) as julio',
'                , nvl(agosto,0) as agosto',
'                , nvl(septiembre,0) as septiembre',
'                , nvl(octubre,0) as octubre',
'                , nvl(noviembre,0) as noviembre',
'                , nvl(diciembre,0) as diciembre',
'                , id_impsto',
'                , nmbre_impsto',
'             from   ',
'                     (',
'                         select     extract(year from b.fcha_rcdo) as vgncia',
'                                  , extract(month from b.fcha_rcdo) as mes',
'                                  , a.vlor_rcdos     ',
'                                  , a.id_impsto',
'                                  , a.nmbre_impsto',
'                                from v_re_g_recaudos_control a',
'                                    join re_g_recaudos b',
'                                      on b.id_rcdo_cntrol = a.id_rcdo_cntrol',
'                               where b.cdgo_rcdo_estdo=''AP''',
'                                 and a.cdgo_clnte        = :F_CDGO_CLNTE',
'                                 and a.id_impsto         = nvl( pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                         , p_nodo => ''id_impsto'' ) , a.id_impsto )',
'                                 and a.id_impsto_sbmpsto = nvl( pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                         , p_nodo => ''id_impsto_sbmpsto'' ) , a.id_impsto_sbmpsto )',
'                                 and b.fcha_rcdo between pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                                  , p_nodo => ''fcha_incial'' )',
'                                 and pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                              , p_nodo => ''fcha_fnal'' )',
'                                 and a.id_bnco = nvl( pkg_gn_generalidades.fnc_ca_extract_value( p_xml  => :P2_XML',
'                                                                                             , p_nodo => ''id_bnco'' ) , a.id_bnco )',
'                      )',
'             pivot ( sum(vlor_rcdos) for (mes) in (1 as enero,2 as febrero,3 as marzo,4 as abril,5 as mayo,6 as junio',
'                                                       ,  7 as julio,8 as agosto,9 as septiembre,10 as octubre,11 as noviembre,12 as diciembre))'))
,p_format=>'PDF'
,p_output_file_name=>'re_g_lstdo_rcdo_vgncia_x_mes'
,p_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(76630155531546657)
,p_shared_query_id=>wwv_flow_api.id(23106720395332716)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select vgncia,',
'       id_impsto,',
'       nmbre_impsto,',
'       nvl(enero_numero, 0) enero_numero,',
'       nvl(enero_valor, 0) enero_valor,',
'       nvl(febrero_numero, 0) febrero_numero,',
'       nvl(febrero_valor, 0) febrero_valor,',
'       nvl(marzo_numero, 0) marzo_numero,',
'       nvl(marzo_valor, 0) marzo_valor,',
'       nvl(abril_numero, 0) abril_numero,',
'       nvl(abril_valor, 0) abril_valor,',
'       nvl(mayo_numero, 0) mayo_numero,',
'       nvl(mayo_valor, 0) mayo_valor,',
'       nvl(junio_numero, 0) junio_numero,',
'       nvl(junio_valor, 0) junio_valor,',
'       nvl(julio_numero, 0) julio_numero,',
'       nvl(julio_valor, 0) julio_valor,',
'       nvl(agosto_numero, 0) agosto_numero,',
'       nvl(agosto_valor, 0) agosto_valor,',
'       nvl(septiembre_numero, 0) septiembre_numero,',
'       nvl(septiembre_valor, 0) septiembre_valor,',
'       nvl(octubre_numero, 0) octubre_numero,',
'       nvl(octubre_valor, 0) octubre_valor,',
'       nvl(noviembre_numero, 0) noviembre_numero,',
'       nvl(noviembre_valor, 0) noviembre_valor,',
'       nvl(diciembre_numero, 0) diciembre_numero,',
'       nvl(diciembre_valor, 0) diciembre_valor,',
'       (nvl(enero_numero, 0) + nvl(febrero_numero, 0) +',
'       nvl(marzo_numero, 0) + nvl(abril_numero, 0) + nvl(mayo_numero, 0) +',
'       nvl(junio_numero, 0) + nvl(julio_numero, 0) + nvl(agosto_numero, 0) +',
'       nvl(septiembre_numero, 0) + nvl(octubre_numero, 0) +',
'       nvl(noviembre_numero, 0) + nvl(diciembre_numero, 0)) numero_total,',
'       (nvl(enero_valor, 0) + nvl(febrero_valor, 0) + nvl(marzo_valor, 0) +',
'       nvl(abril_valor, 0) + nvl(mayo_valor, 0) + nvl(junio_valor, 0) +',
'       nvl(julio_valor, 0) + nvl(agosto_valor, 0) +',
'       nvl(septiembre_valor, 0) + nvl(octubre_valor, 0) +',
'       nvl(noviembre_valor, 0) + nvl(diciembre_valor, 0)) valor_total,',
'       json_value(:p37_json, ''$.fcha_incial'') as fcha_incial,',
'       json_value(:p37_json, ''$.fcha_fnal'') as fcha_fnal,',
'       upper(json_value(:p37_json, ''$.nmbre_rprte '')) as nmbre_rprte',
'  from (select extract(year from b.fcha_rcdo) as vgncia,',
'               extract(month from b.fcha_rcdo) as mes,',
'               sum(b.vlor) vlor,',
'               d.id_impsto,',
'               d.nmbre_impsto,',
'               count(distinct(b.id_rcdo)) nmro_rcdos',
'          from v_re_g_recaudos_control a',
'          join re_g_recaudos b',
'            on b.id_rcdo_cntrol = a.id_rcdo_cntrol',
'          join si_i_sujetos_impuesto c',
'            on b.id_sjto_impsto = c.id_sjto_impsto',
'          join df_c_impuestos d',
'            on c.id_impsto = d.id_impsto',
'         where b.cdgo_rcdo_estdo = ''AP''',
'           and a.cdgo_clnte = :f_cdgo_clnte',
'           and d.id_impsto =',
'               nvl(json_value(:p37_json, ''$.id_impsto''), d.id_impsto)',
'              --and a.id_impsto_sbmpsto = nvl( json_value(:p37_json ,''$.id_impsto_sbmpsto'' ) , a.id_impsto_sbmpsto )',
'           and b.fcha_rcdo between json_value(:p37_json, ''$.fcha_incial'') and',
'               json_value(:p37_json, ''$.fcha_fnal'')',
'           and a.id_bnco =',
'               nvl(json_value(:p37_json, ''$.id_bnco''), a.id_bnco)',
'         group by extract(year from b.fcha_rcdo),',
'                  extract(month from b.fcha_rcdo),',
'                  d.id_impsto,',
'                  d.nmbre_impsto)',
'pivot(sum(nmro_rcdos) as numero, sum(vlor) as valor',
'   for(mes) in(1 as enero,',
'               2 as febrero,',
'               3 as marzo,',
'               4 as abril,',
'               5 as mayo,',
'               6 as junio,',
'               7 as julio,',
'               8 as agosto,',
'               9 as septiembre,',
'               10 as octubre,',
'               11 as noviembre,',
'               12 as diciembre)) e'))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(76630321736546657)
,p_shared_query_id=>wwv_flow_api.id(23106720395332716)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'select upper(b.nmbre_clnte)nmbre_clnte,',
'        upper(b.slgan)slgan,',
'         pkg_gn_generalidades.fnc_cl_convertir_blob_a_base64( p_blob => a.file_blob ) as lgo_slgan,',
'          to_char(systimestamp, ''DD/MM/YYYY'') HOY,',
'         :F_IP as ipaddr,',
'         :F_NMBRE_USRIO as Usuario,       ',
'        a.file_mimetype,',
'        (select upper(nmbre_impsto) from df_c_impuestos m where m.id_impsto = :P_ID_IMPSTO)nmbre_impsto,',
'        (select upper(nmbre_rprte) from gn_d_reportes m where m.id_rprte = :P_ID_RPRTE)nmbre_rpte',
'   from df_c_imagenes_cliente a',
'   join df_s_clientes b on a.cdgo_clnte = b.cdgo_clnte ',
'  where a.cdgo_clnte = :F_CDGO_CLNTE',
'    and a.cdgo_imgen_clnte = ''L_E''',
'    '))
);
end;
/
