prompt --application/shared_components/reports/report_queries/si_g_gnral_prptrio_x_prmtros
begin
wwv_flow_api.create_shared_query(
 p_id=>wwv_flow_api.id(40433030475669049)
,p_name=>'si_g_gnral_prptrio_x_prmtros'
,p_query_text=>wwv_flow_string.join(wwv_flow_t_varchar2(
' select trim( c.prmer_nmbre||'' ''||c.sgndo_nmbre||'' ''||c.prmer_aplldo||'' ''||c.sgndo_aplldo) as nmbre',
'              , c.idntfccion',
'              , b.idntfccion_sjto_frmtda',
'              , b.idntfccion_sjto',
'              , b.drccion',
'              , a.mtrcla_inmblria',
'              , a.dscrpcion_prdio_clsfccion',
'              , a.avluo_ctstral',
'              , a.area_trrno',
'              , a.area_cnstrda ',
'              , a.dscrpcion_prdo_dstno',
'              , a.dscrpcion_estrto',
'              , a.cdgo_estrto',
'              , json_value(:P14_JSON, ''$.nmbre_rprte'') as nombre_reporte',
'           from v_si_i_predios a',
'           join v_si_i_sujetos_impuesto b',
'             on a.id_sjto_impsto       = b.id_sjto_impsto',
'           join si_i_sujetos_responsable c',
'             on b.id_sjto_impsto       = c.id_sjto_impsto',
'          where b.cdgo_clnte           = :F_CDGO_CLNTE ',
'            and b.id_impsto            = json_value( :P14_JSON, ''$.id_impsto'')',
'            and a.cdgo_prdio_clsfccion = nvl( json_value( :P14_JSON , ''$.dscrpcion_prdio_clsfccion'' ), a.cdgo_prdio_clsfccion )',
'            and a.id_prdio_dstno       = nvl( json_value( :P14_JSON , ''$.prdio_dstno''),a.id_prdio_dstno)',
'            and a.avluo_ctstral ',
'        between json_value( :P14_JSON , ''$.avluo_dsde'' ) ',
'            and json_value( :P14_JSON , ''$.avluo_hsta'' )',
'            and a.cdgo_estrto          = nvl( json_value(:P14_JSON, ''$.estrto'' ) , a.cdgo_estrto )',
'            and substr( b.idntfccion_sjto , 1 , 4 ) || substr( b.idntfccion_sjto , 9 , 4 ) = nvl( json_value(:P14_JSON, ''$.mnzna'') , substr( b.idntfccion_sjto , 1 , 4 ) || substr( b.idntfccion_sjto , 9 , 4 ))',
'            and substr( b.idntfccion_sjto , 1 , 4 )                                        = nvl( json_value(:P14_JSON, ''$.sctor'') , substr( b.idntfccion_sjto , 1 , 4 ));'))
,p_report_layout_id=>wwv_flow_api.id(45681153339235509)
,p_format=>'PDF'
,p_output_file_name=>'si_g_gnral_prptrio_x_prmtros'
,p_content_disposition=>'ATTACHMENT'
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(22521580956762928)
,p_shared_query_id=>wwv_flow_api.id(40433030475669049)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'/*',
'            with t_temp as (',
'                        select y.id_sjto_impsto',
'                              , trim( y.prmer_nmbre||'' ''||y.sgndo_nmbre||'' ''||y.prmer_aplldo||'' ''||y.sgndo_aplldo) as nmbre',
'                              , y.idntfccion',
'                              , x.idntfccion_sjto_frmtda',
'                              , x.idntfccion_sjto',
'                              , x.drccion',
unistr('                              , decode(y.prncpal_s_n,''S'',''S\00ED'',''No'') as prncipal'),
'                          from v_si_i_sujetos_impuesto  x',
'                          join si_i_sujetos_responsable y on x.id_sjto_impsto = y.id_sjto_impsto',
'                         where x.cdgo_clnte           = :F_CDGO_CLNTE ',
'                           and x.id_impsto            = json_value( :P37_JSON, ''$.id_impsto'')',
'                           and x.id_sjto_estdo        = nvl(json_value(:P37_JSON, ''$.estdo'' ),x.id_sjto_estdo)',
'                           and trim( y.prmer_nmbre||'' ''||y.sgndo_nmbre||'' ''||y.prmer_aplldo||'' ''||y.sgndo_aplldo) like ''%''||trim(json_value(:P37_JSON, ''$.nmbre_prptrio''))||''%''',
'                            or trim( y.prmer_nmbre||'' ''||y.sgndo_nmbre||'' ''||y.prmer_aplldo||'' ''||y.sgndo_aplldo) is null',
'                           and y.idntfccion           = nvl( json_value(:P37_JSON, ''$.idntfccion_prptrio'' ) ,  y.idntfccion ) ',
'                    )',
'         select b.nmbre',
'              , b.idntfccion',
'              , b.idntfccion_sjto_frmtda',
'              , b.idntfccion_sjto',
'              , b.drccion',
'              , a.mtrcla_inmblria',
'              , a.dscrpcion_prdio_clsfccion',
'              , a.avluo_ctstral',
'              , a.area_trrno',
'              , a.area_cnstrda ',
'              , a.dscrpcion_prdo_dstno',
'              , a.dscrpcion_estrto',
'              , a.cdgo_estrto',
'              , upper(json_value(:P37_JSON, ''$.nmbre_rprte'')) as nombre_reporte',
'              , json_value(:P37_JSON, ''$.nmbre_prptrio'') as nmbre_prptrio',
'              , b.prncipal ',
'          from v_si_i_predios a',
'          join t_temp         b on a.id_sjto_impsto = b.id_sjto_impsto',
'         where a.cdgo_prdio_clsfccion  = nvl( json_value( :P37_JSON , ''$.dscrpcion_prdio_clsfccion'' ), a.cdgo_prdio_clsfccion )',
'            and a.id_prdio_dstno       = nvl( json_value( :P37_JSON , ''$.prdio_dstno''),a.id_prdio_dstno)',
'            and a.avluo_ctstral        between json_value( :P37_JSON , ''$.avluo_dsde'' ) ',
'                                          and json_value( :P37_JSON , ''$.avluo_hsta'' )',
'            and a.cdgo_estrto          = nvl( json_value(:P37_JSON, ''$.estrto'' ) , a.cdgo_estrto );     */',
'           ',
'select trim( c.prmer_nmbre||'' ''||c.sgndo_nmbre||'' ''||c.prmer_aplldo||'' ''||c.sgndo_aplldo) as nmbre',
'              , c.idntfccion',
'              , b.idntfccion_sjto_frmtda',
'              , b.idntfccion_sjto',
'              , b.drccion',
'              , a.mtrcla_inmblria',
'              , a.dscrpcion_prdio_clsfccion',
'              , a.avluo_ctstral',
'              , a.area_trrno',
'              , a.area_cnstrda ',
'              , a.dscrpcion_prdo_dstno',
'              , a.dscrpcion_estrto',
'              , a.cdgo_estrto',
'              , upper(json_value(:P37_JSON, ''$.nmbre_rprte'')) as nombre_reporte',
'              , json_value(:P37_JSON, ''$.nmbre_prptrio'') as nmbre_prptrio',
unistr('              , decode(c.prncpal_s_n,''S'',''S\00ED'',''No'') as prncipal'),
'           from v_si_i_predios a',
'           join v_si_i_sujetos_impuesto  b',
'             on a.id_sjto_impsto       = b.id_sjto_impsto',
'           join si_i_sujetos_responsable c',
'             on b.id_sjto_impsto       = c.id_sjto_impsto',
'          where b.cdgo_clnte           = :F_CDGO_CLNTE ',
'            and b.id_impsto            = json_value( :P37_JSON, ''$.id_impsto'')',
'            and b.id_sjto_estdo        = nvl(json_value(:P37_JSON, ''$.estdo'' ),b.id_sjto_estdo)',
'            and a.cdgo_prdio_clsfccion = nvl( json_value( :P37_JSON , ''$.dscrpcion_prdio_clsfccion'' ), a.cdgo_prdio_clsfccion )',
'            and a.id_prdio_dstno       = nvl( json_value( :P37_JSON , ''$.prdio_dstno''),a.id_prdio_dstno)',
'            and a.avluo_ctstral ',
'        between json_value( :P37_JSON , ''$.avluo_dsde'' ) ',
'            and json_value( :P37_JSON , ''$.avluo_hsta'' )',
'            and a.cdgo_estrto          = nvl( json_value(:P37_JSON, ''$.estrto'' ) , a.cdgo_estrto )            ',
'            and trim( c.prmer_nmbre||'' ''||c.sgndo_nmbre||'' ''||c.prmer_aplldo||'' ''||c.sgndo_aplldo) like ''%''||trim(json_value(:P37_JSON, ''$.nmbre_prptrio''))||''%''',
'             or trim( c.prmer_nmbre||'' ''||c.sgndo_nmbre||'' ''||c.prmer_aplldo||'' ''||c.sgndo_aplldo) is null',
'            and c.idntfccion           = nvl( json_value(:P37_JSON, ''$.idntfccion_prptrio'' ) ,  c.idntfccion ) ',
'            '))
);
wwv_flow_api.create_shared_query_stmnt(
 p_id=>wwv_flow_api.id(22521720784762929)
,p_shared_query_id=>wwv_flow_api.id(40433030475669049)
,p_sql_statement=>wwv_flow_string.join(wwv_flow_t_varchar2(
'----------Encabezado y Pie de Pagina-----------------',
'select upper(b.nmbre_clnte) as nmbre_clnte,',
'       upper(b.slgan)slgan,',
'       pkg_gn_generalidades.fnc_cl_convertir_blob_a_base64( p_blob => a.file_blob ) as lgo_slgan,',
'       to_char(systimestamp, ''DD/MM/YYYY'') HOY,',
'       :F_IP as ipaddr,',
'       :F_NMBRE_USRIO as Usuario,       ',
'       a.file_mimetype,        ',
'       (select upper(nmbre_rprte) from gn_d_reportes m where m.id_rprte = :P_ID_RPRTE) as nmbre_rpte',
'from df_c_imagenes_cliente a',
'   join df_s_clientes b on a.cdgo_clnte = b.cdgo_clnte ',
'  where a.cdgo_clnte = :F_CDGO_CLNTE',
'    and a.cdgo_imgen_clnte = ''L_E'';'))
);
end;
/
