prompt --install
@application/set_environment.sql
@application/delete_application.sql
@application/create_application.sql
@application/shared_components/navigation/lists/escritorio_menú_de_navegación.sql
@application/shared_components/navigation/lists/desktop_navegation_menu_dynamic.sql
@application/shared_components/navigation/lists/lista_perfil.sql
@application/shared_components/navigation/lists/regresar.sql
@application/shared_components/navigation/lists/desktop_navigation_bar.sql
@application/shared_components/navigation/lists/operaciones_sobre_fecha_calendario.sql
@application/shared_components/navigation/lists/wizard_progress_list.sql
@application/shared_components/files/favicon_monteria_png.sql
@application/shared_components/files/logo_transparente_tax_png.sql
@application/plugin_settings.sql
@application/shared_components/security/authorizations/esquema_autorizacion_boton.sql
@application/shared_components/security/authorizations/esquema_autorizacion_pagina.sql
@application/shared_components/security/authorizations/esquema_autorizacion_region.sql
@application/shared_components/navigation/navigation_bar.sql
@application/shared_components/logic/application_processes.sql
@application/shared_components/logic/application_processes.sql
@application/shared_components/logic/application_items.sql
@application/shared_components/logic/application_computations.sql
@application/shared_components/logic/application_settings.sql
@application/shared_components/navigation/tabs/standard.sql
@application/shared_components/navigation/tabs/parent.sql
@application/shared_components/user_interface/lovs/lv_bancos.sql
@application/shared_components/user_interface/lovs/lv_cargos.sql
@application/shared_components/user_interface/lovs/lv_carroceria.sql
@application/shared_components/user_interface/lovs/lv_categoria_vehiculo.sql
@application/shared_components/user_interface/lovs/lv_clases_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_clasificacion_predio.sql
@application/shared_components/user_interface/lovs/lv_columnas.sql
@application/shared_components/user_interface/lovs/lv_conceptos.sql
@application/shared_components/user_interface/lovs/lv_datos_tipo.sql
@application/shared_components/user_interface/lovs/lv_decretos.sql
@application/shared_components/user_interface/lovs/lv_definicion_cliente_ctgria.sql
@application/shared_components/user_interface/lovs/lv_definicion_cliente_formato.sql
@application/shared_components/user_interface/lovs/lv_departamentos.sql
@application/shared_components/user_interface/lovs/lv_destinos_igac.sql
@application/shared_components/user_interface/lovs/lv_entidad.sql
@application/shared_components/user_interface/lovs/lv_entidades.sql
@application/shared_components/user_interface/lovs/lv_entidades_tipo.sql
@application/shared_components/user_interface/lovs/lv_estrato.sql
@application/shared_components/user_interface/lovs/lv_expresion_redondeo.sql
@application/shared_components/user_interface/lovs/lv_factores_tipo.sql
@application/shared_components/user_interface/lovs/lv_formastos_tipo.sql
@application/shared_components/user_interface/lovs/lv_formatos_tipo_archivo.sql
@application/shared_components/user_interface/lovs/lv_funcionario.sql
@application/shared_components/user_interface/lovs/lv_grupo_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_identificaciones_tipo.sql
@application/shared_components/user_interface/lovs/lv_impuestos.sql
@application/shared_components/user_interface/lovs/lv_impuestos_x_menu.sql
@application/shared_components/user_interface/lovs/lv_impuestos_x_menu_x_usuario.sql
@application/shared_components/user_interface/lovs/lv_impuesto_subimpuesto.sql
@application/shared_components/user_interface/lovs/lv_impuesto_x_usuario.sql
@application/shared_components/user_interface/lovs/lv_impuesto_x_usuario_x_tipo_sujeto.sql
@application/shared_components/user_interface/lovs/lv_indicadores_economicos.sql
@application/shared_components/user_interface/lovs/lv_indicadores_tipo.sql
@application/shared_components/user_interface/lovs/lv_ind_calculo_area.sql
@application/shared_components/user_interface/lovs/lv_linea_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_marcas_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_metodos_asignacion.sql
@application/shared_components/user_interface/lovs/lv_metodos_distribucion.sql
@application/shared_components/user_interface/lovs/lv_oficina.sql
@application/shared_components/user_interface/lovs/lv_operacion_mat_o.sql
@application/shared_components/user_interface/lovs/lv_operacion_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_operadores_tipo.sql
@application/shared_components/user_interface/lovs/lv_pais.sql
@application/shared_components/user_interface/lovs/lv_predios_destino.sql
@application/shared_components/user_interface/lovs/lv_predios_destino1.sql
@application/shared_components/user_interface/lovs/lv_predio_uso_suelo.sql
@application/shared_components/user_interface/lovs/lv_procesos.sql
@application/shared_components/user_interface/lovs/lv_profesiones.sql
@application/shared_components/user_interface/lovs/lv_recurso_a_i_r.sql
@application/shared_components/user_interface/lovs/lv_rgmen.sql
@application/shared_components/user_interface/lovs/lv_servicio_vehiculos.sql
@application/shared_components/user_interface/lovs/lv_si_no.sql
@application/shared_components/user_interface/lovs/lv_si_no_s_n.sql
@application/shared_components/user_interface/lovs/lv_si_no_s_n_1.sql
@application/shared_components/user_interface/lovs/lv_subimpuestos_x_usuario.sql
@application/shared_components/user_interface/lovs/lv_tabla_destino.sql
@application/shared_components/user_interface/lovs/lv_tasa_diaria_formula.sql
@application/shared_components/user_interface/lovs/lv_tipos_ajuste.sql
@application/shared_components/user_interface/lovs/lv_tipo_acto.sql
@application/shared_components/user_interface/lovs/lv_tipo_dia.sql
@application/shared_components/user_interface/lovs/lv_tipo_instancia.sql
@application/shared_components/user_interface/lovs/lv_tipo_recurso.sql
@application/shared_components/user_interface/lovs/lv_tipo_regimen.sql
@application/shared_components/user_interface/lovs/lv_tipo_variacion.sql
@application/shared_components/user_interface/lovs/lv_tpo_sjto.sql
@application/shared_components/user_interface/lovs/lv_trcro.sql
@application/shared_components/user_interface/lovs/lv_vigencias.sql
@application/pages/page_groups.sql
@application/shared_components/navigation/breadcrumbs/ruta_de_navegación.sql
@application/shared_components/user_interface/templates/page/left_side_column.sql
@application/shared_components/user_interface/templates/page/left_and_right_side_columns.sql
@application/shared_components/user_interface/templates/page/login.sql
@application/shared_components/user_interface/templates/page/master_detail.sql
@application/shared_components/user_interface/templates/page/minimal_no_navigation.sql
@application/shared_components/user_interface/templates/page/modal_dialog.sql
@application/shared_components/user_interface/templates/page/right_side_column.sql
@application/shared_components/user_interface/templates/page/standard.sql
@application/shared_components/user_interface/templates/page/wizard_modal_dialog.sql
@application/shared_components/user_interface/templates/page/left_side_column_002.sql
@application/shared_components/user_interface/templates/page/left_and_right_side_columns_002.sql
@application/shared_components/user_interface/templates/page/login_002.sql
@application/shared_components/user_interface/templates/page/master_detail_002.sql
@application/shared_components/user_interface/templates/page/modal_dialog_002.sql
@application/shared_components/user_interface/templates/page/right_side_column_002.sql
@application/shared_components/user_interface/templates/page/wizard_modal_dialog_002.sql
@application/shared_components/user_interface/templates/page/standard_002.sql
@application/shared_components/user_interface/templates/page/minimal_no_navigation_002.sql
@application/shared_components/user_interface/templates/button/icon.sql
@application/shared_components/user_interface/templates/button/text.sql
@application/shared_components/user_interface/templates/button/text_with_icon.sql
@application/shared_components/user_interface/templates/button/icon_002.sql
@application/shared_components/user_interface/templates/button/text_002.sql
@application/shared_components/user_interface/templates/button/text_with_icon_002.sql
@application/shared_components/user_interface/templates/region/alert.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid.sql
@application/shared_components/user_interface/templates/region/breadcrumb_prueba.sql
@application/shared_components/user_interface/templates/region/buttons_container.sql
@application/shared_components/user_interface/templates/region/carousel_container.sql
@application/shared_components/user_interface/templates/region/collapsible.sql
@application/shared_components/user_interface/templates/region/content_block.sql
@application/shared_components/user_interface/templates/region/hero.sql
@application/shared_components/user_interface/templates/region/inline_dialog.sql
@application/shared_components/user_interface/templates/region/interactive_report.sql
@application/shared_components/user_interface/templates/region/login.sql
@application/shared_components/user_interface/templates/region/standard.sql
@application/shared_components/user_interface/templates/region/tabs_container.sql
@application/shared_components/user_interface/templates/region/title_bar.sql
@application/shared_components/user_interface/templates/region/wizard_container.sql
@application/shared_components/user_interface/templates/region/alert_002.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes_002.sql
@application/shared_components/user_interface/templates/region/hero_002.sql
@application/shared_components/user_interface/templates/region/blank_with_attributes_no_grid_002.sql
@application/shared_components/user_interface/templates/region/carousel_container_002.sql
@application/shared_components/user_interface/templates/region/buttons_container_002.sql
@application/shared_components/user_interface/templates/region/collapsible_002.sql
@application/shared_components/user_interface/templates/region/content_block_002.sql
@application/shared_components/user_interface/templates/region/inline_dialog_002.sql
@application/shared_components/user_interface/templates/region/interactive_report_002.sql
@application/shared_components/user_interface/templates/region/login_002.sql
@application/shared_components/user_interface/templates/region/standard_002.sql
@application/shared_components/user_interface/templates/region/tabs_container_002.sql
@application/shared_components/user_interface/templates/region/title_bar_002.sql
@application/shared_components/user_interface/templates/region/wizard_container_002.sql
@application/shared_components/user_interface/templates/region/breadcrumb_prueba_002.sql
@application/shared_components/user_interface/templates/list/badge_list.sql
@application/shared_components/user_interface/templates/list/cards.sql
@application/shared_components/user_interface/templates/list/links_list.sql
@application/shared_components/user_interface/templates/list/media_list.sql
@application/shared_components/user_interface/templates/list/menu_bar.sql
@application/shared_components/user_interface/templates/list/menu_popup.sql
@application/shared_components/user_interface/templates/list/navigation_bar.sql
@application/shared_components/user_interface/templates/list/side_navigation_menu.sql
@application/shared_components/user_interface/templates/list/tabs.sql
@application/shared_components/user_interface/templates/list/top_navigation_menu.sql
@application/shared_components/user_interface/templates/list/top_navigation_tabs.sql
@application/shared_components/user_interface/templates/list/wizard_progress.sql
@application/shared_components/user_interface/templates/list/top_navigation_tabs_002.sql
@application/shared_components/user_interface/templates/list/badge_list_002.sql
@application/shared_components/user_interface/templates/list/cards_002.sql
@application/shared_components/user_interface/templates/list/menu_bar_002.sql
@application/shared_components/user_interface/templates/list/navigation_bar_002.sql
@application/shared_components/user_interface/templates/list/wizard_progress_002.sql
@application/shared_components/user_interface/templates/list/links_list_002.sql
@application/shared_components/user_interface/templates/list/media_list_002.sql
@application/shared_components/user_interface/templates/list/side_navigation_menu_002.sql
@application/shared_components/user_interface/templates/list/menu_popup_002.sql
@application/shared_components/user_interface/templates/list/tabs_002.sql
@application/shared_components/user_interface/templates/list/top_navigation_menu_002.sql
@application/shared_components/user_interface/templates/report/alerts.sql
@application/shared_components/user_interface/templates/report/badge_list.sql
@application/shared_components/user_interface/templates/report/cards.sql
@application/shared_components/user_interface/templates/report/comments.sql
@application/shared_components/user_interface/templates/report/media_list.sql
@application/shared_components/user_interface/templates/report/search_results.sql
@application/shared_components/user_interface/templates/report/standard.sql
@application/shared_components/user_interface/templates/report/timeline.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_column.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_row.sql
@application/shared_components/user_interface/templates/report/tareas.sql
@application/shared_components/user_interface/templates/report/media_list_002.sql
@application/shared_components/user_interface/templates/report/alerts_002.sql
@application/shared_components/user_interface/templates/report/badge_list_002.sql
@application/shared_components/user_interface/templates/report/cards_002.sql
@application/shared_components/user_interface/templates/report/comments_002.sql
@application/shared_components/user_interface/templates/report/search_results_002.sql
@application/shared_components/user_interface/templates/report/standard_002.sql
@application/shared_components/user_interface/templates/report/timeline_002.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_row_002.sql
@application/shared_components/user_interface/templates/report/value_attribute_pairs_column_002.sql
@application/shared_components/user_interface/templates/label/hidden.sql
@application/shared_components/user_interface/templates/label/optional.sql
@application/shared_components/user_interface/templates/label/optional_above.sql
@application/shared_components/user_interface/templates/label/optional_floating.sql
@application/shared_components/user_interface/templates/label/required.sql
@application/shared_components/user_interface/templates/label/required_above.sql
@application/shared_components/user_interface/templates/label/required_floating.sql
@application/shared_components/user_interface/templates/label/optional_floating_002.sql
@application/shared_components/user_interface/templates/label/required_floating_002.sql
@application/shared_components/user_interface/templates/label/hidden_002.sql
@application/shared_components/user_interface/templates/label/optional_002.sql
@application/shared_components/user_interface/templates/label/optional_above_002.sql
@application/shared_components/user_interface/templates/label/required_002.sql
@application/shared_components/user_interface/templates/label/required_above_002.sql
@application/shared_components/user_interface/templates/breadcrumb/breadcrumb.sql
@application/shared_components/user_interface/templates/breadcrumb/breadcrumb_002.sql
@application/shared_components/user_interface/templates/popuplov.sql
@application/shared_components/user_interface/templates/calendar/calendar.sql
@application/shared_components/user_interface/templates/calendar/calendar_002.sql
@application/shared_components/user_interface/themes.sql
@application/shared_components/user_interface/theme_style.sql
@application/shared_components/user_interface/theme_files.sql
@application/shared_components/user_interface/theme_display_points.sql
@application/shared_components/user_interface/template_opt_groups.sql
@application/shared_components/user_interface/template_options.sql
@application/shared_components/logic/build_options.sql
@application/shared_components/globalization/language.sql
@application/shared_components/globalization/messages.sql
@application/shared_components/globalization/dyntranslations.sql
@application/shared_components/user_interface/shortcuts/ok_to_get_next_prev_pk_value.sql
@application/shared_components/user_interface/shortcuts/delete_confirm_msg.sql
@application/shared_components/reports/report_queries/registro_ajuste_50000.sql
@application/shared_components/reports/report_queries/prueba.sql
@application/shared_components/reports/report_layouts/si_g_nvddes_prsona_23001.sql
@application/shared_components/reports/report_layouts/prueba.sql
@application/shared_components/reports/report_layouts/registro.sql
@application/shared_components/reports/report_layouts/gf_g_prescriones_respuesta.sql
@application/shared_components/security/authentications/sin_autenticación.sql
@application/shared_components/security/authentications/custom.sql
@application/shared_components/plugins/region_type/com_infortributos_workflow.sql
@application/shared_components/plugins/region_type/com_oracle_apex_badge_list.sql
@application/shared_components/plugins/region_type/apex_material_cards.sql
@application/shared_components/plugins/dynamic_action/com_infortributos_notificationmenu.sql
@application/shared_components/plugins/region_type/com_jk64_heatmap.sql
@application/shared_components/plugins/region_type/com_jk64_simple_google_map.sql
@application/shared_components/plugins/item_type/autonumeric.sql
@application/shared_components/plugins/region_type/com_infortributos_sujeto_tributo.sql
@application/shared_components/plugins/item_type/be_ctb_select2.sql
@application/shared_components/plugins/item_type/ca_trevis_apex_ig_simple_checkbox.sql
@application/user_interfaces.sql
@application/user_interfaces/combined_files.sql
@application/pages/page_00000.sql
@application/pages/page_00001.sql
@application/pages/page_00002.sql
@application/pages/page_00003.sql
@application/pages/page_00004.sql
@application/pages/page_00005.sql
@application/pages/page_00006.sql
@application/pages/page_00007.sql
@application/pages/page_00008.sql
@application/pages/page_00009.sql
@application/pages/page_00010.sql
@application/pages/page_00011.sql
@application/pages/page_00012.sql
@application/pages/page_00013.sql
@application/pages/page_00014.sql
@application/pages/page_00015.sql
@application/pages/page_00016.sql
@application/pages/page_00017.sql
@application/pages/page_00018.sql
@application/pages/page_00019.sql
@application/pages/page_00020.sql
@application/pages/page_00021.sql
@application/pages/page_00022.sql
@application/pages/page_00023.sql
@application/pages/page_00024.sql
@application/pages/page_00025.sql
@application/pages/page_00026.sql
@application/pages/page_00027.sql
@application/pages/page_00028.sql
@application/pages/page_00029.sql
@application/pages/page_00030.sql
@application/pages/page_00031.sql
@application/pages/page_00032.sql
@application/pages/page_00033.sql
@application/pages/page_00034.sql
@application/pages/page_00035.sql
@application/pages/page_00036.sql
@application/pages/page_00037.sql
@application/pages/page_00038.sql
@application/pages/page_00039.sql
@application/pages/page_00040.sql
@application/pages/page_00041.sql
@application/pages/page_00042.sql
@application/pages/page_00043.sql
@application/pages/page_00044.sql
@application/pages/page_00045.sql
@application/pages/page_00046.sql
@application/pages/page_00047.sql
@application/pages/page_00048.sql
@application/pages/page_00049.sql
@application/pages/page_00050.sql
@application/pages/page_00051.sql
@application/pages/page_00052.sql
@application/pages/page_00053.sql
@application/pages/page_00054.sql
@application/pages/page_00055.sql
@application/pages/page_00056.sql
@application/pages/page_00057.sql
@application/pages/page_00058.sql
@application/pages/page_00059.sql
@application/pages/page_00060.sql
@application/pages/page_00061.sql
@application/pages/page_00062.sql
@application/pages/page_00063.sql
@application/pages/page_00064.sql
@application/pages/page_00065.sql
@application/pages/page_00066.sql
@application/pages/page_00067.sql
@application/pages/page_00068.sql
@application/pages/page_00069.sql
@application/pages/page_00070.sql
@application/pages/page_00071.sql
@application/pages/page_00072.sql
@application/pages/page_00073.sql
@application/pages/page_00074.sql
@application/pages/page_00075.sql
@application/pages/page_00076.sql
@application/pages/page_00077.sql
@application/pages/page_00078.sql
@application/pages/page_00079.sql
@application/pages/page_00080.sql
@application/pages/page_00081.sql
@application/pages/page_00082.sql
@application/pages/page_00083.sql
@application/pages/page_00084.sql
@application/pages/page_00085.sql
@application/pages/page_00086.sql
@application/pages/page_00087.sql
@application/pages/page_00088.sql
@application/pages/page_00089.sql
@application/pages/page_00090.sql
@application/pages/page_00091.sql
@application/pages/page_00092.sql
@application/pages/page_00093.sql
@application/pages/page_00094.sql
@application/pages/page_00095.sql
@application/pages/page_00096.sql
@application/pages/page_00097.sql
@application/pages/page_00098.sql
@application/pages/page_00099.sql
@application/pages/page_00100.sql
@application/pages/page_00101.sql
@application/pages/page_00102.sql
@application/pages/page_00103.sql
@application/pages/page_00104.sql
@application/pages/page_00105.sql
@application/pages/page_00106.sql
@application/pages/page_00107.sql
@application/pages/page_00108.sql
@application/pages/page_00109.sql
@application/pages/page_00110.sql
@application/pages/page_00111.sql
@application/pages/page_00112.sql
@application/pages/page_00113.sql
@application/pages/page_00114.sql
@application/pages/page_00115.sql
@application/pages/page_00116.sql
@application/pages/page_00117.sql
@application/pages/page_00118.sql
@application/pages/page_00119.sql
@application/pages/page_00120.sql
@application/pages/page_00121.sql
@application/pages/page_00122.sql
@application/pages/page_00123.sql
@application/pages/page_00124.sql
@application/pages/page_00125.sql
@application/pages/page_00126.sql
@application/pages/page_00127.sql
@application/pages/page_00128.sql
@application/pages/page_00129.sql
@application/pages/page_00130.sql
@application/pages/page_00131.sql
@application/pages/page_00132.sql
@application/pages/page_00133.sql
@application/pages/page_00134.sql
@application/pages/page_00135.sql
@application/pages/page_00136.sql
@application/pages/page_00137.sql
@application/pages/page_00138.sql
@application/pages/page_00139.sql
@application/pages/page_00140.sql
@application/pages/page_00141.sql
@application/pages/page_00142.sql
@application/pages/page_00143.sql
@application/pages/page_00144.sql
@application/pages/page_00145.sql
@application/pages/page_00146.sql
@application/pages/page_00147.sql
@application/pages/page_00148.sql
@application/pages/page_00149.sql
@application/pages/page_00150.sql
@application/pages/page_00151.sql
@application/pages/page_00152.sql
@application/pages/page_00153.sql
@application/pages/page_00154.sql
@application/pages/page_00155.sql
@application/pages/page_00157.sql
@application/pages/page_00158.sql
@application/pages/page_00159.sql
@application/pages/page_00160.sql
@application/pages/page_00161.sql
@application/pages/page_00162.sql
@application/pages/page_00163.sql
@application/pages/page_00164.sql
@application/pages/page_00167.sql
@application/pages/page_00170.sql
@application/pages/page_00172.sql
@application/pages/page_00173.sql
@application/pages/page_00174.sql
@application/pages/page_00176.sql
@application/pages/page_00177.sql
@application/pages/page_00178.sql
@application/pages/page_00179.sql
@application/pages/page_00180.sql
@application/pages/page_00182.sql
@application/pages/page_00183.sql
@application/pages/page_00184.sql
@application/pages/page_00185.sql
@application/pages/page_00186.sql
@application/pages/page_00187.sql
@application/pages/page_00188.sql
@application/pages/page_00189.sql
@application/pages/page_00190.sql
@application/pages/page_00191.sql
@application/pages/page_00199.sql
@application/pages/page_00900.sql
@application/pages/page_00901.sql
@application/pages/page_00902.sql
@application/pages/page_00903.sql
@application/pages/page_00904.sql
@application/pages/page_00905.sql
@application/pages/page_00906.sql
@application/pages/page_00907.sql
@application/pages/page_00908.sql
@application/pages/page_00909.sql
@application/pages/page_00910.sql
@application/pages/page_00999.sql
@application/deployment/definition.sql
@application/deployment/checks.sql
@application/deployment/buildoptions.sql
@application/end_environment.sql
